/* This file was generated by the Hex-Rays decompiler version 9.4.0.260713.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int (__fastcall *__fastcall sub_188(_DWORD *a1, int (**a2)()))(int *a1, int a2, int a3, int a4);
int __fastcall sub_2A4(int *a1, int a2, int a3, int a4);
int sub_370();
int sub_378();
int __fastcall sub_38C(int a1, int a2);
int __fastcall sub_488(int a1, _DWORD *a2);
int __fastcall sub_4CC(int a1, int a2, int a3, int a4, _DWORD *a5);
int __fastcall sub_574(int *a1, int a2);
void __fastcall sub_71C(int a1, const char *a2);
int __fastcall sub_750(const char *a1, int a2, int a3, int a4);
int __fastcall sub_808(_DWORD *a1, _DWORD *a2);
int __fastcall sub_868(int a1, int a2, int a3);
int __fastcall sub_9F0(_DWORD **a1, int a2, int a3);
int __fastcall sub_AC0(int result);
int __fastcall sub_B94(int a1, int a2, int a3, int a4, int *a5, int a6);
int __fastcall sub_C40(int *a1);
int __fastcall sub_C88(int a1, int a2, int a3);
int __fastcall sub_DE0(int result, int a2, int a3, int *a4);
int *__fastcall sub_1014(int a1, int a2, int a3);
int *__fastcall sub_10B0(int *result, int a2, int a3, int a4);
int *__fastcall sub_1110(int *result);
int *__fastcall sub_1188(int *a1);
void sub_139E();
void sub_13D6();
_DWORD *__fastcall sub_13FC(_DWORD *a1);
int __fastcall sub_1434(int a1, int a2);
int __fastcall sub_1588(int *a1, int a2, int a3, int a4, _DWORD *a5);
int __fastcall sub_1644(_DWORD **a1);
int *__fastcall sub_1680(int *result);
BOOL __fastcall sub_16D8(int *a1, int a2, int a3);
int *__fastcall sub_171C(int *result, int a2);
int __fastcall sub_1764(int a1, int a2, int a3, int a4);
int __fastcall sub_181C(int a1, int a2, int a3);
int __fastcall sub_18C0(int a1, int a2, int a3);
int __fastcall sub_1984(int a1);
int __fastcall sub_1A24(int a1, _BYTE *a2, int a3, int a4);
int __fastcall sub_1D24(int a1, _BYTE *a2, int a3, int a4);
int sub_1EC0(int a1, ...);
int __fastcall sub_2068(int a1, int a2);
void __fastcall sub_21F8(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_229C(int result, int a2);
void __fastcall sub_22F4(int *a1);
BOOL __fastcall sub_232C(int a1, int a2);
int __fastcall sub_235C(int a1, _DWORD *a2);
void sub_23A8();
void sub_23D0();
void sub_23E4();
int __fastcall sub_2434(int a1, int a2, int a3, int a4);
void sub_24EC();
void __fastcall sub_2500(_BYTE *a1, _DWORD *a2, int **a3);
void sub_2624(_BYTE *a1, ...);
void sub_2670();
void sub_2684();
void sub_26FC();
void sub_2710();
void sub_274C(int a1, _BYTE *a2, ...);
void __fastcall sub_27A8(int a1, _BYTE *a2, int **a3);
void sub_281C();
void sub_286C();
void sub_2894();
int __fastcall sub_2B8C(int a1, int a2, int a3, int a4);
int __fastcall sub_2BB8(int a1, int a2, int a3, int a4);
int __fastcall sub_2C20(int a1, int a2, int a3, int a4);
void sub_2DB8();
__int64 __fastcall sub_2E30(int a1, int a2, int a3, int a4, __int64 a5);
_DWORD *__fastcall sub_2F1C(_DWORD *result, unsigned int a2);
_DWORD *__fastcall sub_2F74(_BYTE *a1, char *a2, unsigned int a3);
int __fastcall sub_3028(unsigned int a1, unsigned int a2);
int __fastcall sub_30FC(unsigned int a1, unsigned int a2);
int sub_31CC();
int sub_31E0();
_DWORD *__fastcall sub_31F0(_DWORD *result, char *a2, unsigned int a3, int a4);
int sub_325C();
_UNKNOWN **sub_3274();
void sub_3358();
int __fastcall sub_3370(int a1, int a2, int a3, const char *a4);
int __fastcall sub_3418(int a1, _DWORD *a2);
int sub_3484();
int __fastcall sub_349C(int a1, int a2, int a3, const char *a4);
int sub_3500();
int sub_3518();
int __fastcall sub_3564(int a1, int a2, int a3, const char *a4);
int sub_36C4();
int __fastcall sub_36D4(char a1, int a2, int a3, int a4);
_DWORD *sub_36EC();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_FF; // weak
_UNKNOWN loc_2BC; // weak
_UNKNOWN loc_2C0; // weak
_UNKNOWN loc_2D0; // weak
_UNKNOWN loc_2FC; // weak
_UNKNOWN loc_1250; // weak
_UNKNOWN *off_336C = &unk_C0; // weak
_UNKNOWN unk_3648; // weak
_DWORD dword_3748[20] =
{
  0,
  238,
  44,
  44,
  49,
  253,
  44,
  44,
  97,
  262,
  44,
  44,
  146,
  258,
  44,
  44,
  196,
  239,
  44,
  44
}; // weak
_DWORD dword_3798[20] =
{
  11,
  184,
  44,
  44,
  75,
  190,
  44,
  44,
  142,
  190,
  44,
  44,
  207,
  190,
  44,
  44,
  271,
  182,
  44,
  44
}; // weak
_DWORD dword_37E8[20] =
{
  0,
  165,
  32,
  31,
  36,
  175,
  32,
  31,
  72,
  182,
  32,
  31,
  108,
  178,
  32,
  31,
  144,
  165,
  32,
  31
}; // weak
_UNKNOWN unk_3838; // weak
_DWORD dword_3888[20] =
{
  0,
  318,
  44,
  44,
  49,
  333,
  44,
  44,
  97,
  342,
  44,
  44,
  146,
  338,
  44,
  44,
  196,
  319,
  44,
  44
}; // weak
_DWORD dword_38D8[20] =
{
  6,
  166,
  44,
  45,
  92,
  183,
  44,
  45,
  182,
  186,
  44,
  45,
  261,
  183,
  44,
  45,
  351,
  164,
  44,
  45
}; // weak
_UNKNOWN unk_3928; // weak
_DWORD dword_3978[20] =
{
  44,
  245,
  44,
  44,
  132,
  245,
  44,
  44,
  221,
  263,
  44,
  44,
  301,
  260,
  44,
  44,
  390,
  241,
  44,
  44
}; // weak
_DWORD dword_39C8[20] =
{
  19,
  531,
  47,
  47,
  86,
  537,
  47,
  47,
  156,
  542,
  47,
  47,
  226,
  538,
  47,
  47,
  296,
  530,
  47,
  47
}; // weak
_UNKNOWN unk_3A18; // weak
char aAbnormalTermin[21] = "Abnormal termination"; // weak


//----- (00000188) --------------------------------------------------------
int (__fastcall *__fastcall sub_188(_DWORD *a1, int (**a2)()))(int *a1, int a2, int a3, int a4)
{
  *a1 = 320;
  *a2 = sub_370;
  a2[1] = sub_378;
  a2[2] = (int (*)())sub_2A4;
  return sub_2A4;
}

//----- (000002A4) --------------------------------------------------------
int __fastcall sub_2A4(int *a1, int a2, int a3, int a4)
{
  bool v4; // zf
  bool v5; // zf

  if ( a2 == 8 )
  {
LABEL_22:
    if ( a1[60] != 0 )
      sub_181C((int)a1, a3, a2);
  }
  else if ( a2 > 8 )
  {
    if ( a2 != 13 )
    {
      if ( a2 > 13 )
      {
        v5 = a2 == 14;
        if ( a2 != 14 )
          v5 = a2 == 28672;
        if ( !v5 && a2 == 28674 )
          sub_229C(a1[70], 28674);
      }
      else
      {
        v4 = a2 == 9;
        if ( a2 != 9 )
          v4 = a2 == 10;
        if ( !v4 )
          v4 = a2 == 11;
        if ( v4 )
          sub_1764((int)a1, a3, a4, a2);
      }
    }
  }
  else
  {
    switch ( a2 )
    {
      case 0:
        sub_C88((int)a1, a3, a4);
        break;
      case 1:
        sub_1680(a1);
        break;
      case 2:
      case 3:
      case 4:
        sub_18C0((int)a1, a2, a3);
        break;
      case 5:
      case 6:
      case 7:
        goto LABEL_22;
      default:
        return 1;
    }
  }
  return 1;
}

//----- (00000370) --------------------------------------------------------
int sub_370()
{
  return 0;
}

//----- (00000378) --------------------------------------------------------
int sub_378()
{
  return 0;
}

//----- (0000038C) --------------------------------------------------------
int __fastcall sub_38C(int a1, int a2)
{
  int v4; // r0
  int v5; // r4
  int v6; // r0
  _DWORD v8[2]; // [sp+Ch] [bp-30h] BYREF
  int v9; // [sp+14h] [bp-28h]
  int v10; // [sp+18h] [bp-24h]
  int v11; // [sp+1Ch] [bp-20h] BYREF
  int v12; // [sp+20h] [bp-1Ch]

  sub_2DB8();
  v5 = v4;
  sub_2F1C(&v11, 0x20u);
  v8[0] = 0;
  v8[1] = 0;
  v9 = 0;
  v10 = 0;
  v6 = (*(int (__fastcall **)(_DWORD, int))(**(_DWORD **)(v5 + 72) + 32))(*(_DWORD *)(v5 + 72), a2);
  if ( v6 != 0 )
    return sub_1A24(*(_DWORD *)(v5 + 76), "Set active layer error\n, error flag = %d\n", v6, *(_DWORD *)(v5 + 76));
  (*(void (__fastcall **)(int, int *))(*(_DWORD *)a1 + 16))(a1, &v11);
  v10 = v12;
  v9 = v11;
  return (*(int (__fastcall **)(_DWORD, _DWORD, int, int, _DWORD *, _DWORD))(**(_DWORD **)(v5 + 72) + 148))(
           *(_DWORD *)(v5 + 72),
           0,
           *(_DWORD *)(v5 + 220) - v12,
           a1,
           v8,
           0);
}
// 3A0: variable 'v4' is possibly undefined

//----- (00000488) --------------------------------------------------------
int __fastcall sub_488(int a1, _DWORD *a2)
{
  int v4; // r0
  int v5; // r4

  sub_2DB8();
  v5 = v4;
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(v4 + 72) + 32))(*(_DWORD *)(v4 + 72), a1);
  return (*(int (__fastcall **)(_DWORD, int, _DWORD, _DWORD))(**(_DWORD **)(v5 + 72) + 36))(
           *(_DWORD *)(v5 + 72),
           a1,
           *a2,
           a2[1]);
}
// 498: variable 'v4' is possibly undefined

//----- (000004CC) --------------------------------------------------------
int __fastcall sub_4CC(int a1, int a2, int a3, int a4, _DWORD *a5)
{
  int v8; // r6
  int result; // r0
  int v10; // r1
  _DWORD v11[2]; // [sp+8h] [bp-30h] BYREF
  int v12; // [sp+10h] [bp-28h]
  int v13; // [sp+14h] [bp-24h]
  _DWORD v14[8]; // [sp+18h] [bp-20h] BYREF

  sub_2F1C(v14, 0x20u);
  v11[0] = 0;
  v11[1] = 0;
  v12 = 0;
  v13 = 0;
  (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)a2 + 16))(a2, v14);
  v13 = v14[1];
  v12 = v14[0];
  v8 = a3 - v14[0];
  (*(void (__fastcall **)(int, int, _DWORD, int, _DWORD *, _DWORD))(*(_DWORD *)a1 + 148))(a1, v8, 0, a2, v11, 0);
  result = v12;
  v10 = v13;
  *a5 = v8;
  a5[1] = 0;
  a5[2] = result;
  a5[3] = v10;
  return result;
}

//----- (00000574) --------------------------------------------------------
int __fastcall sub_574(int *a1, int a2)
{
  int v4; // r0
  int result; // r0
  int v6; // [sp+10h] [bp-18h]
  int v7; // [sp+14h] [bp-14h]
  int v8; // [sp+18h] [bp-10h] BYREF
  int v9; // [sp+1Ch] [bp-Ch]
  int v10; // [sp+20h] [bp-8h]
  int v11; // [sp+24h] [bp-4h]

  v8 = 0;
  v9 = 0;
  v10 = 0;
  v11 = 0;
  v7 = a1[55];
  v6 = a1[54];
  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1[18] + 32))(a1[18], a2);
  (*(void (__fastcall **)(int, _DWORD, _DWORD, int, int))(*(_DWORD *)a1[18] + 92))(a1[18], 0, 0, v6, v7);
  v4 = a1[67];
  if ( a1[62] != 0 )
  {
    sub_488(v4, a1 + 26);
    (*(void (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1[18] + 88))(a1[18], 1, (unsigned __int8)a1[65]);
    sub_488(a1[68], a1 + 26);
    (*(void (__fastcall **)(int, int, _DWORD))(*(_DWORD *)a1[18] + 88))(a1[18], 1, (unsigned __int8)a1[66]);
    (*(void (__fastcall **)(int, int))(*(_DWORD *)a1[18] + 32))(a1[18], a2);
    v8 = a2;
    v9 = a1[67];
    v10 = a1[68];
    (*(void (__fastcall **)(int, int, int *, int))(*(_DWORD *)a1[18] + 176))(a1[18], 3, &v8, 1);
  }
  else
  {
    sub_488(v4, a1 + 26);
    (*(void (__fastcall **)(int, int))(*(_DWORD *)a1[18] + 32))(a1[18], a2);
    v8 = a2;
    v9 = a1[67];
    (*(void (__fastcall **)(int, int, int *, int))(*(_DWORD *)a1[18] + 176))(a1[18], 2, &v8, 1);
  }
  sub_38C(a1[24], a2);
  result = a1[60];
  if ( result != 0 )
    return sub_4CC(a1[18], a1[25], a1[54], a1[55], a1 + 50);
  return result;
}

//----- (0000071C) --------------------------------------------------------
void __fastcall sub_71C(int a1, const char *a2)
{
  int v4; // r0

  sub_2DB8();
  sub_274C(a1, "%s%s", (const char *)(v4 + 288), a2);
}
// 72C: variable 'v4' is possibly undefined

//----- (00000750) --------------------------------------------------------
int __fastcall sub_750(const char *a1, int a2, int a3, int a4)
{
  int v8; // r4
  _DWORD v10[64]; // [sp+Ch] [bp-100h] BYREF

  sub_2F1C(v10, 0x100u);
  sub_71C((int)v10, a1);
  v8 = (*(int (__fastcall **)(int, _DWORD *, void (*)(), void (*)(), int))(*(_DWORD *)a4 + 164))(
         a4,
         v10,
         sub_23D0,
         sub_23E4,
         a2);
  if ( v8 != 0 )
    sub_1A24(
      a3,
      "Load bmp res error, file = %s, line = %d\n, path = %s, error flag = %d\n",
      (int)"src\\app_memory_card_init.c",
      45);
  return v8;
}

//----- (00000808) --------------------------------------------------------
int __fastcall sub_808(_DWORD *a1, _DWORD *a2)
{
  int v4; // r4
  int v5; // r0
  _DWORD v7[2]; // [sp+0h] [bp-168h] BYREF
  int v8; // [sp+8h] [bp-160h]
  int v9; // [sp+Ch] [bp-15Ch]

  v4 = sub_23A8();
  sub_2F1C(v7, 0x168u);
  (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)v4 + 16))(v4, v7);
  *a2 = v9;
  v5 = v8;
  *a1 = v8;
  if ( *a2 > v5 )
    return 2;
  else
    return 1;
}
// 23A8: using guessed type int sub_23A8(void);

//----- (00000868) --------------------------------------------------------
int __fastcall sub_868(int a1, int a2, int a3)
{
  int v6; // r0
  int v7; // r1
  const char *v8; // r0

  sub_2DB8();
  v7 = v6;
  v8 = nullptr;
  switch ( a3 )
  {
    case 0:
      if ( a2 == 1 )
        v8 = "res\\heng_sun_flower.zbmp";
      else
        v8 = "res\\shu_sun_flower.zbmp";
      break;
    case 1:
      if ( a2 == 1 )
        v8 = "res\\heng_beach.zbmp";
      else
        v8 = "res\\shu_beach.zbmp";
      break;
    case 2:
      if ( a2 == 1 )
        v8 = "res\\heng_purple_flower.zbmp";
      else
        v8 = "res\\shu_purple_flower.zbmp";
      break;
    case 3:
      if ( a2 == 1 )
        v8 = "res\\heng_butterfly.zbmp";
      else
        v8 = "res\\shu_butterfly.zbmp";
      break;
    case 4:
      if ( a2 == 1 )
        v8 = "res\\heng_boat.zbmp";
      else
        v8 = "res\\shu_boat.zbmp";
      break;
    default:
      return sub_750(v8, a1, *(_DWORD *)(v7 + 76), *(_DWORD *)(v7 + 72));
  }
  return sub_750(v8, a1, *(_DWORD *)(v7 + 76), *(_DWORD *)(v7 + 72));
}
// 87C: variable 'v6' is possibly undefined

//----- (000009F0) --------------------------------------------------------
int __fastcall sub_9F0(_DWORD **a1, int a2, int a3)
{
  int v6; // r5
  _DWORD v8[2]; // [sp+Ch] [bp-30h] BYREF
  int v9; // [sp+14h] [bp-28h]
  int v10; // [sp+18h] [bp-24h]
  int v11; // [sp+1Ch] [bp-20h] BYREF
  int v12; // [sp+20h] [bp-1Ch]
  int v13; // [sp+38h] [bp-4h]

  sub_2F1C(&v11, 0x20u);
  v8[0] = 0;
  v8[1] = 0;
  v9 = 0;
  v10 = 0;
  (*(void (__fastcall **)(_DWORD *, int *))(*a1[22] + 16))(a1[22], &v11);
  v10 = v12;
  v9 = v11;
  v6 = 2 * v11 * v12;
  (*(void (__fastcall **)(_DWORD *, int, _DWORD *, int, int, int))(*a1[18] + 16))(a1[18], a2, v8, 1, v13, v6);
  (*(void (__fastcall **)(_DWORD *, int *))(*a1[23] + 16))(a1[23], &v11);
  (*(void (__fastcall **)(_DWORD *, int, _DWORD *, int, int, int))(*a1[18] + 16))(a1[18], a3, v8, 1, v13, v6);
  return 0;
}

//----- (00000AC0) --------------------------------------------------------
int __fastcall sub_AC0(int result)
{
  int *v1; // r4
  unsigned int v2; // r0
  int v3; // r1
  const char *v4; // r0

  v1 = (int *)result;
  if ( result != 0 )
  {
    (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(result + 84) + 72))(*(_DWORD *)(result + 84));
    sub_2670();
    sub_2684();
    sub_3028(5u, v2);
    v1[57] = v3;
    sub_868((int)(v1 + 22), v1[59], v3);
    sub_868((int)(v1 + 23), v1[59], v1[57]);
    if ( v1[59] == 1 )
      v4 = "res\\heng_icon.zbmp";
    else
      v4 = "res\\shu_icon.zbmp";
    sub_750(v4, (int)(v1 + 24), v1[19], v1[18]);
    result = v1[60];
    if ( result != 0 )
      return sub_750("res\\exit_btn.zbmp", (int)(v1 + 25), v1[19], v1[18]);
  }
  return result;
}
// AEC: variable 'v2' is possibly undefined
// AF0: variable 'v3' is possibly undefined

//----- (00000B94) --------------------------------------------------------
int __fastcall sub_B94(int a1, int a2, int a3, int a4, int *a5, int a6)
{
  int v10; // r0
  int result; // r0
  _DWORD v12[8]; // [sp+4h] [bp-40h] BYREF
  int v13; // [sp+24h] [bp-20h] BYREF
  int v14; // [sp+28h] [bp-1Ch]

  sub_2F1C(&v13, 0x20u);
  sub_2F1C(v12, 0x20u);
  (*(void (__fastcall **)(int, int *))(*(_DWORD *)a3 + 16))(a3, &v13);
  (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)a4 + 16))(a4, v12);
  v10 = v12[1];
  *a5 = (a1 - v13) / 2;
  result = a2 - v10 + a6;
  a5[1] = (result - v14) / 2;
  a5[3] = v14;
  a5[2] = v13;
  return result;
}

//----- (00000C40) --------------------------------------------------------
int __fastcall sub_C40(int *a1)
{
  int v2; // r0
  int result; // r0

  a1[56] = sub_B94(a1[54], a1[55], a1[22], a1[24], a1 + 26, a1[69]);
  sub_2684();
  result = v2 % 8;
  a1[64] = result;
  return result;
}
// C7C: variable 'v2' is possibly undefined

//----- (00000C88) --------------------------------------------------------
int __fastcall sub_C88(int a1, int a2, int a3)
{
  int v5; // r5
  int v7; // r0
  int result; // r0

  v5 = a1 + 72;
  sub_2710();
  if ( a1 != 0 && a2 == 0 )
    *(_DWORD *)(a1 + 240) = *(_DWORD *)(a3 + 256) == 0;
  *(_DWORD *)(a1 + 284) = sub_232C(a2, a3);
  v7 = sub_23A8();
  *(_DWORD *)(a1 + 84) = v7;
  if ( v7 != 0 )
  {
    result = (*(int (__fastcall **)(int, int, int))(*(_DWORD *)v7 + 8))(v7, 16777221, v5);
    if ( result == 0 )
    {
      result = (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 84) + 8))(
                 *(_DWORD *)(a1 + 84),
                 16777219,
                 a1 + 76);
      if ( result == 0 )
        result = 0;
    }
  }
  else
  {
    result = -1;
  }
  if ( result == 0 )
  {
    sub_2710();
    sub_2894();
    sub_26FC();
    *(_DWORD *)(a1 + 236) = sub_808((_DWORD *)(a1 + 216), (_DWORD *)(a1 + 220));
    *(_DWORD *)(a1 + 244) = 1;
    sub_DE0(a1 + 120, *(_DWORD *)(a1 + 216), *(_DWORD *)(a1 + 220), (int *)(a1 + 276));
    sub_AC0(a1);
    result = sub_9F0((_DWORD **)a1, 1, 2);
    if ( result == 0 )
    {
      *(_DWORD *)(a1 + 272) = 2;
      *(_DWORD *)(a1 + 268) = 1;
      sub_C40((int *)a1);
      return sub_1434(-1, a1);
    }
  }
  return result;
}
// 23A8: using guessed type int sub_23A8(void);

//----- (00000DE0) --------------------------------------------------------
int __fastcall sub_DE0(int result, int a2, int a3, int *a4)
{
  int v4; // lr
  _DWORD *v7; // r5
  int v8; // r1
  int v9; // r2
  int v10; // r3
  int v11; // r12
  _DWORD *v12; // r1
  _DWORD *v13; // r5
  int v14; // r3
  int v15; // r7
  int v16; // r12
  _DWORD *v17; // r5
  int v18; // r1
  int v19; // r2
  int v20; // r3
  int v21; // r12
  _DWORD *v22; // r5
  int v23; // r1
  int v24; // r2
  int v25; // r3
  int v26; // r12
  _DWORD *v27; // r6
  int v28; // r1
  int v29; // r2
  int v30; // r3
  int v31; // r12
  int v32; // lr
  _DWORD *v33; // r1
  _DWORD *v34; // r5
  int v35; // r3
  int v36; // r7
  int v37; // r12
  _DWORD *v38; // r5
  int v39; // r1
  int v40; // r2
  int v41; // r3
  int v42; // r12
  _DWORD *v43; // r5
  int v44; // r1
  int v45; // r2
  int v46; // r3
  int v47; // r12
  _DWORD *v48; // r5
  int v49; // r1
  int v50; // r2
  int v51; // r3
  int v52; // r12
  _DWORD *v53; // r1
  _DWORD *v54; // r5
  int v55; // r3
  int v56; // r7
  int v57; // r12

  v4 = 0;
  if ( a2 == 360 )
  {
    do
    {
      v48 = (_DWORD *)(result + 16 * v4);
      v49 = dword_39C8[4 * v4];
      v50 = dword_39C8[4 * v4 + 1];
      v51 = dword_39C8[4 * v4 + 2];
      v52 = dword_39C8[4 * v4++ + 3];
      *v48 = v49;
      v48[1] = v50;
      v48[2] = v51;
      v48[3] = v52;
    }
    while ( v4 < 5 );
    goto LABEL_34;
  }
  if ( a2 > 360 )
  {
    switch ( a2 )
    {
      case 400:
        do
        {
          v38 = (_DWORD *)(result + 16 * v4);
          v39 = dword_38D8[4 * v4];
          v40 = dword_38D8[4 * v4 + 1];
          v41 = dword_38D8[4 * v4 + 2];
          v42 = dword_38D8[4 * v4++ + 3];
          *v38 = v39;
          v38[1] = v40;
          v38[2] = v41;
          v38[3] = v42;
        }
        while ( v4 < 5 );
        break;
      case 480:
        do
        {
          v43 = (_DWORD *)(result + 16 * v4);
          v44 = dword_3978[4 * v4];
          v45 = dword_3978[4 * v4 + 1];
          v46 = dword_3978[4 * v4 + 2];
          v47 = dword_3978[4 * v4++ + 3];
          *v43 = v44;
          v43[1] = v45;
          v43[2] = v46;
          v43[3] = v47;
        }
        while ( v4 < 5 );
        break;
      case 600:
        do
        {
          v53 = (_DWORD *)((char *)&unk_3A18 + 16 * v4);
          v54 = (_DWORD *)(result + 16 * v4);
          v55 = v53[1];
          v56 = v53[2];
          v57 = v53[3];
          ++v4;
          *v54 = *v53;
          v54[1] = v55;
          v54[2] = v56;
          v54[3] = v57;
        }
        while ( v4 < 5 );
        result = 25;
        goto LABEL_37;
      default:
        return result;
    }
LABEL_32:
    *a4 = 24;
    return result;
  }
  switch ( a2 )
  {
    case 176:
      do
      {
        v7 = (_DWORD *)(result + 16 * v4);
        v8 = dword_37E8[4 * v4];
        v9 = dword_37E8[4 * v4 + 1];
        v10 = dword_37E8[4 * v4 + 2];
        v11 = dword_37E8[4 * v4++ + 3];
        *v7 = v8;
        v7[1] = v9;
        v7[2] = v10;
        v7[3] = v11;
      }
      while ( v4 < 5 );
LABEL_34:
      *a4 = 17;
      return result;
    case 220:
      do
      {
        v12 = (_DWORD *)((char *)&unk_3838 + 16 * v4);
        v13 = (_DWORD *)(result + 16 * v4);
        v14 = v12[1];
        v15 = v12[2];
        v16 = v12[3];
        ++v4;
        *v13 = *v12;
        v13[1] = v14;
        v13[2] = v15;
        v13[3] = v16;
      }
      while ( v4 < 5 );
      result = 14;
      goto LABEL_37;
    case 240:
      if ( a3 == 400 )
      {
        do
        {
          v17 = (_DWORD *)(result + 16 * v4);
          v18 = dword_3888[4 * v4];
          v19 = dword_3888[4 * v4 + 1];
          v20 = dword_3888[4 * v4 + 2];
          v21 = dword_3888[4 * v4++ + 3];
          *v17 = v18;
          v17[1] = v19;
          v17[2] = v20;
          v17[3] = v21;
        }
        while ( v4 < 5 );
      }
      else if ( a3 == 320 )
      {
        do
        {
          v22 = (_DWORD *)(result + 16 * v4);
          v23 = dword_3748[4 * v4];
          v24 = dword_3748[4 * v4 + 1];
          v25 = dword_3748[4 * v4 + 2];
          v26 = dword_3748[4 * v4++ + 3];
          *v22 = v23;
          v22[1] = v24;
          v22[2] = v25;
          v22[3] = v26;
        }
        while ( v4 < 5 );
      }
      goto LABEL_32;
    case 320:
      if ( a3 == 240 )
      {
        do
        {
          v27 = (_DWORD *)(result + 16 * v4);
          v28 = dword_3798[4 * v4];
          v29 = dword_3798[4 * v4 + 1];
          v30 = dword_3798[4 * v4 + 2];
          v31 = dword_3798[4 * v4++ + 3];
          *v27 = v28;
          v27[1] = v29;
          v27[2] = v30;
          v27[3] = v31;
        }
        while ( v4 < 5 );
        *a4 = 15;
      }
      if ( a3 == 480 )
      {
        v32 = 0;
        do
        {
          v33 = (_DWORD *)((char *)&unk_3928 + 16 * v32);
          v34 = (_DWORD *)(result + 16 * v32);
          v35 = v33[1];
          v36 = v33[2];
          v37 = v33[3];
          ++v32;
          *v34 = *v33;
          v34[1] = v35;
          v34[2] = v36;
          v34[3] = v37;
        }
        while ( v32 < 5 );
        result = 16;
LABEL_37:
        *a4 = result;
      }
      break;
    default:
      break;
  }
  return result;
}
// 3748: using guessed type _DWORD dword_3748[20];
// 3798: using guessed type _DWORD dword_3798[20];
// 37E8: using guessed type _DWORD dword_37E8[20];
// 3888: using guessed type _DWORD dword_3888[20];
// 38D8: using guessed type _DWORD dword_38D8[20];
// 3978: using guessed type _DWORD dword_3978[20];
// 39C8: using guessed type _DWORD dword_39C8[20];

//----- (00001014) --------------------------------------------------------
int *__fastcall sub_1014(int a1, int a2, int a3)
{
  int *result; // r0
  _DWORD v7[2]; // [sp+8h] [bp-30h] BYREF
  int v8; // [sp+10h] [bp-28h] BYREF
  int v9; // [sp+14h] [bp-24h]
  int v10; // [sp+18h] [bp-20h] BYREF
  int v11; // [sp+1Ch] [bp-1Ch]
  int v12; // [sp+34h] [bp-4h]

  sub_2F1C(&v10, 0x20u);
  v7[0] = 0;
  v7[1] = 0;
  result = &v8;
  v8 = 0;
  v9 = 0;
  if ( a3 != 0 )
  {
    (*(void (__fastcall **)(int, int *))(*(_DWORD *)a3 + 16))(a3, &v10);
    v9 = v11;
    v8 = v10;
    return (int *)(*(int (__fastcall **)(int, int, _DWORD *, int, int, int))(*(_DWORD *)a1 + 16))(
                    a1,
                    a2,
                    v7,
                    1,
                    v12,
                    2 * v10 * v11);
  }
  return result;
}

//----- (000010B0) --------------------------------------------------------
int *__fastcall sub_10B0(int *result, int a2, int a3, int a4)
{
  int *v6; // r5

  v6 = result;
  if ( a4 != 0 )
  {
    (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a4 + 72) + 20))(*(_DWORD *)(a4 + 72), a2);
    (*(void (__fastcall **)(int))(*(_DWORD *)*v6 + 4))(*v6);
    sub_868((int)v6, *(_DWORD *)(a4 + 236), a3);
    return sub_1014(*(_DWORD *)(a4 + 72), a2, *v6);
  }
  return result;
}

//----- (00001110) --------------------------------------------------------
int *__fastcall sub_1110(int *result)
{
  int *v1; // r4

  v1 = result;
  if ( result != nullptr )
  {
    sub_1644((_DWORD **)result);
    (*(void (__fastcall **)(int))(*(_DWORD *)v1[18] + 24))(v1[18]);
    v1[59] = sub_808(v1 + 54, v1 + 55);
    sub_1188(v1);
    sub_DE0((int)(v1 + 30), v1[54], v1[55], v1 + 69);
    result = (int *)sub_B94(v1[54], v1[55], v1[22], v1[24], v1 + 26, v1[69]);
    v1[56] = (int)result;
  }
  return result;
}

//----- (00001188) --------------------------------------------------------
int *__fastcall sub_1188(int *a1)
{
  int v1; // r2
  int v3; // r1
  bool v4; // zf
  int v5; // r0
  const char *v6; // r0

  v1 = a1[62];
  v3 = a1[59];
  v4 = v1 == 0;
  if ( v1 == 0 )
    v1 = a1[57];
  v5 = (int)(a1 + 22);
  if ( !v4 )
    v1 = a1[58];
  sub_868(v5, v3, v1);
  sub_868((int)(a1 + 23), a1[59], a1[57]);
  if ( a1[59] == 1 )
    v6 = "res\\heng_icon.zbmp";
  else
    v6 = "res\\shu_icon.zbmp";
  sub_750(v6, (int)(a1 + 24), a1[19], a1[18]);
  sub_1014(a1[18], a1[67], a1[22]);
  return sub_1014(a1[18], a1[68], a1[23]);
}

//----- (0000139E) --------------------------------------------------------
void sub_139E()
{
  JUMPOUT(0xECE);
}
// 13A2: control flows out of bounds to ECE

//----- (000013D6) --------------------------------------------------------
void sub_13D6()
{
  JUMPOUT(0xF06);
}
// 13DA: control flows out of bounds to F06

//----- (000013FC) --------------------------------------------------------
_DWORD *__fastcall sub_13FC(_DWORD *a1)
{
  int v1; // r2
  int v2; // r1
  _DWORD *result; // r0

  a1[65] = 0;
  a1[66] = 255;
  a1[62] = 0;
  v1 = a1[23];
  a1[23] = a1[22];
  a1[22] = v1;
  v2 = a1[67];
  a1[67] = a1[68];
  result = a1 + 67;
  result[1] = v2;
  return result;
}

//----- (00001434) --------------------------------------------------------
int __fastcall sub_1434(int a1, int a2)
{
  int v3; // r0
  int v4; // r0
  int result; // r0
  _DWORD v6[2]; // [sp+Ch] [bp-20h] BYREF
  int v7; // [sp+14h] [bp-18h]
  int v8; // [sp+18h] [bp-14h]
  _DWORD v9[4]; // [sp+1Ch] [bp-10h] BYREF

  memset(v9, 0, sizeof(v9));
  v6[0] = 0;
  v6[1] = 0;
  v7 = 0;
  v8 = 0;
  if ( *(_DWORD *)(a2 + 280) == 0 )
  {
    sub_21F8(*(_DWORD *)(a2 + 84), 50, (int)sub_1434, 0, a2, *(_DWORD *)(a2 + 284));
    *(_DWORD *)(a2 + 280) = v3;
  }
  if ( *(_DWORD *)(a2 + 248) != 0 )
  {
    *(_DWORD *)(a2 + 260) -= 20;
    v4 = *(_DWORD *)(a2 + 264) + 20;
    *(_DWORD *)(a2 + 264) = v4;
    if ( *(int *)(a2 + 260) <= 0 || v4 >= 255 )
      sub_13FC((_DWORD *)a2);
  }
  else
  {
    sub_1588(
      (int *)(a2 + 104),
      *(_DWORD *)(a2 + 216),
      *(_DWORD *)(a2 + 224),
      *(_DWORD *)(a2 + 88),
      (_DWORD *)(a2 + 256));
  }
  if ( *(_DWORD *)(a2 + 240) != 0 )
  {
    v7 = *(_DWORD *)(a2 + 216);
    v8 = *(_DWORD *)(a2 + 220);
    sub_574((int *)a2, 0);
    v9[0] = 0;
    return (*(int (__fastcall **)(_DWORD, _DWORD *, int, _DWORD *))(**(_DWORD **)(a2 + 72) + 44))(
             *(_DWORD *)(a2 + 72),
             v6,
             1,
             v9);
  }
  else
  {
    result = *(_DWORD *)(a2 + 244);
    if ( result == 0 )
      result = (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(a2 + 72) + 200))(
                 *(_DWORD *)(a2 + 72),
                 0,
                 0,
                 *(_DWORD *)(a2 + 216),
                 *(_DWORD *)(a2 + 220));
    *(_DWORD *)(a2 + 244) = 0;
  }
  return result;
}
// 1498: variable 'v3' is possibly undefined

//----- (00001588) --------------------------------------------------------
int __fastcall sub_1588(int *a1, int a2, int a3, int a4, _DWORD *a5)
{
  int v5; // lr
  int v6; // lr
  int v8; // lr
  int v9; // lr

  switch ( *a5 )
  {
    case 0:
      v5 = *a1 + 1;
      goto LABEL_4;
    case 1:
      v5 = *a1 - 1;
LABEL_4:
      *a1 = v5;
      return ((int (*)(void))loc_1250)();
    case 2:
      goto LABEL_5;
    case 3:
      goto LABEL_6;
    case 4:
      v9 = *a1 + 1;
      goto LABEL_14;
    case 5:
      v8 = *a1 + 1;
      goto LABEL_12;
    case 6:
      v9 = *a1 - 1;
LABEL_14:
      *a1 = v9;
LABEL_5:
      v6 = a1[1] + 1;
      goto LABEL_7;
    case 7:
      v8 = *a1 - 1;
LABEL_12:
      *a1 = v8;
LABEL_6:
      v6 = a1[1] - 1;
LABEL_7:
      a1[1] = v6;
      break;
    default:
      return ((int (*)(void))loc_1250)();
  }
  return ((int (*)(void))loc_1250)();
}

//----- (00001644) --------------------------------------------------------
int __fastcall sub_1644(_DWORD **a1)
{
  (*(void (__fastcall **)(_DWORD *))(*a1[22] + 4))(a1[22]);
  (*(void (__fastcall **)(_DWORD *))(*a1[23] + 4))(a1[23]);
  return (*(int (__fastcall **)(_DWORD *))(*a1[24] + 4))(a1[24]);
}

//----- (00001680) --------------------------------------------------------
int *__fastcall sub_1680(int *result)
{
  int *v1; // r4

  v1 = result;
  if ( result != nullptr )
  {
    sub_1644((_DWORD **)result);
    if ( v1[60] != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v1[25] + 4))(v1[25]);
    (*(void (__fastcall **)(int))(*(_DWORD *)v1[18] + 24))(v1[18]);
    result = (int *)v1[70];
    if ( result != nullptr )
    {
      sub_22F4(result);
      v1[70] = 0;
      return nullptr;
    }
  }
  return result;
}

//----- (000016D8) --------------------------------------------------------
BOOL __fastcall sub_16D8(int *a1, int a2, int a3)
{
  int v3; // r1
  BOOL result; // r0

  result = false;
  if ( *a1 <= a2 && *a1 + a1[2] > a2 )
  {
    v3 = a1[1];
    if ( v3 <= a3 && v3 + a1[3] > a3 )
      return true;
  }
  return result;
}

//----- (0000171C) --------------------------------------------------------
int *__fastcall sub_171C(int *result, int a2)
{
  int *v2; // r4

  v2 = result;
  if ( result != nullptr )
  {
    result[58] = result[57];
    result[57] = a2;
    sub_10B0(result + 23, result[68], a2, (int)result);
    v2[62] = 1;
    v2[66] = 0;
    v2[65] = 255;
    return (_DWORD *)&unk_FF;
  }
  return result;
}

//----- (00001764) --------------------------------------------------------
int __fastcall sub_1764(int a1, int a2, int a3, int a4)
{
  int *v4; // r10
  int i; // r4

  v4 = (int *)(a1 + 200);
  for ( i = 0; i < 5; ++i )
  {
    if ( sub_16D8((int *)(a1 + 16 * i + 120), a2, a3) )
    {
      if ( *(_DWORD *)(a1 + 228) == i )
        return 0;
      if ( a4 == 9 )
      {
        if ( *(_DWORD *)(a1 + 248) != 0 )
          sub_13FC((_DWORD *)a1);
        sub_171C((int *)a1, i);
        return 0;
      }
    }
    else if ( sub_16D8(v4, a2, a3) && a4 == 10 )
    {
      (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 84) + 36))(*(_DWORD *)(a1 + 84), 0);
    }
  }
  return -1;
}

//----- (0000181C) --------------------------------------------------------
int __fastcall sub_181C(int a1, int a2, int a3)
{
  int v4; // r0
  int v5; // r4

  v4 = *(_DWORD *)(a1 + 228);
  if ( a3 != 6 )
    return -1;
  if ( a2 == 11 )
  {
    (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 84) + 36))(*(_DWORD *)(a1 + 84), 0);
    return 0;
  }
  if ( a2 > 11 )
  {
    if ( a2 != 15 )
    {
      if ( a2 == 16 )
        goto LABEL_9;
      return -1;
    }
LABEL_12:
    v5 = v4 - 1;
    if ( v4 - 1 < 0 )
      v5 = 4;
    goto LABEL_14;
  }
  if ( a2 == 4 )
    goto LABEL_12;
  if ( a2 == 6 )
  {
LABEL_9:
    v5 = v4 + 1;
    if ( v4 + 1 >= 5 )
      v5 = 0;
LABEL_14:
    if ( *(_DWORD *)(a1 + 248) != 0 )
      sub_13FC((_DWORD *)a1);
    sub_171C((int *)a1, v5);
    return 0;
  }
  return -1;
}

//----- (000018C0) --------------------------------------------------------
int __fastcall sub_18C0(int a1, int a2, int a3)
{
  int *v7; // r0
  _DWORD v8[90]; // [sp+0h] [bp-168h] BYREF

  sub_2F1C(v8, 0x168u);
  if ( a1 != 0 )
  {
    switch ( a2 )
    {
      case 2:
        v7 = *(int **)(a1 + 280);
        if ( v7 != nullptr )
        {
          sub_22F4(v7);
          *(_DWORD *)(a1 + 280) = 0;
        }
        return 0;
      case 3:
        (*(void (__fastcall **)(_DWORD, _DWORD *))(**(_DWORD **)(a1 + 84) + 16))(*(_DWORD *)(a1 + 84), v8);
        if ( *(_DWORD *)(a1 + 220) != v8[3] )
          sub_1110((int *)a1);
        sub_1434(-1, a1);
        return 0;
      case 4:
        if ( a3 == 1 )
          sub_1110((int *)a1);
        if ( *(_DWORD *)(a1 + 240) == 0 )
          sub_1984(a1);
        return 0;
      default:
        break;
    }
  }
  return -1;
}

//----- (00001984) --------------------------------------------------------
int __fastcall sub_1984(int a1)
{
  int v3; // [sp+4h] [bp-14h] BYREF
  _DWORD v4[4]; // [sp+8h] [bp-10h] BYREF

  memset(v4, 0, sizeof(v4));
  v3 = 0;
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 52))(*(_DWORD *)(a1 + 72));
  (*(void (__fastcall **)(_DWORD, int *, _DWORD *))(**(_DWORD **)(a1 + 72) + 192))(*(_DWORD *)(a1 + 72), &v3, v4);
  (*(void (__fastcall **)(_DWORD, int, _DWORD))(**(_DWORD **)(a1 + 72) + 196))(*(_DWORD *)(a1 + 72), 3, v4[0]);
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 3);
  sub_574((int *)a1, 3);
  return (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 56))(*(_DWORD *)(a1 + 72));
}

//----- (00001A24) --------------------------------------------------------
int __fastcall sub_1A24(int a1, _BYTE *a2, int a3, int a4)
{
  int v4; // r5
  int v5; // r4
  int v6; // r0
  int result; // r0
  int v8; // r4
  int v9; // r0
  int *v10; // [sp+0h] [bp-21Ch] BYREF
  _BYTE v11[6]; // [sp+4h] [bp-218h] BYREF
  _BYTE v12[506]; // [sp+Ah] [bp-212h] BYREF
  _BYTE var18[32]; // [sp+204h] [bp-18h] BYREF
  int varg_r0; // [sp+228h] [bp+Ch] BYREF
  _BYTE *varg_r1; // [sp+22Ch] [bp+10h]
  _DWORD varg_r2[2]; // [sp+230h] [bp+14h] BYREF

  varg_r0 = a1;
  varg_r1 = a2;
  varg_r2[0] = a3;
  varg_r2[1] = a4;
  sub_2F74(var18, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  v4 = 0;
  if ( varg_r0 == 0 )
  {
    v5 = sub_23A8();
    v6 = sub_23A8();
    result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v6 + 8))(v5, 16777219, &varg_r0);
    if ( result != 0 )
      return result;
    v4 = 1;
  }
  var18[0] = (*(int (__fastcall **)(int, int))(*(_DWORD *)varg_r0 + 48))(varg_r0, 1);
  if ( var18[0] == 0 )
    var18[0] = (*(int (__fastcall **)(int, _DWORD))(*(_DWORD *)varg_r0 + 48))(varg_r0, 0);
  result = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)varg_r0 + 8))(varg_r0, var18, 12);
  v8 = result;
  if ( result != 0 )
  {
    sub_2F74(v11, "Trace:", 0x200u);
    v10 = varg_r2;
    sub_27A8((int)v12, varg_r1, &v10);
    v10 = nullptr;
    sub_2894();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v8 + 12))(v8, v11, v9);
    result = (*(int (__fastcall **)(int))(*(_DWORD *)v8 + 4))(v8);
  }
  if ( v4 != 0 )
    return (*(int (__fastcall **)(int))(*(_DWORD *)varg_r0 + 4))(varg_r0);
  return result;
}
// 1B2C: variable 'v9' is possibly undefined
// 23A8: using guessed type int sub_23A8(void);

//----- (00001D24) --------------------------------------------------------
int __fastcall sub_1D24(int a1, _BYTE *a2, int a3, int a4)
{
  int v4; // r5
  int v5; // r0
  int v6; // r4
  int v7; // r0
  int result; // r0
  int v9; // r4
  int v10; // r0
  int v11; // r6
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int *v16; // [sp+4h] [bp-21Ch] BYREF
  _BYTE v17[512]; // [sp+8h] [bp-218h] BYREF
  _BYTE var18[36]; // [sp+208h] [bp-18h] BYREF
  int varg_r0; // [sp+230h] [bp+10h] BYREF
  _BYTE *varg_r1; // [sp+234h] [bp+14h]
  _DWORD varg_r2[2]; // [sp+238h] [bp+18h] BYREF

  varg_r0 = a1;
  varg_r1 = a2;
  varg_r2[0] = a3;
  varg_r2[1] = a4;
  sub_2F74(var18, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  v4 = 0;
  if ( varg_r0 == 0 )
  {
    sub_23A8();
    v6 = v5;
    sub_23A8();
    result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v7 + 8))(v6, 16777219, &varg_r0);
    if ( result != 0 )
      return result;
    v4 = 1;
  }
  var18[0] = (*(int (__fastcall **)(int, int))(*(_DWORD *)varg_r0 + 48))(varg_r0, 1);
  if ( var18[0] == 0 )
    var18[0] = (*(int (__fastcall **)(int, _DWORD))(*(_DWORD *)varg_r0 + 48))(varg_r0, 0);
  result = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)varg_r0 + 8))(varg_r0, var18, 12);
  v9 = result;
  if ( result != 0 )
  {
    sub_2F74(v17, "Trace:", 0x200u);
    v16 = varg_r2;
    sub_23A8();
    v11 = v10;
    sub_23A8();
    v13 = (*(int (__fastcall **)(int))(*(_DWORD *)v12 + 72))(v11);
    sub_274C((int)v17, "Trace: tick=%10d ", v13);
    sub_2894();
    sub_27A8((int)&v17[v14], varg_r1, &v16);
    v16 = nullptr;
    sub_281C();
    sub_2894();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v9 + 12))(v9, v17, v15);
    result = (*(int (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
  }
  if ( v4 != 0 )
    return (*(int (__fastcall **)(int))(*(_DWORD *)varg_r0 + 4))(varg_r0);
  return result;
}
// 1D58: variable 'v5' is possibly undefined
// 1D60: variable 'v7' is possibly undefined
// 1DFC: variable 'v10' is possibly undefined
// 1E04: variable 'v12' is possibly undefined
// 1E30: variable 'v14' is possibly undefined
// 1E70: variable 'v15' is possibly undefined

//----- (00001EC0) --------------------------------------------------------
int sub_1EC0(int a1, ...)
{
  int v1; // r0
  int v2; // r4
  unsigned int v3; // r5
  int v4; // r4
  unsigned int v5; // r0
  int v6; // r1
  int v7; // r7
  unsigned int v8; // r1
  unsigned int v9; // r6
  int v10; // r1
  int v11; // r8
  int v12; // r6
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int *v17; // [sp+8h] [bp-220h] BYREF
  _BYTE v18[512]; // [sp+Ch] [bp-21Ch] BYREF
  _BYTE v19[24]; // [sp+20Ch] [bp-1Ch] BYREF
  _BYTE *var4[8]; // [sp+224h] [bp-4h] BYREF
  va_list varg_r1; // [sp+244h] [bp+1Ch] BYREF

  va_start(varg_r1, a1);
  sub_2F74(v19, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  sub_23A8();
  v2 = v1;
  v3 = (*(int (__fastcall **)(int))(*(_DWORD *)v1 + 72))(v1);
  (*(void (__fastcall **)(int, int, _BYTE **))(*(_DWORD *)v2 + 8))(v2, 16777219, var4);
  v19[0] = (*(int (__fastcall **)(_BYTE *, int))(*(_DWORD *)var4[0] + 48))(var4[0], 1);
  if ( v19[0] == 0 )
    v19[0] = (*(int (__fastcall **)(_BYTE *, _DWORD))(*(_DWORD *)var4[0] + 48))(var4[0], 0);
  v4 = (*(int (__fastcall **)(_BYTE *, _BYTE *, int))(*(_DWORD *)var4[0] + 8))(var4[0], v19, 12);
  if ( v4 != 0 )
  {
    v5 = sub_30FC(0x3E8u, v3);
    v7 = v6;
    sub_30FC(0xE10u, v5);
    v9 = v8;
    sub_30FC(0x3Cu, v8);
    v11 = v10;
    v12 = sub_30FC(0x3Cu, v9);
    v13 = sub_30FC(0x36EE80u, v3);
    sub_274C((int)v18, "%02d:%02d:%02d:%03d--", v13, v12, v11, v7);
    va_copy((va_list)v17, varg_r1);
    sub_2894();
    sub_27A8((int)&v18[v14], var4[7], &v17);
    v17 = nullptr;
    sub_2894();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v4 + 12))(v4, v18, v15);
    (*(void (__fastcall **)(int))(*(_DWORD *)v4 + 4))(v4);
  }
  return (*(int (__fastcall **)(_BYTE *))(*(_DWORD *)var4[0] + 4))(var4[0]);
}
// 1EE4: variable 'v1' is possibly undefined
// 1F78: variable 'v6' is possibly undefined
// 1F88: variable 'v8' is possibly undefined
// 1F94: variable 'v10' is possibly undefined
// 1FE4: variable 'v14' is possibly undefined
// 2018: variable 'v15' is possibly undefined

//----- (00002068) --------------------------------------------------------
int __fastcall sub_2068(int a1, int a2)
{
  int v4; // r0
  int v5; // r4
  int v6; // r0
  int v7; // r4
  int v8; // r0
  bool v9; // zf
  int v10; // r0
  int v11; // r0
  _BYTE v13[32]; // [sp+4h] [bp-3Ch] BYREF
  _BYTE v14[24]; // [sp+24h] [bp-1Ch] BYREF
  int v15; // [sp+3Ch] [bp-4h] BYREF

  sub_2F74(v14, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  sub_23A8();
  v5 = v4;
  sub_23A8();
  (*(void (__fastcall **)(int, int, int *))(*(_DWORD *)v6 + 8))(v5, 16777219, &v15);
  v14[0] = (*(int (__fastcall **)(int, int))(*(_DWORD *)v15 + 48))(v15, 1);
  if ( v14[0] == 0 )
    v14[0] = (*(int (__fastcall **)(int, _DWORD))(*(_DWORD *)v15 + 48))(v15, 0);
  v7 = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v15 + 8))(v15, v14, 12);
  if ( v7 != 0 )
  {
    sub_2F74(v13, "TraceDump:", 0x20u);
    sub_2894();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v7 + 12))(v7, v13, v8);
    v9 = a1 == 0;
    if ( a1 != 0 )
      v9 = a2 == 0;
    if ( v9 )
    {
      sub_286C();
      sub_2894();
      (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v7 + 12))(v7, v13, v10);
    }
    else
    {
      (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v7 + 12))(v7, a1, a2);
    }
    sub_286C();
    sub_2894();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v7 + 12))(v7, v13, v11);
    (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 4))(v7);
  }
  return (*(int (__fastcall **)(int))(*(_DWORD *)v15 + 4))(v15);
}
// 2090: variable 'v4' is possibly undefined
// 2098: variable 'v6' is possibly undefined
// 2138: variable 'v8' is possibly undefined
// 2190: variable 'v10' is possibly undefined
// 21BC: variable 'v11' is possibly undefined

//----- (000021F8) --------------------------------------------------------
void __fastcall sub_21F8(int a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD *v10; // r0
  _DWORD *v11; // r4

  sub_23D0();
  v11 = v10;
  if ( v10 != nullptr )
  {
    sub_2710();
    *v11 = a1;
    v11[1] = a5;
    v11[5] = a2;
    v11[7] = a3;
    v11[4] = a4;
    v11[6] = (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 72))(a1);
    v11[3] = -1;
    if ( a6 != 0 )
      v11[3] = (*(int (__fastcall **)(_DWORD, _DWORD, int (__fastcall *)(int, _DWORD *), _DWORD))(*(_DWORD *)*v11 + 60))(
                 *v11,
                 v11[5],
                 sub_235C,
                 v11[4]);
  }
}
// 221C: variable 'v10' is possibly undefined

//----- (0000229C) --------------------------------------------------------
int __fastcall sub_229C(int result, int a2)
{
  int v2; // r5
  int v3; // r4

  v2 = result;
  v3 = result;
  if ( a2 == 28674 )
  {
    result = (*(int (**)(void))(**(_DWORD **)result + 72))();
    if ( (unsigned int)(result - *(_DWORD *)(v3 + 24)) >= *(_DWORD *)(v3 + 20) )
    {
      *(_DWORD *)(v3 + 24) = result;
      return (*(int (__fastcall **)(int, _DWORD))(v3 + 28))(v2, *(_DWORD *)(v3 + 4));
    }
  }
  return result;
}

//----- (000022F4) --------------------------------------------------------
void __fastcall sub_22F4(int *a1)
{
  if ( a1 != nullptr )
  {
    if ( a1[3] >= 0 )
      (*(void (**)(void))(*(_DWORD *)*a1 + 64))();
    a1[3] = -1;
    sub_23E4();
  }
}

//----- (0000232C) --------------------------------------------------------
BOOL __fastcall sub_232C(int a1, int a2)
{
  bool v2; // zf

  if ( a1 != 0 )
    return true;
  v2 = a2 == 0;
  if ( a2 != 0 )
    v2 = *(_DWORD *)(a2 + 256) == 0;
  return v2 || *(_BYTE *)a2 != 2;
}

//----- (0000235C) --------------------------------------------------------
int __fastcall sub_235C(int a1, _DWORD *a2)
{
  int result; // r0

  ((void (__fastcall *)(_DWORD, _DWORD))a2[7])(0, a2[1]);
  result = (*(int (__fastcall **)(_DWORD, _DWORD, int (*)(), _DWORD))(*(_DWORD *)*a2 + 60))(*a2, a2[5], sub_235C, a2[4]);
  a2[3] = result;
  return result;
}

//----- (000023A8) --------------------------------------------------------
void sub_23A8()
{
  JUMPOUT(0xE12FFF1E);
}
// 23B8: control flows out of bounds to E12FFF1E

//----- (000023D0) --------------------------------------------------------
void sub_23D0()
{
  JUMPOUT(0xE8980002);
}
// 23E0: control flows out of bounds to E8980002

//----- (000023E4) --------------------------------------------------------
void sub_23E4()
{
  JUMPOUT(0xE0800008);
}
// 23F4: control flows out of bounds to E0800008

//----- (00002434) --------------------------------------------------------
int __fastcall sub_2434(int a1, int a2, int a3, int a4)
{
  return MEMORY[0xA000012](a1, a2, a3, a4);
}

//----- (000024EC) --------------------------------------------------------
void sub_24EC()
{
  JUMPOUT(0xE3140000);
}
// 24FC: control flows out of bounds to E3140000

//----- (00002500) --------------------------------------------------------
void __fastcall sub_2500(_BYTE *a1, _DWORD *a2, int **a3)
{
  int v4; // r5
  unsigned __int8 *v6; // r0
  unsigned __int8 *v7; // r1
  unsigned int v8; // r0
  bool v9; // zf
  int *v10; // r0
  int v11; // r3
  int v12; // r0
  _DWORD *v13; // r2
  int v14; // r1
  bool v15; // zf
  int v16; // r2

  v4 = 0;
  while ( 1 )
  {
    v14 = (unsigned __int8)*a1;
    if ( *a1 == 0 )
      break;
    ++a1;
    if ( v14 == 37 )
    {
      if ( *a1 == 37 )
      {
        ++a1;
      }
      else
      {
        sub_24EC();
        if ( v6 == nullptr )
          return;
        v7 = v6;
        v8 = *v6;
        if ( v8 == 111 )
        {
LABEL_23:
          v16 = *(*a3)++;
          a2[2 * v4 + 1] = v16;
          goto LABEL_15;
        }
        if ( v8 > 0x6F )
        {
          v15 = v8 == 112;
          if ( v8 != 112 )
            v15 = v8 == 115;
          if ( v15 || v8 == 117 || v8 == 120 )
            goto LABEL_23;
        }
        else
        {
          v9 = v8 == 88;
          if ( v8 != 88 )
            v9 = v8 == 99;
          if ( !v9 )
            v9 = v8 == 100;
          if ( v9 )
            goto LABEL_23;
          if ( v8 == 102 )
          {
            v10 = *a3;
            *a3 += 2;
            v11 = *v10;
            v12 = v10[1];
            v13 = &a2[2 * v4];
            v13[1] = v11;
            v13[2] = v12;
          }
        }
LABEL_15:
        a1 = v7 + 1;
        ++v4;
      }
    }
  }
  *a2 = v4;
}
// 253C: variable 'v6' is possibly undefined

//----- (00002624) --------------------------------------------------------
void sub_2624(_BYTE *a1, ...)
{
  int v1; // r0
  int *v2; // [sp+4h] [bp-88h] BYREF
  _DWORD v3[33]; // [sp+8h] [bp-84h] BYREF
  _BYTE *varg_r0; // [sp+90h] [bp+4h]
  va_list varg_r1; // [sp+94h] [bp+8h] BYREF

  va_start(varg_r1, a1);
  varg_r0 = a1;
  va_copy((va_list)v2, varg_r1);
  sub_2500(a1, v3, &v2);
  if ( v1 != 0 )
    MEMORY[0xE3150002](varg_r0, v3);
}
// 264C: variable 'v1' is possibly undefined

//----- (00002670) --------------------------------------------------------
void sub_2670()
{
  JUMPOUT(0x10855008);
}
// 2680: control flows out of bounds to 10855008

//----- (00002684) --------------------------------------------------------
void sub_2684()
{
  JUMPOUT(0xE3C55002);
}
// 2694: control flows out of bounds to E3C55002

//----- (000026FC) --------------------------------------------------------
void sub_26FC()
{
  JUMPOUT(0x28B4000C);
}
// 270C: control flows out of bounds to 28B4000C

//----- (00002710) --------------------------------------------------------
void sub_2710()
{
  JUMPOUT(0x28A5000C);
}
// 2720: control flows out of bounds to 28A5000C

//----- (0000274C) --------------------------------------------------------
void sub_274C(int a1, _BYTE *a2, ...)
{
  int v3; // r0
  int *v4; // [sp+0h] [bp-88h] BYREF
  _DWORD v5[33]; // [sp+4h] [bp-84h] BYREF
  _BYTE *varg_r1; // [sp+94h] [bp+Ch]
  va_list varg_r2; // [sp+98h] [bp+10h] BYREF

  va_start(varg_r2, a2);
  varg_r1 = a2;
  va_copy((va_list)v4, varg_r2);
  sub_2500(a2, v5, &v4);
  if ( v3 != 0 )
    MEMORY[0xEAFFFFE8](a1, varg_r1, v5);
}
// 2778: variable 'v3' is possibly undefined

//----- (000027A8) --------------------------------------------------------
void __fastcall sub_27A8(int a1, _BYTE *a2, int **a3)
{
  int v5; // r0
  _DWORD v6[33]; // [sp+0h] [bp-84h] BYREF

  sub_2500(a2, v6, a3);
  if ( v5 != 0 )
    MEMORY[0xEAFFFFE8](a1, a2, v6);
}
// 27C8: variable 'v5' is possibly undefined

//----- (0000281C) --------------------------------------------------------
void sub_281C()
{
  JUMPOUT(0xE0822008);
}
// 282C: control flows out of bounds to E0822008

//----- (0000286C) --------------------------------------------------------
void sub_286C()
{
  JUMPOUT(0xE3A00000);
}
// 287C: control flows out of bounds to E3A00000

//----- (00002894) --------------------------------------------------------
void sub_2894()
{
  JUMPOUT(0xE3A0B000);
}
// 28A4: control flows out of bounds to E3A0B000

//----- (00002B8C) --------------------------------------------------------
int __fastcall sub_2B8C(int a1, int a2, int a3, int a4)
{
  return loc_2BC(a1, a2, a3, a4);
}

//----- (00002BB8) --------------------------------------------------------
int __fastcall sub_2BB8(int a1, int a2, int a3, int a4)
{
  return loc_2C0(a1, a2, a3, a4);
}

//----- (00002C20) --------------------------------------------------------
int __fastcall sub_2C20(int a1, int a2, int a3, int a4)
{
  return loc_2D0(a1, a2, a3, a4);
}

//----- (00002DB8) --------------------------------------------------------
void sub_2DB8()
{
  __asm { BX              R0 }
}

//----- (00002E30) --------------------------------------------------------
__int64 __fastcall sub_2E30(int a1, int a2, int a3, int a4, __int64 a5)
{
  loc_2FC(a1, a2, a3, a4);
  return a5;
}

//----- (00002F1C) --------------------------------------------------------
_DWORD *__fastcall sub_2F1C(_DWORD *result, unsigned int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  _DWORD *v4; // r0
  int v5; // r1
  int v6; // r1
  _BYTE *v7; // r0

  v2 = a2 >= 0x20;
  v3 = a2 - 32;
  do
  {
    if ( !v2 )
      break;
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    v4 = result + 4;
    *v4 = 0;
    v4[1] = 0;
    v4[2] = 0;
    v4[3] = 0;
    result = v4 + 4;
    v2 = v3 >= 0x20;
    v3 -= 32;
  }
  while ( v2 );
  v2 = __CFSHL__(v3, 28);
  v5 = v3 << 28;
  if ( v2 )
  {
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    result += 4;
  }
  if ( v5 < 0 )
  {
    *result = 0;
    result[1] = 0;
    result += 2;
  }
  v2 = __CFSHL__(v5, 2);
  v6 = 4 * v5;
  if ( v2 )
    *result++ = 0;
  if ( v6 != 0 )
  {
    if ( v6 < 0 )
    {
      *(_BYTE *)result = 0;
      v7 = (char *)result + 1;
      *v7 = 0;
      result = v7 + 1;
    }
    if ( (v6 & 0x40000000) != 0 )
    {
      *(_BYTE *)result = 0;
      return (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (00002F74) --------------------------------------------------------
_DWORD *__fastcall sub_2F74(_BYTE *a1, char *a2, unsigned int a3)
{
  unsigned int v3; // r12
  char v4; // r3
  char v5; // t1
  bool v6; // cf
  bool v7; // cc
  unsigned int v8; // r2
  char v9; // t1
  char v10; // t1
  unsigned int v11; // r3
  unsigned int v13; // r2
  char *v14; // r1
  unsigned int v15; // r12
  unsigned int v16; // t1
  unsigned int v17; // r3
  unsigned int v18; // t1
  unsigned int v19; // r3
  unsigned int v20; // t1
  unsigned int v21; // r3
  unsigned int v22; // t1

  if ( a3 <= 3 )
    goto LABEL_22;
  v3 = (unsigned __int8)a1 & 3;
  if ( ((unsigned __int8)a1 & 3) != 0 )
  {
    v5 = *a2++;
    v4 = v5;
    v6 = v3 >= 2;
    v7 = ((unsigned __int8)a1 & 3) == 3;
    v8 = a3 + v3;
    if ( ((unsigned __int8)a1 & 3) != 3 )
    {
      v9 = *a2++;
      LOBYTE(v3) = v9;
    }
    *a1++ = v4;
    if ( !v6 )
    {
      v10 = *a2++;
      v4 = v10;
    }
    a3 = v8 - 4;
    if ( !v7 )
      *a1++ = v3;
    if ( !v6 )
      *a1++ = v4;
  }
  v11 = (unsigned __int8)a2 & 3;
  if ( ((unsigned __int8)a2 & 3) != 0 )
  {
    v6 = a3 >= 4;
    v13 = a3 - 4;
    if ( v6 )
    {
      v16 = *(_DWORD *)&a2[-v11];
      v14 = &a2[-v11];
      v15 = v16;
      if ( v11 == 2 )
      {
        do
        {
          v19 = HIWORD(v15);
          v20 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v20;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v19 | (v20 << 16);
          a1 += 4;
        }
        while ( v6 );
      }
      else if ( v11 > 2 )
      {
        do
        {
          v21 = HIBYTE(v15);
          v22 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v22;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v21 | (v22 << 8);
          a1 += 4;
        }
        while ( v6 );
      }
      else
      {
        do
        {
          v17 = v15 >> 8;
          v18 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v18;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v17 | (v18 << 24);
          a1 += 4;
        }
        while ( v6 );
      }
    }
LABEL_22:
    JUMPOUT(0x323C);
  }
  return sub_31F0(a1, a2, a3, 0);
}
// 2F78: control flows out of bounds to 323C

//----- (00003028) --------------------------------------------------------
int __fastcall sub_3028(unsigned int a1, unsigned int a2)
{
  unsigned int v2; // r2
  int v3; // r3
  char v4; // cf
  bool v5; // cf
  unsigned int v6; // r2
  bool v7; // cf
  unsigned int v8; // r2
  bool v9; // cf
  unsigned int v10; // r2
  bool v11; // cf
  bool v12; // cf
  bool v13; // cf
  unsigned int v14; // r2
  bool v15; // cf
  unsigned int v16; // r2
  bool v17; // cf
  unsigned int v18; // off

  v2 = a1 & 0x80000000;
  if ( (a1 & 0x80000000) != 0 )
    a1 = -a1;
  v3 = v2 ^ ((int)a2 >> 31);
  if ( (a2 & 0x80000000) != 0 )
    a2 = -a2;
  if ( a2 >> 3 < a1 )
    goto LABEL_27;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF000000;
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF0000u;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 |= 0xFF00u;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  v4 = a1 == 0;
  if ( a1 == 0 )
    return sub_3370(2, 2, v2, (const char *)v3);
  do
  {
    if ( v4 )
      a1 >>= 8;
LABEL_15:
    v5 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v6 = v2 + v5 + v2;
    v7 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v8 = v6 + v7 + v6;
    v9 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v10 = v8 + v9 + v8;
    v11 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v10 + v11 + v10;
LABEL_24:
    v12 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v12 + v2;
LABEL_27:
    v13 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v14 = v2 + v13 + v2;
    v15 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v16 = v14 + v15 + v14;
    v17 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v18 = v17 + v16;
    v4 = __CFADD__(v17, v16) | __CFADD__(v16, v18);
    v2 = v16 + v18;
  }
  while ( v4 );
  return (v2 ^ (v3 >> 31)) + ((unsigned int)v3 >> 31);
}

//----- (000030FC) --------------------------------------------------------
int __fastcall sub_30FC(unsigned int a1, unsigned int a2)
{
  int v2; // r2
  char v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // cf
  int v7; // r2
  bool v8; // cf
  int v9; // r2
  bool v10; // cf
  bool v11; // cf
  bool v12; // cf
  int v13; // r2
  bool v14; // cf
  int v15; // r2
  bool v16; // cf
  int v17; // off

  v2 = 0;
  if ( a2 >> 3 < a1 )
    goto LABEL_23;
  if ( a2 >> 8 < a1 )
    goto LABEL_11;
  a1 <<= 8;
  v2 = -16777216;
  if ( a2 >> 4 < a1 )
    goto LABEL_20;
  if ( a2 >> 8 < a1 )
    goto LABEL_11;
  a1 <<= 8;
  v2 = -65536;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 = -256;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_20;
  v3 = a1 == 0;
  if ( a1 == 0 )
    return sub_3370(2, 2, v2);
  do
  {
    if ( v3 )
      a1 >>= 8;
LABEL_11:
    v4 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v5 = v2 + v4 + v2;
    v6 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v7 = v5 + v6 + v5;
    v8 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v9 = v7 + v8 + v7;
    v10 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v9 + v10 + v9;
LABEL_20:
    v11 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v11 + v2;
LABEL_23:
    v12 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v13 = v2 + v12 + v2;
    v14 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v15 = v13 + v14 + v13;
    v16 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v17 = v16 + v15;
    v3 = __CFADD__(v16, v15) | __CFADD__(v15, v17);
    v2 = v15 + v17;
  }
  while ( v3 );
  return v2;
}
// 3370: using guessed type int __fastcall sub_3370(_DWORD, _DWORD, _DWORD);

//----- (000031CC) --------------------------------------------------------
int sub_31CC()
{
  sub_3358();
  return sub_31E0();
}

//----- (000031F0) --------------------------------------------------------
_DWORD *__fastcall sub_31F0(_DWORD *result, char *a2, unsigned int a3, int a4)
{
  bool v4; // cf
  unsigned int i; // r2
  _DWORD *v6; // r1
  int v7; // r3
  int v8; // r4
  int v9; // r12
  int v10; // lr
  _DWORD *v11; // r0
  int v12; // r4
  int v13; // r12
  int v14; // lr
  int v15; // r4
  int v16; // r12
  int v17; // lr
  int v18; // r4
  char v19; // r12
  int v20; // t1
  bool v21; // cf
  bool v22; // nf
  int v23; // r2
  char v24; // t1
  _BYTE *v25; // r0

  v4 = a3 >= 0x20;
  for ( i = a3 - 32; v4; i -= 32 )
  {
    if ( !v4 )
      break;
    v7 = *(_DWORD *)a2;
    v8 = *((_DWORD *)a2 + 1);
    v9 = *((_DWORD *)a2 + 2);
    v10 = *((_DWORD *)a2 + 3);
    v6 = a2 + 16;
    *result = v7;
    result[1] = v8;
    result[2] = v9;
    result[3] = v10;
    v11 = result + 4;
    a4 = *v6;
    v12 = v6[1];
    v13 = v6[2];
    v14 = v6[3];
    a2 = (char *)(v6 + 4);
    *v11 = a4;
    v11[1] = v12;
    v11[2] = v13;
    v11[3] = v14;
    result = v11 + 4;
    v4 = i >= 0x20;
  }
  if ( __CFSHL__(i, 28) )
  {
    a4 = *(_DWORD *)a2;
    v15 = *((_DWORD *)a2 + 1);
    v16 = *((_DWORD *)a2 + 2);
    v17 = *((_DWORD *)a2 + 3);
    a2 += 16;
    *result = a4;
    result[1] = v15;
    result[2] = v16;
    result[3] = v17;
    result += 4;
  }
  if ( (i & 8) != 0 )
  {
    a4 = *(_DWORD *)a2;
    v18 = *((_DWORD *)a2 + 1);
    a2 += 8;
    *result = a4;
    result[1] = v18;
    result += 2;
  }
  v19 = 0;
  if ( __CFSHL__(i, 30) )
  {
    v20 = *(_DWORD *)a2;
    a2 += 4;
    LOBYTE(a4) = v20;
    *result++ = v20;
  }
  if ( i << 30 != 0 )
  {
    v21 = __CFSHL__(i, 31);
    v23 = i << 31;
    v22 = v23 < 0;
    if ( v23 < 0 )
    {
      v24 = *a2++;
      LOBYTE(v23) = v24;
    }
    if ( v21 )
    {
      LOBYTE(a4) = *a2;
      v19 = a2[1];
    }
    if ( v22 )
    {
      *(_BYTE *)result = v23;
      result = (_DWORD *)((char *)result + 1);
    }
    if ( v21 )
    {
      *(_BYTE *)result = a4;
      v25 = (char *)result + 1;
      *v25 = v19;
      return v25 + 1;
    }
  }
  return result;
}

//----- (0000325C) --------------------------------------------------------
int sub_325C()
{
  return sub_31CC();
}

//----- (00003274) --------------------------------------------------------
_UNKNOWN **sub_3274()
{
  _DWORD *v0; // r4

  sub_36EC();
  v0 = (_DWORD *)sub_3500();
  v0[8] = 0;
  v0[9] = 1;
  v0[10] = 0;
  v0[11] = 0;
  v0[12] = 0;
  return &off_336C;
}
// 3348: returning address of temporary local variable '%var_C'
// 336C: using guessed type _UNKNOWN *off_336C;

//----- (00003358) --------------------------------------------------------
void sub_3358()
{
  ;
}

//----- (00003370) --------------------------------------------------------
int __fastcall sub_3370(int a1, int a2, int a3, const char *a4)
{
  int result; // r0

  result = sub_349C(a1, a2, a3, a4);
  if ( result != 0 )
    return sub_3484();
  return result;
}

//----- (00003418) --------------------------------------------------------
int __fastcall sub_3418(int a1, _DWORD *a2)
{
  int v2; // r4
  char *v3; // r3
  int v4; // r2
  int v5; // lr
  unsigned int v6; // r3
  unsigned int v7; // r1
  _DWORD savedregs[2]; // [sp+8h] [bp+0h] BYREF

  v2 = sub_3500();
  v3 = (char *)savedregs - *(_DWORD *)(v2 + 28);
  v4 = *(_DWORD *)(v2 + 20);
  *a2 = v4;
  v5 = v4 + a1;
  if ( v4 + a1 > (unsigned int)v3 )
    return 0;
  v6 = ((unsigned int)&v3[v5] >> 1) & 0x7FFFFFF8 | (__CFADD__(v3, v5) << 31);
  v7 = (v5 + 4103) & 0xFFFFFFF8;
  if ( v7 > v6 )
    v7 = v6;
  *(_DWORD *)(v2 + 20) = v7;
  return v7 - v4;
}

//----- (00003484) --------------------------------------------------------
int sub_3484()
{
  return __semihost(24, (void *)0x20026);
}

//----- (0000349C) --------------------------------------------------------
int __fastcall sub_349C(int a1, int a2, int a3, const char *a4)
{
  return sub_3564(a1, a2, 0xFFFF8187, a4);
}

//----- (00003500) --------------------------------------------------------
int sub_3500()
{
  _DWORD **v0; // r9

  return **v0 + 4;
}
// 3500: variable 'v0' is possibly undefined

//----- (00003518) --------------------------------------------------------
int sub_3518()
{
  int v0; // r9
  int v1; // r0
  int *v3; // [sp+0h] [bp-14h] BYREF
  int v4; // [sp+4h] [bp-10h] BYREF

  v3 = &v4;
  __semihost(22, &v3);
  v1 = v4;
  if ( v4 == 0 )
    v1 = 100;
  return v1 + v0;
}
// 354C: variable 'v0' is possibly undefined

//----- (00003564) --------------------------------------------------------
int __fastcall sub_3564(int a1, int a2, int a3, const char *a4)
{
  const char *v4; // r5
  char *v5; // r2
  const char *v6; // r4
  bool v7; // zf
  int v8; // r1
  int v9; // r2
  int v10; // r3
  char v11; // t1
  char v12; // t1

  v5 = (char *)(a1 - 1);
  if ( (unsigned int)(a1 - 1) >= 0xD )
    v4 = "Unknown signal";
  v6 = (const char *)&unk_3648;
  if ( (unsigned int)(a1 - 1) < 0xD )
  {
    a4 = "Abnormal termination";
    v5 = &aAbnormalTermin[23 * a1];
    v4 = v5 - 23;
    if ( a1 == 2 )
    {
      if ( (a2 & 0x4000000) != 0 )
      {
        v6 = "Invalid Operation";
      }
      else if ( (a2 & 0x8000002) != 0 )
      {
        v6 = "Divide By Zero";
      }
      else if ( (a2 & 0x10000000) != 0 )
      {
        v6 = "Overflow";
      }
      else if ( (a2 & 0x20000000) != 0 )
      {
        v6 = "Underflow";
      }
      else if ( (a2 & 0x40000000) != 0 )
      {
        v6 = "Inexact Result";
      }
    }
    else if ( a1 == 8 )
    {
      v6 = (const char *)a2;
    }
    else
    {
      v7 = a1 == 9;
      if ( a1 == 9 )
        v7 = a2 == 1;
      if ( v7 )
        v4 = ": Heap memory corrupted";
    }
  }
  sub_36D4(10, a2, (int)v5, (int)a4);
  while ( *v4 != 0 )
  {
    v11 = *v4++;
    sub_36D4(v11, v8, v9, v10);
  }
  while ( *v6 != 0 )
  {
    v12 = *v6++;
    sub_36D4(v12, v8, v9, v10);
  }
  sub_36D4(10, v8, v9, v10);
  return 1;
}
// 35F8: variable 'v4' is possibly undefined
// 3608: variable 'v8' is possibly undefined
// 3608: variable 'v9' is possibly undefined
// 3608: variable 'v10' is possibly undefined

//----- (000036C4) --------------------------------------------------------
int sub_36C4()
{
  return sub_3500() + 4;
}

//----- (000036D4) --------------------------------------------------------
int __fastcall sub_36D4(char a1, int a2, int a3, int a4)
{
  int v5; // [sp+0h] [bp-4h] BYREF

  v5 = a4;
  LOBYTE(v5) = a1;
  return __semihost(3, &v5);
}

//----- (000036EC) --------------------------------------------------------
_DWORD *sub_36EC()
{
  _DWORD *result; // r0

  result = (_DWORD *)sub_36C4();
  *result = 0;
  return result;
}

// nfuncs=85 queued=84 decompiled=84 lumina nreq=0 worse=0 better=0
// ALL OK, 84 function(s) have been successfully decompiled
