/* This file was generated by the Hex-Rays decompiler version 9.4.0.260713.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void __noreturn sub_14();
_DWORD *__fastcall sub_280(_DWORD *a1, int a2, int a3, int a4);
int __fastcall sub_374(int a1, _DWORD *a2, int a3, int a4);
int *__fastcall sub_3C8(_DWORD *a1, int a2, int a3, int a4, int a5, int a6);
__int16 *__fastcall sub_494(int a1, int a2, int a3, __int16 *a4, unsigned int a5, unsigned __int8 a6);
_DWORD *__fastcall sub_6D4(int a1, int a2);
int __fastcall sub_70C(int a1);
int __fastcall sub_758(_DWORD *a1, int a2);
void __fastcall sub_790(int a1);
void sub_7B0();
void sub_810();
void sub_870();
void sub_8D8();
int sub_950();
int sub_AE4();
int sub_C04();
BOOL __fastcall sub_C54(int a1, int a2, int a3, int a4, int a5, int a6);
void sub_C80();
_DWORD *sub_E94();
int sub_1000();
int sub_10CC();
int sub_1B3C();
int sub_1ED0();
int sub_1F5C();
int __fastcall sub_2040(int a1, int a2);
int __fastcall sub_20AC(int a1);
int sub_2138();
int __fastcall sub_2210(int a1, int a2);
int __fastcall sub_260C(_DWORD, _DWORD); // weak
int sub_2788();
int sub_27A4();
int __fastcall sub_27BC(int a1, int a2, unsigned __int8 *a3);
void __fastcall sub_29C4(int *a1, int a2, int a3);
int __fastcall sub_2B68(int a1, int a2, int a3);
void __fastcall sub_2BC4(int a1);
int __fastcall sub_2CB0(int a1, int a2, int a3, unsigned __int8 *a4);
int (__fastcall *__fastcall sub_3018(_DWORD *a1, _DWORD *a2))(int a1, int a2, int a3, unsigned __int8 *a4);
void __fastcall sub_3040(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_30E4(int result, int a2);
void __fastcall sub_313C(int *a1);
int __fastcall sub_3174(int a1, _DWORD *a2);
void sub_31C0();
void sub_31E8();
void sub_31FC();
int __fastcall sub_324C(int a1, int a2, int a3, int a4);
void sub_3304();
void __fastcall sub_3318(_BYTE *a1, _DWORD *a2, int **a3);
void sub_343C(_BYTE *a1, ...);
void sub_3488();
void sub_349C();
void sub_3514();
void sub_3528();
void sub_3564(int a1, _BYTE *a2, ...);
void __fastcall sub_35C0(int a1, _BYTE *a2, int **a3);
void sub_3634();
void sub_3710();
int __fastcall sub_39A4(int a1, int a2, int a3, int a4);
int __fastcall sub_39D0(int a1, int a2, int a3, int a4);
int __fastcall sub_3A38(int a1, int a2, int a3, int a4);
void sub_3BD0();
__int64 __fastcall sub_3C48(int a1, int a2, int a3, int a4, __int64 a5);
_DWORD *__fastcall sub_3D34(_DWORD *result, unsigned int a2);
_DWORD *__fastcall sub_3D8C(_BYTE *a1, char *a2, unsigned int a3);
_DWORD *__fastcall sub_3E40(_DWORD *result, char *a2, unsigned int a3, int a4);
int __fastcall sub_3EAC(unsigned int a1, unsigned int a2);
unsigned int __fastcall sub_3F80(int a1);
int sub_3FD0();
int sub_3FE4();
int sub_3FF4();
_UNKNOWN **sub_400C();
void sub_40F0();
int __fastcall sub_4108(int a1, int a2, int a3, const char *a4);
int __fastcall sub_41B0(int a1, _DWORD *a2);
int sub_421C();
int __fastcall sub_4234(int a1, int a2, int a3, const char *a4);
int sub_4298();
int sub_42B0();
int __fastcall sub_42FC(int a1, int a2, int a3, const char *a4);
int sub_445C();
int __fastcall sub_446C(char a1, int a2, int a3, int a4);
_DWORD *sub_4484();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_2BC; // weak
_UNKNOWN loc_2C0; // weak
_UNKNOWN loc_2D0; // weak
_UNKNOWN loc_2FC; // weak
_UNKNOWN *off_4104 = &unk_C0; // weak
_UNKNOWN unk_43E0; // weak
char aAbnormalTermin[21] = "Abnormal termination"; // weak


//----- (00000014) --------------------------------------------------------
void __noreturn sub_14()
{
  JUMPOUT(0xFFFFFB88);
}
// 16: control flows out of bounds to FFFFFB88

//----- (00000280) --------------------------------------------------------
_DWORD *__fastcall sub_280(_DWORD *a1, int a2, int a3, int a4)
{
  _DWORD *result; // r0
  int v6; // r1
  int v7; // r1
  int i; // r2
  _DWORD *v9; // r1
  int v10; // r2
  int v11; // r1
  int j; // r2
  int v13; // [sp+4h] [bp-4h] BYREF

  v13 = a4;
  sub_3D8C(&v13, "zms2c:\\zmaee\\loction.dat", 4u);
  result = a1;
  if ( a1 == nullptr || *a1 != v13 )
    return nullptr;
  a1[2] = a1 + 7;
  v6 = (int)&a1[3 * a1[1] + 7];
  a1[4] = v6;
  a1[6] = v6 + 28 * a1[3];
  v7 = a1[2];
  for ( i = a1[1]; i > 0; --i )
  {
    *(_DWORD *)(v7 + 8) += a1;
    v7 += 12;
  }
  v9 = (_DWORD *)a1[4];
  v10 = a1[3];
  while ( v10 > 0 )
  {
    --v10;
    v9[4] += a1;
    v9[5] += a1;
    v9[6] += a1;
    v9 += 7;
  }
  v11 = a1[6];
  for ( j = a1[5]; j > 0; --j )
  {
    *(_DWORD *)(v11 + 4) += a1;
    v11 += 8;
  }
  return result;
}

//----- (00000374) --------------------------------------------------------
int __fastcall sub_374(int a1, _DWORD *a2, int a3, int a4)
{
  if ( sub_280(a2, (int)a2, a3, a4) == nullptr )
    sub_3528();
  return sub_70C(a1);
}

//----- (000003C8) --------------------------------------------------------
int *__fastcall sub_3C8(_DWORD *a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD *v6; // r6
  bool v7; // cc
  int *v10; // r4
  int *v11; // r0

  v6 = a1;
  v7 = a3 <= 0;
  if ( a3 >= 0 )
    a1 = (_DWORD *)a1[2];
  if ( a3 >= 0 )
    v7 = (int)a1 <= a3;
  v10 = nullptr;
  if ( !v7 )
  {
    sub_31E8();
    v10 = v11;
    sub_3528();
    *v10 = sub_758(v6, a3);
    v10[1] = a3;
    v10[2] = a4;
    v10[3] = 0;
    v10[4] = 0;
    v10[5] = a5;
    v10[6] = a6;
    v10[7] = 0;
    v10[8] = 0;
    v10[9] = 1;
    v10[11] = 0;
    v10[10] = 1;
  }
  return v10;
}
// 400: variable 'v11' is possibly undefined

//----- (00000494) --------------------------------------------------------
__int16 *__fastcall sub_494(int a1, int a2, int a3, __int16 *a4, unsigned int a5, unsigned __int8 a6)
{
  int v7; // r6
  __int16 *result; // r0
  bool v9; // cc
  int v10; // r11
  __int16 *v11; // r4
  __int16 *v12; // r0
  int v13; // r1
  int v14; // r8
  int v15; // r1
  int v16; // r10
  int v17; // r1
  int v18; // r0
  int v19; // [sp+4h] [bp-74h] BYREF
  _DWORD v20[8]; // [sp+38h] [bp-40h] BYREF
  int v21; // [sp+58h] [bp-20h] BYREF
  int v22; // [sp+5Ch] [bp-1Ch]
  int v23; // [sp+60h] [bp-18h]
  int v24; // [sp+64h] [bp-14h]
  int v25; // [sp+68h] [bp-10h]
  int v26; // [sp+6Ch] [bp-Ch]
  int v27; // [sp+70h] [bp-8h]
  __int16 *v28; // [sp+74h] [bp-4h]

  v25 = a1;
  v26 = a2;
  v27 = a3;
  v28 = a4;
  v21 = 0;
  v22 = 0;
  v23 = 0;
  v24 = 0;
  v7 = 0;
  sub_3D34(v20, 0x20u);
  result = v28;
  v9 = v28 != nullptr;
  if ( v28 != nullptr )
  {
    result = *((__int16 **)v28 + 3);
    v9 = (unsigned int)result > a5;
  }
  if ( v9 )
  {
    result = (__int16 *)(*((_DWORD *)v28 + 4) + 28 * a5);
    v10 = *result;
    if ( v10 > 0 )
    {
      v11 = *((__int16 **)result + 4);
      v22 = 0;
      v21 = 0;
      do
      {
        v12 = (__int16 *)(*((_DWORD *)v28 + 2) + 12 * *v11);
        v23 = *v12;
        v24 = v12[1];
        v13 = v11[1];
        if ( (a6 & 2) != 0 )
          v14 = v26 - v13 - *v12;
        else
          v14 = v13 + v26;
        v15 = v11[2];
        if ( (a6 & 1) != 0 )
          v16 = v27 - v15 - v12[1];
        else
          v16 = v15 + v27;
        v17 = ((unsigned __int8)v11[3] ^ a6) & 3;
        if ( (((unsigned __int8)v11[3] ^ a6) & 3) != 0 )
        {
          switch ( v17 )
          {
            case 1:
              v7 = 3;
              break;
            case 2:
              v7 = 1;
              break;
            case 3:
              v7 = 6;
              break;
            default:
              break;
          }
        }
        else
        {
          v7 = 0;
        }
        v20[0] = v23;
        v20[1] = v24;
        v20[3] = 16711935;
        v20[2] = *((_DWORD *)v12 + 1);
        v20[7] = *((_DWORD *)v12 + 2);
        sub_3D34(&v19, 0x34u);
        v18 = (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 48))(a1);
        (*(void (__fastcall **)(int, int, int *))(*(_DWORD *)a1 + 28))(a1, v18, &v19);
        result = (__int16 *)(*(int (__fastcall **)(int, int, int, _DWORD *, int *, int, int))(*(_DWORD *)a1 + 172))(
                              a1,
                              v14,
                              v16,
                              v20,
                              &v21,
                              v7,
                              1);
        v11 += 4;
        --v10;
      }
      while ( v10 != 0 );
    }
  }
  return result;
}

//----- (000006D4) --------------------------------------------------------
_DWORD *__fastcall sub_6D4(int a1, int a2)
{
  _DWORD *v4; // r0
  _DWORD *v5; // r4
  int v6; // r0

  sub_31E8();
  v5 = v4;
  sub_31E8();
  v5[3] = v6;
  v5[2] = 0;
  *v5 = a1;
  v5[1] = a2;
  return v5;
}
// 6E8: variable 'v4' is possibly undefined
// 6F8: variable 'v6' is possibly undefined

//----- (0000070C) --------------------------------------------------------
int __fastcall sub_70C(int a1)
{
  if ( *(_DWORD *)(a1 + 8) < *(_DWORD *)(a1 + 4) )
  {
    sub_3514();
    ++*(_DWORD *)(a1 + 8);
  }
  return *(_DWORD *)(a1 + 8);
}

//----- (00000758) --------------------------------------------------------
int __fastcall sub_758(_DWORD *a1, int a2)
{
  bool v2; // cc

  if ( a1 == nullptr )
    return 0;
  v2 = a2 <= 0;
  if ( a2 >= 0 )
    v2 = a1[2] <= a2;
  if ( v2 )
    return 0;
  else
    return a1[3] + *a1 * a2;
}

//----- (00000790) --------------------------------------------------------
void __fastcall sub_790(int a1)
{
  if ( a1 != 0 )
  {
    sub_31FC();
    sub_31FC();
  }
}

//----- (000007B0) --------------------------------------------------------
void sub_7B0()
{
  sub_3BD0();
}

//----- (00000810) --------------------------------------------------------
void sub_810()
{
  sub_3BD0();
}

//----- (00000870) --------------------------------------------------------
void sub_870()
{
  sub_3BD0();
}

//----- (000008D8) --------------------------------------------------------
void sub_8D8()
{
  sub_3BD0();
}

//----- (00000950) --------------------------------------------------------
int sub_950()
{
  int v0; // r0
  int v1; // r4
  int v2; // r3
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  _DWORD v14[6]; // [sp+0h] [bp-48h] BYREF
  _DWORD v15[12]; // [sp+18h] [bp-30h] BYREF

  sub_3BD0();
  v1 = v0;
  sub_3D34(v15, 0x30u);
  sub_3E40(v14, "c:\\zmaee\\loction.dat", 0x18u, v2);
  v3 = (*(int (__fastcall **)(_DWORD, int))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 1);
  if ( v3 != 0 )
    LOBYTE(v14[0]) = v3;
  v4 = (*(int (__fastcall **)(_DWORD, _DWORD *, int))(**(_DWORD **)(v1 + 84) + 8))(*(_DWORD *)(v1 + 84), v14, 1);
  *(_DWORD *)(v1 + 160) = v4;
  if ( v4 != 0 )
  {
    (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v4 + 8))(v4, v15, 48);
    qmemcpy((void *)(v1 + 184), v15, 44);
    v12 = v15[11];
  }
  else
  {
    v5 = (*(int (__fastcall **)(_DWORD, _DWORD *, int))(**(_DWORD **)(v1 + 84) + 8))(*(_DWORD *)(v1 + 84), v14, 22);
    *(_DWORD *)(v1 + 160) = v5;
    (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v5 + 12))(v5, v15, 48);
    *(_DWORD *)(v1 + 184) = 100;
    sub_7B0();
    *(_DWORD *)(v1 + 188) = v6;
    *(_DWORD *)(v1 + 192) = 240;
    sub_810();
    *(_DWORD *)(v1 + 196) = v7;
    *(_DWORD *)(v1 + 200) = -100;
    sub_870();
    *(_DWORD *)(v1 + 204) = v8;
    *(_DWORD *)(v1 + 208) = 0;
    sub_8D8();
    *(_DWORD *)(v1 + 212) = v9;
    *(_DWORD *)(v1 + 216) = 350;
    sub_810();
    *(_DWORD *)(v1 + 220) = v10 + 50;
    *(_DWORD *)(v1 + 224) = -150;
    sub_870();
    v12 = v11 + 10;
  }
  *(_DWORD *)(v1 + 228) = v12;
  return (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 160) + 4))(*(_DWORD *)(v1 + 160));
}
// 95C: variable 'v0' is possibly undefined
// 97C: variable 'v2' is possibly undefined
// 9FC: variable 'v6' is possibly undefined
// A0C: variable 'v7' is possibly undefined
// A1C: variable 'v8' is possibly undefined
// A2C: variable 'v9' is possibly undefined
// A3C: variable 'v10' is possibly undefined
// A50: variable 'v11' is possibly undefined

//----- (00000AE4) --------------------------------------------------------
int sub_AE4()
{
  int v0; // r0
  int v1; // r4
  char v2; // r5
  int v3; // r0
  int v5; // [sp+0h] [bp-34h] BYREF
  _DWORD v6[12]; // [sp+4h] [bp-30h] BYREF

  sub_3BD0();
  v1 = v0;
  sub_3D34(v6, 0x30u);
  v5 = 0;
  v2 = (*(int (__fastcall **)(_DWORD, int))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 1);
  sub_3634();
  LOBYTE(v5) = v2;
  v3 = (*(int (__fastcall **)(_DWORD, int *, int))(**(_DWORD **)(v1 + 84) + 8))(*(_DWORD *)(v1 + 84), &v5, 4);
  *(_DWORD *)(v1 + 160) = v3;
  if ( v3 != 0 )
  {
    qmemcpy(v6, (const void *)(v1 + 184), sizeof(v6));
    (*(void (__fastcall **)(_DWORD, _DWORD *, int))(**(_DWORD **)(v1 + 160) + 12))(*(_DWORD *)(v1 + 160), v6, 48);
  }
  return (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 160) + 4))(*(_DWORD *)(v1 + 160));
}
// AF0: variable 'v0' is possibly undefined

//----- (00000C04) --------------------------------------------------------
int sub_C04()
{
  int v0; // r0
  int v1; // r4
  int v2; // r0
  int result; // r0

  sub_3BD0();
  v1 = v0;
  sub_349C();
  result = v2 % 4;
  *(_DWORD *)(v1 + 232) = result;
  if ( result != 0 )
  {
    if ( result != 1 && result != 2 )
    {
      if ( result != 3 )
        return result;
      result = 3;
    }
  }
  else
  {
    result = 0;
  }
  *(_DWORD *)(v1 + 176) = result;
  return result;
}
// C0C: variable 'v0' is possibly undefined
// C20: variable 'v2' is possibly undefined

//----- (00000C54) --------------------------------------------------------
BOOL __fastcall sub_C54(int a1, int a2, int a3, int a4, int a5, int a6)
{
  bool v6; // cc

  v6 = a6 < a2;
  if ( a6 >= a2 )
    v6 = a2 + a4 < a6;
  if ( !v6 )
  {
    v6 = a5 < a1;
    if ( a5 >= a1 )
      v6 = a1 + a3 < a5;
  }
  return !v6;
}

//----- (00000C80) --------------------------------------------------------
void sub_C80()
{
  _DWORD *v0; // r0
  _DWORD *v1; // r4
  int v2; // r0
  int v3; // r5
  int v4; // r0
  _DWORD v5[2]; // [sp+4h] [bp-168h] BYREF
  int v6; // [sp+Ch] [bp-160h]
  int v7; // [sp+10h] [bp-15Ch]

  sub_3D34(v5, 0x168u);
  sub_3BD0();
  v1 = v0;
  if ( v0 != nullptr )
  {
    sub_31C0();
    v3 = v2;
    sub_31C0();
    if ( (*(int (__fastcall **)(int, _DWORD *))(*(_DWORD *)v4 + 16))(v3, v5) == 0 )
    {
      if ( v6 == 176 )
      {
        if ( v7 != 220 )
          goto LABEL_23;
        v1[25] = 1;
      }
      if ( v6 == 220 )
      {
        if ( v7 != 176 )
          goto LABEL_23;
        v1[25] = 4;
      }
      if ( v6 == 320 )
      {
        if ( v7 != 480 )
        {
LABEL_16:
          if ( v7 == 320 )
          {
            v1[25] = 7;
LABEL_18:
            if ( v6 == 240 )
            {
              if ( v7 == 320 )
                v1[25] = 2;
              if ( v7 == 400 )
                v1[25] = 3;
            }
          }
LABEL_23:
          if ( v7 == 240 )
          {
            if ( v6 == 320 )
              v1[25] = 5;
            if ( v6 == 400 )
              v1[25] = 6;
          }
          if ( v6 == 360 )
          {
            if ( v7 != 600 )
              goto LABEL_46;
            v1[25] = 10;
          }
          if ( v6 == 600 )
          {
            if ( v7 != 360 )
              goto LABEL_46;
            v1[25] = 11;
          }
          if ( v6 == 288 )
          {
            if ( v7 != 480 )
              goto LABEL_46;
            v1[25] = 12;
          }
          if ( v6 == 480 )
          {
            if ( v7 != 288 )
              goto LABEL_44;
            v1[25] = 13;
          }
          if ( v6 == 272 )
          {
            if ( v7 != 480 )
              goto LABEL_46;
            v1[25] = 14;
          }
          if ( v6 == 480 )
          {
LABEL_44:
            if ( v7 == 272 )
              v1[25] = 15;
          }
LABEL_46:
          v1[22] = v6;
          v1[23] = v7;
          return;
        }
        v1[25] = 8;
      }
      if ( v6 == 480 )
      {
        if ( v7 != 320 )
          goto LABEL_23;
        v1[25] = 9;
      }
      if ( v6 != 320 )
        goto LABEL_18;
      goto LABEL_16;
    }
  }
}
// C98: variable 'v0' is possibly undefined
// CA4: variable 'v2' is possibly undefined
// CAC: variable 'v4' is possibly undefined

//----- (00000E94) --------------------------------------------------------
_DWORD *sub_E94()
{
  int v0; // r0
  int v1; // r4
  int v2; // r0
  int v3; // r6
  int v4; // r0
  int v5; // r5
  int v6; // r0
  int v7; // r1
  int v8; // r2
  int v9; // r3
  _DWORD *result; // r0
  _DWORD v11[16]; // [sp+4h] [bp-40h] BYREF

  sub_3BD0();
  v1 = v0;
  sub_3D34(v11, 0x40u);
  sub_3528();
  sub_3710();
  if ( v2 != 0 )
  {
    v3 = v2 - (v1 + 4);
    sub_3514();
    *((_BYTE *)v11 + v3 + 1) = 0;
    sub_3634();
    sub_3634();
  }
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 1);
  v4 = (*(int (__fastcall **)(_DWORD, _DWORD *, int))(**(_DWORD **)(v1 + 84) + 8))(*(_DWORD *)(v1 + 84), v11, 1);
  *(_DWORD *)(v1 + 156) = v4;
  (*(void (__fastcall **)(int, int, _DWORD))(*(_DWORD *)v4 + 32))(v4, 1, 0);
  v5 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 156) + 36))(*(_DWORD *)(v1 + 156));
  sub_31E8();
  *(_DWORD *)(v1 + 164) = v6;
  sub_3528();
  if ( *(_DWORD *)(v1 + 164) != 0 )
  {
    (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD))(**(_DWORD **)(v1 + 156) + 32))(*(_DWORD *)(v1 + 156), 0, 0);
    (*(void (__fastcall **)(_DWORD, _DWORD, int))(**(_DWORD **)(v1 + 156) + 8))(
      *(_DWORD *)(v1 + 156),
      *(_DWORD *)(v1 + 164),
      v5);
  }
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 156) + 4))(*(_DWORD *)(v1 + 156));
  result = sub_280(*(_DWORD **)(v1 + 164), v7, v8, v9);
  *(_DWORD *)(v1 + 172) = result;
  return result;
}
// EA0: variable 'v0' is possibly undefined
// ED8: variable 'v2' is possibly undefined
// F7C: variable 'v6' is possibly undefined
// FD4: variable 'v7' is possibly undefined
// FD4: variable 'v8' is possibly undefined
// FD4: variable 'v9' is possibly undefined

//----- (00001000) --------------------------------------------------------
int sub_1000()
{
  _DWORD *v0; // r0
  _DWORD *v1; // r4
  int v2; // r0
  int result; // r0
  _DWORD v4[2]; // [sp+8h] [bp-10h] BYREF
  int v5; // [sp+10h] [bp-8h]
  int v6; // [sp+14h] [bp-4h]

  sub_3BD0();
  v1 = v0;
  v5 = 0;
  v6 = 0;
  v4[0] = 0;
  v4[1] = 0;
  v5 = v0[22];
  v6 = v0[23];
  v0[33] = 2 * v0[23] * v0[22];
  sub_31E8();
  v1[34] = v2;
  result = (*(int (__fastcall **)(_DWORD, int, _DWORD *, int, int, _DWORD))(*(_DWORD *)v1[19] + 16))(
             v1[19],
             1,
             v4,
             1,
             v2,
             v1[33]);
  if ( result == 0 )
  {
    (*(void (__fastcall **)(_DWORD, int))(*(_DWORD *)v1[19] + 32))(v1[19], 1);
    return (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD *, _DWORD))(*(_DWORD *)v1[19] + 148))(
             v1[19],
             0,
             0,
             v1[26],
             v4,
             0);
  }
  return result;
}
// 100C: variable 'v0' is possibly undefined
// 1058: variable 'v2' is possibly undefined

//----- (000010CC) --------------------------------------------------------
int sub_10CC()
{
  int v0; // r0
  int v1; // r4
  int result; // r0
  int v3; // r8
  const char *v4; // r0
  int v5; // r0
  int v6; // r8
  const char *v7; // r0
  int v8; // r0
  int v9; // r8
  const char *v10; // r0
  int v11; // r0
  int v12; // r8
  const char *v13; // r0
  int v14; // r0
  int v15; // r8
  const char *v16; // r0
  int v17; // r0
  int v18; // r8
  const char *v19; // r0
  int v20; // r0
  int v21; // r8
  const char *v22; // r0
  int v23; // r0
  int v24; // r8
  const char *v25; // r0
  int v26; // r0
  int v27; // r8
  const char *v28; // r0
  int v29; // r0
  int v30; // r8
  const char *v31; // r0
  int v32; // r0
  int v33; // r8
  const char *v34; // r0
  int v35; // r0
  int v36; // r8
  const char *v37; // r0
  int v38; // r0
  int v39; // r8
  const char *v40; // r0
  int v41; // r0
  int v42; // r8
  const char *v43; // r0
  int v44; // r0
  int v45; // r8
  const char *v46; // r0
  int v47; // r0
  _DWORD v48[64]; // [sp+8h] [bp-100h] BYREF

  sub_3BD0();
  v1 = v0;
  sub_3D34(v48, 0x100u);
  LOBYTE(v48[0]) = (*(int (__fastcall **)(_DWORD, int))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 1);
  if ( LOBYTE(v48[0]) == 0 )
    LOBYTE(v48[0]) = (*(int (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 0);
  if ( LOBYTE(v48[0]) != *(unsigned __int8 *)(v1 + 4) )
    LOBYTE(v48[0]) = *(_BYTE *)(v1 + 4);
  result = *(_DWORD *)(v1 + 100);
  switch ( result )
  {
    case 1:
      sub_3528();
      v3 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v4 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\176X220BG.gif.zbmp", v4, v3);
      v5 = *(_DWORD *)(v1 + 104);
      if ( v5 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 4:
      sub_3528();
      v6 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v7 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\220X176BG.gif.zbmp", v7, v6);
      v8 = *(_DWORD *)(v1 + 104);
      if ( v8 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v8 + 4))(v8);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 2:
      sub_3528();
      v9 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v10 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\240X320BG.gif.zbmp", v10, v9);
      v11 = *(_DWORD *)(v1 + 104);
      if ( v11 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v11 + 4))(v11);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 5:
      sub_3528();
      v12 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v13 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\320X240BG.gif.zbmp", v13, v12);
      v14 = *(_DWORD *)(v1 + 104);
      if ( v14 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v14 + 4))(v14);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 3:
      sub_3528();
      v15 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v16 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\240X400BG.gif.zbmp", v16, v15);
      v17 = *(_DWORD *)(v1 + 104);
      if ( v17 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v17 + 4))(v17);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 6:
      sub_3528();
      v18 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v19 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\400X240BG.gif.zbmp", v19, v18);
      v20 = *(_DWORD *)(v1 + 104);
      if ( v20 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v20 + 4))(v20);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 8:
      sub_3528();
      v21 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v22 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\480X320_S.gif.zbmp", v22, v21);
      v23 = *(_DWORD *)(v1 + 104);
      if ( v23 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v23 + 4))(v23);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 9:
      sub_3528();
      v24 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v25 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\480X320_H.gif.zbmp", v25, v24);
      v26 = *(_DWORD *)(v1 + 104);
      if ( v26 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v26 + 4))(v26);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 7:
      sub_3528();
      v27 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v28 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\320X320.gif.zbmp", v28, v27);
      v29 = *(_DWORD *)(v1 + 104);
      if ( v29 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v29 + 4))(v29);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 10:
      sub_3528();
      v30 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v31 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\360X600.gif.zbmp", v31, v30);
      v32 = *(_DWORD *)(v1 + 104);
      if ( v32 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v32 + 4))(v32);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 11:
      sub_3528();
      v33 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v34 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\600X360.gif.zbmp", v34, v33);
      v35 = *(_DWORD *)(v1 + 104);
      if ( v35 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v35 + 4))(v35);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 12:
      sub_3528();
      v36 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v37 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\288X480.zbmp", v37, v36);
      v38 = *(_DWORD *)(v1 + 104);
      if ( v38 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v38 + 4))(v38);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 13:
      sub_3528();
      v39 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v40 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\480X288.zbmp", v40, v39);
      v41 = *(_DWORD *)(v1 + 104);
      if ( v41 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v41 + 4))(v41);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 14:
      sub_3528();
      v42 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v43 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\272X480.zbmp", v43, v42);
      v44 = *(_DWORD *)(v1 + 104);
      if ( v44 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v44 + 4))(v44);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    case 15:
      sub_3528();
      v45 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
      v46 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
      sub_3564((int)v48 + 1, "%s%08x\\res\\480X272.zbmp", v46, v45);
      v47 = *(_DWORD *)(v1 + 104);
      if ( v47 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v47 + 4))(v47);
      return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
               *(_DWORD *)(v1 + 76),
               v48,
               sub_31E8,
               sub_31FC,
               v1 + 104);
    default:
      break;
  }
  return result;
}
// 10D8: variable 'v0' is possibly undefined

//----- (00001B3C) --------------------------------------------------------
int sub_1B3C()
{
  int v0; // r0
  int v1; // r4
  int v2; // r6
  const char *v3; // r0
  int v4; // r0
  int v5; // r6
  const char *v6; // r0
  int v7; // r0
  int v8; // r6
  const char *v9; // r0
  int v10; // r0
  int v11; // r6
  const char *v12; // r0
  int v13; // r0
  int v14; // r6
  const char *v15; // r0
  int v16; // r0
  _DWORD v18[64]; // [sp+8h] [bp-100h] BYREF

  sub_3BD0();
  v1 = v0;
  sub_3D34(v18, 0x100u);
  LOBYTE(v18[0]) = (*(int (__fastcall **)(_DWORD, int))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 1);
  if ( LOBYTE(v18[0]) == 0 )
    LOBYTE(v18[0]) = (*(int (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(v1 + 84) + 48))(*(_DWORD *)(v1 + 84), 0);
  if ( LOBYTE(v18[0]) != *(unsigned __int8 *)(v1 + 4) )
    LOBYTE(v18[0]) = *(_BYTE *)(v1 + 4);
  sub_3528();
  v2 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
  v3 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
  sub_3564((int)v18 + 1, "%s%08x\\res\\exit.png.zbmp", v3, v2);
  v4 = *(_DWORD *)(v1 + 108);
  if ( v4 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v4 + 4))(v4);
  (*(void (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
    *(_DWORD *)(v1 + 76),
    v18,
    sub_31E8,
    sub_31FC,
    v1 + 108);
  sub_3528();
  v5 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
  v6 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
  sub_3564((int)v18 + 1, "%s%08x\\res\\bubble1.png.zbmp", v6, v5);
  v7 = *(_DWORD *)(v1 + 112);
  if ( v7 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 4))(v7);
  (*(void (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
    *(_DWORD *)(v1 + 76),
    v18,
    sub_31E8,
    sub_31FC,
    v1 + 112);
  sub_3528();
  v8 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
  v9 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
  sub_3564((int)v18 + 1, "%s%08x\\res\\bubble2.png.zbmp", v9, v8);
  v10 = *(_DWORD *)(v1 + 116);
  if ( v10 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v10 + 4))(v10);
  (*(void (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
    *(_DWORD *)(v1 + 76),
    v18,
    sub_31E8,
    sub_31FC,
    v1 + 116);
  sub_3528();
  v11 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
  v12 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
  sub_3564((int)v18 + 1, "%s%08x\\res\\small.png.zbmp", v12, v11);
  v13 = *(_DWORD *)(v1 + 124);
  if ( v13 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 4))(v13);
  (*(void (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
    *(_DWORD *)(v1 + 76),
    v18,
    sub_31E8,
    sub_31FC,
    v1 + 124);
  sub_3528();
  v14 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 44))(*(_DWORD *)(v1 + 72));
  v15 = (const char *)(*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 28))(*(_DWORD *)(v1 + 72));
  sub_3564((int)v18 + 1, "%s%08x\\res\\micro.png.zbmp", v15, v14);
  v16 = *(_DWORD *)(v1 + 120);
  if ( v16 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v16 + 4))(v16);
  return (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(v1 + 76) + 164))(
           *(_DWORD *)(v1 + 76),
           v18,
           sub_31E8,
           sub_31FC,
           v1 + 120);
}
// 1B48: variable 'v0' is possibly undefined

//----- (00001ED0) --------------------------------------------------------
int sub_1ED0()
{
  int v0; // r0
  int v1; // r6
  int i; // r5
  _DWORD *v3; // r4
  int result; // r0
  unsigned int v5; // r0
  unsigned int v6; // r7
  unsigned int v7; // r0
  unsigned int v8; // r8
  char v9; // r0
  int v10; // r1
  int v11; // r1

  sub_3BD0();
  v1 = v0;
  for ( i = 0; i < 15; ++i )
  {
    v3 = (_DWORD *)(v1 + 24 * i);
    result = v3[74];
    if ( result == 0 )
    {
      sub_349C();
      v6 = v5;
      sub_349C();
      v8 = v7;
      sub_349C();
      v3[73] = (v9 & 1) == 0;
      sub_3EAC(*(_DWORD *)(v1 + 88), v6);
      v3[69] = v10;
      result = sub_3EAC(*(_DWORD *)(v1 + 92), v8);
      v3[70] = v11;
      v3[71] = 24;
      v3[74] = 1;
      v3[72] = 24;
    }
  }
  return result;
}
// 1ED8: variable 'v0' is possibly undefined
// 1F00: variable 'v5' is possibly undefined
// 1F08: variable 'v7' is possibly undefined
// 1F10: variable 'v9' is possibly undefined
// 1F2C: variable 'v10' is possibly undefined
// 1F3C: variable 'v11' is possibly undefined

//----- (00001F5C) --------------------------------------------------------
int sub_1F5C()
{
  _DWORD *v0; // r0
  bool v1; // zf
  _DWORD *v2; // r4
  int result; // r0
  int i; // r5
  _DWORD *v5; // r0
  _DWORD v6[4]; // [sp+Ch] [bp-10h] BYREF

  sub_3BD0();
  v2 = v0;
  v1 = v0 == nullptr;
  v6[1] = 0;
  v6[0] = 0;
  result = 24;
  v6[3] = 24;
  v6[2] = 24;
  if ( !v1 )
  {
    result = v2[19];
    v1 = result == 0;
  }
  if ( !v1 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)result + 52))(result);
    for ( i = 0; i < 15; ++i )
    {
      v5 = &v2[6 * i];
      if ( v5[74] == 1 )
      {
        if ( v5[73] == 1 )
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD *, _DWORD))(*(_DWORD *)v2[19] + 148))(
            v2[19],
            v5[69],
            v5[70],
            v2[31],
            v6,
            0);
        else
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD *, _DWORD))(*(_DWORD *)v2[19] + 148))(
            v2[19],
            v5[69],
            v5[70],
            v2[30],
            v6,
            0);
      }
    }
    return (*(int (__fastcall **)(_DWORD))(*(_DWORD *)v2[19] + 56))(v2[19]);
  }
  return result;
}
// 1F68: variable 'v0' is possibly undefined

//----- (00002040) --------------------------------------------------------
int __fastcall sub_2040(int a1, int a2)
{
  unsigned int v4; // r0
  unsigned int v5; // r6
  char v6; // r0
  _DWORD *v7; // r4
  int v8; // r1
  int v9; // r6
  int v10; // r1

  sub_349C();
  v5 = v4;
  sub_349C();
  sub_349C();
  v7 = (_DWORD *)(a1 + 24 * a2);
  v7[73] = (v6 & 1) != 0;
  sub_3EAC(*(_DWORD *)(a1 + 88), v5);
  v9 = v8;
  sub_3F80(v8);
  v7[69] = v9 - v10;
  v7[70] = *(_DWORD *)(a1 + 88);
  v7[71] = 24;
  v7[72] = 24;
  return 24;
}
// 2050: variable 'v4' is possibly undefined
// 205C: variable 'v6' is possibly undefined
// 2080: variable 'v8' is possibly undefined
// 208C: variable 'v10' is possibly undefined

//----- (000020AC) --------------------------------------------------------
int __fastcall sub_20AC(int a1)
{
  int v2; // r4
  int result; // r0
  unsigned int v4; // r0
  int v5; // r1
  int v6; // r1

  v2 = 0;
  while ( 1 )
  {
    result = *(_DWORD *)(a1 + 24 * v2 + 296);
    if ( result == 0 )
      break;
    if ( ++v2 >= 15 )
      return result;
  }
  *(_DWORD *)(a1 + 24 * v2 + 296) = 1;
  sub_349C();
  sub_3EAC(7u, v4);
  if ( v5 != 0 )
  {
    v6 = v2;
  }
  else
  {
    result = sub_2040(a1, v2);
    v6 = v2 + 1;
    if ( v2 + 1 >= 15 )
      return result;
    *(_DWORD *)(a1 + 24 * v6 + 296) = 1;
  }
  return sub_2040(a1, v6);
}
// 20E8: variable 'v4' is possibly undefined
// 20F0: variable 'v5' is possibly undefined

//----- (00002138) --------------------------------------------------------
int sub_2138()
{
  int v0; // r0
  int v1; // r4
  int i; // r6
  int v3; // r7
  _DWORD *v4; // r5
  int v5; // r0
  _DWORD v7[4]; // [sp+8h] [bp-10h] BYREF

  sub_3BD0();
  v1 = v0;
  v7[0] = 0;
  v7[1] = 0;
  v7[2] = 24;
  v7[3] = 24;
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(v0 + 76) + 52))(*(_DWORD *)(v0 + 76));
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(v1 + 76) + 32))(*(_DWORD *)(v1 + 76), 1);
  for ( i = 0; *(_DWORD *)(v1 + 1636) > i; ++i )
  {
    v3 = v1 + 4 * i;
    v4 = *(_DWORD **)(v3 + 636);
    if ( v4 != nullptr )
    {
      (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD *, _DWORD))(**(_DWORD **)(v1 + 76) + 148))(
        *(_DWORD *)(v1 + 76),
        *v4,
        v4[1],
        *(_DWORD *)(v1 + 116),
        v7,
        0);
      v5 = v4[1] - 10;
      v4[1] = v5;
      if ( v5 + 50 <= 0 )
      {
        sub_31FC();
        *(_DWORD *)(v1 + 1640) = 0;
        *(_DWORD *)(v3 + 636) = 0;
      }
    }
  }
  return (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 76) + 56))(*(_DWORD *)(v1 + 76));
}
// 2148: variable 'v0' is possibly undefined

//----- (00002210) --------------------------------------------------------
int __fastcall sub_2210(int a1, int a2)
{
  int v4; // r0
  unsigned int v5; // r10
  _DWORD *v6; // r0
  bool v7; // zf
  _DWORD *v8; // r6
  int result; // r0
  int i; // r7
  _DWORD *v11; // r0
  int v12; // r0
  int v13; // r6
  int j; // r7
  int v15; // r8
  _DWORD *v16; // r5
  int v17; // r0
  int v18; // r1
  bool v19; // cc
  int v20; // r5
  int v21; // r1
  int v22; // r2
  int v23; // r1
  int v24; // r2
  int v25; // r0
  int v26; // r7
  _DWORD *v27; // r6
  int v28; // r0
  char v29; // r0
  int v30; // r0
  int v31; // r0
  int v32; // [sp+Ch] [bp-34h] BYREF
  int v33; // [sp+10h] [bp-30h]
  int v34; // [sp+14h] [bp-2Ch]
  int v35; // [sp+18h] [bp-28h]
  _DWORD v36[5]; // [sp+1Ch] [bp-24h] BYREF
  int v37; // [sp+30h] [bp-10h]
  int v38; // [sp+34h] [bp-Ch]
  int v39; // [sp+38h] [bp-8h]
  int v40; // [sp+3Ch] [bp-4h]

  v37 = 0;
  v38 = 0;
  v39 = 0;
  v40 = 0;
  memset(&v36[1], 0, 16);
  v36[0] = 1;
  v4 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 72))(*(_DWORD *)(a1 + 72));
  v38 = 0;
  v37 = 0;
  v5 = v4;
  v39 = *(_DWORD *)(a1 + 88);
  v40 = *(_DWORD *)(a1 + 92);
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 52))(*(_DWORD *)(a1 + 76));
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 76) + 32))(*(_DWORD *)(a1 + 76), a2);
  (*(void (__fastcall **)(_DWORD, int, _DWORD *, _DWORD))(**(_DWORD **)(a1 + 76) + 176))(
    *(_DWORD *)(a1 + 76),
    1,
    v36,
    0);
  sub_3BD0();
  v8 = v6;
  v7 = v6 == nullptr;
  result = 24;
  v35 = 24;
  v34 = 24;
  v33 = 0;
  v32 = 0;
  if ( !v7 )
  {
    result = v8[19];
    v7 = result == 0;
  }
  if ( !v7 )
  {
    (*(void (__fastcall **)(int, int))(*(_DWORD *)result + 32))(result, a2);
    for ( i = 0; i < 15; ++i )
    {
      v11 = &v8[6 * i];
      if ( v11[74] == 1 )
      {
        if ( v11[73] == 1 )
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, int *, _DWORD))(*(_DWORD *)v8[19] + 148))(
            v8[19],
            v11[69],
            v11[70],
            v8[31],
            &v32,
            0);
        else
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, int *, _DWORD))(*(_DWORD *)v8[19] + 148))(
            v8[19],
            v11[69],
            v11[70],
            v8[30],
            &v32,
            0);
      }
    }
    (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 76) + 32))(*(_DWORD *)(a1 + 76), a2);
    sub_494(
      *(_DWORD *)(a1 + 76),
      *(_DWORD *)(a1 + 184),
      *(_DWORD *)(a1 + 188),
      *(__int16 **)(a1 + 172),
      *(_DWORD *)(a1 + 176),
      0);
    sub_494(
      *(_DWORD *)(a1 + 76),
      *(_DWORD *)(a1 + 192),
      *(_DWORD *)(a1 + 196),
      *(__int16 **)(a1 + 172),
      *(_DWORD *)(a1 + 176) + 1,
      0);
    sub_494(
      *(_DWORD *)(a1 + 76),
      *(_DWORD *)(a1 + 200),
      *(_DWORD *)(a1 + 204),
      *(__int16 **)(a1 + 172),
      *(_DWORD *)(a1 + 176) + 2,
      2u);
    sub_494(
      *(_DWORD *)(a1 + 76),
      *(_DWORD *)(a1 + 208),
      *(_DWORD *)(a1 + 212),
      *(__int16 **)(a1 + 172),
      *(_DWORD *)(a1 + 176) + 3,
      2u);
    if ( *(_DWORD *)(a1 + 264) == 1 )
    {
      sub_3BD0();
      v13 = v12;
      v32 = 0;
      v33 = 0;
      v34 = 24;
      v35 = 24;
      (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(v12 + 76) + 32))(*(_DWORD *)(v12 + 76), a2);
      for ( j = 0; *(_DWORD *)(v13 + 1636) > j; ++j )
      {
        v15 = v13 + 4 * j;
        v16 = *(_DWORD **)(v15 + 636);
        if ( v16 != nullptr )
        {
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, int *, _DWORD))(**(_DWORD **)(v13 + 76) + 148))(
            *(_DWORD *)(v13 + 76),
            *v16,
            v16[1],
            *(_DWORD *)(v13 + 116),
            &v32,
            0);
          v17 = v16[1] - 10;
          v16[1] = v17;
          if ( v17 + 50 <= 0 )
          {
            sub_31FC();
            *(_DWORD *)(v13 + 1640) = 0;
            *(_DWORD *)(v15 + 636) = 0;
          }
        }
      }
    }
    v18 = *(_DWORD *)(a1 + 184) - *(_DWORD *)(a1 + 240);
    *(_DWORD *)(a1 + 184) = v18;
    v19 = v18 < -130;
    if ( v18 < -130 )
    {
      *(_DWORD *)(a1 + 240) = 5;
      v18 = *(_DWORD *)(a1 + 88);
    }
    v20 = 0;
    if ( v19 )
      *(_DWORD *)(a1 + 184) = v18 + 50;
    v21 = *(_DWORD *)(a1 + 192) - *(_DWORD *)(a1 + 244);
    *(_DWORD *)(a1 + 192) = v21;
    if ( v21 < -130 )
    {
      *(_DWORD *)(a1 + 244) = 5;
      *(_DWORD *)(a1 + 192) = *(_DWORD *)(a1 + 88) + 50;
    }
    v22 = *(_DWORD *)(a1 + 200) + *(_DWORD *)(a1 + 248);
    *(_DWORD *)(a1 + 200) = v22;
    v23 = *(_DWORD *)(a1 + 88);
    if ( v22 > v23 + 130 )
    {
      *(_DWORD *)(a1 + 248) = 5;
      *(_DWORD *)(a1 + 200) = -130;
    }
    v24 = *(_DWORD *)(a1 + 208) + *(_DWORD *)(a1 + 252);
    *(_DWORD *)(a1 + 208) = v24;
    if ( v24 > v23 + 120 )
    {
      *(_DWORD *)(a1 + 252) = 5;
      *(_DWORD *)(a1 + 208) = -130;
    }
    do
    {
      sub_349C();
      v26 = v25 % 4;
      v27 = (_DWORD *)(a1 + 24 * v20);
      if ( v27[74] == 1 )
      {
        v28 = v27[70];
        if ( v28 <= -5 )
          v27[74] = 0;
        v27[70] = v28 - 10;
        sub_349C();
        v7 = (v29 & 1) == 0;
        v30 = v27[69];
        if ( v7 )
          v31 = v30 + v26;
        else
          v31 = v30 - v26;
        v27[69] = v31;
      }
      ++v20;
    }
    while ( v20 < 15 );
    if ( *(_DWORD *)(a1 + 272) + 400 < v5 )
    {
      sub_20AC(a1);
      *(_DWORD *)(a1 + 272) = v5;
    }
    return (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 56))(*(_DWORD *)(a1 + 76));
  }
  return result;
}
// 22C8: variable 'v6' is possibly undefined
// 243C: variable 'v12' is possibly undefined
// 2588: variable 'v25' is possibly undefined
// 25B8: variable 'v29' is possibly undefined

//----- (0000260C) --------------------------------------------------------
int sub_260C()
{
  int v0; // r0
  int v1; // r4
  int v2; // r0
  int result; // r0
  int v4; // [sp+8h] [bp-24h] BYREF
  int v5; // [sp+Ch] [bp-20h] BYREF
  int v6; // [sp+10h] [bp-1Ch]
  int v7; // [sp+14h] [bp-18h]
  int v8; // [sp+18h] [bp-14h]
  int v9; // [sp+1Ch] [bp-10h]
  int v10; // [sp+20h] [bp-Ch]
  int v11; // [sp+24h] [bp-8h]
  int v12; // [sp+28h] [bp-4h]

  sub_3BD0();
  v1 = v0;
  v9 = 0;
  v10 = 0;
  v11 = 0;
  v12 = 0;
  v5 = 0;
  v6 = 0;
  v7 = 0;
  v8 = 0;
  v4 = 0;
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(v0 + 72) + 72))(*(_DWORD *)(v0 + 72));
  v10 = 0;
  v9 = 0;
  v11 = *(_DWORD *)(v1 + 88);
  v12 = *(_DWORD *)(v1 + 92);
  if ( *(_DWORD *)(v1 + 1656) == 0 )
  {
    sub_3040(*(_DWORD *)(v1 + 72), 20, (int)sub_260C, 3030, v1, *(_DWORD *)(v1 + 1660));
    *(_DWORD *)(v1 + 1656) = v2;
  }
  if ( *(_DWORD *)(v1 + 96) != 0 )
  {
    sub_2210(v1, 0);
    v8 = 30;
    v7 = 30;
    (*(void (__fastcall **)(_DWORD, int, int, _DWORD, int *, int))(**(_DWORD **)(v1 + 76) + 148))(
      *(_DWORD *)(v1 + 76),
      *(_DWORD *)(v1 + 88) - 30,
      *(_DWORD *)(v1 + 92) - 30,
      *(_DWORD *)(v1 + 108),
      &v5,
      1);
    v5 = 0;
    v6 = 0;
    v7 = *(_DWORD *)(v1 + 88);
    v8 = *(_DWORD *)(v1 + 92);
    v4 = 0;
    (*(void (__fastcall **)(_DWORD, int *, int, int *))(**(_DWORD **)(v1 + 76) + 44))(*(_DWORD *)(v1 + 76), &v5, 1, &v4);
  }
  else if ( *(_DWORD *)(v1 + 128) != 0 )
  {
    *(_DWORD *)(v1 + 128) = 0;
  }
  else
  {
    (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(v1 + 76) + 200))(
      *(_DWORD *)(v1 + 76),
      0,
      0,
      *(_DWORD *)(v1 + 88),
      *(_DWORD *)(v1 + 92));
  }
  result = *(_DWORD *)(v1 + 1640) + 20;
  *(_DWORD *)(v1 + 1640) = result;
  return result;
}
// 2618: variable 'v0' is possibly undefined
// 26A8: variable 'v2' is possibly undefined
// 260C: using guessed type int sub_260C();

//----- (00002788) --------------------------------------------------------
int sub_2788()
{
  sub_10CC();
  sub_1ED0();
  sub_1B3C();
  sub_E94();
  return sub_1000();
}

//----- (000027A4) --------------------------------------------------------
int sub_27A4()
{
  int v0; // r0

  sub_3BD0();
  return sub_260C(-1, v0);
}
// 27B8: variable 'v0' is possibly undefined
// 260C: using guessed type int __fastcall sub_260C(_DWORD, _DWORD);

//----- (000027BC) --------------------------------------------------------
int __fastcall sub_27BC(int a1, int a2, unsigned __int8 *a3)
{
  int *v5; // r0
  int *v6; // r4
  int v7; // r0
  int result; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r0

  sub_3BD0();
  v6 = v5;
  sub_3528();
  sub_31C0();
  v6[18] = v7;
  (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 72))(v7);
  sub_3488();
  result = v6[18];
  if ( result != 0 )
  {
    result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)result + 8))(result, 16777221, v6 + 19);
    if ( result == 0 )
    {
      result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v6[18] + 8))(v6[18], 16777227, v6 + 20);
      if ( result == 0 )
      {
        result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v6[18] + 8))(v6[18], 16777219, v6 + 21);
        if ( result == 0 )
        {
          if ( a2 != 0 || a3 == nullptr )
            goto LABEL_16;
          v9 = *a3;
          if ( v9 == 1 )
          {
            if ( *((_DWORD *)a3 + 64) != 0 )
            {
              v6[24] = 0;
LABEL_15:
              v6[415] = 1;
              goto LABEL_16;
            }
          }
          else if ( v9 == 2 && *((_DWORD *)a3 + 64) != 0 )
          {
            v6[415] = 0;
            v6[24] = 0;
LABEL_16:
            v6[32] = 1;
            v6[414] = 0;
            sub_3040(v6[18], 20, (int)sub_260C, 3030, (int)v6, v6[415]);
            v6[414] = v10;
            sub_C04();
            sub_C80();
            v6[46] = 250;
            sub_7B0();
            v6[47] = v11;
            v6[48] = 300;
            sub_810();
            v6[49] = v12;
            v6[50] = -100;
            sub_870();
            v6[51] = v13;
            v6[52] = 0;
            sub_8D8();
            v6[53] = v14;
            v6[54] = 350;
            sub_810();
            v6[55] = v15 + 50;
            v6[56] = -150;
            sub_870();
            v6[57] = v16 + 10;
            v6[45] = 2;
            v6[66] = 0;
            v6[409] = 0;
            v6[60] = 5;
            v6[410] = 0;
            v6[61] = 5;
            v6[62] = 5;
            v6[63] = 5;
            v6[64] = 5;
            v6[65] = 5;
            sub_2788();
            return sub_27A4();
          }
          v6[24] = 1;
          goto LABEL_15;
        }
      }
    }
  }
  return result;
}
// 27D0: variable 'v5' is possibly undefined
// 27E8: variable 'v7' is possibly undefined
// 28F0: variable 'v10' is possibly undefined
// 2908: variable 'v11' is possibly undefined
// 2918: variable 'v12' is possibly undefined
// 2928: variable 'v13' is possibly undefined
// 2934: variable 'v14' is possibly undefined
// 2944: variable 'v15' is possibly undefined
// 2958: variable 'v16' is possibly undefined
// 260C: using guessed type int __fastcall sub_260C(_DWORD, _DWORD);

//----- (000029C4) --------------------------------------------------------
void __fastcall sub_29C4(int *a1, int a2, int a3)
{
  _DWORD *v6; // r0
  int v7; // r1
  int v8; // r1
  int v9; // r1
  int i; // r5

  if ( sub_C54(a1[46], a1[47], 130, 80, a2, a3) )
  {
    a1[410] = 0;
    a1[60] = 10;
    a1[66] = 1;
    sub_31E8();
    *v6 = a1[46] - 10;
    v7 = a1[47];
LABEL_5:
    v8 = v7 + 10;
    goto LABEL_10;
  }
  if ( sub_C54(a1[48], a1[49], 130, 80, a2, a3) )
  {
    a1[410] = 0;
    a1[61] = 10;
    a1[66] = 1;
    sub_31E8();
    *v6 = a1[48] - 10;
    v7 = a1[49];
    goto LABEL_5;
  }
  if ( sub_C54(a1[50] - 120, a1[51], 130, 80, a2, a3) )
  {
    a1[410] = 0;
    a1[62] = 10;
    a1[66] = 1;
    sub_31E8();
    *v6 = a1[50] - 20;
    v8 = a1[51] + 15;
  }
  else
  {
    if ( !sub_C54(a1[52] - 120, a1[53], 130, 80, a2, a3) )
      return;
    a1[410] = 0;
    a1[63] = 10;
    a1[66] = 1;
    sub_31E8();
    *v6 = a1[52] - 20;
    v8 = a1[53] + 20;
  }
LABEL_10:
  v6[1] = v8;
  if ( v6 != nullptr )
  {
    v9 = a1[409];
    if ( v9 >= 250 )
    {
      for ( i = 0; a1[409] >= i; ++i )
      {
        if ( a1[i + 159] != 0 )
          sub_31FC();
      }
      a1[409] = 0;
    }
    else
    {
      a1[409] = v9 + 1;
      a1[v9 + 159] = (int)v6;
    }
  }
}
// 2A1C: variable 'v6' is possibly undefined

//----- (00002B68) --------------------------------------------------------
int __fastcall sub_2B68(int a1, int a2, int a3)
{
  int result; // r0

  result = *(_DWORD *)(a1 + 96);
  if ( result != 0 )
  {
    result = sub_C54(*(_DWORD *)(a1 + 88) - 30, *(_DWORD *)(a1 + 92) - 30, 30, 30, a2, a3);
    if ( result != 0 )
      return (*(int (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 36))(*(_DWORD *)(a1 + 72), 0);
  }
  return result;
}

//----- (00002BC4) --------------------------------------------------------
void __fastcall sub_2BC4(int a1)
{
  int i; // r5
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int j; // r5
  int v8; // r0

  if ( *(_DWORD *)(a1 + 136) != 0 )
  {
    sub_31FC();
    *(_DWORD *)(a1 + 136) = 0;
  }
  if ( *(_DWORD *)(a1 + 164) != 0 )
  {
    sub_31FC();
    *(_DWORD *)(a1 + 164) = 0;
  }
  for ( i = 0; *(_DWORD *)(a1 + 1636) > i; ++i )
  {
    if ( *(_DWORD *)(a1 + 4 * i + 636) != 0 )
      sub_31FC();
  }
  if ( a1 != 0 )
  {
    v3 = *(_DWORD *)(a1 + 104);
    if ( v3 != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v3 + 4))(v3);
    v4 = *(_DWORD *)(a1 + 108);
    if ( v4 != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v4 + 4))(v4);
    v5 = *(_DWORD *)(a1 + 112);
    if ( v5 != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
    v6 = *(_DWORD *)(a1 + 116);
    if ( v6 != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v6 + 4))(v6);
    for ( j = 0; j < 2; ++j )
    {
      v8 = *(_DWORD *)(a1 + 4 * j + 120);
      if ( v8 != 0 )
        (*(void (__fastcall **)(int))(*(_DWORD *)v8 + 4))(v8);
    }
  }
  sub_313C(*(int **)(a1 + 1656));
  *(_DWORD *)(a1 + 1656) = 0;
}

//----- (00002CB0) --------------------------------------------------------
int __fastcall sub_2CB0(int a1, int a2, int a3, unsigned __int8 *a4)
{
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  _DWORD v14[4]; // [sp+10h] [bp-24h] BYREF
  int v15; // [sp+20h] [bp-14h] BYREF
  int v16; // [sp+24h] [bp-10h] BYREF
  int v17; // [sp+28h] [bp-Ch]
  int v18; // [sp+2Ch] [bp-8h]
  int v19; // [sp+30h] [bp-4h]

  v16 = 0;
  v17 = 0;
  v18 = 0;
  v19 = 0;
  if ( a2 != 0 )
  {
    switch ( a2 )
    {
      case 2:
        (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 76) + 32))(*(_DWORD *)(a1 + 76), 0);
        v17 = 1;
        v16 = 0;
        (*(void (__fastcall **)(_DWORD, int, int *, _DWORD))(**(_DWORD **)(a1 + 76) + 176))(
          *(_DWORD *)(a1 + 76),
          2,
          &v16,
          0);
        sub_313C(*(int **)(a1 + 1656));
        *(_DWORD *)(a1 + 1656) = 0;
        if ( *(_DWORD *)(a1 + 76) != 0 )
        {
          if ( *(_DWORD *)(a1 + 136) != 0 )
          {
            sub_31FC();
            *(_DWORD *)(a1 + 136) = 0;
          }
          v5 = a1 + 4 * *(_DWORD *)(a1 + 1636);
          if ( *(_DWORD *)(v5 + 636) != 0 )
            *(_DWORD *)(v5 + 636) = 0;
          (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 24))(*(_DWORD *)(a1 + 76));
        }
        break;
      case 3:
        sub_C80();
        sub_10CC();
        sub_1ED0();
        sub_1000();
        sub_27A4();
        break;
      case 5:
        if ( a3 == 11 )
          (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 36))(*(_DWORD *)(a1 + 72), 0);
        break;
      case 9:
        sub_29C4((int *)a1, a3, (int)a4);
        break;
      case 10:
        sub_2B68(a1, a3, (int)a4);
        break;
      case 4:
        if ( a3 == 1 )
        {
          if ( *(_DWORD *)(a1 + 76) != 0 )
          {
            if ( *(_DWORD *)(a1 + 136) != 0 )
            {
              sub_31FC();
              *(_DWORD *)(a1 + 136) = 0;
            }
            if ( *(_DWORD *)(a1 + 164) != 0 )
            {
              sub_31FC();
              *(_DWORD *)(a1 + 164) = 0;
            }
            v6 = a1 + 4 * *(_DWORD *)(a1 + 1636);
            if ( *(_DWORD *)(v6 + 636) != 0 )
              *(_DWORD *)(v6 + 636) = 0;
            (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 24))(*(_DWORD *)(a1 + 76));
            sub_313C(*(int **)(a1 + 1656));
            *(_DWORD *)(a1 + 1656) = 0;
            (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 4))(*(_DWORD *)(a1 + 76));
            *(_DWORD *)(a1 + 76) = 0;
            (*(void (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 72) + 8))(
              *(_DWORD *)(a1 + 72),
              16777221,
              a1 + 76);
          }
          sub_C80();
          sub_7B0();
          *(_DWORD *)(a1 + 188) = v7;
          sub_810();
          *(_DWORD *)(a1 + 196) = v8;
          sub_870();
          *(_DWORD *)(a1 + 204) = v9;
          sub_8D8();
          *(_DWORD *)(a1 + 212) = v10;
          *(_DWORD *)(a1 + 216) = 350;
          sub_810();
          *(_DWORD *)(a1 + 220) = v11 + 50;
          *(_DWORD *)(a1 + 224) = -150;
          sub_870();
          *(_DWORD *)(a1 + 228) = v12 + 10;
          sub_10CC();
          sub_E94();
          sub_1000();
          sub_27A4();
        }
        if ( *(_DWORD *)(a1 + 96) == 0 )
        {
          v15 = 0;
          memset(v14, 0, sizeof(v14));
          (*(void (__fastcall **)(_DWORD, int *, _DWORD *))(**(_DWORD **)(a1 + 76) + 192))(
            *(_DWORD *)(a1 + 76),
            &v15,
            v14);
          (*(void (__fastcall **)(_DWORD, int, _DWORD))(**(_DWORD **)(a1 + 76) + 196))(*(_DWORD *)(a1 + 76), 2, v14[0]);
          sub_2210(a1, 2);
          (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 76) + 20))(*(_DWORD *)(a1 + 76), 2);
        }
        break;
      case 1:
        sub_2BC4(a1);
        (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 24))(*(_DWORD *)(a1 + 76));
        (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 76) + 4))(*(_DWORD *)(a1 + 76));
        (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 84) + 4))(*(_DWORD *)(a1 + 84));
        (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 80) + 4))(*(_DWORD *)(a1 + 80));
        (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 4))(*(_DWORD *)(a1 + 72));
        break;
      case 28674:
        sub_30E4(*(_DWORD *)(a1 + 1656), 28674);
        break;
      default:
        break;
    }
  }
  else
  {
    sub_27BC(a1, a3, a4);
  }
  return 1;
}
// 2EB0: variable 'v7' is possibly undefined
// 2EB8: variable 'v8' is possibly undefined
// 2EC0: variable 'v9' is possibly undefined
// 2EC8: variable 'v10' is possibly undefined
// 2ED8: variable 'v11' is possibly undefined
// 2EEC: variable 'v12' is possibly undefined

//----- (00003018) --------------------------------------------------------
int (__fastcall *__fastcall sub_3018(_DWORD *a1, _DWORD *a2))(int a1, int a2, int a3, unsigned __int8 *a4)
{
  *a1 = 1664;
  *a2 = 0;
  a2[1] = 0;
  a2[2] = sub_2CB0;
  return sub_2CB0;
}

//----- (00003040) --------------------------------------------------------
void __fastcall sub_3040(int a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD *v10; // r0
  _DWORD *v11; // r4

  sub_31E8();
  v11 = v10;
  if ( v10 != nullptr )
  {
    sub_3528();
    *v11 = a1;
    v11[1] = a5;
    v11[5] = a2;
    v11[7] = a3;
    v11[4] = a4;
    v11[6] = (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 72))(a1);
    v11[3] = -1;
    if ( a6 != 0 )
      v11[3] = (*(int (__fastcall **)(_DWORD, _DWORD, int (__fastcall *)(int, _DWORD *), _DWORD))(*(_DWORD *)*v11 + 60))(
                 *v11,
                 v11[5],
                 sub_3174,
                 v11[4]);
  }
}
// 3064: variable 'v10' is possibly undefined

//----- (000030E4) --------------------------------------------------------
int __fastcall sub_30E4(int result, int a2)
{
  int v2; // r5
  int v3; // r4

  v2 = result;
  v3 = result;
  if ( a2 == 28674 )
  {
    result = (*(int (**)(void))(**(_DWORD **)result + 72))();
    if ( (unsigned int)(result - *(_DWORD *)(v3 + 24)) >= *(_DWORD *)(v3 + 20) )
    {
      *(_DWORD *)(v3 + 24) = result;
      return (*(int (__fastcall **)(int, _DWORD))(v3 + 28))(v2, *(_DWORD *)(v3 + 4));
    }
  }
  return result;
}

//----- (0000313C) --------------------------------------------------------
void __fastcall sub_313C(int *a1)
{
  if ( a1 != nullptr )
  {
    if ( a1[3] >= 0 )
      (*(void (**)(void))(*(_DWORD *)*a1 + 64))();
    a1[3] = -1;
    sub_31FC();
  }
}

//----- (00003174) --------------------------------------------------------
int __fastcall sub_3174(int a1, _DWORD *a2)
{
  int result; // r0

  ((void (__fastcall *)(_DWORD, _DWORD))a2[7])(0, a2[1]);
  result = (*(int (__fastcall **)(_DWORD, _DWORD, int (*)(), _DWORD))(*(_DWORD *)*a2 + 60))(*a2, a2[5], sub_3174, a2[4]);
  a2[3] = result;
  return result;
}

//----- (000031C0) --------------------------------------------------------
void sub_31C0()
{
  JUMPOUT(0xE12FFF1E);
}
// 31D0: control flows out of bounds to E12FFF1E

//----- (000031E8) --------------------------------------------------------
void sub_31E8()
{
  JUMPOUT(0xE8980002);
}
// 31F8: control flows out of bounds to E8980002

//----- (000031FC) --------------------------------------------------------
void sub_31FC()
{
  JUMPOUT(0xE0800008);
}
// 320C: control flows out of bounds to E0800008

//----- (0000324C) --------------------------------------------------------
int __fastcall sub_324C(int a1, int a2, int a3, int a4)
{
  return MEMORY[0xA000012](a1, a2, a3, a4);
}

//----- (00003304) --------------------------------------------------------
void sub_3304()
{
  JUMPOUT(0xE3140000);
}
// 3314: control flows out of bounds to E3140000

//----- (00003318) --------------------------------------------------------
void __fastcall sub_3318(_BYTE *a1, _DWORD *a2, int **a3)
{
  int v4; // r5
  unsigned __int8 *v6; // r0
  unsigned __int8 *v7; // r1
  unsigned int v8; // r0
  bool v9; // zf
  int *v10; // r0
  int v11; // r3
  int v12; // r0
  _DWORD *v13; // r2
  int v14; // r1
  bool v15; // zf
  int v16; // r2

  v4 = 0;
  while ( 1 )
  {
    v14 = (unsigned __int8)*a1;
    if ( *a1 == 0 )
      break;
    ++a1;
    if ( v14 == 37 )
    {
      if ( *a1 == 37 )
      {
        ++a1;
      }
      else
      {
        sub_3304();
        if ( v6 == nullptr )
          return;
        v7 = v6;
        v8 = *v6;
        if ( v8 == 111 )
        {
LABEL_23:
          v16 = *(*a3)++;
          a2[2 * v4 + 1] = v16;
          goto LABEL_15;
        }
        if ( v8 > 0x6F )
        {
          v15 = v8 == 112;
          if ( v8 != 112 )
            v15 = v8 == 115;
          if ( v15 || v8 == 117 || v8 == 120 )
            goto LABEL_23;
        }
        else
        {
          v9 = v8 == 88;
          if ( v8 != 88 )
            v9 = v8 == 99;
          if ( !v9 )
            v9 = v8 == 100;
          if ( v9 )
            goto LABEL_23;
          if ( v8 == 102 )
          {
            v10 = *a3;
            *a3 += 2;
            v11 = *v10;
            v12 = v10[1];
            v13 = &a2[2 * v4];
            v13[1] = v11;
            v13[2] = v12;
          }
        }
LABEL_15:
        a1 = v7 + 1;
        ++v4;
      }
    }
  }
  *a2 = v4;
}
// 3354: variable 'v6' is possibly undefined

//----- (0000343C) --------------------------------------------------------
void sub_343C(_BYTE *a1, ...)
{
  int v1; // r0
  int *v2; // [sp+4h] [bp-88h] BYREF
  _DWORD v3[33]; // [sp+8h] [bp-84h] BYREF
  _BYTE *varg_r0; // [sp+90h] [bp+4h]
  va_list varg_r1; // [sp+94h] [bp+8h] BYREF

  va_start(varg_r1, a1);
  varg_r0 = a1;
  va_copy((va_list)v2, varg_r1);
  sub_3318(a1, v3, &v2);
  if ( v1 != 0 )
    MEMORY[0xE3150002](varg_r0, v3);
}
// 3464: variable 'v1' is possibly undefined

//----- (00003488) --------------------------------------------------------
void sub_3488()
{
  JUMPOUT(0x10855008);
}
// 3498: control flows out of bounds to 10855008

//----- (0000349C) --------------------------------------------------------
void sub_349C()
{
  JUMPOUT(0xE3C55002);
}
// 34AC: control flows out of bounds to E3C55002

//----- (00003514) --------------------------------------------------------
void sub_3514()
{
  JUMPOUT(0x28B4000C);
}
// 3524: control flows out of bounds to 28B4000C

//----- (00003528) --------------------------------------------------------
void sub_3528()
{
  JUMPOUT(0x28A5000C);
}
// 3538: control flows out of bounds to 28A5000C

//----- (00003564) --------------------------------------------------------
void sub_3564(int a1, _BYTE *a2, ...)
{
  int v3; // r0
  int *v4; // [sp+0h] [bp-88h] BYREF
  _DWORD v5[33]; // [sp+4h] [bp-84h] BYREF
  _BYTE *varg_r1; // [sp+94h] [bp+Ch]
  va_list varg_r2; // [sp+98h] [bp+10h] BYREF

  va_start(varg_r2, a2);
  varg_r1 = a2;
  va_copy((va_list)v4, varg_r2);
  sub_3318(a2, v5, &v4);
  if ( v3 != 0 )
    MEMORY[0xEAFFFFE8](a1, varg_r1, v5);
}
// 3590: variable 'v3' is possibly undefined

//----- (000035C0) --------------------------------------------------------
void __fastcall sub_35C0(int a1, _BYTE *a2, int **a3)
{
  int v5; // r0
  _DWORD v6[33]; // [sp+0h] [bp-84h] BYREF

  sub_3318(a2, v6, a3);
  if ( v5 != 0 )
    MEMORY[0xEAFFFFE8](a1, a2, v6);
}
// 35E0: variable 'v5' is possibly undefined

//----- (00003634) --------------------------------------------------------
void sub_3634()
{
  JUMPOUT(0xE0822008);
}
// 3644: control flows out of bounds to E0822008

//----- (00003710) --------------------------------------------------------
void sub_3710()
{
  JUMPOUT(0x1084400C);
}
// 3720: control flows out of bounds to 1084400C

//----- (000039A4) --------------------------------------------------------
int __fastcall sub_39A4(int a1, int a2, int a3, int a4)
{
  return loc_2BC(a1, a2, a3, a4);
}

//----- (000039D0) --------------------------------------------------------
int __fastcall sub_39D0(int a1, int a2, int a3, int a4)
{
  return loc_2C0(a1, a2, a3, a4);
}

//----- (00003A38) --------------------------------------------------------
int __fastcall sub_3A38(int a1, int a2, int a3, int a4)
{
  return loc_2D0(a1, a2, a3, a4);
}

//----- (00003BD0) --------------------------------------------------------
void sub_3BD0()
{
  __asm { BX              R0 }
}

//----- (00003C48) --------------------------------------------------------
__int64 __fastcall sub_3C48(int a1, int a2, int a3, int a4, __int64 a5)
{
  loc_2FC(a1, a2, a3, a4);
  return a5;
}

//----- (00003D34) --------------------------------------------------------
_DWORD *__fastcall sub_3D34(_DWORD *result, unsigned int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  _DWORD *v4; // r0
  int v5; // r1
  int v6; // r1
  _BYTE *v7; // r0

  v2 = a2 >= 0x20;
  v3 = a2 - 32;
  do
  {
    if ( !v2 )
      break;
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    v4 = result + 4;
    *v4 = 0;
    v4[1] = 0;
    v4[2] = 0;
    v4[3] = 0;
    result = v4 + 4;
    v2 = v3 >= 0x20;
    v3 -= 32;
  }
  while ( v2 );
  v2 = __CFSHL__(v3, 28);
  v5 = v3 << 28;
  if ( v2 )
  {
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    result += 4;
  }
  if ( v5 < 0 )
  {
    *result = 0;
    result[1] = 0;
    result += 2;
  }
  v2 = __CFSHL__(v5, 2);
  v6 = 4 * v5;
  if ( v2 )
    *result++ = 0;
  if ( v6 != 0 )
  {
    if ( v6 < 0 )
    {
      *(_BYTE *)result = 0;
      v7 = (char *)result + 1;
      *v7 = 0;
      result = v7 + 1;
    }
    if ( (v6 & 0x40000000) != 0 )
    {
      *(_BYTE *)result = 0;
      return (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (00003D8C) --------------------------------------------------------
_DWORD *__fastcall sub_3D8C(_BYTE *a1, char *a2, unsigned int a3)
{
  unsigned int v3; // r12
  char v4; // r3
  char v5; // t1
  bool v6; // cf
  bool v7; // cc
  unsigned int v8; // r2
  char v9; // t1
  char v10; // t1
  unsigned int v11; // r3
  unsigned int v13; // r2
  char *v14; // r1
  unsigned int v15; // r12
  unsigned int v16; // t1
  unsigned int v17; // r3
  unsigned int v18; // t1
  unsigned int v19; // r3
  unsigned int v20; // t1
  unsigned int v21; // r3
  unsigned int v22; // t1

  if ( a3 <= 3 )
    goto LABEL_22;
  v3 = (unsigned __int8)a1 & 3;
  if ( ((unsigned __int8)a1 & 3) != 0 )
  {
    v5 = *a2++;
    v4 = v5;
    v6 = v3 >= 2;
    v7 = ((unsigned __int8)a1 & 3) == 3;
    v8 = a3 + v3;
    if ( ((unsigned __int8)a1 & 3) != 3 )
    {
      v9 = *a2++;
      LOBYTE(v3) = v9;
    }
    *a1++ = v4;
    if ( !v6 )
    {
      v10 = *a2++;
      v4 = v10;
    }
    a3 = v8 - 4;
    if ( !v7 )
      *a1++ = v3;
    if ( !v6 )
      *a1++ = v4;
  }
  v11 = (unsigned __int8)a2 & 3;
  if ( ((unsigned __int8)a2 & 3) != 0 )
  {
    v6 = a3 >= 4;
    v13 = a3 - 4;
    if ( v6 )
    {
      v16 = *(_DWORD *)&a2[-v11];
      v14 = &a2[-v11];
      v15 = v16;
      if ( v11 == 2 )
      {
        do
        {
          v19 = HIWORD(v15);
          v20 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v20;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v19 | (v20 << 16);
          a1 += 4;
        }
        while ( v6 );
      }
      else if ( v11 > 2 )
      {
        do
        {
          v21 = HIBYTE(v15);
          v22 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v22;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v21 | (v22 << 8);
          a1 += 4;
        }
        while ( v6 );
      }
      else
      {
        do
        {
          v17 = v15 >> 8;
          v18 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v18;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v17 | (v18 << 24);
          a1 += 4;
        }
        while ( v6 );
      }
    }
LABEL_22:
    JUMPOUT(0x3E8C);
  }
  return sub_3E40(a1, a2, a3, 0);
}
// 3D90: control flows out of bounds to 3E8C

//----- (00003E40) --------------------------------------------------------
_DWORD *__fastcall sub_3E40(_DWORD *result, char *a2, unsigned int a3, int a4)
{
  bool v4; // cf
  unsigned int i; // r2
  _DWORD *v6; // r1
  int v7; // r3
  int v8; // r4
  int v9; // r12
  int v10; // lr
  _DWORD *v11; // r0
  int v12; // r4
  int v13; // r12
  int v14; // lr
  int v15; // r4
  int v16; // r12
  int v17; // lr
  int v18; // r4
  char v19; // r12
  int v20; // t1
  bool v21; // cf
  bool v22; // nf
  int v23; // r2
  char v24; // t1
  _BYTE *v25; // r0

  v4 = a3 >= 0x20;
  for ( i = a3 - 32; v4; i -= 32 )
  {
    if ( !v4 )
      break;
    v7 = *(_DWORD *)a2;
    v8 = *((_DWORD *)a2 + 1);
    v9 = *((_DWORD *)a2 + 2);
    v10 = *((_DWORD *)a2 + 3);
    v6 = a2 + 16;
    *result = v7;
    result[1] = v8;
    result[2] = v9;
    result[3] = v10;
    v11 = result + 4;
    a4 = *v6;
    v12 = v6[1];
    v13 = v6[2];
    v14 = v6[3];
    a2 = (char *)(v6 + 4);
    *v11 = a4;
    v11[1] = v12;
    v11[2] = v13;
    v11[3] = v14;
    result = v11 + 4;
    v4 = i >= 0x20;
  }
  if ( __CFSHL__(i, 28) )
  {
    a4 = *(_DWORD *)a2;
    v15 = *((_DWORD *)a2 + 1);
    v16 = *((_DWORD *)a2 + 2);
    v17 = *((_DWORD *)a2 + 3);
    a2 += 16;
    *result = a4;
    result[1] = v15;
    result[2] = v16;
    result[3] = v17;
    result += 4;
  }
  if ( (i & 8) != 0 )
  {
    a4 = *(_DWORD *)a2;
    v18 = *((_DWORD *)a2 + 1);
    a2 += 8;
    *result = a4;
    result[1] = v18;
    result += 2;
  }
  v19 = 0;
  if ( __CFSHL__(i, 30) )
  {
    v20 = *(_DWORD *)a2;
    a2 += 4;
    LOBYTE(a4) = v20;
    *result++ = v20;
  }
  if ( i << 30 != 0 )
  {
    v21 = __CFSHL__(i, 31);
    v23 = i << 31;
    v22 = v23 < 0;
    if ( v23 < 0 )
    {
      v24 = *a2++;
      LOBYTE(v23) = v24;
    }
    if ( v21 )
    {
      LOBYTE(a4) = *a2;
      v19 = a2[1];
    }
    if ( v22 )
    {
      *(_BYTE *)result = v23;
      result = (_DWORD *)((char *)result + 1);
    }
    if ( v21 )
    {
      *(_BYTE *)result = a4;
      v25 = (char *)result + 1;
      *v25 = v19;
      return v25 + 1;
    }
  }
  return result;
}

//----- (00003EAC) --------------------------------------------------------
int __fastcall sub_3EAC(unsigned int a1, unsigned int a2)
{
  unsigned int v2; // r2
  int v3; // r3
  char v4; // cf
  bool v5; // cf
  unsigned int v6; // r2
  bool v7; // cf
  unsigned int v8; // r2
  bool v9; // cf
  unsigned int v10; // r2
  bool v11; // cf
  bool v12; // cf
  bool v13; // cf
  unsigned int v14; // r2
  bool v15; // cf
  unsigned int v16; // r2
  bool v17; // cf
  unsigned int v18; // off

  v2 = a1 & 0x80000000;
  if ( (a1 & 0x80000000) != 0 )
    a1 = -a1;
  v3 = v2 ^ ((int)a2 >> 31);
  if ( (a2 & 0x80000000) != 0 )
    a2 = -a2;
  if ( a2 >> 3 < a1 )
    goto LABEL_27;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF000000;
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF0000u;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 |= 0xFF00u;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  v4 = a1 == 0;
  if ( a1 == 0 )
    return sub_4108(2, 2, v2, (const char *)v3);
  do
  {
    if ( v4 )
      a1 >>= 8;
LABEL_15:
    v5 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v6 = v2 + v5 + v2;
    v7 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v8 = v6 + v7 + v6;
    v9 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v10 = v8 + v9 + v8;
    v11 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v10 + v11 + v10;
LABEL_24:
    v12 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v12 + v2;
LABEL_27:
    v13 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v14 = v2 + v13 + v2;
    v15 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v16 = v14 + v15 + v14;
    v17 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v18 = v17 + v16;
    v4 = __CFADD__(v17, v16) | __CFADD__(v16, v18);
    v2 = v16 + v18;
  }
  while ( v4 );
  return (v2 ^ (v3 >> 31)) + ((unsigned int)v3 >> 31);
}

//----- (00003F80) --------------------------------------------------------
unsigned int __fastcall sub_3F80(int a1)
{
  int v1; // r3
  int v2; // r1
  unsigned int v3; // r0
  unsigned int result; // r0

  v1 = a1;
  if ( a1 < 0 )
    a1 = -a1;
  v2 = a1 - 10;
  v3 = a1 - ((unsigned int)a1 >> 2) + ((a1 - ((unsigned int)a1 >> 2)) >> 4);
  result = (v3 + (v3 >> 8) + ((v3 + (v3 >> 8)) >> 16)) >> 3;
  if ( (int)(v2 - 10 * result) >= 0 )
    ++result;
  if ( v1 < 0 )
    return -result;
  return result;
}

//----- (00003FD0) --------------------------------------------------------
int sub_3FD0()
{
  sub_40F0();
  return sub_3FE4();
}

//----- (00003FF4) --------------------------------------------------------
int sub_3FF4()
{
  return sub_3FD0();
}

//----- (0000400C) --------------------------------------------------------
_UNKNOWN **sub_400C()
{
  _DWORD *v0; // r4

  sub_4484();
  v0 = (_DWORD *)sub_4298();
  v0[8] = 0;
  v0[9] = 1;
  v0[10] = 0;
  v0[11] = 0;
  v0[12] = 0;
  return &off_4104;
}
// 40E0: returning address of temporary local variable '%var_C'
// 4104: using guessed type _UNKNOWN *off_4104;

//----- (000040F0) --------------------------------------------------------
void sub_40F0()
{
  ;
}

//----- (00004108) --------------------------------------------------------
int __fastcall sub_4108(int a1, int a2, int a3, const char *a4)
{
  int result; // r0

  result = sub_4234(a1, a2, a3, a4);
  if ( result != 0 )
    return sub_421C();
  return result;
}

//----- (000041B0) --------------------------------------------------------
int __fastcall sub_41B0(int a1, _DWORD *a2)
{
  int v2; // r4
  char *v3; // r3
  int v4; // r2
  int v5; // lr
  unsigned int v6; // r3
  unsigned int v7; // r1
  _DWORD savedregs[2]; // [sp+8h] [bp+0h] BYREF

  v2 = sub_4298();
  v3 = (char *)savedregs - *(_DWORD *)(v2 + 28);
  v4 = *(_DWORD *)(v2 + 20);
  *a2 = v4;
  v5 = v4 + a1;
  if ( v4 + a1 > (unsigned int)v3 )
    return 0;
  v6 = ((unsigned int)&v3[v5] >> 1) & 0x7FFFFFF8 | (__CFADD__(v3, v5) << 31);
  v7 = (v5 + 4103) & 0xFFFFFFF8;
  if ( v7 > v6 )
    v7 = v6;
  *(_DWORD *)(v2 + 20) = v7;
  return v7 - v4;
}

//----- (0000421C) --------------------------------------------------------
int sub_421C()
{
  return __semihost(24, (void *)0x20026);
}

//----- (00004234) --------------------------------------------------------
int __fastcall sub_4234(int a1, int a2, int a3, const char *a4)
{
  return sub_42FC(a1, a2, 0xFFFF8187, a4);
}

//----- (00004298) --------------------------------------------------------
int sub_4298()
{
  _DWORD **v0; // r9

  return **v0 + 4;
}
// 4298: variable 'v0' is possibly undefined

//----- (000042B0) --------------------------------------------------------
int sub_42B0()
{
  int v0; // r9
  int v1; // r0
  int *v3; // [sp+0h] [bp-14h] BYREF
  int v4; // [sp+4h] [bp-10h] BYREF

  v3 = &v4;
  __semihost(22, &v3);
  v1 = v4;
  if ( v4 == 0 )
    v1 = 100;
  return v1 + v0;
}
// 42E4: variable 'v0' is possibly undefined

//----- (000042FC) --------------------------------------------------------
int __fastcall sub_42FC(int a1, int a2, int a3, const char *a4)
{
  const char *v4; // r5
  char *v5; // r2
  const char *v6; // r4
  bool v7; // zf
  int v8; // r1
  int v9; // r2
  int v10; // r3
  char v11; // t1
  char v12; // t1

  v5 = (char *)(a1 - 1);
  if ( (unsigned int)(a1 - 1) >= 0xD )
    v4 = "Unknown signal";
  v6 = (const char *)&unk_43E0;
  if ( (unsigned int)(a1 - 1) < 0xD )
  {
    a4 = "Abnormal termination";
    v5 = &aAbnormalTermin[23 * a1];
    v4 = v5 - 23;
    if ( a1 == 2 )
    {
      if ( (a2 & 0x4000000) != 0 )
      {
        v6 = "Invalid Operation";
      }
      else if ( (a2 & 0x8000002) != 0 )
      {
        v6 = "Divide By Zero";
      }
      else if ( (a2 & 0x10000000) != 0 )
      {
        v6 = "Overflow";
      }
      else if ( (a2 & 0x20000000) != 0 )
      {
        v6 = "Underflow";
      }
      else if ( (a2 & 0x40000000) != 0 )
      {
        v6 = "Inexact Result";
      }
    }
    else if ( a1 == 8 )
    {
      v6 = (const char *)a2;
    }
    else
    {
      v7 = a1 == 9;
      if ( a1 == 9 )
        v7 = a2 == 1;
      if ( v7 )
        v4 = ": Heap memory corrupted";
    }
  }
  sub_446C(10, a2, (int)v5, (int)a4);
  while ( *v4 != 0 )
  {
    v11 = *v4++;
    sub_446C(v11, v8, v9, v10);
  }
  while ( *v6 != 0 )
  {
    v12 = *v6++;
    sub_446C(v12, v8, v9, v10);
  }
  sub_446C(10, v8, v9, v10);
  return 1;
}
// 4390: variable 'v4' is possibly undefined
// 43A0: variable 'v8' is possibly undefined
// 43A0: variable 'v9' is possibly undefined
// 43A0: variable 'v10' is possibly undefined

//----- (0000445C) --------------------------------------------------------
int sub_445C()
{
  return sub_4298() + 4;
}

//----- (0000446C) --------------------------------------------------------
int __fastcall sub_446C(char a1, int a2, int a3, int a4)
{
  int v5; // [sp+0h] [bp-4h] BYREF

  v5 = a4;
  LOBYTE(v5) = a1;
  return __semihost(3, &v5);
}

//----- (00004484) --------------------------------------------------------
_DWORD *sub_4484()
{
  _DWORD *result; // r0

  result = (_DWORD *)sub_445C();
  *result = 0;
  return result;
}

// nfuncs=82 queued=80 decompiled=80 lumina nreq=0 worse=0 better=0
// ALL OK, 80 function(s) have been successfully decompiled
