/* This file was generated by the Hex-Rays decompiler version 9.4.0.260713.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

_DWORD *sub_80274();
_DWORD *sub_80290();
_DWORD *sub_802AC();
_DWORD *sub_802C8();
int __fastcall sub_802EC(int result);
_DWORD *__fastcall sub_804C4(_DWORD *result, int a2, int a3, int a4);
int __fastcall sub_80604(int result);
int __fastcall sub_8060C(int a1);
_DWORD *__fastcall sub_8062C(int a1, _DWORD *a2);
_DWORD *__fastcall sub_806F8(_DWORD *result, _DWORD *a2);
int __fastcall sub_8071C(_DWORD *a1, int a2, int a3);
int __fastcall sub_80790(int a1, int a2);
int sub_807C8();
_DWORD *__fastcall sub_8081C(int a1);
int __fastcall sub_81160(int a1);
int __fastcall sub_81290(int a1);
int __fastcall sub_812BC(int a1);
void *__fastcall sub_81300(int a1, _BYTE *a2);
int sub_81474();
int sub_81670();
int __fastcall sub_818B8(int a1, int a2, int a3);
int __fastcall sub_81ABC(int a1);
_DWORD *__fastcall sub_81FD8(int a1);
int __fastcall sub_82138(int a1, int a2, int a3);
_DWORD *__fastcall sub_821D0(int a1);
_DWORD *__fastcall sub_822DC(int a1, int a2);
int __fastcall sub_82330(int result, int a2);
int __fastcall sub_82424(int *a1);
int sub_82584();
int __fastcall sub_826EC(int a1);
int __fastcall sub_827DC(int a1, int a2);
void __fastcall __spoils<R2,R3,R12,LR> sub_82954(int a1, int a2, int a3, int a4);
int __fastcall sub_82AB0(int a1, int a2, int a3, _DWORD *a4);
int (__fastcall *__fastcall sub_82E24(_DWORD *a1, int (__fastcall **a2)(int a1)))(int a1, int a2, int a3, _DWORD *a4);
int sub_82E54();
int __fastcall sub_82E68(int a1);
int __fastcall sub_82E80(int a1);
int __fastcall sub_82E98(int a1);
int __fastcall sub_82EBC(_DWORD *a1);
int __fastcall sub_82FF8(int a1, int a2, int a3, int a4);
int __fastcall sub_8313C(int a1, _DWORD *a2);
int __fastcall sub_831B0(int a1, unsigned __int8 *a2, int a3, int a4);
int __fastcall sub_83260(_DWORD *a1);
int __fastcall sub_836A4(int a1, int a2, int a3, int a4);
int __fastcall sub_8395C(int a1);
int __fastcall sub_83C60(int a1);
int __fastcall sub_83D44(int *a1);
int *__fastcall sub_83E24(_DWORD *a1);
BOOL __fastcall sub_83F50(int a1);
int __fastcall sub_841D4(int a1);
BOOL __fastcall sub_8433C(int a1, int a2, _DWORD *a3);
int sub_843E8();
int sub_84410();
int sub_84424();
int sub_84460();
int __fastcall sub_84474(int a1, int a2, int a3, int a4);
int sub_844C0();
int sub_84538();
int __fastcall sub_8454C(_BYTE *a1, _DWORD *a2, int **a3);
int sub_84670(_BYTE *a1, ...);
int sub_8470C();
int sub_84748();
int sub_8475C();
int sub_84798(int a1, _BYTE *a2, ...);
int __fastcall sub_847F4(int a1, _BYTE *a2, int **a3);
int sub_84854();
int sub_84868();
int sub_8487C();
int sub_84890();
int sub_848A4();
int sub_848B8();
int sub_848CC();
int sub_848E0();
int sub_84944();
int sub_8496C();
int sub_849BC();
int sub_849E4();
int sub_84A0C();
int sub_84A34();
int __fastcall sub_84BD8(int a1, int a2, int a3, int a4);
int __fastcall sub_84C04(int a1, int a2, int a3, int a4);
int __fastcall sub_84C6C(int a1, int a2, int a3, int a4);
void sub_84D94();
void sub_84DA4();
int sub_84E04();
__int64 __fastcall sub_84E7C(int a1, int a2, int a3, int a4, __int64 a5);
int __fastcall sub_84F60(int a1, int a2);
int __fastcall sub_84FD8(int a1, const char *a2, _DWORD *a3, int a4);
int __fastcall sub_85128(int a1, const char *a2);
int *__fastcall sub_85248(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_85340(int result);
int __fastcall sub_853A8(int a1);
int __fastcall sub_853C0(int a1, const char *a2, int a3);
int __fastcall sub_8540C(int a1, const char *a2, _DWORD *a3);
int __fastcall sub_85510(int a1, int a2, int a3);
_DWORD *__fastcall sub_8562C(_DWORD *result, unsigned int a2);
int __fastcall sub_85684(unsigned int a1, unsigned int a2);
int __fastcall sub_85758(unsigned int a1, unsigned int a2);
unsigned int __fastcall sub_85818(int a1);
int sub_85868();
int sub_8587C();
int sub_8588C();
_UNKNOWN **sub_858A4();
void sub_85988();
int __fastcall sub_859A0(int a1, int a2, int a3, const char *a4);
int __fastcall sub_85A48(int a1, _DWORD *a2);
int sub_85AB4();
int __fastcall sub_85ACC(int a1, int a2, int a3, const char *a4);
int sub_85B30();
int sub_85B48();
int __fastcall sub_85B94(int a1, int a2, int a3, const char *a4);
int sub_85CF4();
int __fastcall sub_85D04(char a1, int a2, int a3, int a4);
_DWORD *sub_85D1C();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN *off_8599C = (_UNKNOWN *)0xC0; // weak
_UNKNOWN unk_85C78; // weak
_UNKNOWN unk_85D30; // weak
_UNKNOWN unk_85D36; // weak
_UNKNOWN unk_85D3C; // weak
_UNKNOWN unk_85D42; // weak
_UNKNOWN unk_85D48; // weak
_UNKNOWN unk_85D50; // weak
_UNKNOWN unk_85DB8; // weak
_UNKNOWN unk_85E3E; // weak
_UNKNOWN unk_85E48; // weak
_UNKNOWN unk_85E52; // weak
char aAbnormalTermin[21] = "Abnormal termination"; // weak


//----- (00080274) --------------------------------------------------------
_DWORD *sub_80274()
{
  _DWORD v1[16]; // [sp+4h] [bp-40h] BYREF

  return sub_8562C(v1, 0x40u);
}

//----- (00080290) --------------------------------------------------------
_DWORD *sub_80290()
{
  _DWORD v1[16]; // [sp+4h] [bp-40h] BYREF

  return sub_8562C(v1, 0x40u);
}

//----- (000802AC) --------------------------------------------------------
_DWORD *sub_802AC()
{
  _DWORD v1[16]; // [sp+4h] [bp-40h] BYREF

  return sub_8562C(v1, 0x40u);
}

//----- (000802C8) --------------------------------------------------------
_DWORD *sub_802C8()
{
  _DWORD v1[256]; // [sp+4h] [bp-400h] BYREF

  return sub_8562C(v1, 0x400u);
}

//----- (000802EC) --------------------------------------------------------
int __fastcall sub_802EC(int result)
{
  int v1; // r8
  unsigned __int16 *v2; // r7
  unsigned __int8 *v3; // r4
  bool v4; // zf
  unsigned int v5; // r11
  int v6; // r1
  int v7; // r0
  int v8; // r6
  unsigned int v9; // r5
  int v10; // r0
  int v11; // r5
  int v12; // r6
  int v13; // r2
  int v14; // r10
  int v15; // r1
  __int16 v16; // [sp+Ch] [bp-2Ch] BYREF
  __int16 v17; // [sp+Eh] [bp-2Ah]
  _BYTE v18[4]; // [sp+10h] [bp-28h] BYREF
  int v19; // [sp+14h] [bp-24h] BYREF
  _DWORD v20[4]; // [sp+18h] [bp-20h] BYREF
  int v21; // [sp+28h] [bp-10h]
  int v22; // [sp+2Ch] [bp-Ch]
  int v23; // [sp+30h] [bp-8h]
  int v24; // [sp+34h] [bp-4h]

  v2 = *(unsigned __int16 **)(result + 20);
  v3 = (unsigned __int8 *)result;
  v4 = v2 == nullptr;
  if ( v2 != nullptr )
  {
    v1 = *(_DWORD *)(result + 24);
    v4 = v1 == 0;
  }
  if ( v4 )
    return result;
  v5 = *(_DWORD *)(result + 28);
  if ( *(_DWORD *)(result + 48) == 0 )
    (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(result + 56) + 112))(
      *(_DWORD *)(result + 56),
      *(_DWORD *)(result + 4),
      *(_DWORD *)(result + 8),
      *(_DWORD *)(result + 12),
      *(_DWORD *)(result + 16),
      *(_DWORD *)(result + 36));
  v6 = *v3;
  v21 = *((_DWORD *)v3 + 1) + v6;
  v7 = v3[1];
  v8 = *((_DWORD *)v3 + 2) + v7;
  v23 = *((_DWORD *)v3 + 3) - v6 - v3[2];
  v9 = *((_DWORD *)v3 + 4) - v7 - v3[3];
  v10 = sub_85684(v5, v9);
  v11 = v8 + ((int)(v9 - v5 * v10) >> 1);
  v22 = v11;
  v12 = v21;
  v13 = *((_DWORD *)v3 + 8);
  v20[3] = v5;
  if ( v13 > 0 )
    v11 -= v5 * v10 * v13;
  v24 = v22 + v5 * v10;
  while ( 1 )
  {
    if ( v1 < 1 )
    {
      result = 1;
      goto LABEL_22;
    }
    if ( v24 <= v11 )
      break;
    v14 = *v2;
    v16 = *v2;
    v17 = 0;
    (*(void (__fastcall **)(_DWORD, __int16 *, int, int *, _BYTE *))(**((_DWORD **)v3 + 14) + 76))(
      *((_DWORD *)v3 + 14),
      &v16,
      1,
      &v19,
      v18);
    if ( v21 + v23 < v19 + v12 )
    {
      if ( v14 != 10 )
        goto LABEL_14;
      goto LABEL_13;
    }
    if ( v14 == 10 )
    {
LABEL_13:
      ++v2;
      --v1;
LABEL_14:
      v11 += v5;
      v12 = v21;
    }
    else
    {
      v20[2] = v19;
      ++v2;
      --v1;
      v20[1] = v11;
      v20[0] = v12;
      if ( v22 <= v11 )
      {
        v15 = *((_DWORD *)v3 + 10);
        v16 = v14;
        v17 = 0;
        (*(void (__fastcall **)(_DWORD, _DWORD *, __int16 *, int, int, _DWORD, int))(**((_DWORD **)v3 + 14) + 80))(
          *((_DWORD *)v3 + 14),
          v20,
          &v16,
          1,
          v15,
          0,
          17);
      }
      v12 += v19;
    }
  }
  result = 0;
LABEL_22:
  *((_DWORD *)v3 + 11) = result;
  return result;
}
// E: found interdependent unknown calls
// 8042C: variable 'v1' is possibly undefined

//----- (000804C4) --------------------------------------------------------
_DWORD *__fastcall sub_804C4(_DWORD *result, int a2, int a3, int a4)
{
  bool v4; // zf
  _DWORD *v5; // r4
  int v6; // r5
  bool v7; // zf
  bool v8; // zf
  bool v9; // zf

  v4 = a2 == 9;
  if ( a2 != 9 )
    v4 = a2 == 11;
  if ( !v4 )
    v4 = a2 == 10;
  v5 = result;
  if ( v4 )
  {
    if ( a2 == 9 )
    {
      result[13] = a4;
      return result;
    }
    if ( a2 == 10 )
    {
      v6 = a4 - result[13];
      sub_802C8();
      result = sub_802AC();
      if ( v6 <= 20 )
      {
        if ( v6 >= -20 )
          return result;
        result = (_DWORD *)v5[11];
        if ( result != nullptr )
          return result;
        ++v5[8];
      }
      else
      {
        result = (_DWORD *)v5[8];
        if ( (int)result <= 0 )
          return result;
        v5[8] = (char *)result - 1;
      }
      return sub_802C8();
    }
  }
  else
  {
    v7 = a2 == 5;
    if ( a2 != 5 )
      v7 = a2 == 6;
    if ( v7 && a2 != 5 )
    {
      v8 = a3 == 14;
      if ( a3 != 14 )
        v8 = a3 == 8;
      if ( v8 )
      {
        result = (_DWORD *)result[11];
        if ( result == nullptr )
        {
          result = (_DWORD *)(v5[8] + 1);
LABEL_35:
          v5[8] = result;
        }
      }
      else
      {
        v9 = a3 == 13;
        if ( a3 != 13 )
          v9 = a3 == 2;
        if ( v9 )
        {
          result = (_DWORD *)result[8];
          if ( (int)result > 0 )
          {
            result = (_DWORD *)((char *)result - 1);
            goto LABEL_35;
          }
        }
      }
    }
  }
  return result;
}

//----- (00080604) --------------------------------------------------------
int __fastcall sub_80604(int result)
{
  if ( result != 0 )
    return sub_8060C();
  return result;
}
// 8060C: using guessed type int sub_8060C(void);

//----- (0008060C) --------------------------------------------------------
int __fastcall sub_8060C(int a1)
{
  if ( *(_DWORD *)(a1 + 20) != 0 )
    sub_84424();
  return sub_84424();
}

//----- (0008062C) --------------------------------------------------------
_DWORD *__fastcall sub_8062C(int a1, _DWORD *a2)
{
  _DWORD *v4; // r4

  v4 = (_DWORD *)sub_84410();
  sub_8475C();
  v4[15] = sub_802EC;
  v4[16] = sub_80604;
  v4[17] = sub_804C4;
  v4[14] = a1;
  v4[1] = *a2;
  v4[2] = a2[1];
  v4[3] = a2[2];
  v4[4] = a2[3];
  *v4 = 101058054;
  v4[7] = (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 72))(a1) + 8;
  v4[8] = 0;
  v4[5] = 0;
  v4[10] = -1;
  v4[6] = 0;
  v4[12] = 1;
  v4[13] = 0;
  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 64))(a1, 1);
  return v4;
}

//----- (000806F8) --------------------------------------------------------
_DWORD *__fastcall sub_806F8(_DWORD *result, _DWORD *a2)
{
  result[1] = *a2;
  result[2] = a2[1];
  result[3] = a2[2];
  result[4] = a2[3];
  return result;
}

//----- (0008071C) --------------------------------------------------------
int __fastcall sub_8071C(_DWORD *a1, int a2, int a3)
{
  if ( a1[5] != 0 )
    sub_84424();
  a1[5] = sub_84410();
  sub_84748();
  *(_WORD *)(a1[5] + 2 * a3) = 0;
  a1[6] = a3;
  a1[8] = 0;
  return 0;
}

//----- (00080790) --------------------------------------------------------
int __fastcall sub_80790(int a1, int a2)
{
  int result; // r0

  result = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 56) + 72))(*(_DWORD *)(a1 + 56)) + a2;
  *(_DWORD *)(a1 + 28) = result;
  return result;
}

//----- (000807C8) --------------------------------------------------------
int sub_807C8()
{
  unsigned int i; // r4

  for ( i = 0; sub_848E0() > i; ++i )
    ;
  return sub_84748();
}

//----- (0008081C) --------------------------------------------------------
_DWORD *__fastcall sub_8081C(int a1)
{
  int v2; // r5
  int v3; // r0
  int v4; // r6
  int v5; // r7
  int i; // r5
  int v7; // r5
  int v8; // r5
  int v9; // r0
  int v10; // lr
  int v11; // r0
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r1
  int v17; // r0
  int v18; // r0
  int v19; // r2
  int v20; // r1
  int v21; // r0
  int v22; // r1
  int v23; // r2
  int v24; // r1
  int v25; // r2
  int v26; // r0
  int v27; // r1
  int v28; // r0
  int v29; // r0
  int v30; // r1
  char v32[40]; // [sp+Ch] [bp-20Ch] BYREF
  int v33; // [sp+174h] [bp-A4h] BYREF
  int v34; // [sp+178h] [bp-A0h]
  int v35; // [sp+194h] [bp-84h] BYREF
  int v36; // [sp+198h] [bp-80h] BYREF
  int v37; // [sp+19Ch] [bp-7Ch]
  int v38; // [sp+1A0h] [bp-78h]
  int v39; // [sp+1A4h] [bp-74h]
  int v40; // [sp+1A8h] [bp-70h] BYREF
  int v41; // [sp+1ACh] [bp-6Ch]
  int v42; // [sp+1B0h] [bp-68h]
  int v43; // [sp+1B4h] [bp-64h]
  _DWORD v44[16]; // [sp+1B8h] [bp-60h] BYREF
  int v45[8]; // [sp+1F8h] [bp-20h] BYREF

  sub_8562C(v45, 0x20u);
  sub_8562C(v44, 0x40u);
  sub_8475C();
  v2 = sub_843E8();
  v3 = sub_843E8();
  (*(void (__fastcall **)(int, char *))(*(_DWORD *)v3 + 16))(v2, v32);
  (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 0);
  v4 = 2;
  sub_807C8();
  sub_848B8();
  sub_84868();
  if ( (*(int (__fastcall **)(_DWORD, _DWORD *, int (*)(), int (*)(), int *))(**(_DWORD **)(a1 + 72) + 164))(
         *(_DWORD *)(a1 + 72),
         v44,
         sub_84410,
         sub_84424,
         &v35) == 0 )
  {
    (*(void (__fastcall **)(int, int *))(*(_DWORD *)v35 + 16))(v35, &v33);
    v40 = 0;
    v42 = v33;
    v41 = 0;
    v5 = 0;
    v43 = v34;
    while ( *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12) > v5 )
    {
      for ( i = 0; *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) > i; i += v42 )
        (*(void (__fastcall **)(_DWORD, int, int, int, int *, _DWORD))(**(_DWORD **)(a1 + 72) + 148))(
          *(_DWORD *)(a1 + 72),
          i,
          v5,
          v35,
          &v40,
          0);
      v5 += v43;
    }
    (*(void (__fastcall **)(int))(*(_DWORD *)v35 + 4))(v35);
  }
  if ( *(int *)(*(_DWORD *)(a1 + 76) + 12) > 176 )
  {
    sub_8475C();
    sub_848B8();
    sub_84868();
    if ( (*(int (__fastcall **)(_DWORD, _DWORD *, int (*)(), int (*)(), int *))(**(_DWORD **)(a1 + 72) + 164))(
           *(_DWORD *)(a1 + 72),
           v44,
           sub_84410,
           sub_84424,
           &v35) == 0 )
    {
      sub_8475C();
      (*(void (__fastcall **)(int, int *))(*(_DWORD *)v35 + 16))(v35, &v33);
      v40 = 0;
      v42 = v33;
      v41 = 0;
      v7 = 0;
      v43 = v34;
      v4 = v34;
      while ( *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) > v7 )
      {
        (*(void (__fastcall **)(_DWORD, int, _DWORD, int, int *, _DWORD))(**(_DWORD **)(a1 + 72) + 148))(
          *(_DWORD *)(a1 + 72),
          v7,
          0,
          v35,
          &v40,
          0);
        v7 += v42;
      }
      (*(void (__fastcall **)(int))(*(_DWORD *)v35 + 4))(v35);
    }
    sub_8475C();
    sub_848B8();
    sub_84868();
    if ( (*(int (__fastcall **)(_DWORD, _DWORD *, int (*)(), int (*)(), int *))(**(_DWORD **)(a1 + 72) + 164))(
           *(_DWORD *)(a1 + 72),
           v44,
           sub_84410,
           sub_84424,
           &v35) == 0 )
    {
      sub_8475C();
      (*(void (__fastcall **)(int, int *))(*(_DWORD *)v35 + 16))(v35, &v33);
      v40 = 0;
      v42 = v33;
      v41 = 0;
      v43 = v34;
      (*(void (__fastcall **)(_DWORD, int, _DWORD, int, int *, _DWORD))(**(_DWORD **)(a1 + 72) + 148))(
        *(_DWORD *)(a1 + 72),
        (*(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - v33) / 2,
        0,
        v35,
        &v40,
        0);
      (*(void (__fastcall **)(int))(*(_DWORD *)v35 + 4))(v35);
    }
  }
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 68))(*(_DWORD *)(a1 + 72));
  v8 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 72))(*(_DWORD *)(a1 + 72));
  v40 = 0;
  v41 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12) - v8;
  v42 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8);
  v43 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12) - v41;
  if ( *(_DWORD *)(a1 + 84) == 2 )
  {
    v9 = sub_84A34();
    (*(void (__fastcall **)(_DWORD, int *, void *, int, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 80))(
      *(_DWORD *)(a1 + 72),
      &v40,
      &unk_85D3C,
      v9,
      -1,
      0,
      1);
    v10 = sub_84A34();
    (*(void (__fastcall **)(_DWORD, int *, void *, int, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 80))(
      *(_DWORD *)(a1 + 72),
      &v40,
      &unk_85D42,
      v10,
      -1,
      0,
      2);
  }
  else
  {
    v11 = sub_84A34();
    (*(void (__fastcall **)(_DWORD, int *, void *, int, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 80))(
      *(_DWORD *)(a1 + 72),
      &v40,
      &unk_85D30,
      v11,
      -1,
      0,
      1);
    v12 = sub_84A34();
    (*(void (__fastcall **)(_DWORD, int *, void *, int, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 80))(
      *(_DWORD *)(a1 + 72),
      &v40,
      &unk_85D36,
      v12,
      -1,
      0,
      2);
  }
  if ( *(_DWORD *)(a1 + 84) != 2 )
  {
    if ( *(int *)(*(_DWORD *)(a1 + 76) + 12) < 220 )
    {
      v41 = v4 + 1;
      v40 = 2;
      v42 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - 2;
      v13 = v8 + 1;
    }
    else
    {
      v40 = 8;
      v41 = v4 + 12;
      v42 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - 8;
      v13 = v8 + 3;
    }
    v43 = v13;
    v14 = sub_84A34();
    (*(void (__fastcall **)(_DWORD, int *, void *, int, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 80))(
      *(_DWORD *)(a1 + 72),
      &v40,
      &unk_85D48,
      v14,
      -1,
      0,
      1);
    v36 = v40 - 6;
    if ( sub_84890() != 0 || sub_84890() != 0 )
    {
      v18 = *(_DWORD *)(a1 + 76);
      if ( *(int *)(v18 + 8) >= 176 )
      {
        v22 = v40;
        if ( *(int *)(v18 + 12) < 220 )
        {
          v23 = v40 + 2 * v8 + 4;
          *(_DWORD *)(a1 + 216) = v23;
          v24 = v41;
          *(_DWORD *)(a1 + 220) = v41;
          *(_DWORD *)(a1 + 224) = *(_DWORD *)(v18 + 8) - v23 - 2;
          *(_DWORD *)(a1 + 228) = v8 + 1;
          v21 = v24 + v8 + 1;
        }
        else
        {
          *(_DWORD *)(a1 + 216) = v40;
          v25 = v41 + v43;
          *(_DWORD *)(a1 + 220) = v41 + v43;
          *(_DWORD *)(a1 + 224) = *(_DWORD *)(v18 + 8) - v22 - 2;
          *(_DWORD *)(a1 + 228) = v8 + 1;
          v21 = v25 + v8 + 1 - 3;
        }
      }
      else
      {
        v19 = v40 + 2 * v8 + 2;
        *(_DWORD *)(a1 + 216) = v19;
        v20 = v41;
        *(_DWORD *)(a1 + 220) = v41;
        *(_DWORD *)(a1 + 224) = *(_DWORD *)(v18 + 8) - v19 - 1;
        *(_DWORD *)(a1 + 228) = v8;
        v21 = v20 + v8;
      }
      v37 = v21;
      if ( sub_8496C() == 0 && sub_8496C() == 0 && sub_8496C() == 0 && sub_8496C() == 0 )
      {
        if ( sub_8496C() == 0 )
        {
LABEL_42:
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int))(**(_DWORD **)(a1 + 72) + 112))(
            *(_DWORD *)(a1 + 72),
            *(_DWORD *)(a1 + 216),
            *(_DWORD *)(a1 + 220),
            *(_DWORD *)(a1 + 224),
            *(_DWORD *)(a1 + 228),
            -1);
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 104))(
            *(_DWORD *)(a1 + 72),
            *(_DWORD *)(a1 + 216),
            *(_DWORD *)(a1 + 220),
            *(_DWORD *)(a1 + 216) + *(_DWORD *)(a1 + 224),
            *(_DWORD *)(a1 + 220),
            -65536);
          (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, int, int))(**(_DWORD **)(a1 + 72) + 104))(
            *(_DWORD *)(a1 + 72),
            *(_DWORD *)(a1 + 216),
            *(_DWORD *)(a1 + 220),
            *(_DWORD *)(a1 + 216),
            *(_DWORD *)(a1 + 220) + *(_DWORD *)(a1 + 228),
            -65536);
          (*(void (__fastcall **)(_DWORD, _DWORD, int, int, int, int))(**(_DWORD **)(a1 + 72) + 104))(
            *(_DWORD *)(a1 + 72),
            *(_DWORD *)(a1 + 216),
            *(_DWORD *)(a1 + 220) + *(_DWORD *)(a1 + 228),
            *(_DWORD *)(a1 + 216) + *(_DWORD *)(a1 + 224),
            *(_DWORD *)(a1 + 220) + *(_DWORD *)(a1 + 228),
            -65536);
          (*(void (__fastcall **)(_DWORD, int, _DWORD, int, int, int))(**(_DWORD **)(a1 + 72) + 104))(
            *(_DWORD *)(a1 + 72),
            *(_DWORD *)(a1 + 216) + *(_DWORD *)(a1 + 224),
            *(_DWORD *)(a1 + 220),
            *(_DWORD *)(a1 + 216) + *(_DWORD *)(a1 + 224),
            *(_DWORD *)(a1 + 220) + *(_DWORD *)(a1 + 228),
            -65536);
          goto LABEL_43;
        }
        v29 = v40 + 2 * v8 + 3;
        *(_DWORD *)(a1 + 216) = v29;
        v30 = v41;
        *(_DWORD *)(a1 + 220) = v41;
        *(_DWORD *)(a1 + 224) = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - v29 - 2;
        *(_DWORD *)(a1 + 228) = v8;
        v28 = v30 + v8;
LABEL_41:
        v37 = v28;
        goto LABEL_42;
      }
      v26 = v40;
      *(_DWORD *)(a1 + 216) = v40;
      v27 = v41 + v43;
      *(_DWORD *)(a1 + 220) = v41 + v43;
      *(_DWORD *)(a1 + 224) = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - v26 - 2;
      *(_DWORD *)(a1 + 228) = v8;
      v17 = v27 + v8;
    }
    else
    {
      v15 = v40;
      *(_DWORD *)(a1 + 216) = v40;
      v16 = v41 + v43;
      *(_DWORD *)(a1 + 220) = v41 + v43;
      *(_DWORD *)(a1 + 224) = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - v15 - 3;
      *(_DWORD *)(a1 + 228) = v8 + 3;
      v17 = v16 + v8 + 3;
    }
    v28 = v17 - 3;
    goto LABEL_41;
  }
  v36 = 2;
  v37 = v4;
LABEL_43:
  v38 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8) - v36 - 3;
  v39 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12) - v37 - v8;
  return sub_806F8(*(_DWORD **)(a1 + 80), &v36);
}

//----- (00081160) --------------------------------------------------------
int __fastcall sub_81160(int a1)
{
  int v2; // r0

  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 1);
  (*(void (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 72) + 84))(*(_DWORD *)(a1 + 72), 1, -65536);
  (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int))(**(_DWORD **)(a1 + 72) + 112))(
    *(_DWORD *)(a1 + 72),
    0,
    0,
    *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8),
    *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12),
    -65536);
  sub_802C8();
  sub_802AC();
  sub_802AC();
  sub_802AC();
  sub_802AC();
  sub_802C8();
  sub_84A34();
  sub_802AC();
  v2 = sub_84A34();
  (*(void (__fastcall **)(_DWORD, int, int, int, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 80))(
    *(_DWORD *)(a1 + 72),
    a1 + 216,
    a1 + 88,
    v2,
    -16777216,
    0,
    20);
  return (*(int (**)(void))(*(_DWORD *)(a1 + 80) + 60))();
}

//----- (00081290) --------------------------------------------------------
int __fastcall sub_81290(int a1)
{
  int v2; // r2

  v2 = sub_84A34();
  return sub_8071C(*(_DWORD **)(a1 + 80), (int)&unk_85D50, v2);
}

//----- (000812BC) --------------------------------------------------------
int __fastcall sub_812BC(int a1)
{
  return (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 40))(
           *(_DWORD *)(a1 + 72),
           0,
           0,
           *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8));
}

//----- (00081300) --------------------------------------------------------
void *__fastcall sub_81300(int a1, _BYTE *a2)
{
  int v3; // r12
  void *result; // r0

  sub_84748();
  if ( *a2 != 49 )
    return (void *)sub_849BC();
  v3 = (unsigned __int8)a2[1];
  result = &unk_85DB8;
  if ( v3 == 51 )
  {
    switch ( a2[2] )
    {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto LABEL_10;
      default:
        return result;
    }
  }
  if ( v3 != 53 )
  {
    if ( v3 == 56 )
    {
      switch ( a2[2] )
      {
        case '0':
        case '1':
        case '2':
        case '3':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
          goto LABEL_10;
        default:
          return (void *)sub_849BC();
      }
    }
    else if ( v3 == 52 )
    {
LABEL_10:
      sub_849BC();
      sub_849BC();
    }
    return (void *)sub_849BC();
  }
  switch ( a2[2] )
  {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto LABEL_10;
    default:
      return result;
  }
}

//----- (00081474) --------------------------------------------------------
int sub_81474()
{
  int v0; // r4
  int v1; // r0
  int v2; // r4
  unsigned int v3; // r8
  unsigned int v4; // r6
  unsigned int v5; // r7
  unsigned int v6; // r5
  unsigned __int16 v8; // [sp+4h] [bp-C0h] BYREF
  __int16 v9; // [sp+10h] [bp-B4h] BYREF
  _DWORD v10[16]; // [sp+14h] [bp-B0h] BYREF
  _DWORD v11[8]; // [sp+54h] [bp-70h] BYREF
  _BYTE v12[8]; // [sp+74h] [bp-50h] BYREF
  int v13; // [sp+7Ch] [bp-48h]
  int v14; // [sp+C0h] [bp-4h] BYREF

  v14 = 0;
  sub_8562C(v11, 0x20u);
  sub_8562C(v10, 0x40u);
  v9 = -1;
  sub_807C8();
  sub_848B8();
  sub_84868();
  v0 = sub_843E8();
  v1 = sub_843E8();
  if ( (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v1 + 8))(v0, 16777219, &v14) == 0 )
  {
    (*(void (__fastcall **)(int, _DWORD *, _BYTE *))(*(_DWORD *)v14 + 12))(v14, v10, v12);
    v2 = (*(int (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v14 + 8))(v14, v10, 1);
    sub_8475C();
    sub_84748();
    v3 = (unsigned __int16)sub_84854();
    if ( v2 != 0 )
    {
      v4 = 0;
      v5 = (unsigned __int16)v13 >> 2;
      while ( v4 <= v5 )
      {
        v6 = (v4 + v5) >> 1;
        if ( v6 == 0 )
          break;
        (*(void (__fastcall **)(int, _DWORD, unsigned int))(*(_DWORD *)v2 + 32))(v2, 0, 4 * v6 - 4);
        (*(void (__fastcall **)(int, unsigned __int16 *, int))(*(_DWORD *)v2 + 8))(v2, &v8, 2);
        if ( v3 >= v8 )
        {
          if ( v3 <= v8 )
          {
            (*(void (__fastcall **)(int, __int16 *, int))(*(_DWORD *)v2 + 8))(v2, &v9, 2);
            break;
          }
          v4 = (v6 + 1) & 0xFFFEFFFF;
        }
        else
        {
          v5 = (unsigned __int16)(v6 - 1);
        }
      }
      (*(void (__fastcall **)(int))(*(_DWORD *)v2 + 4))(v2);
    }
    if ( v14 != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v14 + 4))(v14);
  }
  return v9;
}

//----- (00081670) --------------------------------------------------------
int sub_81670()
{
  unsigned int v0; // r0
  int v1; // r1
  int v2; // r6
  int result; // r0
  __int16 v4; // r5
  int v5; // r4
  int v6; // r0
  int v7; // r0
  int v8; // r4
  int v9; // r0
  int v10; // r4
  int v11; // [sp+4h] [bp-90h] BYREF
  _DWORD v12[8]; // [sp+8h] [bp-8Ch] BYREF
  __int16 v13; // [sp+28h] [bp-6Ch] BYREF
  int v14; // [sp+2Ch] [bp-68h]
  int v15; // [sp+30h] [bp-64h]
  _DWORD v16[16]; // [sp+34h] [bp-60h] BYREF
  _DWORD v17[8]; // [sp+74h] [bp-20h] BYREF

  sub_8562C(v17, 0x20u);
  sub_8562C(v16, 0x40u);
  v14 = 0;
  v15 = 0;
  v13 = -1;
  sub_8562C(v12, 0x20u);
  v11 = 0;
  sub_84748();
  v0 = sub_84854();
  sub_85684(0x3E8u, v0);
  v2 = v1;
  result = sub_81474();
  v4 = result;
  if ( result >= 0 )
  {
    sub_807C8();
    sub_848B8();
    sub_84868();
    v5 = sub_843E8();
    v6 = sub_843E8();
    result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v6 + 8))(v5, 16777219, &v11);
    if ( result == 0 )
    {
      v7 = (*(int (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v11 + 8))(v11, v16, 1);
      v8 = v7;
      if ( v7 != 0 )
      {
        (*(void (__fastcall **)(int, _DWORD, int))(*(_DWORD *)v7 + 32))(v7, 0, 2000 * v4 + 2 * v2);
        (*(void (__fastcall **)(int, __int16 *, int))(*(_DWORD *)v8 + 8))(v8, &v13, 2);
        (*(void (__fastcall **)(int))(*(_DWORD *)v8 + 4))(v8);
      }
      sub_802AC();
      if ( v13 >= 0 )
      {
        sub_8475C();
        sub_848B8();
        sub_84868();
        v9 = (*(int (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v11 + 8))(v11, v16, 1);
        v10 = v9;
        if ( v9 != 0 )
        {
          (*(void (__fastcall **)(int, _DWORD, int))(*(_DWORD *)v9 + 32))(v9, 0, 22 * v13);
          (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v10 + 8))(v10, v12, 22);
          (*(void (__fastcall **)(int))(*(_DWORD *)v10 + 4))(v10);
          sub_849BC();
        }
      }
      result = v11;
      if ( v11 != 0 )
        return (*(int (__fastcall **)(int))(*(_DWORD *)v11 + 4))(v11);
    }
  }
  return result;
}
// 816F4: variable 'v1' is possibly undefined

//----- (000818B8) --------------------------------------------------------
int __fastcall sub_818B8(int a1, int a2, int a3)
{
  signed int v4; // r8
  int v5; // r5
  int v6; // r1
  unsigned __int8 v7; // r0
  bool v8; // zf
  int v9; // r4
  int v10; // r0
  int result; // r0
  int v12; // r4
  unsigned int v13; // r6
  unsigned int v14; // r7
  unsigned int v15; // r5
  signed int v16; // [sp+14h] [bp-B4h] BYREF
  _BYTE v17[8]; // [sp+18h] [bp-B0h] BYREF
  int v18; // [sp+20h] [bp-A8h]
  int v19; // [sp+64h] [bp-64h] BYREF
  _DWORD v20[16]; // [sp+68h] [bp-60h] BYREF
  _DWORD v21[8]; // [sp+A8h] [bp-20h] BYREF

  sub_8562C(v21, 0x20u);
  sub_8562C(v20, 0x40u);
  v19 = 0;
  sub_84748();
  v4 = sub_84854();
  v5 = (unsigned __int8)sub_85684(0x64u, v4);
  v7 = sub_85818(v6);
  v8 = v5 == 1;
  if ( v5 != 1 )
    v8 = v5 == 2;
  if ( v8 )
    v4 = 100 * (__int16)v5 + 10 * v7;
  sub_807C8();
  sub_848B8();
  sub_84868();
  v9 = sub_843E8();
  v10 = sub_843E8();
  result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v10 + 8))(v9, 16777219, &v19);
  if ( result == 0 )
  {
    (*(void (__fastcall **)(int, _DWORD *, _BYTE *))(*(_DWORD *)v19 + 12))(v19, v20, v17);
    v12 = (*(int (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v19 + 8))(v19, v20, 1);
    if ( v12 != 0 )
    {
      v13 = 0;
      v14 = (unsigned __int16)v18 >> 4;
      while ( v13 <= v14 )
      {
        v15 = (v13 + v14) >> 1;
        if ( v15 == 0 )
          break;
        (*(void (__fastcall **)(int, _DWORD, unsigned int))(*(_DWORD *)v12 + 32))(v12, 0, 16 * v15 - 16);
        (*(void (__fastcall **)(int, signed int *, int))(*(_DWORD *)v12 + 8))(v12, &v16, 4);
        if ( v4 >= v16 )
        {
          if ( v4 <= v16 )
          {
            (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v12 + 8))(v12, a3, 12);
            break;
          }
          v13 = (v15 + 1) & 0xFFFEFFFF;
        }
        else
        {
          v14 = (unsigned __int16)(v15 - 1);
        }
      }
      (*(void (__fastcall **)(int))(*(_DWORD *)v12 + 4))(v12);
    }
    result = v19;
    if ( v19 != 0 )
      return (*(int (__fastcall **)(int))(*(_DWORD *)v19 + 4))(v19);
  }
  return result;
}
// 81938: variable 'v6' is possibly undefined

//----- (00081ABC) --------------------------------------------------------
int __fastcall sub_81ABC(int a1)
{
  int v2; // r5
  int v3; // r0
  _DWORD v5[16]; // [sp+4h] [bp-100h] BYREF
  _DWORD v6[16]; // [sp+44h] [bp-C0h] BYREF
  _DWORD v7[32]; // [sp+84h] [bp-80h] BYREF

  sub_8562C(v7, 0x80u);
  sub_8562C(v6, 0x40u);
  sub_8562C(v5, 0x40u);
  v2 = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8);
  sub_84A34();
  sub_844C0();
  sub_84890();
  if ( LOBYTE(v5[0]) == 48 )
  {
    sub_818B8(a1, (int)v5, (int)v6);
    if ( sub_84A34() != 0 )
    {
      if ( v2 < 176 )
        goto LABEL_19;
      if ( sub_84890() != 0 && sub_84890() != 0 )
        sub_849BC();
      if ( sub_84890() != 0 || sub_84890() != 0 && sub_84890() != 0 )
        goto LABEL_19;
    }
    else
    {
      if ( v2 < 176 )
        goto LABEL_19;
      if ( sub_84890() != 0 && sub_84890() != 0 )
        sub_849BC();
      if ( sub_84890() != 0 || sub_84890() != 0 && sub_84890() != 0 )
        goto LABEL_19;
    }
LABEL_18:
    sub_849BC();
LABEL_19:
    sub_849BC();
    goto LABEL_41;
  }
  if ( LOBYTE(v5[0]) != 49 || (unsigned int)sub_848E0() > 0xB )
  {
    sub_84A0C();
    goto LABEL_41;
  }
  sub_81670();
  if ( sub_84A34() != 0 )
  {
    if ( v2 < 176 )
      goto LABEL_19;
    if ( sub_84890() != 0 && sub_84890() != 0 )
      sub_849BC();
    if ( sub_84890() != 0 || sub_84890() != 0 && sub_84890() != 0 )
      goto LABEL_19;
    goto LABEL_18;
  }
  if ( v2 >= 176 )
  {
    if ( sub_84890() != 0 && sub_84890() != 0 )
      sub_849BC();
    if ( sub_84890() == 0 && (sub_84890() == 0 || sub_84890() == 0) )
      sub_849BC();
  }
  sub_849BC();
  sub_802C8();
  sub_84A34();
  sub_80290();
LABEL_41:
  if ( sub_8470C() != 0 && sub_8470C() != 0 )
  {
    if ( sub_8470C() != 0 )
    {
      if ( sub_8470C() != 0 )
        goto LABEL_48;
    }
    else
    {
      sub_848E0();
    }
  }
  sub_84A0C();
LABEL_48:
  if ( sub_849E4() == 0 )
    sub_84A0C();
  v3 = sub_84A34();
  sub_8071C(*(_DWORD **)(a1 + 80), (int)v7, v3);
  sub_81160(a1);
  return sub_812BC(a1);
}

//----- (00081FD8) --------------------------------------------------------
_DWORD *__fastcall sub_81FD8(int a1)
{
  _DWORD v3[4]; // [sp+Ch] [bp-10h] BYREF

  v3[0] = 0;
  v3[1] = 0;
  v3[2] = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8);
  v3[3] = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12);
  (*(void (__fastcall **)(_DWORD, int, _DWORD *, int))(**(_DWORD **)(a1 + 72) + 12))(*(_DWORD *)(a1 + 72), 1, v3, 1);
  sub_802C8();
  sub_802AC();
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 1);
  sub_802C8();
  sub_802AC();
  (*(void (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 72) + 84))(*(_DWORD *)(a1 + 72), 1, -8684677);
  (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int))(**(_DWORD **)(a1 + 72) + 112))(
    *(_DWORD *)(a1 + 72),
    0,
    0,
    *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8),
    *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12),
    -8684677);
  (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 0);
  return sub_802C8();
}

//----- (00082138) --------------------------------------------------------
int __fastcall sub_82138(int a1, int a2, int a3)
{
  sub_8475C();
  sub_802C8();
  sub_802AC();
  if ( a3 > 0 )
    sub_84748();
  sub_84A34();
  sub_802AC();
  return sub_8071C(*(_DWORD **)(a1 + 80), 0, 0);
}

//----- (000821D0) --------------------------------------------------------
_DWORD *__fastcall sub_821D0(int a1)
{
  int v2; // r5
  int v3; // r0
  _DWORD v5[4]; // [sp+4h] [bp-10h] BYREF

  v2 = sub_843E8();
  v3 = sub_843E8();
  (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 16))(v2, *(_DWORD *)(a1 + 76));
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 24))(*(_DWORD *)(a1 + 72));
  (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 0);
  sub_81FD8(a1);
  v5[0] = 0;
  v5[1] = 0;
  v5[2] = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 8);
  v5[3] = *(_DWORD *)(*(_DWORD *)(a1 + 76) + 12);
  sub_806F8(*(_DWORD **)(a1 + 80), v5);
  if ( *(int *)(*(_DWORD *)(a1 + 76) + 12) < 220 )
    sub_80790(*(_DWORD *)(a1 + 80), 2);
  sub_802C8();
  sub_8081C(a1);
  sub_81160(a1);
  sub_812BC(a1);
  return sub_802C8();
}

//----- (000822DC) --------------------------------------------------------
_DWORD *__fastcall sub_822DC(int a1, int a2)
{
  int v2; // r0

  *(_DWORD *)(a2 + 304) = -1;
  v2 = *(_DWORD *)(a2 + 300);
  if ( v2 != 0 )
  {
    sub_85340(v2);
    *(_DWORD *)(a2 + 300) = 0;
  }
  return sub_802C8();
}

//----- (00082330) --------------------------------------------------------
int __fastcall sub_82330(int result, int a2)
{
  int v2; // r4
  int v3; // r5
  int v4; // r0

  v2 = result;
  if ( result != 0 )
  {
    if ( a2 == 1 )
      sub_85128(1029, (const char *)(result + 232));
    sub_802C8();
    *(_DWORD *)(v2 + 84) = 0;
    sub_8071C(*(_DWORD **)(v2 + 80), 0, 0);
    sub_821D0(v2);
    result = *(_DWORD *)(v2 + 300);
    if ( result != 0 )
    {
      v3 = sub_843E8();
      v4 = sub_843E8();
      result = (*(int (__fastcall **)(int, _DWORD, _DWORD *(__fastcall *)(int, int), _DWORD))(*(_DWORD *)v4 + 60))(
                 v3,
                 0,
                 sub_822DC,
                 0);
      *(_DWORD *)(v2 + 304) = result;
    }
  }
  return result;
}

//----- (00082424) --------------------------------------------------------
int __fastcall sub_82424(int *a1)
{
  int v2; // r5
  int v3; // r0
  int v4; // r5
  int v5; // r0
  _DWORD *v6; // r0
  _DWORD v8[4]; // [sp+4h] [bp-10h] BYREF

  v2 = sub_843E8();
  v3 = sub_843E8();
  (*(void (__fastcall **)(int, int, int *))(*(_DWORD *)v3 + 8))(v2, 16777221, a1 + 18);
  a1[19] = sub_84410();
  sub_8475C();
  v4 = sub_843E8();
  v5 = sub_843E8();
  (*(void (__fastcall **)(int, int))(*(_DWORD *)v5 + 16))(v4, a1[19]);
  a1[75] = 0;
  a1[74] = 0;
  sub_8475C();
  sub_848E0();
  sub_84748();
  v8[0] = 0;
  v8[1] = 0;
  v8[2] = *(_DWORD *)(a1[19] + 8);
  v8[3] = *(_DWORD *)(a1[19] + 12);
  v6 = sub_8062C(a1[18], v8);
  a1[20] = (int)v6;
  if ( *(int *)(a1[19] + 12) < 220 )
    sub_80790((int)v6, 2);
  sub_8475C();
  a1[21] = 0;
  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1[18] + 64))(a1[18], 1);
  a1[76] = -1;
  sub_81FD8((int)a1);
  (*(void (__fastcall **)(int))(*(_DWORD *)a1[18] + 52))(a1[18]);
  (*(void (__fastcall **)(int))(*(_DWORD *)a1[18] + 56))(a1[18]);
  sub_8081C((int)a1);
  sub_81160((int)a1);
  return sub_812BC((int)a1);
}

//----- (00082584) --------------------------------------------------------
int sub_82584()
{
  int v0; // r4
  int v1; // r0
  int result; // r0
  int v3; // r4
  int v4; // r5
  int v5; // r0
  int v6; // r5
  int v7; // r4
  int v8; // r0
  _DWORD v9[16]; // [sp+0h] [bp-44h] BYREF
  int v10; // [sp+40h] [bp-4h] BYREF

  v10 = 0;
  sub_8562C(v9, 0x40u);
  v0 = sub_843E8();
  v1 = sub_843E8();
  result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v1 + 8))(v0, 16777219, &v10);
  if ( result == 0 )
  {
    result = v10;
    if ( v10 != 0 )
    {
      v3 = 1;
      while ( 1 )
      {
        sub_8475C();
        LOBYTE(v9[0]) = (*(int (__fastcall **)(int, int))(*(_DWORD *)v10 + 48))(v10, v3);
        if ( LOBYTE(v9[0]) != 0 )
        {
          v4 = sub_843E8();
          v5 = sub_843E8();
          (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 28))(v4);
          sub_84868();
          sub_84868();
          v6 = (*(int (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v10 + 8))(v10, v9, 1);
          if ( v6 != 0 )
            break;
        }
        if ( --v3 < 0 )
          goto LABEL_9;
      }
      sub_802C8();
      v7 = sub_843E8();
      v8 = sub_843E8();
      (*(void (__fastcall **)(int, int, int, _DWORD *))(*(_DWORD *)v8 + 80))(v7, 1, 50, v9);
      (*(void (__fastcall **)(int))(*(_DWORD *)v6 + 4))(v6);
LABEL_9:
      result = v10;
      if ( v10 != 0 )
        return (*(int (__fastcall **)(int))(*(_DWORD *)v10 + 4))(v10);
    }
  }
  return result;
}
// 82670: conditional instruction was optimized away because r5.4==0

//----- (000826EC) --------------------------------------------------------
int __fastcall sub_826EC(int a1)
{
  int v2; // r5
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int result; // r0

  if ( *(int *)(a1 + 304) >= 0 )
  {
    v2 = sub_843E8();
    v3 = sub_843E8();
    (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 64))(v2, *(_DWORD *)(a1 + 304));
    *(_DWORD *)(a1 + 304) = -1;
  }
  v4 = *(_DWORD *)(a1 + 300);
  if ( v4 != 0 )
  {
    sub_85340(v4);
    *(_DWORD *)(a1 + 300) = 0;
    sub_802C8();
  }
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 24))(*(_DWORD *)(a1 + 72));
  (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 32))(*(_DWORD *)(a1 + 72), 0);
  v5 = *(_DWORD *)(a1 + 72);
  if ( v5 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
  if ( *(_DWORD *)(a1 + 76) != 0 )
    sub_84424();
  result = *(_DWORD *)(a1 + 80);
  if ( result != 0 )
    return (*(int (**)(void))(result + 64))();
  return result;
}

//----- (000827DC) --------------------------------------------------------
int __fastcall sub_827DC(int a1, int a2)
{
  int v4; // r0
  void *v5; // r3
  int v7; // r7
  int i; // r5
  int v9; // r0
  int v10; // r4
  int (__fastcall *v11)(int, _DWORD); // r2
  int v12; // [sp+0h] [bp-10h]

  v12 = a1;
  if ( a1 == 0 )
    return v12;
  if ( a2 != 0 )
  {
    if ( sub_84A34() != 0 )
    {
      if ( a2 != 2 )
      {
        if ( a2 == 1 )
        {
          if ( (unsigned int)sub_84A34() >= 8 )
          {
            v7 = *(unsigned __int16 *)(a1 + 92);
            for ( i = 3; sub_84A34() > i; ++i )
            {
              if ( *(unsigned __int16 *)(a1 + 2 * i + 88) != v7 )
              {
                sub_81ABC(a1);
                return v12;
              }
            }
          }
          v9 = sub_84A34();
          sub_8071C(*(_DWORD **)(a1 + 80), (int)&unk_85E52, v9);
          sub_81160(a1);
          sub_812BC(a1);
        }
        return v12;
      }
      *(_DWORD *)(a1 + 84) = 1;
      (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 24))(*(_DWORD *)(a1 + 72));
      v4 = sub_84A34();
      v5 = &unk_85E48;
      v12 = 1;
    }
    else
    {
      *(_DWORD *)(a1 + 84) = 1;
      (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 24))(*(_DWORD *)(a1 + 72));
      v4 = sub_84A34();
      v5 = &unk_85E3E;
      v12 = 1;
    }
    sub_84C6C(a1 + 88, v4, 14, (int)v5);
    return v12;
  }
  v10 = sub_843E8();
  v11 = *(int (__fastcall **)(int, _DWORD))(*(_DWORD *)sub_843E8() + 36);
  return v11(v10, 0);
}

//----- (00082954) --------------------------------------------------------
void __fastcall __spoils<R2,R3,R12,LR> sub_82954(int a1, int a2, int a3, int a4)
{
  int v5; // [sp+8h] [bp-8h] BYREF
  int v6; // [sp+Ch] [bp-4h]

  v5 = a3;
  v6 = a4;
  if ( a1 != 0 )
  {
    if ( a2 != 0 )
    {
      v5 = -458378008;
      v6 = 45241;
      sub_802C8();
      (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 24))(*(_DWORD *)(a1 + 72));
      *(_DWORD *)(a1 + 84) = 3;
      sub_802C8();
      sub_802C8();
      *(_DWORD *)(a1 + 300) = sub_85248(1029, *(_DWORD *)(a1 + 296), 0, (int)&v5, (int)sub_82330, a1);
      sub_802C8();
    }
    else
    {
      *(_DWORD *)(a1 + 84) = 0;
      sub_8071C(*(_DWORD **)(a1 + 80), 0, 0);
      sub_8081C(a1);
      sub_81160(a1);
      sub_812BC(a1);
    }
  }
}

//----- (00082AB0) --------------------------------------------------------
int __fastcall sub_82AB0(int a1, int a2, int a3, _DWORD *a4)
{
  int *v4; // r8
  int v8; // r4
  bool v9; // zf
  bool v10; // zf
  int v11; // r0
  bool v12; // zf
  bool v13; // zf
  int v14; // r0
  int v15; // r7
  int v16; // r8
  int v17; // r10
  int v18; // r0
  int v19; // r2
  int v20; // r3
  int v21; // r0
  int v22; // r0
  int v23; // r1
  int v24; // r0
  int v25; // r0
  int v26; // r1
  bool v27; // zf
  int v29; // r0
  bool v30; // zf
  int v31; // r0
  bool v32; // zf
  int v33; // r4
  int v34; // r0
  bool v35; // zf
  bool v36; // zf
  _DWORD v37[4]; // [sp+4h] [bp-10h] BYREF

  v4 = (int *)a1;
  v8 = a1;
  if ( a1 == 0 )
    return 0;
  v9 = a2 == 0;
  if ( a2 != 0 )
    v9 = a2 == 1;
  if ( !v9 )
  {
    a1 = *(_DWORD *)(a1 + 300);
    v9 = a1 == 0;
  }
  if ( v9 )
  {
    if ( a2 == 0 )
    {
      if ( !sub_8433C((int)v4, a3, a4) )
      {
        sub_82424(v4);
        sub_82584();
        return 1;
      }
      return 0;
    }
    v10 = a2 == 9;
    if ( a2 != 9 )
      v10 = a2 == 11;
    if ( v10 || a2 == 10 )
    {
      v11 = *(_DWORD *)(v8 + 84);
      v12 = v11 == 0;
      if ( v11 != 0 )
        v12 = v11 == 2;
      if ( v12 )
      {
        (*(void (**)(void))(*(_DWORD *)(v8 + 80) + 68))();
        sub_81160(v8);
        sub_812BC(v8);
      }
      v13 = a2 == 9;
      if ( a2 != 9 )
        v13 = a2 == 11;
      if ( v13 )
        return 0;
      v14 = *(_DWORD *)(v8 + 76);
      v15 = 0;
      v16 = *(_DWORD *)(v14 + 8);
      v17 = *(_DWORD *)(v14 + 12);
      v18 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(v8 + 72) + 72))(*(_DWORD *)(v8 + 72));
      if ( v17 - (v18 + 8) < (int)a4 )
      {
        v21 = 2 * v18 + 8;
        if ( v21 <= a3 )
        {
          if ( v16 - v21 < a3 )
            v15 = 2;
        }
        else
        {
          v15 = 1;
        }
      }
      v22 = *(_DWORD *)(v8 + 84);
      if ( v22 == 0 )
      {
        if ( v15 == 1 )
        {
LABEL_30:
          v23 = 1;
LABEL_38:
          sub_827DC(v8, v23);
          return 1;
        }
        if ( v15 == 2 )
        {
          v23 = 0;
          goto LABEL_38;
        }
        v24 = *(_DWORD *)(v8 + 216);
        if ( v24 >= a3 )
          return 1;
        if ( v24 + *(_DWORD *)(v8 + 224) <= a3 )
          return 1;
        v25 = *(_DWORD *)(v8 + 220);
        if ( v25 >= (int)a4 || v25 + *(_DWORD *)(v8 + 228) <= (int)a4 )
          return 1;
LABEL_37:
        v23 = 2;
        goto LABEL_38;
      }
      if ( v22 != 2 )
        return 1;
      if ( v15 == 1 )
      {
LABEL_41:
        v26 = 1;
LABEL_44:
        sub_82954(v8, v26, v19, v20);
        return 1;
      }
      if ( v15 != 2 )
        return 1;
    }
    else
    {
      v27 = a2 == 5;
      if ( a2 != 5 )
        v27 = a2 == 6;
      if ( !v27 )
      {
        if ( a2 == 4 )
        {
          sub_802C8();
        }
        else
        {
          if ( a2 == 2 )
          {
            v37[0] = 0;
            v37[1] = 1;
            v37[2] = 0;
            v37[3] = 0;
            (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(v8 + 72) + 32))(*(_DWORD *)(v8 + 72), 0);
            (*(void (__fastcall **)(_DWORD, int, _DWORD *, _DWORD))(**(_DWORD **)(v8 + 72) + 176))(
              *(_DWORD *)(v8 + 72),
              2,
              v37,
              0);
            (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(v8 + 72) + 24))(*(_DWORD *)(v8 + 72));
            return 1;
          }
          if ( a2 != 3 )
          {
            if ( a2 == 1 )
              sub_826EC(v8);
            return 1;
          }
          if ( *(_DWORD *)(v8 + 84) == 1 )
            *(_DWORD *)(v8 + 84) = 0;
        }
        sub_821D0((int)v4);
        return 1;
      }
      if ( a2 == 5 )
        return 0;
      v29 = *(_DWORD *)(v8 + 84);
      v30 = v29 == 0;
      if ( v29 != 0 )
        v30 = v29 == 2;
      if ( !v30 )
        return 1;
      (*(void (**)(void))(*(_DWORD *)(v8 + 80) + 68))();
      sub_81160(v8);
      sub_812BC(v8);
      v31 = *(_DWORD *)(v8 + 84);
      if ( v31 == 0 )
      {
        if ( a3 == 10 )
          goto LABEL_30;
        v32 = a3 == 25;
        if ( a3 != 25 )
          v32 = a3 == 0;
        if ( !v32 )
        {
          v32 = a3 == 1;
          if ( a3 != 1 )
          {
            v32 = a3 == 2;
            if ( a3 != 2 )
            {
              v32 = a3 == 3;
              if ( a3 != 3 )
              {
                v32 = a3 == 4;
                if ( a3 != 4 )
                {
                  v32 = a3 == 5;
                  if ( a3 != 5 )
                  {
                    v32 = a3 == 6;
                    if ( a3 != 6 )
                    {
                      v32 = a3 == 7;
                      if ( a3 != 7 )
                      {
                        v32 = a3 == 8;
                        if ( a3 != 8 )
                          v32 = a3 == 9;
                      }
                    }
                  }
                }
              }
            }
          }
        }
        if ( !v32 )
        {
          if ( a3 == 11 )
          {
            v33 = sub_843E8();
            v34 = sub_843E8();
            (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v34 + 36))(v33, 0);
          }
          return 1;
        }
        goto LABEL_37;
      }
      if ( v31 != 2 )
        return 1;
      v35 = a3 == 10;
      if ( a3 != 10 )
        v35 = a3 == 25;
      if ( !v35 )
      {
        v35 = a3 == 4;
        if ( a3 != 4 )
          v35 = a3 == 5;
      }
      if ( v35 )
        goto LABEL_41;
      v36 = a3 == 11;
      if ( a3 != 11 )
        v36 = a3 == 6;
      if ( !v36 )
        return 1;
    }
    v26 = 0;
    goto LABEL_44;
  }
  sub_853A8(a1);
  return 1;
}
// 82C64: variable 'v19' is possibly undefined
// 82C64: variable 'v20' is possibly undefined

//----- (00082E24) --------------------------------------------------------
int (__fastcall *__fastcall sub_82E24(_DWORD *a1, int (__fastcall **a2)(int a1)))(int a1, int a2, int a3, _DWORD *a4)
{
  *a1 = 312;
  *a2 = sub_82E80;
  a2[1] = sub_82E98;
  a2[2] = (int (__fastcall *)(int))sub_82AB0;
  return sub_82AB0;
}

//----- (00082E54) --------------------------------------------------------
int sub_82E54()
{
  int result; // r0

  result = sub_84E04();
  if ( result != 0 )
    return *(_DWORD *)(result + 308);
  return result;
}

//----- (00082E68) --------------------------------------------------------
int __fastcall sub_82E68(int a1)
{
  int result; // r0

  result = sub_84E04();
  if ( result != 0 )
    *(_DWORD *)(result + 308) = a1;
  return result;
}

//----- (00082E80) --------------------------------------------------------
int __fastcall sub_82E80(int a1)
{
  if ( a1 != 0 )
    ++*(_DWORD *)(a1 + 68);
  return 0;
}

//----- (00082E98) --------------------------------------------------------
int __fastcall sub_82E98(int a1)
{
  if ( a1 != 0 )
    --*(_DWORD *)(a1 + 68);
  return 0;
}

//----- (00082EBC) --------------------------------------------------------
int __fastcall sub_82EBC(_DWORD *a1)
{
  int v2; // r5
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r5
  int v11; // r0

  if ( (int)a1[121] >= 0 )
  {
    v2 = sub_843E8();
    v3 = sub_843E8();
    (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v3 + 64))(v2, a1[121]);
  }
  if ( a1[112] != 0 )
    sub_84424();
  v4 = a1[132];
  if ( v4 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v4 + 4))(v4);
    a1[132] = 0;
  }
  v5 = a1[130];
  if ( v5 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
    a1[130] = 0;
  }
  v6 = a1[131];
  if ( v6 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v6 + 4))(v6);
    a1[131] = 0;
  }
  v7 = a1[129];
  if ( v7 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 4))(v7);
    a1[129] = 0;
  }
  if ( a1[27] != 0 )
  {
    sub_84424();
    a1[27] = 0;
  }
  v8 = a1[115];
  if ( v8 != 0 )
  {
    v9 = *(_DWORD *)(v8 + 4);
    if ( v9 != 0 )
      (*(void (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
    if ( *(_DWORD *)a1[115] != 0 )
    {
      v10 = sub_843E8();
      v11 = sub_843E8();
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v11 + 92))(v10, *(_DWORD *)a1[115]);
    }
    sub_84424();
  }
  if ( a1[116] != 0 )
    sub_84424();
  return sub_84424();
}

//----- (00082FF8) --------------------------------------------------------
int __fastcall sub_82FF8(int a1, int a2, int a3, int a4)
{
  int v8; // r4
  bool v9; // zf
  int v10; // r8
  int v11; // r0
  int v12; // r0
  int v13; // r0

  v8 = sub_82E54();
  if ( *(_DWORD *)(v8 + 460) == 0 )
  {
    if ( a2 == 28702 )
    {
      *(_DWORD *)(**(_DWORD **)(v8 + 476) + 8) = *(_DWORD *)(v8 + 472);
      if ( v8 == 0 )
        return 0;
    }
    else
    {
      (*(void (__fastcall **)(int, int, int, int))(v8 + 472))(a1, a2, a3, a4);
      if ( a2 != 1 || v8 == 0 )
        return 0;
    }
    goto LABEL_14;
  }
  v9 = a2 == 28703;
  if ( a2 != 28703 )
    v9 = a2 == 28702;
  if ( v9 )
  {
    if ( *(_DWORD *)(v8 + 484) != -1 )
    {
      v10 = sub_843E8();
      v11 = sub_843E8();
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v11 + 64))(v10, *(_DWORD *)(v8 + 484));
      *(_DWORD *)(v8 + 484) = -1;
    }
    v12 = *(_DWORD *)(v8 + 524);
    if ( v12 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v12 + 4))(v12);
      *(_DWORD *)(v8 + 524) = 0;
    }
    v13 = *(_DWORD *)(v8 + 516);
    if ( v13 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 4))(v13);
      *(_DWORD *)(v8 + 516) = 0;
    }
  }
  if ( a2 != 1 )
    return (*(int (__fastcall **)(_DWORD, int, int, int))(**(_DWORD **)(*(_DWORD *)(v8 + 460) + 4) + 16))(
             *(_DWORD *)(*(_DWORD *)(v8 + 460) + 4),
             a2,
             a3,
             a4);
  if ( v8 != 0 )
LABEL_14:
    sub_82EBC((_DWORD *)v8);
  return 0;
}

//----- (0008313C) --------------------------------------------------------
int __fastcall sub_8313C(int a1, _DWORD *a2)
{
  int v3; // r5
  int v4; // r0
  int v5; // r0
  bool v6; // nf

  if ( a2[121] != -1 )
  {
    v3 = sub_843E8();
    v4 = sub_843E8();
    (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v4 + 64))(v3, a2[121]);
    a2[121] = -1;
  }
  v5 = a2[110] + 1;
  v6 = a2[110] - 2 < 0;
  a2[110] = v5;
  if ( v6 != __OFSUB__(v5, 3) )
    return sub_8395C(a2);
  else
    return sub_82FF8(a2[119], 28702, 0, 0);
}
// 831B0: using guessed type int sub_831B0(void);
// 8395C: using guessed type int __fastcall sub_8395C(_DWORD);

//----- (000831B0) --------------------------------------------------------
int __fastcall sub_831B0(int a1, unsigned __int8 *a2, int a3, int a4)
{
  bool v4; // zf
  int v7; // r0
  int v8; // r4
  int v9; // r0
  int v11; // r0
  int v12; // r5

  v4 = a1 == 0;
  if ( a1 != 0 )
    v4 = a2 == nullptr;
  if ( !v4 )
    a1 = *a2;
  if ( !v4 )
    v4 = a1 == 0;
  if ( v4 )
    return 0;
  sub_848E0();
  if ( sub_8496C() == 0 )
    return 0;
  v7 = sub_8496C();
  if ( v7 == 0 )
    return 0;
  v8 = v7 + 1;
  v9 = sub_8496C();
  if ( v9 == 0 )
    return 0;
  v11 = v9 - v8;
  if ( v11 >= a4 - 1 )
    v11 = a4 - 1;
  v12 = v11;
  sub_84748();
  *(_BYTE *)(a3 + v12) = 0;
  return 1;
}

//----- (00083260) --------------------------------------------------------
int __fastcall sub_83260(_DWORD *a1)
{
  int v2; // r8
  int v4; // r7
  int v5; // r5
  int i; // r10
  int v7; // r0
  int v8; // r11
  bool v9; // cc
  bool v10; // cc
  int j; // r11
  int v12; // r6
  bool v13; // zf
  int v14; // r0
  int v15; // r0
  int v16; // r6
  int k; // r8
  _DWORD v18[30]; // [sp+4h] [bp-94h] BYREF
  unsigned __int8 v19[12]; // [sp+7Ch] [bp-1Ch] BYREF
  int v20; // [sp+88h] [bp-10h]
  int v21; // [sp+8Ch] [bp-Ch]
  int v22; // [sp+90h] [bp-8h]
  int v23; // [sp+94h] [bp-4h]

  memset(v19, 0, sizeof(v19));
  sub_8562C(v18, 0x78u);
  v2 = 0;
  if ( sub_831B0(a1[27], "result", (int)v19, 10) == 0 )
    return -1;
  a1[111] = sub_84890() == 0;
  if ( sub_831B0(a1[27], "version", (int)v19, 10) != 0 )
    a1[26] = sub_84854();
  a1[114] = 0;
  if ( sub_831B0(a1[27], "dllupdate", (int)v19, 10) != 0 && sub_84890() == 0 )
    a1[114] = 1;
  if ( a1[111] != 0 )
  {
    sub_831B0(a1[27], "lasttime", (int)(a1 + 1), 32);
    if ( sub_831B0(a1[27], "count", (int)v19, 10) != 0 )
    {
      v4 = sub_84854();
      if ( v4 > 0 )
      {
        v5 = sub_84410();
        if ( v5 == 0 )
          return -2;
        sub_8475C();
        for ( i = 0; i < v4; ++i )
        {
          sub_84798((int)v19, "item_%d", i);
          if ( sub_831B0(a1[27], v19, (int)v18, 120) != 0 )
          {
            v7 = sub_84854();
            *(_DWORD *)(v5 + 104 * i) = v7;
            if ( v7 == *a1 )
            {
              *(_DWORD *)(v5 + 104 * i) = 0;
            }
            else
            {
              v20 = sub_8487C();
              if ( v20 != 0 )
              {
                v23 = v20 + 1;
                v8 = sub_8487C();
                v9 = v8 < 0;
                if ( v8 != 0 )
                  v9 = v8 - v20 - 1 < 32;
                if ( v9 )
                {
                  v22 = v5 + 104 * i;
                  sub_84748();
                  v21 = v8 + 1;
                  v20 = sub_8487C();
                  v10 = v20 < 0;
                  if ( v20 != 0 )
                    v10 = v20 - v8 - 1 < 64;
                  if ( v10 )
                  {
                    sub_84748();
                    *(_DWORD *)(v22 + 100) = sub_84854();
                  }
                }
              }
              for ( j = 0; a1[113] > j; ++j )
              {
                if ( *(_DWORD *)(a1[112] + 104 * j) == *(_DWORD *)(v5 + 104 * i) )
                {
                  sub_84748();
                  *(_DWORD *)(v5 + 104 * i) = 0;
                  break;
                }
              }
              if ( a1[113] <= j )
                ++v2;
            }
          }
        }
        if ( v2 != 0 )
        {
          v12 = a1[112];
          v13 = v12 == 0;
          if ( v12 != 0 )
            v13 = a1[113] == 0;
          if ( v13 )
          {
            v15 = sub_84410();
            a1[112] = v15;
            if ( v15 == 0 )
              goto LABEL_44;
            a1[113] = v2;
          }
          else
          {
            v14 = sub_84410();
            a1[112] = v14;
            if ( v14 == 0 )
            {
              a1[112] = v12;
LABEL_44:
              sub_84424();
              return -2;
            }
            sub_84748();
            sub_84424();
            a1[113] += v2;
          }
          v16 = 0;
          for ( k = a1[113] - v2; a1[113] > k; ++k )
          {
            while ( v16 < v4 && *(_DWORD *)(v5 + 104 * v16) == 0 )
              ++v16;
            if ( v16 >= v4 )
            {
              a1[113] = k;
              break;
            }
            sub_84748();
            ++v16;
          }
        }
        sub_84424();
      }
    }
  }
  return 0;
}
// 8357C: conditional instruction was optimized away because r5.4!=0
// 83610: conditional instruction was optimized away because r5.4!=0
// 83694: conditional instruction was optimized away because r5.4!=0

//----- (000836A4) --------------------------------------------------------
int __fastcall sub_836A4(int a1, int a2, int a3, int a4)
{
  int v6; // r0
  int v7; // r2
  int v8; // r0
  int v9; // r0
  int v11; // r0
  int v12; // r7
  int v13; // r5
  int v14; // r0
  int v15; // r6
  int v16; // r5
  int v17; // r0
  int v18; // r5
  int v19; // r0

  switch ( a2 )
  {
    case 0:
      v6 = *(_DWORD *)(a1 + 524);
      if ( v6 != 0 )
      {
        (*(void (__fastcall **)(int))(*(_DWORD *)v6 + 4))(v6);
        *(_DWORD *)(a1 + 524) = 0;
      }
      v7 = -1;
      v8 = *(_DWORD *)(a1 + 476);
      goto LABEL_23;
    case 2:
      if ( sub_848CC() == 0 )
      {
        if ( *(_DWORD *)(a1 + 108) != 0 )
          sub_84424();
        *(_DWORD *)(a1 + 112) = sub_84854();
        *(_DWORD *)(a1 + 116) = 0;
        v9 = sub_84410();
        *(_DWORD *)(a1 + 108) = v9;
        if ( v9 != 0 )
          sub_8475C();
      }
      return 1;
    case 3:
      if ( *(_DWORD *)(a1 + 108) != 0 )
      {
        sub_84748();
        *(_DWORD *)(a1 + 116) += a4;
      }
      return 1;
    case 4:
      v11 = sub_83260((_DWORD *)a1);
      if ( v11 == -1 )
      {
        if ( *(_DWORD *)(a1 + 484) != -1 )
        {
          v16 = sub_843E8();
          v17 = sub_843E8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v17 + 64))(v16, *(_DWORD *)(a1 + 484));
        }
        v18 = sub_843E8();
        v19 = sub_843E8();
        *(_DWORD *)(a1 + 484) = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, _DWORD *), int))(*(_DWORD *)v19 + 60))(
                                  v18,
                                  10,
                                  sub_8313C,
                                  1);
      }
      else
      {
        if ( v11 == 0 )
        {
          v12 = 104 * *(_DWORD *)(a1 + 452) + 80;
          v13 = sub_84410();
          if ( v13 != 0 )
          {
            sub_8475C();
            sub_84748();
            sub_84748();
            sub_84748();
            sub_84748();
            sub_84748();
            if ( *(_DWORD *)(a1 + 452) != 0 )
              sub_84748();
            sub_84748();
            v14 = (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 520) + 8))(
                    *(_DWORD *)(a1 + 520),
                    a1 + 36,
                    22);
            v15 = v14;
            if ( v14 != 0 )
            {
              (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v14 + 12))(v14, v13, v12);
              (*(void (__fastcall **)(int))(*(_DWORD *)v15 + 4))(v15);
            }
            sub_84424();
          }
        }
        v8 = *(_DWORD *)(a1 + 476);
        v7 = 0;
LABEL_23:
        sub_82FF8(v8, 28702, v7, 0);
      }
      return 0;
    default:
      return 1;
  }
}

//----- (0008395C) --------------------------------------------------------
int __fastcall sub_8395C(int a1)
{
  int v2; // r0
  int v3; // r0
  int v5; // r6
  int v6; // r0
  _BYTE *v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r6
  int v12; // r0
  int v13; // r0
  int v14; // r0
  _DWORD v15[10]; // [sp+14h] [bp-220h] BYREF
  char v16[16]; // [sp+4Ch] [bp-1E8h] BYREF
  char v17[288]; // [sp+5Ch] [bp-1D8h] BYREF
  _DWORD v18[32]; // [sp+17Ch] [bp-B8h] BYREF
  _DWORD v19[14]; // [sp+1FCh] [bp-38h] BYREF

  sub_8562C(v19, 0x38u);
  sub_8562C(v18, 0x80u);
  v2 = *(_DWORD *)(a1 + 524);
  if ( v2 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v2 + 4))(v2);
    *(_DWORD *)(a1 + 524) = 0;
  }
  v3 = (*(int (**)(void))(**(_DWORD **)(a1 + 516) + 28))();
  *(_DWORD *)(a1 + 524) = v3;
  if ( v3 == 0 )
    return -1;
  sub_8475C();
  v5 = sub_843E8();
  v6 = sub_843E8();
  (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)v6 + 16))(v5, v15);
  sub_848B8();
  v7 = (_BYTE *)sub_8496C();
  if ( v7 != nullptr )
    *v7 = 0;
  sub_8475C();
  sub_84798(a1 + 120, "company=%s&model=%s&appid=%d", (const char *)v19, v17, *(_DWORD *)a1);
  v8 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 528) + 64))(*(_DWORD *)(a1 + 528));
  (*(void (__fastcall **)(_DWORD, int, _DWORD *, int))(**(_DWORD **)(a1 + 528) + 44))(
    *(_DWORD *)(a1 + 528),
    v8,
    v19,
    54);
  v9 = sub_848E0();
  sub_84798(v9 + a1 + 120, "&screenw=%d&screenh=%d&capability=%d", v15[2], v15[3], v15[6]);
  v10 = sub_848E0();
  sub_84798(v10 + a1 + 120, "&userid=%d&sdkver=%d&imsi=%s", v15[1], v15[0], (const char *)v19);
  v11 = v15[9] / 1024;
  v12 = sub_848E0();
  sub_84798(v12 + a1 + 120, "&lasttime=%s&maxram=%d&os=%s", (const char *)(a1 + 4), v11, v16);
  v13 = sub_848E0();
  sub_84798(v13 + a1 + 120, "&dllversion=%d&dllname=%s", *(_DWORD *)(a1 + 100), "zmsys006.dll");
  (*(void (__fastcall **)(_DWORD, int (__fastcall *)(int, int, int, int), int))(**(_DWORD **)(a1 + 524) + 8))(
    *(_DWORD *)(a1 + 524),
    sub_836A4,
    a1);
  sub_848B8();
  if ( sub_848A4() == 0 )
    sub_848B8();
  v14 = sub_848E0();
  return (*(int (__fastcall **)(_DWORD, int, _DWORD *, int, const char *, const char *, int, int))(**(_DWORD **)(a1 + 524)
                                                                                                 + 12))(
           *(_DWORD *)(a1 + 524),
           1,
           v18,
           9194,
           "/MenuServer/CheckMenu",
           "Content-Type:application/octet-stream\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\n",
           a1 + 120,
           v14);
}

//----- (00083C60) --------------------------------------------------------
int __fastcall sub_83C60(int a1)
{
  int result; // r0
  int v3; // r4
  int v4; // [sp+0h] [bp-44h] BYREF
  _DWORD v5[16]; // [sp+4h] [bp-40h] BYREF

  sub_8562C(v5, 0x40u);
  *(_DWORD *)(a1 + 100) = 0;
  sub_8475C();
  sub_8496C();
  sub_84748();
  sub_84868();
  result = (*(int (__fastcall **)(_DWORD, _DWORD *, int))(**(_DWORD **)(a1 + 520) + 8))(*(_DWORD *)(a1 + 520), v5, 1);
  v3 = result;
  if ( result != 0 )
  {
    (*(void (__fastcall **)(int, int *, int))(*(_DWORD *)result + 8))(result, &v4, 4);
    if ( v4 == 6006 )
    {
      (*(void (__fastcall **)(int, int *, int))(*(_DWORD *)v3 + 8))(v3, &v4, 4);
      *(_DWORD *)(a1 + 100) = v4;
    }
    return (*(int (__fastcall **)(int))(*(_DWORD *)v3 + 4))(v3);
  }
  return result;
}

//----- (00083D44) --------------------------------------------------------
int __fastcall sub_83D44(int *a1)
{
  int v2; // r5
  int v3; // r0
  int v4; // r1
  bool v5; // zf
  int result; // r0
  _DWORD v7[7]; // [sp+0h] [bp-24h] BYREF
  _BYTE v8[4]; // [sp+1Ch] [bp-8h] BYREF
  int v9; // [sp+20h] [bp-4h] BYREF

  v9 = 0;
  v2 = sub_843E8();
  v3 = sub_843E8();
  (*(void (__fastcall **)(int, int, int *))(*(_DWORD *)v3 + 8))(v2, 16777227, &v9);
  if ( (*(int (__fastcall **)(int, _BYTE *, _DWORD *))(*(_DWORD *)v9 + 36))(v9, v8, v7) == 0 )
  {
    if ( a1[120] != 0 )
      goto LABEL_9;
    v4 = a1[122];
    v5 = v7[0] == v4;
    if ( v7[0] == v4 )
      v5 = v7[1] == a1[123];
    if ( v5 )
      v5 = v7[2] == a1[124];
    if ( v5 )
    {
LABEL_9:
      sub_82FF8(a1[119], 28702, 0, 0);
    }
    else
    {
      sub_84748();
      sub_83C60((int)a1);
      sub_8395C((int)a1);
    }
  }
  result = v9;
  if ( v9 != 0 )
    return (*(int (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
  return result;
}

//----- (00083E24) --------------------------------------------------------
int *__fastcall sub_83E24(_DWORD *a1)
{
  int *v2; // r5
  int v4; // r0
  int v5; // r6
  int v6; // r0
  int v7; // r0
  bool v8; // zf
  int v9; // [sp+0h] [bp-58h]
  int v10; // [sp+4h] [bp-54h]
  int v11; // [sp+Ch] [bp-4Ch] BYREF
  int v12; // [sp+10h] [bp-48h]
  int v13; // [sp+14h] [bp-44h]
  _DWORD v14[16]; // [sp+18h] [bp-40h] BYREF

  sub_8562C(v14, 0x40u);
  v11 = 2;
  v12 = 0;
  v13 = 0;
  v2 = (int *)sub_84410();
  if ( v2 == nullptr )
    return nullptr;
  sub_8475C();
  a1[117] = 71680;
  a1[116] = sub_84410();
  sub_8496C();
  sub_84748();
  sub_84868();
  v4 = sub_843E8();
  v9 = a1[116];
  v10 = a1[117];
  v5 = v4;
  v6 = sub_843E8();
  v7 = (*(int (__fastcall **)(int, _DWORD *, int, int *, int, int))(*(_DWORD *)v6 + 120))(v5, v14, 20, v2 + 1, v9, v10);
  *v2 = v7;
  v8 = v7 == 0;
  if ( v7 != 0 )
    v8 = v2[1] == 0;
  if ( v8 )
  {
    sub_84424();
    sub_84424();
    a1[116] = 0;
    return nullptr;
  }
  v12 = a1[114];
  v13 = a1[26];
  (*(void (__fastcall **)(int, _DWORD, _DWORD, int *))(*(_DWORD *)v2[1] + 12))(v2[1], a1[112], a1[113], &v11);
  return v2;
}

//----- (00083F50) --------------------------------------------------------
BOOL __fastcall sub_83F50(int a1)
{
  int v2; // r7
  int v3; // r6
  int v4; // r0
  int v5; // r4
  int v6; // r0
  unsigned int v7; // r8
  int v8; // r1
  int v9; // r0
  int v10; // r0
  unsigned int v11; // r3
  bool v12; // cc
  int *v13; // r0
  BOOL result; // r0
  int v15; // [sp+0h] [bp-4h] BYREF

  v15 = 0;
  v2 = 0;
  v3 = 0;
  v4 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 520) + 8))(*(_DWORD *)(a1 + 520));
  v5 = v4;
  if ( v4 != 0 )
  {
    (*(void (__fastcall **)(int, int, _DWORD))(*(_DWORD *)v4 + 32))(v4, 1, 0);
    v6 = (*(int (__fastcall **)(int))(*(_DWORD *)v5 + 36))(v5);
    v7 = v6 - 80;
    if ( v6 - 80 < 0
      || (sub_85758(0x68u, v6 - 80), v8 != 0)
      || ((*(void (__fastcall **)(int, _DWORD, _DWORD))(*(_DWORD *)v5 + 32))(v5, 0, 0),
          (*(void (__fastcall **)(int, int *, int))(*(_DWORD *)v5 + 8))(v5, &v15, 4),
          sub_8470C() != 0) )
    {
      v2 = 1;
    }
    else
    {
      (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v5 + 8))(v5, a1 + 4, 32);
      (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v5 + 8))(v5, a1 + 456, 4);
      (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v5 + 8))(v5, a1 + 104, 4);
      (*(void (__fastcall **)(int, _DWORD, int))(*(_DWORD *)v5 + 32))(v5, 0, 48);
      (*(void (__fastcall **)(int, int *, int))(*(_DWORD *)v5 + 8))(v5, &v15, 4);
      v9 = sub_85684(0x68u, v7);
      if ( v9 != v15 )
      {
        v15 = 0;
        v2 = 1;
      }
      if ( v15 != 0 )
      {
        v10 = sub_84410();
        *(_DWORD *)(a1 + 448) = v10;
        if ( v10 != 0 )
        {
          (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v5 + 8))(v5, v10, 104 * v15);
          while ( v3 < v15 )
          {
            v11 = *(_DWORD *)(*(_DWORD *)(a1 + 448) + 104 * v3);
            if ( v11 == 0 )
              goto LABEL_16;
            v12 = v11 > 0x2700;
            if ( v11 >= 0x2700 )
              v12 = v11 - 9984 > 0xF;
            if ( v12 )
            {
LABEL_16:
              sub_84424();
              *(_DWORD *)(a1 + 448) = 0;
              v2 = 1;
              goto LABEL_17;
            }
            ++v3;
          }
        }
        else
        {
          *(_DWORD *)(a1 + 480) = 1;
LABEL_17:
          v15 = 0;
        }
      }
      (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v5 + 8))(v5, a1 + 488, 28);
    }
    (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
    if ( v2 != 0 )
      (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 520) + 16))(*(_DWORD *)(a1 + 520), a1 + 36);
  }
  result = false;
  if ( v15 != 0 )
  {
    *(_DWORD *)(a1 + 452) = v15;
    v13 = sub_83E24((_DWORD *)a1);
    *(_DWORD *)(a1 + 460) = v13;
    if ( v13 != nullptr )
      return true;
  }
  return result;
}
// 83FCC: variable 'v8' is possibly undefined

//----- (000841D4) --------------------------------------------------------
int __fastcall sub_841D4(int a1)
{
  int v2; // r4
  int v3; // r5
  int v4; // r0
  int v5; // r5
  int v6; // r0
  int v7; // r5
  int v8; // r0
  int v9; // r0

  v2 = sub_84410();
  sub_8475C();
  v3 = sub_843E8();
  v4 = sub_843E8();
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v4 + 8))(v3, 16777225, v2 + 528);
  v5 = sub_843E8();
  v6 = sub_843E8();
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v6 + 8))(v5, 16777220, v2 + 516);
  v7 = sub_843E8();
  v8 = sub_843E8();
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v8 + 8))(v7, 16777219, v2 + 520);
  sub_848B8();
  sub_84868();
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(v2 + 520) + 20))(*(_DWORD *)(v2 + 520), v2 + 36);
  sub_84868();
  sub_8475C();
  *(_DWORD *)(v2 + 524) = 0;
  *(_DWORD *)v2 = a1;
  *(_DWORD *)(v2 + 448) = 0;
  *(_DWORD *)(v2 + 452) = 0;
  *(_DWORD *)(v2 + 460) = 0;
  *(_DWORD *)(v2 + 464) = 0;
  *(_DWORD *)(v2 + 468) = 0;
  *(_DWORD *)(v2 + 112) = 0;
  *(_DWORD *)(v2 + 108) = 0;
  v9 = sub_84E04();
  *(_DWORD *)(v2 + 476) = v9;
  *(_DWORD *)(v2 + 472) = *(_DWORD *)(*(_DWORD *)v9 + 8);
  *(_DWORD *)(*(_DWORD *)v9 + 8) = sub_82FF8;
  *(_DWORD *)(v2 + 484) = -1;
  *(_DWORD *)(v2 + 440) = 0;
  return v2;
}

//----- (0008433C) --------------------------------------------------------
BOOL __fastcall sub_8433C(int a1, int a2, _DWORD *a3)
{
  int v5; // r1
  BOOL result; // r0
  int v7; // r0
  int v8; // r0
  BOOL v9; // r4
  int *v10; // r0
  _DWORD v11[16]; // [sp+0h] [bp-40h] BYREF

  sub_8562C(v11, 0x40u);
  if ( a2 == 0 )
    v5 = a3[64];
  result = false;
  if ( a2 != 0 || v5 != 4 || *a3 != 1 )
  {
    if ( sub_84944() != 0 )
    {
      sub_84748();
      a2 = sub_84854();
    }
    v7 = sub_841D4(a2);
    sub_82E68(v7);
    v8 = sub_82E54();
    v9 = sub_83F50(v8);
    v10 = (int *)sub_82E54();
    sub_83D44(v10);
    return v9;
  }
  return result;
}
// 8436C: variable 'v5' is possibly undefined

//----- (000843E8) --------------------------------------------------------
int sub_843E8()
{
  return MEMORY[0x384]();
}
// 384: using guessed type int (*)(void);

//----- (00084410) --------------------------------------------------------
int sub_84410()
{
  return MEMORY[0x38C]();
}
// 38C: using guessed type int (*)(void);

//----- (00084424) --------------------------------------------------------
int sub_84424()
{
  return MEMORY[0x390]();
}
// 390: using guessed type int (*)(void);

//----- (00084460) --------------------------------------------------------
int sub_84460()
{
  return MEMORY[0x39C]();
}
// 39C: using guessed type int (*)(void);

//----- (00084474) --------------------------------------------------------
int __fastcall sub_84474(int a1, int a2, int a3, int a4)
{
  return MEMORY[0x3A0](a1, a2, a3, a4);
}
// 3A0: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (000844C0) --------------------------------------------------------
int sub_844C0()
{
  return MEMORY[0x3A8]();
}
// 3A8: using guessed type int (*)(void);

//----- (00084538) --------------------------------------------------------
int sub_84538()
{
  return MEMORY[0x428]();
}
// 428: using guessed type int (*)(void);

//----- (0008454C) --------------------------------------------------------
int __fastcall sub_8454C(_BYTE *a1, _DWORD *a2, int **a3)
{
  int v4; // r5
  int result; // r0
  int v7; // r1
  unsigned int v8; // r0
  bool v9; // zf
  int *v10; // r0
  int v11; // r3
  int v12; // r0
  _DWORD *v13; // r2
  int v14; // r1
  bool v15; // zf
  int v16; // r2

  v4 = 0;
  while ( 1 )
  {
    v14 = (unsigned __int8)*a1;
    if ( *a1 == 0 )
      break;
    ++a1;
    if ( v14 == 37 )
    {
      if ( *a1 == 37 )
      {
        ++a1;
      }
      else
      {
        result = sub_84538();
        if ( result == 0 )
          return result;
        v7 = result;
        v8 = *(unsigned __int8 *)result;
        if ( v8 == 111 )
        {
LABEL_23:
          v16 = *(*a3)++;
          a2[2 * v4 + 1] = v16;
          goto LABEL_15;
        }
        if ( v8 > 0x6F )
        {
          v15 = v8 == 112;
          if ( v8 != 112 )
            v15 = v8 == 115;
          if ( v15 || v8 == 117 || v8 == 120 )
            goto LABEL_23;
        }
        else
        {
          v9 = v8 == 88;
          if ( v8 != 88 )
            v9 = v8 == 99;
          if ( !v9 )
            v9 = v8 == 100;
          if ( v9 )
            goto LABEL_23;
          if ( v8 == 102 )
          {
            v10 = *a3;
            *a3 += 2;
            v11 = *v10;
            v12 = v10[1];
            v13 = &a2[2 * v4];
            v13[1] = v11;
            v13[2] = v12;
          }
        }
LABEL_15:
        a1 = (_BYTE *)(v7 + 1);
        ++v4;
      }
    }
  }
  *a2 = v4;
  return 1;
}

//----- (00084670) --------------------------------------------------------
int sub_84670(_BYTE *a1, ...)
{
  int result; // r0
  int *v2; // [sp+4h] [bp-88h] BYREF
  _DWORD v3[33]; // [sp+8h] [bp-84h] BYREF
  _BYTE *varg_r0; // [sp+90h] [bp+4h]
  va_list varg_r1; // [sp+94h] [bp+8h] BYREF

  va_start(varg_r1, a1);
  varg_r0 = a1;
  va_copy((va_list)v2, varg_r1);
  result = sub_8454C(a1, v3, &v2);
  if ( result != 0 )
    return MEMORY[0x3C0](varg_r0, v3);
  return result;
}
// 3C0: using guessed type int (__fastcall *)(_DWORD, _DWORD);

//----- (0008470C) --------------------------------------------------------
int sub_8470C()
{
  return MEMORY[0x3D4]();
}
// 3D4: using guessed type int (*)(void);

//----- (00084748) --------------------------------------------------------
int sub_84748()
{
  return MEMORY[0x3E0]();
}
// 3E0: using guessed type int (*)(void);

//----- (0008475C) --------------------------------------------------------
int sub_8475C()
{
  return MEMORY[0x3E4]();
}
// 3E4: using guessed type int (*)(void);

//----- (00084798) --------------------------------------------------------
int sub_84798(int a1, _BYTE *a2, ...)
{
  int result; // r0
  int *v4; // [sp+0h] [bp-88h] BYREF
  _DWORD v5[33]; // [sp+4h] [bp-84h] BYREF
  _BYTE *varg_r1; // [sp+94h] [bp+Ch]
  va_list varg_r2; // [sp+98h] [bp+10h] BYREF

  va_start(varg_r2, a2);
  varg_r1 = a2;
  va_copy((va_list)v4, varg_r2);
  result = sub_8454C(a2, v5, &v4);
  if ( result != 0 )
    return MEMORY[0x3F0](a1, varg_r1, v5);
  return result;
}
// 3F0: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD);

//----- (000847F4) --------------------------------------------------------
int __fastcall sub_847F4(int a1, _BYTE *a2, int **a3)
{
  int result; // r0
  _DWORD v6[33]; // [sp+0h] [bp-84h] BYREF

  result = sub_8454C(a2, v6, a3);
  if ( result != 0 )
    return MEMORY[0x3F0](a1, a2, v6);
  return result;
}
// 3F0: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD);

//----- (00084854) --------------------------------------------------------
int sub_84854()
{
  return MEMORY[0x3F8]();
}
// 3F8: using guessed type int (*)(void);

//----- (00084868) --------------------------------------------------------
int sub_84868()
{
  return MEMORY[0x3FC]();
}
// 3FC: using guessed type int (*)(void);

//----- (0008487C) --------------------------------------------------------
int sub_8487C()
{
  return MEMORY[0x400]();
}
// 400: using guessed type int (*)(void);

//----- (00084890) --------------------------------------------------------
int sub_84890()
{
  return MEMORY[0x404]();
}
// 404: using guessed type int (*)(void);

//----- (000848A4) --------------------------------------------------------
int sub_848A4()
{
  return MEMORY[0x408]();
}
// 408: using guessed type int (*)(void);

//----- (000848B8) --------------------------------------------------------
int sub_848B8()
{
  return MEMORY[0x40C]();
}
// 40C: using guessed type int (*)(void);

//----- (000848CC) --------------------------------------------------------
int sub_848CC()
{
  return MEMORY[0x410]();
}
// 410: using guessed type int (*)(void);

//----- (000848E0) --------------------------------------------------------
int sub_848E0()
{
  return MEMORY[0x414]();
}
// 414: using guessed type int (*)(void);

//----- (00084944) --------------------------------------------------------
int sub_84944()
{
  return MEMORY[0x42C]();
}
// 42C: using guessed type int (*)(void);

//----- (0008496C) --------------------------------------------------------
int sub_8496C()
{
  return MEMORY[0x434]();
}
// 434: using guessed type int (*)(void);

//----- (000849BC) --------------------------------------------------------
int sub_849BC()
{
  return MEMORY[0x444]();
}
// 444: using guessed type int (*)(void);

//----- (000849E4) --------------------------------------------------------
int sub_849E4()
{
  return MEMORY[0x44C]();
}
// 44C: using guessed type int (*)(void);

//----- (00084A0C) --------------------------------------------------------
int sub_84A0C()
{
  return MEMORY[0x454]();
}
// 454: using guessed type int (*)(void);

//----- (00084A34) --------------------------------------------------------
int sub_84A34()
{
  return MEMORY[0x45C]();
}
// 45C: using guessed type int (*)(void);

//----- (00084BD8) --------------------------------------------------------
int __fastcall sub_84BD8(int a1, int a2, int a3, int a4)
{
  return MEMORY[0x4B0](a1, a2, a3, a4);
}
// 4B0: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00084C04) --------------------------------------------------------
int __fastcall sub_84C04(int a1, int a2, int a3, int a4)
{
  return MEMORY[0x4B4](a1, a2, a3, a4);
}
// 4B4: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00084C6C) --------------------------------------------------------
int __fastcall sub_84C6C(int a1, int a2, int a3, int a4)
{
  return MEMORY[0x4C4](a1, a2, a3, a4);
}
// 4C4: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00084D94) --------------------------------------------------------
void sub_84D94()
{
  JUMPOUT(0x84D9A);
}
// 84D96: control flows out of bounds to 84D9A

//----- (00084DA4) --------------------------------------------------------
void sub_84DA4()
{
  JUMPOUT(0x84DAA);
}
// 84DA6: control flows out of bounds to 84DAA

//----- (00084E04) --------------------------------------------------------
int sub_84E04()
{
  return MEMORY[0x4D8]();
}
// 4D8: using guessed type int (*)(void);

//----- (00084E7C) --------------------------------------------------------
__int64 __fastcall sub_84E7C(int a1, int a2, int a3, int a4, __int64 a5)
{
  MEMORY[0x4F0](a1, a2, a3, a4);
  return a5;
}
// 4F0: using guessed type int (__fastcall *)(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00084F60) --------------------------------------------------------
int __fastcall sub_84F60(int a1, int a2)
{
  int v2; // r4
  int v3; // r0
  _DWORD v5[94]; // [sp+4h] [bp-178h] BYREF

  v5[92] = a1;
  v5[93] = a2;
  sub_8562C(v5, 0x168u);
  v2 = sub_843E8();
  v3 = sub_843E8();
  (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)v3 + 16))(v2, v5);
  sub_84748();
  sub_84748();
  sub_84460();
  return 1;
}

//----- (00084FD8) --------------------------------------------------------
int __fastcall sub_84FD8(int a1, const char *a2, _DWORD *a3, int a4)
{
  int v8; // r0
  int v9; // r0
  int v10; // r4
  _BYTE v12[128]; // [sp+0h] [bp-21Ch] BYREF
  int v13; // [sp+80h] [bp-19Ch] BYREF
  _DWORD v14[5]; // [sp+84h] [bp-198h] BYREF
  int v15; // [sp+108h] [bp-114h]
  _BYTE v16[16]; // [sp+20Ch] [bp-10h] BYREF

  memset(v16, 0, sizeof(v16));
  sub_8562C(v14, 0x188u);
  v13 = 0;
  v8 = sub_843E8();
  if ( (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v8 + 8))(v8, 16777219, &v13) != 0 )
    return 0;
  sub_84798((int)v12, "%s%08x.app", a2, a1);
  v9 = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v13 + 8))(v13, v12, 1);
  v10 = v9;
  if ( v9 == 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 4))(v13);
    return 0;
  }
  (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v9 + 8))(v9, v14, 392);
  (*(void (__fastcall **)(int))(*(_DWORD *)v10 + 4))(v10);
  (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 4))(v13);
  if ( v15 == 0x7FFFFFFF )
    return 0;
  sub_84F60((int)v16, a1);
  if ( sub_8470C() == 0 )
    return 0;
  if ( a3 != nullptr )
    *a3 = v15;
  if ( a4 != 0 )
    sub_848B8();
  return 1;
}

//----- (00085128) --------------------------------------------------------
int __fastcall sub_85128(int a1, const char *a2)
{
  int v4; // r5
  int v5; // r0
  int v7; // r0
  int v8; // r5
  _BYTE v9[128]; // [sp+4h] [bp-20Ch] BYREF
  _DWORD v10[34]; // [sp+84h] [bp-18Ch] BYREF
  _BYTE v11[256]; // [sp+10Ch] [bp-104h] BYREF
  int v12; // [sp+20Ch] [bp-4h] BYREF

  v12 = 0;
  sub_8562C(v10, 0x188u);
  v4 = sub_843E8();
  v5 = sub_843E8();
  if ( (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v5 + 8))(v4, 16777219, &v12) == 0 )
  {
    sub_84798((int)v9, "%s%08x.app", a2, a1);
    v7 = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v12 + 8))(v12, v9, 2);
    v8 = v7;
    if ( v7 != 0 )
    {
      (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v7 + 8))(v7, v10, 392);
      sub_84F60((int)v11, a1);
      (*(void (__fastcall **)(int, _DWORD, _DWORD))(*(_DWORD *)v8 + 32))(v8, 0, 0);
      (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v8 + 12))(v8, v10, 392);
      (*(void (__fastcall **)(int))(*(_DWORD *)v8 + 4))(v8);
      (*(void (__fastcall **)(int))(*(_DWORD *)v12 + 4))(v12);
      return 1;
    }
    (*(void (__fastcall **)(int))(*(_DWORD *)v12 + 4))(v12);
  }
  return 0;
}

//----- (00085248) --------------------------------------------------------
int *__fastcall sub_85248(int a1, int a2, int a3, int a4, int a5, int a6)
{
  int *v9; // r4
  int v11; // r5
  int v12; // r0
  int v13; // r0
  bool v14; // zf

  v9 = (int *)sub_84410();
  if ( v9 == nullptr )
    return nullptr;
  sub_8475C();
  v11 = sub_843E8();
  v12 = sub_843E8();
  v13 = (*(int (__fastcall **)(int, const char *, int, int *))(*(_DWORD *)v12 + 88))(v11, "zmsys001.dll", 28, v9 + 1);
  *v9 = v13;
  v14 = v13 == 0;
  if ( v13 != 0 )
  {
    v13 = v9[1];
    v14 = v13 == 0;
  }
  if ( v14 )
  {
    sub_84424();
    return nullptr;
  }
  (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 8))(v13);
  (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)v9[1] + 12))(v9[1], 28672, 5678, 1);
  (*(void (__fastcall **)(int, int, int, int, int, int, int))(*(_DWORD *)v9[1] + 16))(v9[1], a1, a3, a2, a4, a5, a6);
  return v9;
}

//----- (00085340) --------------------------------------------------------
int __fastcall sub_85340(int result)
{
  _DWORD *v1; // r4
  int v2; // r0
  int v3; // r5
  int v4; // r0

  v1 = (_DWORD *)result;
  if ( result != 0 )
  {
    v2 = *(_DWORD *)(result + 4);
    if ( v2 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v2 + 4))(v2);
      v1[1] = 0;
    }
    if ( *v1 != 0 )
    {
      v3 = sub_843E8();
      v4 = sub_843E8();
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v4 + 92))(v3, *v1);
      *v1 = 0;
    }
    return sub_84424();
  }
  return result;
}

//----- (000853A8) --------------------------------------------------------
int __fastcall sub_853A8(int a1)
{
  int result; // r0

  result = *(_DWORD *)(a1 + 4);
  if ( result != 0 )
    return (*(int (__fastcall **)(int))(*(_DWORD *)result + 12))(result);
  return result;
}

//----- (000853C0) --------------------------------------------------------
int __fastcall sub_853C0(int a1, const char *a2, int a3)
{
  int v4; // r0
  bool v5; // cc
  _BYTE v7[64]; // [sp+4h] [bp-44h] BYREF
  int v8; // [sp+44h] [bp-4h] BYREF

  v4 = sub_8540C(a1, a2, &v8);
  v5 = v4 <= 0;
  if ( v4 != 0 )
  {
    v4 = v8;
    v5 = v8 <= 0;
  }
  if ( v5 || v4 > 64 )
    return 1;
  else
    return sub_85510(v4, (int)v7, a3);
}

//----- (0008540C) --------------------------------------------------------
int __fastcall sub_8540C(int a1, const char *a2, _DWORD *a3)
{
  int v6; // r4
  int v7; // r0
  int v9; // r0
  int v10; // r4
  _BYTE v11[128]; // [sp+4h] [bp-20Ch] BYREF
  _DWORD v12[39]; // [sp+84h] [bp-18Ch] BYREF
  int v13; // [sp+20Ch] [bp-4h] BYREF

  v13 = 0;
  sub_8562C(v12, 0x188u);
  v6 = sub_843E8();
  v7 = sub_843E8();
  if ( (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v7 + 8))(v6, 16777219, &v13) == 0 )
  {
    sub_84798((int)v11, "%s%08x.app", a2, a1);
    v9 = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v13 + 8))(v13, v11, 2);
    v10 = v9;
    if ( v9 != 0 )
    {
      (*(void (__fastcall **)(int, _DWORD *, int))(*(_DWORD *)v9 + 8))(v9, v12, 392);
      (*(void (__fastcall **)(int))(*(_DWORD *)v10 + 4))(v10);
      (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 4))(v13);
      *a3 = v12[38];
      sub_84748();
      return 1;
    }
    (*(void (__fastcall **)(int))(*(_DWORD *)v13 + 4))(v13);
  }
  return 0;
}

//----- (00085510) --------------------------------------------------------
int __fastcall sub_85510(int a1, int a2, int a3)
{
  int v6; // r5
  int v7; // r0
  _BYTE *v8; // r1
  int v9; // r2
  int v10; // r0
  int i; // r0
  _DWORD v13[16]; // [sp+8h] [bp-1E8h] BYREF
  _BYTE v14[40]; // [sp+48h] [bp-1A8h] BYREF
  char v15[32]; // [sp+70h] [bp-180h] BYREF
  char v16[288]; // [sp+90h] [bp-160h] BYREF
  _BYTE v17[64]; // [sp+1B0h] [bp-40h] BYREF

  sub_8562C(v13, 0x40u);
  if ( (unsigned int)sub_84474(a2, a1, (int)"a*e#0$sc", 8) <= 0x40 )
  {
    v6 = sub_843E8();
    v7 = sub_843E8();
    (*(void (__fastcall **)(int, _BYTE *))(*(_DWORD *)v7 + 16))(v6, v14);
    sub_84798((int)v17, "%s%s", v15, v16);
    v8 = v17;
    v9 = 131;
    while ( 1 )
    {
      v10 = (unsigned __int8)*v8;
      if ( *v8 == 0 )
        break;
      if ( (unsigned int)(v10 - 65) <= 0x19 )
        v10 += 32;
      v9 = v10 + 241 * v9;
      ++v8;
    }
    if ( v13[0] == v9 )
    {
      for ( i = 0; v13[1] > i; ++i )
      {
        if ( SLOWORD(v13[i + 2]) == a3 )
          return SHIWORD(v13[i + 2]);
      }
    }
  }
  return 1;
}

//----- (0008562C) --------------------------------------------------------
_DWORD *__fastcall sub_8562C(_DWORD *result, unsigned int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  _DWORD *v4; // r0
  int v5; // r1
  int v6; // r1
  _BYTE *v7; // r0

  v2 = a2 >= 0x20;
  v3 = a2 - 32;
  do
  {
    if ( !v2 )
      break;
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    v4 = result + 4;
    *v4 = 0;
    v4[1] = 0;
    v4[2] = 0;
    v4[3] = 0;
    result = v4 + 4;
    v2 = v3 >= 0x20;
    v3 -= 32;
  }
  while ( v2 );
  v2 = __CFSHL__(v3, 28);
  v5 = v3 << 28;
  if ( v2 )
  {
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    result += 4;
  }
  if ( v5 < 0 )
  {
    *result = 0;
    result[1] = 0;
    result += 2;
  }
  v2 = __CFSHL__(v5, 2);
  v6 = 4 * v5;
  if ( v2 )
    *result++ = 0;
  if ( v6 != 0 )
  {
    if ( v6 < 0 )
    {
      *(_BYTE *)result = 0;
      v7 = (char *)result + 1;
      *v7 = 0;
      result = v7 + 1;
    }
    if ( (v6 & 0x40000000) != 0 )
    {
      *(_BYTE *)result = 0;
      return (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (00085684) --------------------------------------------------------
int __fastcall sub_85684(unsigned int a1, unsigned int a2)
{
  unsigned int v2; // r2
  int v3; // r3
  char v4; // cf
  bool v5; // cf
  unsigned int v6; // r2
  bool v7; // cf
  unsigned int v8; // r2
  bool v9; // cf
  unsigned int v10; // r2
  bool v11; // cf
  bool v12; // cf
  bool v13; // cf
  unsigned int v14; // r2
  bool v15; // cf
  unsigned int v16; // r2
  bool v17; // cf
  unsigned int v18; // off

  v2 = a1 & 0x80000000;
  if ( (a1 & 0x80000000) != 0 )
    a1 = -a1;
  v3 = v2 ^ ((int)a2 >> 31);
  if ( (a2 & 0x80000000) != 0 )
    a2 = -a2;
  if ( a2 >> 3 < a1 )
    goto LABEL_27;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF000000;
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF0000u;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 |= 0xFF00u;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  v4 = a1 == 0;
  if ( a1 == 0 )
    return sub_859A0(2, 2, v2, (const char *)v3);
  do
  {
    if ( v4 )
      a1 >>= 8;
LABEL_15:
    v5 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v6 = v2 + v5 + v2;
    v7 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v8 = v6 + v7 + v6;
    v9 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v10 = v8 + v9 + v8;
    v11 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v10 + v11 + v10;
LABEL_24:
    v12 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v12 + v2;
LABEL_27:
    v13 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v14 = v2 + v13 + v2;
    v15 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v16 = v14 + v15 + v14;
    v17 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v18 = v17 + v16;
    v4 = __CFADD__(v17, v16) | __CFADD__(v16, v18);
    v2 = v16 + v18;
  }
  while ( v4 );
  return (v2 ^ (v3 >> 31)) + ((unsigned int)v3 >> 31);
}

//----- (00085758) --------------------------------------------------------
int __fastcall sub_85758(unsigned int a1, unsigned int a2)
{
  int v2; // r2
  char v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // cf
  int v7; // r2
  bool v8; // cf
  int v9; // r2
  bool v10; // cf
  bool v11; // cf
  bool v12; // cf
  int v13; // r2
  bool v14; // cf
  int v15; // r2
  bool v16; // cf
  int v17; // off

  v2 = 0;
  if ( a2 >> 3 < a1 )
    goto LABEL_23;
  if ( a2 >> 8 < a1 )
    goto LABEL_11;
  a1 <<= 8;
  v2 = -16777216;
  if ( a2 >> 4 < a1 )
    goto LABEL_20;
  if ( a2 >> 8 < a1 )
    goto LABEL_11;
  a1 <<= 8;
  v2 = -65536;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 = -256;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_20;
  v3 = a1 == 0;
  if ( a1 == 0 )
    return sub_859A0(2, 2, v2);
  do
  {
    if ( v3 )
      a1 >>= 8;
LABEL_11:
    v4 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v5 = v2 + v4 + v2;
    v6 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v7 = v5 + v6 + v5;
    v8 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v9 = v7 + v8 + v7;
    v10 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v9 + v10 + v9;
LABEL_20:
    v11 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v11 + v2;
LABEL_23:
    v12 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v13 = v2 + v12 + v2;
    v14 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v15 = v13 + v14 + v13;
    v16 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v17 = v16 + v15;
    v3 = __CFADD__(v16, v15) | __CFADD__(v15, v17);
    v2 = v15 + v17;
  }
  while ( v3 );
  return v2;
}
// 859A0: using guessed type int __fastcall sub_859A0(_DWORD, _DWORD, _DWORD);

//----- (00085818) --------------------------------------------------------
unsigned int __fastcall sub_85818(int a1)
{
  int v1; // r3
  int v2; // r1
  unsigned int v3; // r0
  unsigned int result; // r0

  v1 = a1;
  if ( a1 < 0 )
    a1 = -a1;
  v2 = a1 - 10;
  v3 = a1 - ((unsigned int)a1 >> 2) + ((a1 - ((unsigned int)a1 >> 2)) >> 4);
  result = (v3 + (v3 >> 8) + ((v3 + (v3 >> 8)) >> 16)) >> 3;
  if ( (int)(v2 - 10 * result) >= 0 )
    ++result;
  if ( v1 < 0 )
    return -result;
  return result;
}

//----- (00085868) --------------------------------------------------------
int sub_85868()
{
  sub_85988();
  return sub_8587C();
}

//----- (0008588C) --------------------------------------------------------
int sub_8588C()
{
  return sub_85868();
}

//----- (000858A4) --------------------------------------------------------
_UNKNOWN **sub_858A4()
{
  _DWORD *v0; // r4

  sub_85D1C();
  v0 = (_DWORD *)sub_85B30();
  v0[8] = 0;
  v0[9] = 1;
  v0[10] = 0;
  v0[11] = 0;
  v0[12] = 0;
  return &off_8599C;
}
// 85978: returning address of temporary local variable '%var_C'
// 8599C: using guessed type _UNKNOWN *off_8599C;

//----- (00085988) --------------------------------------------------------
void sub_85988()
{
  ;
}

//----- (000859A0) --------------------------------------------------------
int __fastcall sub_859A0(int a1, int a2, int a3, const char *a4)
{
  int result; // r0

  result = sub_85ACC(a1, a2, a3, a4);
  if ( result != 0 )
    return sub_85AB4();
  return result;
}

//----- (00085A48) --------------------------------------------------------
int __fastcall sub_85A48(int a1, _DWORD *a2)
{
  int v2; // r4
  char *v3; // r3
  int v4; // r2
  int v5; // lr
  unsigned int v6; // r3
  unsigned int v7; // r1
  _DWORD savedregs[2]; // [sp+8h] [bp+0h] BYREF

  v2 = sub_85B30();
  v3 = (char *)savedregs - *(_DWORD *)(v2 + 28);
  v4 = *(_DWORD *)(v2 + 20);
  *a2 = v4;
  v5 = v4 + a1;
  if ( v4 + a1 > (unsigned int)v3 )
    return 0;
  v6 = ((unsigned int)&v3[v5] >> 1) & 0x7FFFFFF8 | (__CFADD__(v3, v5) << 31);
  v7 = (v5 + 4103) & 0xFFFFFFF8;
  if ( v7 > v6 )
    v7 = v6;
  *(_DWORD *)(v2 + 20) = v7;
  return v7 - v4;
}

//----- (00085AB4) --------------------------------------------------------
int sub_85AB4()
{
  return __semihost(24, (void *)0x20026);
}

//----- (00085ACC) --------------------------------------------------------
int __fastcall sub_85ACC(int a1, int a2, int a3, const char *a4)
{
  return sub_85B94(a1, a2, 0x78187, a4);
}

//----- (00085B30) --------------------------------------------------------
int sub_85B30()
{
  _DWORD **v0; // r9

  return **v0 + 4;
}
// 85B30: variable 'v0' is possibly undefined

//----- (00085B48) --------------------------------------------------------
int sub_85B48()
{
  int v0; // r9
  int v1; // r0
  int *v3; // [sp+0h] [bp-14h] BYREF
  int v4; // [sp+4h] [bp-10h] BYREF

  v3 = &v4;
  __semihost(22, &v3);
  v1 = v4;
  if ( v4 == 0 )
    v1 = 100;
  return v1 + v0;
}
// 85B7C: variable 'v0' is possibly undefined

//----- (00085B94) --------------------------------------------------------
int __fastcall sub_85B94(int a1, int a2, int a3, const char *a4)
{
  const char *v4; // r5
  char *v5; // r2
  const char *v6; // r4
  bool v7; // zf
  int v8; // r1
  int v9; // r2
  int v10; // r3
  char v11; // t1
  char v12; // t1

  v5 = (char *)(a1 - 1);
  if ( (unsigned int)(a1 - 1) >= 0xD )
    v4 = "Unknown signal";
  v6 = (const char *)&unk_85C78;
  if ( (unsigned int)(a1 - 1) < 0xD )
  {
    a4 = "Abnormal termination";
    v5 = &aAbnormalTermin[23 * a1];
    v4 = v5 - 23;
    if ( a1 == 2 )
    {
      if ( (a2 & 0x4000000) != 0 )
      {
        v6 = "Invalid Operation";
      }
      else if ( (a2 & 0x8000002) != 0 )
      {
        v6 = "Divide By Zero";
      }
      else if ( (a2 & 0x10000000) != 0 )
      {
        v6 = "Overflow";
      }
      else if ( (a2 & 0x20000000) != 0 )
      {
        v6 = "Underflow";
      }
      else if ( (a2 & 0x40000000) != 0 )
      {
        v6 = "Inexact Result";
      }
    }
    else if ( a1 == 8 )
    {
      v6 = (const char *)a2;
    }
    else
    {
      v7 = a1 == 9;
      if ( a1 == 9 )
        v7 = a2 == 1;
      if ( v7 )
        v4 = ": Heap memory corrupted";
    }
  }
  sub_85D04(10, a2, (int)v5, (int)a4);
  while ( *v4 != 0 )
  {
    v11 = *v4++;
    sub_85D04(v11, v8, v9, v10);
  }
  while ( *v6 != 0 )
  {
    v12 = *v6++;
    sub_85D04(v12, v8, v9, v10);
  }
  sub_85D04(10, v8, v9, v10);
  return 1;
}
// 85C28: variable 'v4' is possibly undefined
// 85C38: variable 'v8' is possibly undefined
// 85C38: variable 'v9' is possibly undefined
// 85C38: variable 'v10' is possibly undefined

//----- (00085CF4) --------------------------------------------------------
int sub_85CF4()
{
  return sub_85B30() + 4;
}

//----- (00085D04) --------------------------------------------------------
int __fastcall sub_85D04(char a1, int a2, int a3, int a4)
{
  int v5; // [sp+0h] [bp-4h] BYREF

  v5 = a4;
  LOBYTE(v5) = a1;
  return __semihost(3, &v5);
}

//----- (00085D1C) --------------------------------------------------------
_DWORD *sub_85D1C()
{
  _DWORD *result; // r0

  result = (_DWORD *)sub_85CF4();
  *result = 0;
  return result;
}

// nfuncs=115 queued=113 decompiled=113 lumina nreq=0 worse=0 better=0
// ALL OK, 113 function(s) have been successfully decompiled
