/* This file was generated by the Hex-Rays decompiler version 9.4.0.260713.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void __fastcall sub_274(int a1, int a2);
int __fastcall sub_354(int a1);
int __fastcall sub_3F4(int a1, int a2, int a3, int a4);
int (__fastcall *__fastcall sub_5D4(_DWORD *a1, int (**a2)()))(int a1, int a2, int a3, int a4);
void __fastcall sub_604(int a1);
int sub_6BC();
int sub_6C4();
int __fastcall sub_6DC(int *a1, int a2);
int __fastcall sub_834(int a1, int a2, int a3);
int __fastcall sub_8E0(const char *a1, int a2, int a3);
_DWORD *__fastcall sub_99C(int a1);
BOOL __fastcall sub_A60(int a1, unsigned __int8 *a2);
int __fastcall sub_AA8(_DWORD *a1, int a2, int a3);
_DWORD *__fastcall sub_CC4(_DWORD *a1);
int __fastcall sub_D9C(int a1, int a2);
int __fastcall sub_DE4(int a1, int a2);
int __fastcall sub_DF4(int *a1, int a2);
BOOL __fastcall sub_EF4(int a1, int a2);
int __fastcall sub_F04(int a1);
int __fastcall sub_FD8(int result);
int __fastcall sub_1100(int a1, _BYTE *a2, int a3, int a4);
int __fastcall sub_1400(int a1, _BYTE *a2, int a3, int a4);
int sub_159C(int a1, ...);
int __fastcall sub_1744(int a1, int a2);
int sub_18D4();
void __fastcall sub_18F8(int a1, void (__fastcall *a2)(_DWORD));
void __fastcall sub_1940(int a1, void (__fastcall *a2)(_DWORD, int), int a3);
int __fastcall sub_1990(int *a1, int a2);
int __fastcall sub_19EC(int *a1, int a2);
int __fastcall sub_1A40(int a1, int a2);
int *__fastcall sub_1A4C(int *result, int a2, int a3);
int *__fastcall sub_1AEC(int **a1);
int __fastcall sub_1B2C(int *a1);
int __fastcall sub_1B6C(int a1);
int __fastcall sub_1BD0(int *a1, int a2);
int *__fastcall sub_1C2C(int *result, int a2);
int *__fastcall sub_1CCC(int *a1, _DWORD *a2);
int __fastcall sub_1D30(int a1);
int __fastcall sub_1DBC(int a1);
_DWORD *__fastcall sub_1DCC(int a1, int a2, int a3, int a4, int a5, int a6);
void __fastcall sub_1F40(int a1);
int __fastcall sub_1F68(int result, int a2);
int __fastcall sub_1FB0(int result, int a2, int a3);
BOOL __fastcall sub_2020(_DWORD *a1, int a2);
BOOL __fastcall sub_2040(int a1, int a2, int a3);
_DWORD *__fastcall sub_2090(int a1, int a2, int a3);
void __fastcall sub_2128(_DWORD *a1, int a2, void (__fastcall *a3)(_DWORD *, _DWORD));
int __fastcall sub_21A4(_DWORD *a1, _DWORD *a2);
int *__fastcall sub_2330(int *result);
int __fastcall sub_23D4(int result);
int __fastcall sub_2458(int a1, _DWORD *a2);
_DWORD *__fastcall sub_25E0(_DWORD *result);
void __fastcall sub_2628(int a1, int a2);
void __fastcall sub_2658(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_26FC(int result, int a2);
void __fastcall sub_2754(int *a1);
int __fastcall sub_27BC(int a1, _DWORD *a2);
void sub_2808();
void sub_2830();
void sub_2844();
int __fastcall sub_2894(int a1, int a2, int a3, int a4);
void sub_294C();
void __fastcall sub_2960(_BYTE *a1, _DWORD *a2, int **a3);
void sub_2A84(_BYTE *a1, ...);
void sub_2AD0();
void sub_2AE4();
void sub_2B5C();
void sub_2B70();
void sub_2B98();
void sub_2BAC(int a1, _BYTE *a2, ...);
void __fastcall sub_2C08(int a1, _BYTE *a2, int **a3);
void sub_2C7C();
void sub_2CCC();
void sub_2CF4();
int __fastcall sub_2FEC(int a1, int a2, int a3, int a4);
int __fastcall sub_3018(int a1, int a2, int a3, int a4);
int __fastcall sub_3080(int a1, int a2, int a3, int a4);
__int64 __fastcall sub_3290(int a1, int a2, int a3, int a4, __int64 a5);
_DWORD *__fastcall sub_337C(_DWORD *result, unsigned int a2);
_DWORD *__fastcall sub_33D4(_BYTE *a1, char *a2, unsigned int a3);
int __fastcall sub_3488(unsigned int a1, unsigned int a2);
int __fastcall sub_355C(unsigned int a1, unsigned int a2);
int sub_362C();
int sub_3640();
_DWORD *__fastcall sub_3650(_DWORD *result, char *a2, unsigned int a3, int a4);
int sub_36BC();
_UNKNOWN **sub_36D4();
void sub_37B8();
int __fastcall sub_37D0(int a1, int a2, int a3, const char *a4);
int __fastcall sub_3878(int a1, _DWORD *a2);
int sub_38E4();
int __fastcall sub_38FC(int a1, int a2, int a3, const char *a4);
int sub_3960();
int sub_3978();
int __fastcall sub_39C4(int a1, int a2, int a3, const char *a4);
int sub_3B24();
int __fastcall sub_3B34(char a1, int a2, int a3, int a4);
_DWORD *sub_3B4C();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_2BC; // weak
_UNKNOWN loc_2C0; // weak
_UNKNOWN loc_2D0; // weak
_UNKNOWN loc_2FC; // weak
_UNKNOWN *off_37CC = &unk_C0; // weak
_UNKNOWN unk_3AA8; // weak
_DWORD dword_3B60[12] = { 0, 0, 14, 13, 0, 0, 7, 11, 0, 0, 7, 4 }; // weak
unsigned __int16 word_4044[90] =
{
  0u,
  1143u,
  2287u,
  3429u,
  4571u,
  5711u,
  6850u,
  7986u,
  9120u,
  10252u,
  11380u,
  12504u,
  13625u,
  14742u,
  15854u,
  16961u,
  18064u,
  19160u,
  20251u,
  21336u,
  22414u,
  23486u,
  24550u,
  25606u,
  26655u,
  27696u,
  28729u,
  29752u,
  30767u,
  31772u,
  32767u,
  33753u,
  34728u,
  35693u,
  36647u,
  37589u,
  38521u,
  39440u,
  40347u,
  41243u,
  42125u,
  42995u,
  43852u,
  44695u,
  45525u,
  46340u,
  47142u,
  47929u,
  48702u,
  49460u,
  50203u,
  50931u,
  51643u,
  52339u,
  53019u,
  53683u,
  54331u,
  54963u,
  55577u,
  56175u,
  56755u,
  57319u,
  57864u,
  58393u,
  58903u,
  59395u,
  59870u,
  60326u,
  60763u,
  61183u,
  61583u,
  61965u,
  62328u,
  62672u,
  62997u,
  63302u,
  63589u,
  63856u,
  64103u,
  64331u,
  64540u,
  64729u,
  64898u,
  65047u,
  65176u,
  65286u,
  65376u,
  65446u,
  65496u,
  65526u
}; // weak
_UNKNOWN unk_4100; // weak
char aAbnormalTermin[21] = "Abnormal termination"; // weak


//----- (00000274) --------------------------------------------------------
void __fastcall sub_274(int a1, int a2)
{
  int v3; // r6
  int v4; // r5
  int v5; // r0

  v3 = *(_DWORD *)(a2 + 80);
  v4 = 0;
  if ( *(_DWORD *)(a2 + 160) == 2 )
  {
    do
    {
      sub_25E0(*(_DWORD **)(a2 + 108));
      ++v4;
    }
    while ( v4 < 15 );
    *(_DWORD *)(a2 + 156) = 0;
    *(_DWORD *)(a2 + 160) = 0;
  }
  else if ( *(int *)(a2 + 144) <= 25 )
  {
    sub_25E0(*(_DWORD **)(a2 + 108));
  }
  sub_2330(*(int **)(a2 + 108));
  if ( *(_DWORD *)(a2 + 140) != 0 )
  {
    sub_6DC((int *)a2, 0);
  }
  else
  {
    if ( *(_DWORD *)(a2 + 164) == 0 )
      (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(a2 + 72) + 200))(
        *(_DWORD *)(a2 + 72),
        0,
        0,
        *(_DWORD *)(a2 + 152));
    *(_DWORD *)(a2 + 164) = 0;
  }
  if ( *(_DWORD *)(a2 + 180) == 0 )
  {
    sub_2658(v3, 100, (int)sub_274, 0, a2, *(_DWORD *)(a2 + 184));
    *(_DWORD *)(a2 + 180) = v5;
  }
}
// 34C: variable 'v5' is possibly undefined

//----- (00000354) --------------------------------------------------------
int __fastcall sub_354(int a1)
{
  int v3; // [sp+4h] [bp-14h] BYREF
  _DWORD v4[4]; // [sp+8h] [bp-10h] BYREF

  memset(v4, 0, sizeof(v4));
  v3 = 0;
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 52))(*(_DWORD *)(a1 + 72));
  (*(void (__fastcall **)(_DWORD, int *, _DWORD *))(**(_DWORD **)(a1 + 72) + 192))(*(_DWORD *)(a1 + 72), &v3, v4);
  (*(void (__fastcall **)(_DWORD, int, _DWORD))(**(_DWORD **)(a1 + 72) + 196))(*(_DWORD *)(a1 + 72), 6, v4[0]);
  sub_6DC((int *)a1, 6);
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 56))(*(_DWORD *)(a1 + 72));
  return (*(int (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 72) + 20))(*(_DWORD *)(a1 + 72), 6);
}

//----- (000003F4) --------------------------------------------------------
int __fastcall sub_3F4(int a1, int a2, int a3, int a4)
{
  bool v8; // zf
  _DWORD v10[90]; // [sp+0h] [bp-168h] BYREF

  sub_337C(v10, 0x168u);
  if ( a2 != 8 )
  {
    if ( a2 > 8 )
    {
      if ( a2 != 13 )
      {
        if ( a2 > 13 )
        {
          v8 = a2 == 14;
          if ( a2 != 14 )
            v8 = a2 == 28672;
          if ( !v8 && a2 == 28674 )
            sub_26FC(*(_DWORD *)(a1 + 180), 28674);
        }
        else if ( a2 == 10 )
        {
          if ( *(_DWORD *)(a1 + 140) != 0 && sub_2040(*(_DWORD *)(a1 + 112), a3, a4) )
          {
            (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 80) + 36))(*(_DWORD *)(a1 + 80), 0);
          }
          else
          {
            *(_DWORD *)(a1 + 156) = 1;
            *(_DWORD *)(a1 + 160) = 0;
          }
        }
      }
    }
    else
    {
      switch ( a2 )
      {
        case 0:
          sub_AA8((_DWORD *)a1, a3, a4);
          break;
        case 1:
          sub_604(a1);
          break;
        case 2:
          (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 24))(*(_DWORD *)(a1 + 72));
          sub_2754(*(int **)(a1 + 180));
          *(_DWORD *)(a1 + 180) = 0;
          break;
        case 3:
          (*(void (__fastcall **)(_DWORD, _DWORD *))(**(_DWORD **)(a1 + 80) + 16))(*(_DWORD *)(a1 + 80), v10);
          if ( v10[2] == *(_DWORD *)(a1 + 152) )
          {
            sub_99C(a1);
            sub_1F68(*(_DWORD *)(a1 + 112), *(_DWORD *)(a1 + 72));
          }
          else
          {
            sub_FD8(a1);
          }
          sub_274(-1, a1);
          break;
        case 4:
          if ( a3 == 1 )
          {
            sub_FD8(a1);
          }
          else if ( *(_DWORD *)(a1 + 140) == 0 )
          {
            sub_354(a1);
          }
          break;
        case 5:
          if ( *(_DWORD *)(a1 + 140) != 0 && sub_2020(*(_DWORD **)(a1 + 112), a3) )
            (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 80) + 36))(*(_DWORD *)(a1 + 80), 0);
          break;
        default:
          return 1;
      }
    }
  }
  return 1;
}

//----- (000005D4) --------------------------------------------------------
int (__fastcall *__fastcall sub_5D4(_DWORD *a1, int (**a2)()))(int a1, int a2, int a3, int a4)
{
  *a1 = 232;
  *a2 = sub_6BC;
  a2[1] = sub_6C4;
  a2[2] = (int (*)())sub_3F4;
  return sub_3F4;
}

//----- (00000604) --------------------------------------------------------
void __fastcall sub_604(int a1)
{
  int v2; // r0
  int v3; // r0
  int v4; // r1
  void (__fastcall *v5)(_DWORD *, _DWORD); // r2

  v2 = *(_DWORD *)(a1 + 72);
  if ( v2 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v2 + 24))(v2);
    (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 72) + 4))(*(_DWORD *)(a1 + 72));
  }
  v3 = *(_DWORD *)(a1 + 76);
  if ( v3 != 0 )
    (*(void (__fastcall **)(int))(*(_DWORD *)v3 + 4))(v3);
  sub_1F40(*(_DWORD *)(a1 + 112));
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 88) + 4))(*(_DWORD *)(a1 + 88));
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 92) + 4))(*(_DWORD *)(a1 + 92));
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 104) + 4))(*(_DWORD *)(a1 + 104));
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 100) + 4))(*(_DWORD *)(a1 + 100));
  (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 96) + 4))(*(_DWORD *)(a1 + 96));
  sub_2754(*(int **)(a1 + 180));
  *(_DWORD *)(a1 + 180) = 0;
  sub_2128(*(_DWORD **)(a1 + 108), v4, v5);
}
// 6B8: variable 'v4' is possibly undefined
// 6B8: variable 'v5' is possibly undefined

//----- (000006BC) --------------------------------------------------------
int sub_6BC()
{
  return 0;
}

//----- (000006C4) --------------------------------------------------------
int sub_6C4()
{
  return 0;
}

//----- (000006DC) --------------------------------------------------------
int __fastcall sub_6DC(int *a1, int a2)
{
  int v4; // r7
  int v5; // r6
  int result; // r0
  int v7; // [sp+4h] [bp-20h] BYREF
  int v8; // [sp+8h] [bp-1Ch]
  int v9; // [sp+Ch] [bp-18h]
  int v10; // [sp+10h] [bp-14h]
  _DWORD v11[2]; // [sp+14h] [bp-10h] BYREF
  int v12; // [sp+1Ch] [bp-8h]
  int v13; // [sp+20h] [bp-4h]

  v11[0] = 0;
  v11[1] = 0;
  v12 = 0;
  v13 = 0;
  v7 = 0;
  v8 = 0;
  v9 = 0;
  v10 = 0;
  v4 = 0;
  v5 = 0;
  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1[18] + 32))(a1[18], 2);
  if ( a1[39] != 0 )
  {
    v5 = -2;
    ++a1[40];
    v4 = -2;
  }
  (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)a1[18] + 36))(a1[18], 2, v5, v4);
  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1[18] + 32))(a1[18], a2);
  (*(void (__fastcall **)(int, _DWORD, _DWORD, int, int))(*(_DWORD *)a1[18] + 92))(a1[18], 0, 0, a1[38], a1[37]);
  v9 = 2;
  v8 = 1;
  v7 = a2;
  (*(void (__fastcall **)(int, int, int *, int))(*(_DWORD *)a1[18] + 176))(a1[18], 3, &v7, 1);
  sub_23D4(a1[27]);
  if ( a1[35] != 0 )
    sub_1FB0(a1[28], a1[18], a2);
  v12 = a1[38];
  v13 = a1[37];
  v7 = a2;
  v8 = 2;
  result = a1[35];
  if ( result != 0 )
    return (*(int (__fastcall **)(int, _DWORD *, int, int *))(*(_DWORD *)a1[18] + 44))(a1[18], v11, 1, &v7);
  return result;
}

//----- (00000834) --------------------------------------------------------
int __fastcall sub_834(int a1, int a2, int a3)
{
  _DWORD v7[2]; // [sp+8h] [bp-30h] BYREF
  int v8; // [sp+10h] [bp-28h]
  int v9; // [sp+14h] [bp-24h]
  int v10; // [sp+18h] [bp-20h] BYREF
  int v11; // [sp+1Ch] [bp-1Ch]
  int v12; // [sp+34h] [bp-4h]

  sub_337C(&v10, 0x20u);
  v7[0] = 0;
  v7[1] = 0;
  v8 = 0;
  v9 = 0;
  (*(void (__fastcall **)(int, int *))(*(_DWORD *)a2 + 16))(a2, &v10);
  v9 = v11;
  v8 = v10;
  return (*(int (__fastcall **)(_DWORD, int, _DWORD *, int, int, int))(**(_DWORD **)(a1 + 72) + 16))(
           *(_DWORD *)(a1 + 72),
           a3,
           v7,
           3,
           v12,
           4 * v10 * v11);
}

//----- (000008E0) --------------------------------------------------------
int __fastcall sub_8E0(const char *a1, int a2, int a3)
{
  int result; // r0
  _DWORD v7[64]; // [sp+8h] [bp-100h] BYREF

  sub_337C(v7, 0x100u);
  sub_2BAC((int)v7, "%s%s", (const char *)(a3 + 200), a1);
  result = (*(int (__fastcall **)(_DWORD, _DWORD *, void (*)(), void (*)(), int))(**(_DWORD **)(a3 + 72) + 164))(
             *(_DWORD *)(a3 + 72),
             v7,
             sub_2830,
             sub_2844,
             a2);
  if ( result != 0 )
  {
    sub_1100(*(_DWORD *)(a3 + 76), "Load bmp error, file path = %s, error flag = %d\n", (int)v7, result);
    return -1;
  }
  return result;
}

//----- (0000099C) --------------------------------------------------------
_DWORD *__fastcall sub_99C(int a1)
{
  _DWORD *result; // r0
  _DWORD v3[8]; // [sp+8h] [bp-30h] BYREF
  _DWORD v4[2]; // [sp+28h] [bp-10h] BYREF
  int v5; // [sp+30h] [bp-8h]
  int v6; // [sp+34h] [bp-4h]

  v4[0] = 0;
  v4[1] = 0;
  v5 = 0;
  v6 = 0;
  result = sub_337C(v3, 0x20u);
  if ( a1 != 0 )
  {
    v5 = *(_DWORD *)(a1 + 152);
    v6 = *(_DWORD *)(a1 + 148);
    (*(void (__fastcall **)(_DWORD, _DWORD *))(**(_DWORD **)(a1 + 88) + 16))(*(_DWORD *)(a1 + 88), v3);
    (*(void (__fastcall **)(_DWORD, int, _DWORD *, int, _DWORD, int))(**(_DWORD **)(a1 + 72) + 16))(
      *(_DWORD *)(a1 + 72),
      1,
      v4,
      1,
      v3[7],
      2 * v3[0] * v3[1]);
    sub_834(a1, *(_DWORD *)(a1 + 92), 2);
    sub_834(a1, *(_DWORD *)(a1 + 104), 3);
    return (_DWORD *)sub_834(a1, *(_DWORD *)(a1 + 100), 4);
  }
  return result;
}

//----- (00000A60) --------------------------------------------------------
BOOL __fastcall sub_A60(int a1, unsigned __int8 *a2)
{
  int v2; // r0

  return a1 != 0
      || a2 == nullptr
      || (v2 = *a2) == 1 && *((_DWORD *)a2 + 64) != 0
      || v2 != 2
      || *((_DWORD *)a2 + 64) == 0;
}

//----- (00000AA8) --------------------------------------------------------
int __fastcall sub_AA8(_DWORD *a1, int a2, int a3)
{
  int v6; // r0
  int result; // r0
  bool v8; // zf
  int v9; // r3
  int v10; // r0
  int v11; // r1
  _BYTE v12[8]; // [sp+Ch] [bp-168h] BYREF
  int v13; // [sp+14h] [bp-160h]
  int v14; // [sp+18h] [bp-15Ch]

  a1[46] = 0;
  sub_2808();
  a1[20] = v6;
  if ( v6 == 0 )
    return -1;
  (*(void (__fastcall **)(int))(*(_DWORD *)v6 + 72))(v6);
  sub_2AD0();
  result = (*(int (__fastcall **)(_DWORD, int, _DWORD *))(*(_DWORD *)a1[20] + 8))(a1[20], 16777221, a1 + 18);
  if ( result == 0 )
  {
    result = (*(int (__fastcall **)(_DWORD, int, _DWORD *))(*(_DWORD *)a1[20] + 8))(a1[20], 16777219, a1 + 19);
    if ( result == 0 )
    {
      result = (*(int (__fastcall **)(_DWORD, int, _DWORD *))(*(_DWORD *)a1[20] + 8))(a1[20], 16777227, a1 + 21);
      if ( result == 0 )
      {
        sub_2B70();
        sub_2CF4();
        sub_2B5C();
        v8 = a2 == 0;
        if ( a2 == 0 )
          v8 = *(_DWORD *)(a3 + 256) == 0;
        a1[35] = v8;
        a1[46] = sub_A60(a2, (unsigned __int8 *)a3);
        a1[41] = v9;
        (*(void (__fastcall **)(_DWORD, _BYTE *))(*(_DWORD *)a1[20] + 16))(a1[20], v12);
        v10 = v13;
        a1[38] = v13;
        v11 = v14;
        a1[37] = v14;
        a1[33] = sub_EF4(v10, v11);
        sub_F04((int)a1);
        sub_8E0("res\\sakura_petal_l.zbmp", (int)(a1 + 26), (int)a1);
        sub_8E0("res\\sakura_petal_m.zbmp", (int)(a1 + 25), (int)a1);
        sub_8E0("res\\sakura_petal_s.zbmp", (int)(a1 + 24), (int)a1);
        sub_99C((int)a1);
        a1[28] = sub_1DCC(a1[18], a1[38] - 40, a1[37] - 40, 5, 11, 0);
        sub_CC4(a1);
        a1[34] = 25;
        a1[36] = 0;
        a1[39] = 0;
        a1[45] = 0;
        sub_274(-1, (int)a1);
        return 0;
      }
    }
  }
  return result;
}
// AC8: variable 'v6' is possibly undefined
// BA0: variable 'v9' is possibly undefined

//----- (00000CC4) --------------------------------------------------------
_DWORD *__fastcall sub_CC4(_DWORD *a1)
{
  int v2; // r1
  int v3; // r1
  _DWORD *result; // r0
  _DWORD v5[32]; // [sp+0h] [bp-80h] BYREF

  sub_337C(v5, 0x80u);
  v5[5] = 37;
  v5[4] = 0;
  v2 = a1[31];
  v5[8] = 0;
  v5[6] = v2;
  v5[7] = 55;
  v5[9] = 37;
  v5[10] = a1[38];
  v3 = a1[37];
  v5[16] = 0;
  v5[17] = 0;
  v5[14] = 30;
  v5[11] = v3;
  v5[15] = 150;
  v5[18] = 300;
  v5[12] = 6;
  v5[19] = 400;
  v5[13] = 8;
  v5[21] = 1;
  v5[20] = 1;
  v5[0] = sub_D9C;
  v5[2] = sub_DF4;
  v5[3] = sub_DE4;
  v5[23] = a1;
  result = sub_2090((int)v5, 60, 40);
  a1[27] = result;
  return result;
}

//----- (00000D9C) --------------------------------------------------------
int __fastcall sub_D9C(int a1, int a2)
{
  unsigned int v4; // r0
  int v5; // r1
  unsigned int v6; // r0
  int v7; // r1

  sub_2AE4();
  sub_3488(3u, v4);
  *(_DWORD *)(a1 + 28) = v5;
  sub_2AE4();
  sub_3488(6u, v6);
  *(_DWORD *)(a1 + 32) = v7;
  ++*(_DWORD *)(a2 + 144);
  return 0;
}
// DB4: variable 'v4' is possibly undefined
// DB8: variable 'v5' is possibly undefined
// DC8: variable 'v6' is possibly undefined
// DCC: variable 'v7' is possibly undefined

//----- (00000DE4) --------------------------------------------------------
int __fastcall sub_DE4(int a1, int a2)
{
  int result; // r0

  result = *(_DWORD *)(a2 + 144) - 1;
  *(_DWORD *)(a2 + 144) = result;
  return result;
}

//----- (00000DF4) --------------------------------------------------------
int __fastcall sub_DF4(int *a1, int a2)
{
  int v4; // lr
  int v5; // r5
  int v6; // r2
  int v7; // r3
  int v8; // r12
  int v9; // r0
  _DWORD v11[4]; // [sp+10h] [bp-20h] BYREF
  int v12; // [sp+20h] [bp-10h]
  int v13; // [sp+24h] [bp-Ch]
  int v14; // [sp+28h] [bp-8h]
  int v15; // [sp+2Ch] [bp-4h]

  v12 = 0;
  v13 = 0;
  v14 = 0;
  v15 = 0;
  memset(v11, 0, sizeof(v11));
  v12 = *a1 >> 16;
  v13 = a1[1] >> 16;
  v4 = 0;
  v5 = 0;
  v6 = dword_3B60[4 * a1[7] + 1];
  v7 = dword_3B60[4 * a1[7] + 2];
  v8 = dword_3B60[4 * a1[7] + 3];
  v11[0] = dword_3B60[4 * a1[7]];
  v11[1] = v6;
  v11[2] = v7;
  v11[3] = v8;
  v9 = a1[7];
  if ( v9 != 0 )
  {
    if ( v9 == 1 )
    {
      v5 = *(_DWORD *)(a2 + 100);
    }
    else if ( v9 == 2 )
    {
      v5 = *(_DWORD *)(a2 + 96);
    }
  }
  else
  {
    v5 = *(_DWORD *)(a2 + 104);
  }
  if ( *(_DWORD *)(a2 + 140) == 0 )
    v4 = 6;
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a2 + 72) + 32))(*(_DWORD *)(a2 + 72), v4);
  (*(void (__fastcall **)(_DWORD, int, int, int, _DWORD *, int, int))(**(_DWORD **)(a2 + 72) + 152))(
    *(_DWORD *)(a2 + 72),
    v12,
    v13,
    v5,
    v11,
    a1[8],
    1);
  return 0;
}
// 3B60: using guessed type _DWORD dword_3B60[12];

//----- (00000EF4) --------------------------------------------------------
BOOL __fastcall sub_EF4(int a1, int a2)
{
  return a1 > a2;
}

//----- (00000F04) --------------------------------------------------------
int __fastcall sub_F04(int a1)
{
  int v2; // r1
  int v3; // r2
  int v4; // r1
  const char *v5; // r0
  int result; // r0
  _DWORD v7[8]; // [sp+4h] [bp-20h] BYREF

  sub_337C(v7, 0x20u);
  v2 = a1 + 88;
  if ( *(_DWORD *)(a1 + 132) != 0 )
  {
    sub_8E0("res\\heng_bg.zbmp", v2, a1);
    v3 = a1;
    v4 = a1 + 92;
    v5 = "res\\heng_sakura.zbmp";
  }
  else
  {
    sub_8E0("res\\bg.zbmp", v2, a1);
    v3 = a1;
    v4 = a1 + 92;
    v5 = "res\\sukura.zbmp";
  }
  sub_8E0(v5, v4, v3);
  (*(void (__fastcall **)(_DWORD, _DWORD *))(**(_DWORD **)(a1 + 92) + 16))(*(_DWORD *)(a1 + 92), v7);
  *(_DWORD *)(a1 + 128) = v7[1];
  result = v7[0];
  *(_DWORD *)(a1 + 124) = v7[0];
  return result;
}

//----- (00000FD8) --------------------------------------------------------
int __fastcall sub_FD8(int result)
{
  int v1; // r4
  int v2; // r0
  int v3; // r1
  _DWORD v4[2]; // [sp+0h] [bp-168h] BYREF
  int v5; // [sp+8h] [bp-160h]
  int v6; // [sp+Ch] [bp-15Ch]

  v1 = result;
  if ( result != 0 )
  {
    (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(result + 88) + 4))(*(_DWORD *)(result + 88));
    (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 92) + 4))(*(_DWORD *)(v1 + 92));
    sub_1F40(*(_DWORD *)(v1 + 112));
    (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(v1 + 72) + 24))(*(_DWORD *)(v1 + 72));
    sub_337C(v4, 0x168u);
    (*(void (__fastcall **)(_DWORD, _DWORD *))(**(_DWORD **)(v1 + 80) + 16))(*(_DWORD *)(v1 + 80), v4);
    v2 = v5;
    *(_DWORD *)(v1 + 152) = v5;
    v3 = v6;
    *(_DWORD *)(v1 + 148) = v6;
    *(_DWORD *)(v1 + 132) = sub_EF4(v2, v3);
    *(_DWORD *)(*(_DWORD *)(v1 + 108) + 40) = *(_DWORD *)(v1 + 152);
    *(_DWORD *)(*(_DWORD *)(v1 + 108) + 44) = *(_DWORD *)(v1 + 148);
    sub_F04(v1);
    sub_99C(v1);
    *(_DWORD *)(v1 + 112) = sub_1DCC(
                              *(_DWORD *)(v1 + 72),
                              *(_DWORD *)(v1 + 152) - 40,
                              *(_DWORD *)(v1 + 148) - 40,
                              5,
                              11,
                              0);
    *(_DWORD *)(*(_DWORD *)(v1 + 108) + 24) = *(_DWORD *)(v1 + 124);
    *(_DWORD *)(*(_DWORD *)(v1 + 108) + 100) = *(_DWORD *)(*(_DWORD *)(v1 + 108) + 32) << 16;
    *(_DWORD *)(*(_DWORD *)(v1 + 108) + 104) = *(_DWORD *)(*(_DWORD *)(v1 + 108) + 36) << 16;
    *(_DWORD *)(*(_DWORD *)(v1 + 108) + 108) = *(_DWORD *)(*(_DWORD *)(v1 + 108) + 40) << 16;
    result = *(_DWORD *)(v1 + 108);
    *(_DWORD *)(result + 112) = *(_DWORD *)(result + 44) << 16;
  }
  return result;
}

//----- (00001100) --------------------------------------------------------
int __fastcall sub_1100(int a1, _BYTE *a2, int a3, int a4)
{
  int v4; // r5
  int v5; // r0
  int v6; // r4
  int v7; // r0
  int result; // r0
  int v9; // r4
  int v10; // r0
  int *v11; // [sp+0h] [bp-21Ch] BYREF
  _BYTE v12[6]; // [sp+4h] [bp-218h] BYREF
  _BYTE v13[506]; // [sp+Ah] [bp-212h] BYREF
  _BYTE var18[32]; // [sp+204h] [bp-18h] BYREF
  int varg_r0; // [sp+228h] [bp+Ch] BYREF
  _BYTE *varg_r1; // [sp+22Ch] [bp+10h]
  _DWORD varg_r2[2]; // [sp+230h] [bp+14h] BYREF

  varg_r0 = a1;
  varg_r1 = a2;
  varg_r2[0] = a3;
  varg_r2[1] = a4;
  sub_33D4(var18, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  v4 = 0;
  if ( varg_r0 == 0 )
  {
    sub_2808();
    v6 = v5;
    sub_2808();
    result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v7 + 8))(v6, 16777219, &varg_r0);
    if ( result != 0 )
      return result;
    v4 = 1;
  }
  var18[0] = (*(int (__fastcall **)(int, int))(*(_DWORD *)varg_r0 + 48))(varg_r0, 1);
  if ( var18[0] == 0 )
    var18[0] = (*(int (__fastcall **)(int, _DWORD))(*(_DWORD *)varg_r0 + 48))(varg_r0, 0);
  result = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)varg_r0 + 8))(varg_r0, var18, 12);
  v9 = result;
  if ( result != 0 )
  {
    sub_33D4(v12, "Trace:", 0x200u);
    v11 = varg_r2;
    sub_2C08((int)v13, varg_r1, &v11);
    v11 = nullptr;
    sub_2CF4();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v9 + 12))(v9, v12, v10);
    result = (*(int (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
  }
  if ( v4 != 0 )
    return (*(int (__fastcall **)(int))(*(_DWORD *)varg_r0 + 4))(varg_r0);
  return result;
}
// 1134: variable 'v5' is possibly undefined
// 113C: variable 'v7' is possibly undefined
// 1208: variable 'v10' is possibly undefined

//----- (00001400) --------------------------------------------------------
int __fastcall sub_1400(int a1, _BYTE *a2, int a3, int a4)
{
  int v4; // r5
  int v5; // r0
  int v6; // r4
  int v7; // r0
  int result; // r0
  int v9; // r4
  int v10; // r0
  int v11; // r6
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int *v16; // [sp+4h] [bp-21Ch] BYREF
  _BYTE v17[512]; // [sp+8h] [bp-218h] BYREF
  _BYTE var18[36]; // [sp+208h] [bp-18h] BYREF
  int varg_r0; // [sp+230h] [bp+10h] BYREF
  _BYTE *varg_r1; // [sp+234h] [bp+14h]
  _DWORD varg_r2[2]; // [sp+238h] [bp+18h] BYREF

  varg_r0 = a1;
  varg_r1 = a2;
  varg_r2[0] = a3;
  varg_r2[1] = a4;
  sub_33D4(var18, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  v4 = 0;
  if ( varg_r0 == 0 )
  {
    sub_2808();
    v6 = v5;
    sub_2808();
    result = (*(int (__fastcall **)(int, int, int *))(*(_DWORD *)v7 + 8))(v6, 16777219, &varg_r0);
    if ( result != 0 )
      return result;
    v4 = 1;
  }
  var18[0] = (*(int (__fastcall **)(int, int))(*(_DWORD *)varg_r0 + 48))(varg_r0, 1);
  if ( var18[0] == 0 )
    var18[0] = (*(int (__fastcall **)(int, _DWORD))(*(_DWORD *)varg_r0 + 48))(varg_r0, 0);
  result = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)varg_r0 + 8))(varg_r0, var18, 12);
  v9 = result;
  if ( result != 0 )
  {
    sub_33D4(v17, "Trace:", 0x200u);
    v16 = varg_r2;
    sub_2808();
    v11 = v10;
    sub_2808();
    v13 = (*(int (__fastcall **)(int))(*(_DWORD *)v12 + 72))(v11);
    sub_2BAC((int)v17, "Trace: tick=%10d ", v13);
    sub_2CF4();
    sub_2C08((int)&v17[v14], varg_r1, &v16);
    v16 = nullptr;
    sub_2C7C();
    sub_2CF4();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v9 + 12))(v9, v17, v15);
    result = (*(int (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
  }
  if ( v4 != 0 )
    return (*(int (__fastcall **)(int))(*(_DWORD *)varg_r0 + 4))(varg_r0);
  return result;
}
// 1434: variable 'v5' is possibly undefined
// 143C: variable 'v7' is possibly undefined
// 14D8: variable 'v10' is possibly undefined
// 14E0: variable 'v12' is possibly undefined
// 150C: variable 'v14' is possibly undefined
// 154C: variable 'v15' is possibly undefined

//----- (0000159C) --------------------------------------------------------
int sub_159C(int a1, ...)
{
  int v1; // r0
  int v2; // r4
  unsigned int v3; // r5
  int v4; // r4
  unsigned int v5; // r0
  int v6; // r1
  int v7; // r7
  unsigned int v8; // r1
  unsigned int v9; // r6
  int v10; // r1
  int v11; // r8
  int v12; // r6
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int *v17; // [sp+8h] [bp-220h] BYREF
  _BYTE v18[512]; // [sp+Ch] [bp-21Ch] BYREF
  _BYTE v19[24]; // [sp+20Ch] [bp-1Ch] BYREF
  _BYTE *var4[8]; // [sp+224h] [bp-4h] BYREF
  va_list varg_r1; // [sp+244h] [bp+1Ch] BYREF

  va_start(varg_r1, a1);
  sub_33D4(v19, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  sub_2808();
  v2 = v1;
  v3 = (*(int (__fastcall **)(int))(*(_DWORD *)v1 + 72))(v1);
  (*(void (__fastcall **)(int, int, _BYTE **))(*(_DWORD *)v2 + 8))(v2, 16777219, var4);
  v19[0] = (*(int (__fastcall **)(_BYTE *, int))(*(_DWORD *)var4[0] + 48))(var4[0], 1);
  if ( v19[0] == 0 )
    v19[0] = (*(int (__fastcall **)(_BYTE *, _DWORD))(*(_DWORD *)var4[0] + 48))(var4[0], 0);
  v4 = (*(int (__fastcall **)(_BYTE *, _BYTE *, int))(*(_DWORD *)var4[0] + 8))(var4[0], v19, 12);
  if ( v4 != 0 )
  {
    v5 = sub_355C(0x3E8u, v3);
    v7 = v6;
    sub_355C(0xE10u, v5);
    v9 = v8;
    sub_355C(0x3Cu, v8);
    v11 = v10;
    v12 = sub_355C(0x3Cu, v9);
    v13 = sub_355C(0x36EE80u, v3);
    sub_2BAC((int)v18, "%02d:%02d:%02d:%03d--", v13, v12, v11, v7);
    va_copy((va_list)v17, varg_r1);
    sub_2CF4();
    sub_2C08((int)&v18[v14], var4[7], &v17);
    v17 = nullptr;
    sub_2CF4();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v4 + 12))(v4, v18, v15);
    (*(void (__fastcall **)(int))(*(_DWORD *)v4 + 4))(v4);
  }
  return (*(int (__fastcall **)(_BYTE *))(*(_DWORD *)var4[0] + 4))(var4[0]);
}
// 15C0: variable 'v1' is possibly undefined
// 1654: variable 'v6' is possibly undefined
// 1664: variable 'v8' is possibly undefined
// 1670: variable 'v10' is possibly undefined
// 16C0: variable 'v14' is possibly undefined
// 16F4: variable 'v15' is possibly undefined

//----- (00001744) --------------------------------------------------------
int __fastcall sub_1744(int a1, int a2)
{
  int v4; // r0
  int v5; // r4
  int v6; // r0
  int v7; // r4
  int v8; // r0
  bool v9; // zf
  int v10; // r0
  int v11; // r0
  _BYTE v13[32]; // [sp+4h] [bp-3Ch] BYREF
  _BYTE v14[24]; // [sp+24h] [bp-1Ch] BYREF
  int v15; // [sp+3Ch] [bp-4h] BYREF

  sub_33D4(v14, "E:\\zmaee\\LTS_DEBUG.txt", 0x17u);
  sub_2808();
  v5 = v4;
  sub_2808();
  (*(void (__fastcall **)(int, int, int *))(*(_DWORD *)v6 + 8))(v5, 16777219, &v15);
  v14[0] = (*(int (__fastcall **)(int, int))(*(_DWORD *)v15 + 48))(v15, 1);
  if ( v14[0] == 0 )
    v14[0] = (*(int (__fastcall **)(int, _DWORD))(*(_DWORD *)v15 + 48))(v15, 0);
  v7 = (*(int (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v15 + 8))(v15, v14, 12);
  if ( v7 != 0 )
  {
    sub_33D4(v13, "TraceDump:", 0x20u);
    sub_2CF4();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v7 + 12))(v7, v13, v8);
    v9 = a1 == 0;
    if ( a1 != 0 )
      v9 = a2 == 0;
    if ( v9 )
    {
      sub_2CCC();
      sub_2CF4();
      (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v7 + 12))(v7, v13, v10);
    }
    else
    {
      (*(void (__fastcall **)(int, int, int))(*(_DWORD *)v7 + 12))(v7, a1, a2);
    }
    sub_2CCC();
    sub_2CF4();
    (*(void (__fastcall **)(int, _BYTE *, int))(*(_DWORD *)v7 + 12))(v7, v13, v11);
    (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 4))(v7);
  }
  return (*(int (__fastcall **)(int))(*(_DWORD *)v15 + 4))(v15);
}
// 176C: variable 'v4' is possibly undefined
// 1774: variable 'v6' is possibly undefined
// 1814: variable 'v8' is possibly undefined
// 186C: variable 'v10' is possibly undefined
// 1898: variable 'v11' is possibly undefined

//----- (000018D4) --------------------------------------------------------
int sub_18D4()
{
  int v0; // r0
  int v1; // r4

  sub_2830();
  v1 = v0;
  sub_2B70();
  return v1;
}
// 18E0: variable 'v0' is possibly undefined

//----- (000018F8) --------------------------------------------------------
void __fastcall sub_18F8(int a1, void (__fastcall *a2)(_DWORD))
{
  int i; // r4
  int v4; // r6

  if ( a1 != 0 )
  {
    for ( i = *(_DWORD *)(a1 + 4); i != 0; i = v4 )
    {
      v4 = *(_DWORD *)(i + 4);
      if ( a2 != nullptr )
        a2(*(_DWORD *)(i + 8));
      sub_2844();
    }
    sub_2844();
  }
}

//----- (00001940) --------------------------------------------------------
void __fastcall sub_1940(int a1, void (__fastcall *a2)(_DWORD, int), int a3)
{
  int i; // r4
  int v6; // r6

  if ( a1 != 0 )
  {
    for ( i = *(_DWORD *)(a1 + 4); i != 0; i = v6 )
    {
      v6 = *(_DWORD *)(i + 4);
      if ( a2 != nullptr )
        a2(*(_DWORD *)(i + 8), a3);
      sub_2844();
    }
    sub_2844();
  }
}

//----- (00001990) --------------------------------------------------------
int __fastcall sub_1990(int *a1, int a2)
{
  _DWORD *v4; // r0
  int result; // r0

  sub_2830();
  v4[2] = a2;
  if ( a1[1] != 0 )
  {
    *v4 = 0;
    v4[1] = a1[1];
    *(_DWORD *)a1[1] = v4;
    a1[1] = (int)v4;
  }
  else
  {
    a1[1] = (int)v4;
    a1[2] = (int)v4;
    v4[1] = 0;
    *v4 = 0;
  }
  result = *a1 + 1;
  *a1 = result;
  return result;
}
// 19A4: variable 'v4' is possibly undefined

//----- (000019EC) --------------------------------------------------------
int __fastcall sub_19EC(int *a1, int a2)
{
  int *v4; // r0
  int v5; // r1
  int result; // r0

  sub_2830();
  v4[2] = a2;
  v5 = a1[2];
  if ( v5 != 0 )
  {
    *v4 = v5;
    v4[1] = 0;
    *(_DWORD *)(a1[2] + 4) = v4;
    a1[2] = (int)v4;
  }
  else
  {
    a1[1] = (int)v4;
    a1[2] = (int)v4;
    v4[1] = 0;
    *v4 = 0;
  }
  result = *a1 + 1;
  *a1 = result;
  return result;
}
// 1A00: variable 'v4' is possibly undefined

//----- (00001A40) --------------------------------------------------------
int __fastcall sub_1A40(int a1, int a2)
{
  int result; // r0

  result = a2;
  if ( a2 != 0 )
    return *(_DWORD *)(a2 + 4);
  return result;
}

//----- (00001A4C) --------------------------------------------------------
int *__fastcall sub_1A4C(int *result, int a2, int a3)
{
  int v4; // r2
  int *v5; // r5
  int v6; // r3
  bool v7; // cc
  int v8; // r4
  int v9; // r2
  _DWORD *v10; // r0

  v4 = 0;
  v5 = result;
  v6 = a2;
  if ( a2 >= 0 )
  {
    v7 = (int)result <= 0;
    if ( result != nullptr )
    {
      result = (int *)*result;
      v7 = *v5 <= a2;
    }
    if ( !v7 )
    {
      if ( a2 != 0 )
      {
        v8 = v5[1];
        while ( v8 != 0 && v4 != v6 )
        {
          v8 = sub_1A40((int)v5, v8);
          v4 = v9 + 1;
        }
        sub_2830();
        v10[2] = a3;
        *(_DWORD *)(*(_DWORD *)v8 + 4) = v10;
        v10[1] = v8;
        *v10 = *(_DWORD *)v8;
        *(_DWORD *)v8 = v10;
        result = (int *)(*v5 + 1);
        *v5 = (int)result;
      }
      else
      {
        return (int *)sub_1990(v5, a3);
      }
    }
  }
  return result;
}
// 1A98: variable 'v6' is possibly undefined
// 1AAC: variable 'v9' is possibly undefined
// 1AC0: variable 'v10' is possibly undefined

//----- (00001AEC) --------------------------------------------------------
int *__fastcall sub_1AEC(int **a1)
{
  int *result; // r0
  int v3; // r1

  result = a1[2];
  if ( result != nullptr )
  {
    v3 = *result;
    a1[2] = (int *)*result;
    if ( v3 != 0 )
      *(_DWORD *)(v3 + 4) = 0;
    else
      a1[1] = nullptr;
    sub_2844();
    result = (int *)((char *)*a1 - 1);
    *a1 = result;
  }
  return result;
}

//----- (00001B2C) --------------------------------------------------------
int __fastcall sub_1B2C(int *a1)
{
  int result; // r0
  _DWORD *v3; // r1

  result = a1[1];
  if ( result != 0 )
  {
    v3 = *(_DWORD **)(result + 4);
    a1[1] = (int)v3;
    if ( v3 != nullptr )
      *v3 = 0;
    else
      a1[2] = 0;
    sub_2844();
    result = *a1 - 1;
    *a1 = result;
  }
  return result;
}

//----- (00001B6C) --------------------------------------------------------
int __fastcall sub_1B6C(int a1)
{
  if ( a1 != 0 )
    return *(_DWORD *)(a1 + 4);
  else
    return 0;
}

//----- (00001BD0) --------------------------------------------------------
int __fastcall sub_1BD0(int *a1, int a2)
{
  int v3; // r3
  int v4; // r2
  bool v5; // cc
  int v6; // r0
  int v8; // r2

  v3 = (int)a1;
  v4 = 0;
  if ( a2 >= 0 )
  {
    v5 = (int)a1 <= 0;
    if ( a1 != nullptr )
      v5 = *a1 <= a2;
    if ( !v5 )
    {
      v6 = a1[1];
      while ( v6 != 0 )
      {
        if ( v4 == a2 )
          return *(_DWORD *)(v6 + 8);
        v6 = sub_1A40(v3, v6);
        v4 = v8 + 1;
      }
    }
  }
  return 0;
}
// 1C14: variable 'v3' is possibly undefined
// 1C18: variable 'v8' is possibly undefined

//----- (00001C2C) --------------------------------------------------------
int *__fastcall sub_1C2C(int *result, int a2)
{
  int v2; // r4
  int v3; // r3
  int v4; // r2
  bool v5; // cc
  int v6; // r2

  v2 = (int)result;
  v3 = a2;
  v4 = 0;
  if ( a2 >= 0 )
  {
    v5 = (int)result <= 0;
    if ( result != nullptr )
    {
      result = (int *)*result;
      v5 = *(_DWORD *)v2 <= a2;
    }
    if ( !v5 )
    {
      if ( a2 != 0 )
      {
        if ( (int *)((char *)result - 1) == (int *)a2 )
        {
          return sub_1AEC((int **)v2);
        }
        else
        {
          result = *(int **)(v2 + 4);
          while ( result != nullptr )
          {
            if ( v4 == v3 )
            {
              *(_DWORD *)(*result + 4) = result[1];
              *(_DWORD *)result[1] = *result;
              sub_2844();
              result = (int *)(*(_DWORD *)v2 - 1);
              *(_DWORD *)v2 = result;
              return result;
            }
            result = (int *)sub_1A40(v2, (int)result);
            v4 = v6 + 1;
          }
        }
      }
      else
      {
        return (int *)sub_1B2C((int *)v2);
      }
    }
  }
  return result;
}
// 1C84: variable 'v3' is possibly undefined
// 1CBC: variable 'v6' is possibly undefined

//----- (00001CCC) --------------------------------------------------------
int *__fastcall sub_1CCC(int *a1, _DWORD *a2)
{
  int *result; // r0
  _DWORD *v5; // r1

  if ( (_DWORD *)a1[1] == a2 )
    return (int *)sub_1B2C(a1);
  if ( (_DWORD *)a1[2] == a2 )
    return sub_1AEC((int **)a1);
  *(_DWORD *)(*a2 + 4) = a2[1];
  v5 = (_DWORD *)a2[1];
  if ( v5 != nullptr )
    *v5 = *a2;
  sub_2844();
  result = (int *)(*a1 - 1);
  *a1 = (int)result;
  return result;
}

//----- (00001D30) --------------------------------------------------------
int __fastcall sub_1D30(int a1)
{
  int v2; // r0

  while ( a1 >= 360 )
    a1 -= 360;
  while ( a1 < 0 )
    a1 += 360;
  if ( (unsigned int)a1 < 0x5A )
    return word_4044[a1];
  if ( a1 == 90 )
    return 0x10000;
  if ( (unsigned int)(a1 - 91) <= 0x59 )
  {
    a1 = 180 - a1;
    return word_4044[a1];
  }
  if ( (unsigned int)(a1 - 181) >= 0x59 )
  {
    if ( a1 == 270 )
      return -65536;
    v2 = word_4044[360 - a1];
  }
  else
  {
    v2 = word_4044[a1 - 180];
  }
  return -v2;
}
// 4044: using guessed type unsigned __int16 word_4044[90];

//----- (00001DBC) --------------------------------------------------------
int __fastcall sub_1DBC(int a1)
{
  return sub_1D30(90 - a1);
}

//----- (00001DCC) --------------------------------------------------------
_DWORD *__fastcall sub_1DCC(int a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD *v10; // r0
  _DWORD *v11; // r4
  int v12; // r0
  int v13; // r3
  int v15; // [sp+0h] [bp-20h] BYREF
  int v16; // [sp+4h] [bp-1Ch]

  sub_2830();
  v11 = v10;
  sub_2B70();
  v11[2] = a4;
  v11[4] = a2;
  v11[5] = a3;
  *v11 = a5;
  if ( a6 != 0 )
  {
    sub_337C(&v15, 0x20u);
    v11[1] = 0;
    (*(void (__fastcall **)(int, int *))(*(_DWORD *)a6 + 16))(a6, &v15);
    v11[6] = v15;
    v11[7] = v16;
    sub_2830();
    v11[3] = v12;
    sub_2B98();
  }
  else
  {
    v11[1] = 1;
    v11[3] = &unk_4100;
    v11[6] = 38;
    v11[7] = 36;
  }
  v13 = 4 * v11[7] * v11[6];
  v15 = v11[3];
  v16 = v13;
  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 16))(a1, a4);
  if ( a6 != 0 )
  {
    v11[5] = 0;
    v11[4] = 0;
    (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 32))(a1, a4);
    (*(void (__fastcall **)(int, _DWORD, _DWORD, int, _DWORD *, _DWORD))(*(_DWORD *)a1 + 148))(a1, 0, 0, a6, v11 + 4, 0);
    v11[4] = a2;
    v11[5] = a3;
  }
  return v11;
}
// 1DF4: variable 'v10' is possibly undefined
// 1E60: variable 'v12' is possibly undefined

//----- (00001F40) --------------------------------------------------------
void __fastcall sub_1F40(int a1)
{
  if ( a1 != 0 )
  {
    if ( *(_DWORD *)(a1 + 4) == 0 )
      sub_2844();
    sub_2844();
  }
}

//----- (00001F68) --------------------------------------------------------
int __fastcall sub_1F68(int result, int a2)
{
  if ( result != 0 )
    return (*(int (__fastcall **)(int, _DWORD, int, int))(*(_DWORD *)a2 + 16))(
             a2,
             *(_DWORD *)(result + 8),
             result + 16,
             3);
  return result;
}

//----- (00001FB0) --------------------------------------------------------
int __fastcall sub_1FB0(int result, int a2, int a3)
{
  int v4; // [sp+4h] [bp-10h] BYREF
  int v5; // [sp+8h] [bp-Ch]
  int v6; // [sp+Ch] [bp-8h]
  int v7; // [sp+10h] [bp-4h]

  if ( result != 0 )
  {
    v5 = 0;
    v6 = 0;
    v7 = 0;
    v4 = a3;
    v5 = *(_DWORD *)(result + 8);
    (*(void (__fastcall **)(int, int))(*(_DWORD *)a2 + 32))(a2, a3);
    return (*(int (__fastcall **)(int, int, int *, _DWORD))(*(_DWORD *)a2 + 176))(a2, 2, &v4, 0);
  }
  return result;
}

//----- (00002020) --------------------------------------------------------
BOOL __fastcall sub_2020(_DWORD *a1, int a2)
{
  return a1 != nullptr && *a1 == a2;
}

//----- (00002040) --------------------------------------------------------
BOOL __fastcall sub_2040(int a1, int a2, int a3)
{
  _DWORD *v3; // r0
  int v4; // r3
  int v5; // t1
  int v6; // r1
  BOOL result; // r0

  result = false;
  if ( a1 != 0 )
  {
    v5 = *(_DWORD *)(a1 + 16);
    v3 = (_DWORD *)(a1 + 16);
    v4 = v5;
    if ( v5 <= a2 && v4 + v3[2] > a2 )
    {
      v6 = v3[1];
      if ( v6 <= a3 && v6 + v3[3] > a3 )
        return true;
    }
  }
  return result;
}

//----- (00002090) --------------------------------------------------------
_DWORD *__fastcall sub_2090(int a1, int a2, int a3)
{
  _DWORD *v5; // r0
  _DWORD *v6; // r4
  int v7; // r0

  sub_2830();
  v6 = v5;
  sub_2B5C();
  v6[25] = v6[8] << 16;
  v6[26] = v6[9] << 16;
  v6[27] = v6[10] << 16;
  v6[28] = v6[11] << 16;
  v6[24] = a3;
  if ( a2 > 0 )
  {
    sub_2830();
    v6[29] = v7;
    sub_2B70();
    v6[30] = a2;
  }
  v6[31] = sub_18D4();
  return v6;
}
// 20A8: variable 'v5' is possibly undefined
// 210C: variable 'v7' is possibly undefined

//----- (00002128) --------------------------------------------------------
void __fastcall sub_2128(_DWORD *a1, int a2, void (__fastcall *a3)(_DWORD *, _DWORD))
{
  _DWORD *v4; // r5
  int i; // r6
  bool v6; // zf

  if ( a1 != nullptr )
  {
    v4 = (_DWORD *)a1[29];
    if ( v4 != nullptr )
    {
      for ( i = a1[30]; i > 0; --i )
      {
        v6 = *v4 == 0;
        if ( *v4 != 0 )
        {
          a3 = (void (__fastcall *)(_DWORD *, _DWORD))a1[3];
          v6 = a3 == nullptr;
        }
        if ( !v6 )
          a3(v4 + 1, a1[23]);
        v4 = (_DWORD *)((char *)v4 + a1[24] + 4);
      }
      sub_2844();
    }
    sub_1940(a1[31], sub_2628, (int)a1);
    sub_2844();
  }
}
// 2160: variable 'a3' is possibly undefined

//----- (000021A4) --------------------------------------------------------
int __fastcall sub_21A4(_DWORD *a1, _DWORD *a2)
{
  void (__fastcall *v2)(_DWORD *, _DWORD); // r2
  int v5; // r0
  int v6; // r3
  int v7; // r1
  int v8; // r2
  _DWORD *v9; // r0
  bool v10; // cc
  int v11; // r2
  bool v12; // cc
  void (__fastcall *v13)(_DWORD *, _DWORD); // r2
  int v15; // r0
  int v16; // r6
  unsigned int v17; // r0
  int v18; // r1
  int v19; // r0
  int v20; // r6
  unsigned int v21; // r0
  int v22; // r1
  int v23; // r0
  unsigned int v24; // r0
  unsigned int v25; // r1
  int v26; // r0
  int v27; // r4
  int v28; // r1

  v2 = (void (__fastcall *)(_DWORD *, _DWORD))a1[1];
  if ( v2 != nullptr )
    v2(a2, a1[23]);
  *a2 += a2[2] * sub_1DBC(a2[4]);
  v5 = sub_1D30(a2[4]);
  v6 = a2[2];
  v7 = a2[1] + v6 * v5;
  a2[1] = v7;
  v8 = a2[5] - a2[6];
  a2[5] = v8;
  a2[2] = v6 + a2[3];
  v9 = a1 + 25;
  if ( v8 <= 0 )
    goto LABEL_11;
  v10 = *a2 <= *v9;
  if ( *a2 >= *v9 )
    v10 = *v9 + a1[27] <= *a2;
  if ( v10 )
    goto LABEL_11;
  v11 = a1[26];
  v12 = v7 <= v11;
  if ( v7 >= v11 )
    v12 = v11 + a1[28] <= v7;
  if ( v12 )
  {
LABEL_11:
    v13 = (void (__fastcall *)(_DWORD *, _DWORD))a1[3];
    if ( v13 != nullptr )
      v13(a2, a1[23]);
    return 1;
  }
  else
  {
    if ( (a1[22] & 1) != 0 )
    {
      v15 = a1[12];
      if ( a1[13] != v15 )
      {
        sub_2AE4();
        v16 = a1[12];
        sub_3488(a1[13] - v16, v17);
        v15 = v18 + v16;
      }
      a2[2] = v15;
    }
    if ( (a1[22] & 2) != 0 )
    {
      v19 = a1[14];
      if ( a1[15] != v19 )
      {
        sub_2AE4();
        v20 = a1[14];
        sub_3488(a1[15] - v20, v21);
        v19 = v22 + v20;
      }
      a2[4] = v19;
    }
    if ( (a1[22] & 4) != 0 )
    {
      v23 = a1[16];
      if ( a1[17] != v23 )
      {
        sub_2AE4();
        v25 = v24;
        v26 = a1[17];
        v27 = a1[16];
        sub_3488(v26 - v27, v25);
        v23 = v28 + v27;
      }
      a2[3] = v23;
    }
    return 0;
  }
}
// 22A4: variable 'v17' is possibly undefined
// 22A8: variable 'v18' is possibly undefined
// 22E0: variable 'v21' is possibly undefined
// 22E4: variable 'v22' is possibly undefined
// 230C: variable 'v24' is possibly undefined
// 2320: variable 'v28' is possibly undefined

//----- (00002330) --------------------------------------------------------
int *__fastcall sub_2330(int *result)
{
  int *v1; // r4
  _DWORD *v2; // r5
  int i; // r6
  int *v4; // r5
  int *v5; // r6

  v1 = result;
  if ( result != nullptr )
  {
    v2 = (_DWORD *)result[29];
    for ( i = result[30]; i > 0; --i )
    {
      if ( *v2 != 0 && sub_21A4(v1, v2 + 1) != 0 )
        *v2 = 0;
      v2 = (_DWORD *)((char *)v2 + v1[24] + 4);
    }
    result = (int *)sub_1B6C(v1[31]);
    v4 = result;
    while ( v4 != nullptr )
    {
      result = (int *)sub_21A4(v1, (_DWORD *)v4[2]);
      if ( result != nullptr )
      {
        v5 = (int *)v4[1];
        sub_2844();
        result = sub_1CCC((int *)v1[31], v4);
        v4 = v5;
      }
      else
      {
        v4 = (int *)v4[1];
      }
    }
  }
  return result;
}

//----- (000023D4) --------------------------------------------------------
int __fastcall sub_23D4(int result)
{
  bool v1; // zf
  int v2; // r4
  _DWORD *v3; // r5
  int i; // r6
  int j; // r5

  v2 = result;
  v1 = result == 0;
  if ( result != 0 )
  {
    result = *(_DWORD *)(result + 8);
    v1 = result == 0;
  }
  if ( !v1 )
  {
    v3 = *(_DWORD **)(v2 + 116);
    for ( i = *(_DWORD *)(v2 + 120); i > 0; --i )
    {
      if ( *v3 != 0 )
        (*(void (__fastcall **)(_DWORD *, _DWORD))(v2 + 8))(v3 + 1, *(_DWORD *)(v2 + 92));
      v3 = (_DWORD *)((char *)v3 + *(_DWORD *)(v2 + 96) + 4);
    }
    result = sub_1B6C(*(_DWORD *)(v2 + 124));
    for ( j = result; j != 0; j = *(_DWORD *)(j + 4) )
    {
      result = *(_DWORD *)(j + 8);
      if ( result != 0 )
        result = (*(int (__fastcall **)(int, _DWORD))(v2 + 8))(result, *(_DWORD *)(v2 + 92));
    }
  }
  return result;
}

//----- (00002458) --------------------------------------------------------
int __fastcall sub_2458(int a1, _DWORD *a2)
{
  int v4; // r1
  unsigned int v5; // r0
  int v6; // r1
  unsigned int v7; // r0
  int v8; // r0
  int v9; // r6
  unsigned int v10; // r0
  int v11; // r1
  int v12; // r0
  int v13; // r6
  unsigned int v14; // r0
  int v15; // r1
  int v16; // r0
  int v17; // r6
  unsigned int v18; // r0
  int v19; // r1
  int v20; // r0
  int v21; // r6
  unsigned int v22; // r0
  int v23; // r1
  int v24; // r0
  int v25; // r6
  unsigned int v26; // r0
  int v27; // r1
  int result; // r0

  if ( *(_DWORD *)(a1 + 24) != 0 )
  {
    sub_2AE4();
    sub_3488(*(_DWORD *)(a1 + 24), v5);
  }
  else
  {
    v4 = 0;
  }
  *a2 = v4 + *(_DWORD *)(a1 + 16);
  if ( *(_DWORD *)(a1 + 28) != 0 )
  {
    sub_2AE4();
    sub_3488(*(_DWORD *)(a1 + 28), v7);
  }
  else
  {
    v6 = 0;
  }
  a2[1] = v6 + *(_DWORD *)(a1 + 20);
  v8 = *(_DWORD *)(a1 + 48);
  if ( *(_DWORD *)(a1 + 52) != v8 )
  {
    sub_2AE4();
    v9 = *(_DWORD *)(a1 + 48);
    sub_3488(*(_DWORD *)(a1 + 52) - v9, v10);
    v8 = v11 + v9;
  }
  a2[2] = v8;
  v12 = *(_DWORD *)(a1 + 64);
  if ( *(_DWORD *)(a1 + 68) != v12 )
  {
    sub_2AE4();
    v13 = *(_DWORD *)(a1 + 64);
    sub_3488(*(_DWORD *)(a1 + 68) - v13, v14);
    v12 = v15 + v13;
  }
  a2[3] = v12;
  v16 = *(_DWORD *)(a1 + 56);
  if ( *(_DWORD *)(a1 + 60) != v16 )
  {
    sub_2AE4();
    v17 = *(_DWORD *)(a1 + 56);
    sub_3488(*(_DWORD *)(a1 + 60) - v17, v18);
    v16 = v19 + v17;
  }
  a2[4] = v16;
  v20 = *(_DWORD *)(a1 + 72);
  if ( *(_DWORD *)(a1 + 76) != v20 )
  {
    sub_2AE4();
    v21 = *(_DWORD *)(a1 + 72);
    sub_3488(*(_DWORD *)(a1 + 76) - v21, v22);
    v20 = v23 + v21;
  }
  a2[5] = v20;
  v24 = *(_DWORD *)(a1 + 80);
  if ( *(_DWORD *)(a1 + 84) != v24 )
  {
    sub_2AE4();
    v25 = *(_DWORD *)(a1 + 80);
    sub_3488(*(_DWORD *)(a1 + 84) - v25, v26);
    v24 = v27 + v25;
  }
  a2[6] = v24;
  *a2 <<= 16;
  result = a2[1] << 16;
  a2[1] = result;
  if ( *(_DWORD *)a1 != 0 )
    return (*(int (__fastcall **)(_DWORD *, _DWORD))a1)(a2, *(_DWORD *)(a1 + 92));
  return result;
}
// 2480: variable 'v5' is possibly undefined
// 2488: variable 'v4' is possibly undefined
// 24AC: variable 'v7' is possibly undefined
// 24B4: variable 'v6' is possibly undefined
// 24E0: variable 'v10' is possibly undefined
// 24E4: variable 'v11' is possibly undefined
// 2510: variable 'v14' is possibly undefined
// 2514: variable 'v15' is possibly undefined
// 2540: variable 'v18' is possibly undefined
// 2544: variable 'v19' is possibly undefined
// 2570: variable 'v22' is possibly undefined
// 2574: variable 'v23' is possibly undefined
// 25A0: variable 'v26' is possibly undefined
// 25A4: variable 'v27' is possibly undefined

//----- (000025E0) --------------------------------------------------------
_DWORD *__fastcall sub_25E0(_DWORD *result)
{
  _DWORD *v1; // r1
  int i; // r2

  if ( result != nullptr )
  {
    v1 = (_DWORD *)result[29];
    for ( i = result[30]; i > 0; --i )
    {
      if ( *v1 == 0 )
      {
        *v1 = 1;
        return (_DWORD *)sub_2458((int)result, v1 + 1);
      }
      v1 = (_DWORD *)((char *)v1 + result[24] + 4);
    }
  }
  return result;
}

//----- (00002628) --------------------------------------------------------
void __fastcall sub_2628(int a1, int a2)
{
  if ( a1 != 0 )
  {
    (*(void (__fastcall **)(int, _DWORD))(a2 + 12))(a1, *(_DWORD *)(a2 + 92));
    sub_2844();
  }
}

//----- (00002658) --------------------------------------------------------
void __fastcall sub_2658(int a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD *v10; // r0
  _DWORD *v11; // r4

  sub_2830();
  v11 = v10;
  if ( v10 != nullptr )
  {
    sub_2B70();
    *v11 = a1;
    v11[1] = a5;
    v11[5] = a2;
    v11[7] = a3;
    v11[4] = a4;
    v11[6] = (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 72))(a1);
    v11[3] = -1;
    if ( a6 != 0 )
      v11[3] = (*(int (__fastcall **)(_DWORD, _DWORD, int (__fastcall *)(int, _DWORD *), _DWORD))(*(_DWORD *)*v11 + 60))(
                 *v11,
                 v11[5],
                 sub_27BC,
                 v11[4]);
  }
}
// 267C: variable 'v10' is possibly undefined

//----- (000026FC) --------------------------------------------------------
int __fastcall sub_26FC(int result, int a2)
{
  int v2; // r5
  int v3; // r4

  v2 = result;
  v3 = result;
  if ( a2 == 28674 )
  {
    result = (*(int (**)(void))(**(_DWORD **)result + 72))();
    if ( (unsigned int)(result - *(_DWORD *)(v3 + 24)) >= *(_DWORD *)(v3 + 20) )
    {
      *(_DWORD *)(v3 + 24) = result;
      return (*(int (__fastcall **)(int, _DWORD))(v3 + 28))(v2, *(_DWORD *)(v3 + 4));
    }
  }
  return result;
}

//----- (00002754) --------------------------------------------------------
void __fastcall sub_2754(int *a1)
{
  if ( a1 != nullptr )
  {
    if ( a1[3] >= 0 )
      (*(void (**)(void))(*(_DWORD *)*a1 + 64))();
    a1[3] = -1;
    sub_2844();
  }
}

//----- (000027BC) --------------------------------------------------------
int __fastcall sub_27BC(int a1, _DWORD *a2)
{
  int result; // r0

  ((void (__fastcall *)(_DWORD, _DWORD))a2[7])(0, a2[1]);
  result = (*(int (__fastcall **)(_DWORD, _DWORD, int (*)(), _DWORD))(*(_DWORD *)*a2 + 60))(*a2, a2[5], sub_27BC, a2[4]);
  a2[3] = result;
  return result;
}

//----- (00002808) --------------------------------------------------------
void sub_2808()
{
  JUMPOUT(0xE12FFF1E);
}
// 2818: control flows out of bounds to E12FFF1E

//----- (00002830) --------------------------------------------------------
void sub_2830()
{
  JUMPOUT(0xE8980002);
}
// 2840: control flows out of bounds to E8980002

//----- (00002844) --------------------------------------------------------
void sub_2844()
{
  JUMPOUT(0xE0800008);
}
// 2854: control flows out of bounds to E0800008

//----- (00002894) --------------------------------------------------------
int __fastcall sub_2894(int a1, int a2, int a3, int a4)
{
  return MEMORY[0xA000012](a1, a2, a3, a4);
}

//----- (0000294C) --------------------------------------------------------
void sub_294C()
{
  JUMPOUT(0xE3140000);
}
// 295C: control flows out of bounds to E3140000

//----- (00002960) --------------------------------------------------------
void __fastcall sub_2960(_BYTE *a1, _DWORD *a2, int **a3)
{
  int v4; // r5
  unsigned __int8 *v6; // r0
  unsigned __int8 *v7; // r1
  unsigned int v8; // r0
  bool v9; // zf
  int *v10; // r0
  int v11; // r3
  int v12; // r0
  _DWORD *v13; // r2
  int v14; // r1
  bool v15; // zf
  int v16; // r2

  v4 = 0;
  while ( 1 )
  {
    v14 = (unsigned __int8)*a1;
    if ( *a1 == 0 )
      break;
    ++a1;
    if ( v14 == 37 )
    {
      if ( *a1 == 37 )
      {
        ++a1;
      }
      else
      {
        sub_294C();
        if ( v6 == nullptr )
          return;
        v7 = v6;
        v8 = *v6;
        if ( v8 == 111 )
        {
LABEL_23:
          v16 = *(*a3)++;
          a2[2 * v4 + 1] = v16;
          goto LABEL_15;
        }
        if ( v8 > 0x6F )
        {
          v15 = v8 == 112;
          if ( v8 != 112 )
            v15 = v8 == 115;
          if ( v15 || v8 == 117 || v8 == 120 )
            goto LABEL_23;
        }
        else
        {
          v9 = v8 == 88;
          if ( v8 != 88 )
            v9 = v8 == 99;
          if ( !v9 )
            v9 = v8 == 100;
          if ( v9 )
            goto LABEL_23;
          if ( v8 == 102 )
          {
            v10 = *a3;
            *a3 += 2;
            v11 = *v10;
            v12 = v10[1];
            v13 = &a2[2 * v4];
            v13[1] = v11;
            v13[2] = v12;
          }
        }
LABEL_15:
        a1 = v7 + 1;
        ++v4;
      }
    }
  }
  *a2 = v4;
}
// 299C: variable 'v6' is possibly undefined

//----- (00002A84) --------------------------------------------------------
void sub_2A84(_BYTE *a1, ...)
{
  int v1; // r0
  int *v2; // [sp+4h] [bp-88h] BYREF
  _DWORD v3[33]; // [sp+8h] [bp-84h] BYREF
  _BYTE *varg_r0; // [sp+90h] [bp+4h]
  va_list varg_r1; // [sp+94h] [bp+8h] BYREF

  va_start(varg_r1, a1);
  varg_r0 = a1;
  va_copy((va_list)v2, varg_r1);
  sub_2960(a1, v3, &v2);
  if ( v1 != 0 )
    MEMORY[0xE3150002](varg_r0, v3);
}
// 2AAC: variable 'v1' is possibly undefined

//----- (00002AD0) --------------------------------------------------------
void sub_2AD0()
{
  JUMPOUT(0x10855008);
}
// 2AE0: control flows out of bounds to 10855008

//----- (00002AE4) --------------------------------------------------------
void sub_2AE4()
{
  JUMPOUT(0xE3C55002);
}
// 2AF4: control flows out of bounds to E3C55002

//----- (00002B5C) --------------------------------------------------------
void sub_2B5C()
{
  JUMPOUT(0x28B4000C);
}
// 2B6C: control flows out of bounds to 28B4000C

//----- (00002B70) --------------------------------------------------------
void sub_2B70()
{
  JUMPOUT(0x28A5000C);
}
// 2B80: control flows out of bounds to 28A5000C

//----- (00002B98) --------------------------------------------------------
void sub_2B98()
{
  JUMPOUT(0x44857004);
}
// 2BA8: control flows out of bounds to 44857004

//----- (00002BAC) --------------------------------------------------------
void sub_2BAC(int a1, _BYTE *a2, ...)
{
  int v3; // r0
  int *v4; // [sp+0h] [bp-88h] BYREF
  _DWORD v5[33]; // [sp+4h] [bp-84h] BYREF
  _BYTE *varg_r1; // [sp+94h] [bp+Ch]
  va_list varg_r2; // [sp+98h] [bp+10h] BYREF

  va_start(varg_r2, a2);
  varg_r1 = a2;
  va_copy((va_list)v4, varg_r2);
  sub_2960(a2, v5, &v4);
  if ( v3 != 0 )
    MEMORY[0xEAFFFFE8](a1, varg_r1, v5);
}
// 2BD8: variable 'v3' is possibly undefined

//----- (00002C08) --------------------------------------------------------
void __fastcall sub_2C08(int a1, _BYTE *a2, int **a3)
{
  int v5; // r0
  _DWORD v6[33]; // [sp+0h] [bp-84h] BYREF

  sub_2960(a2, v6, a3);
  if ( v5 != 0 )
    MEMORY[0xEAFFFFE8](a1, a2, v6);
}
// 2C28: variable 'v5' is possibly undefined

//----- (00002C7C) --------------------------------------------------------
void sub_2C7C()
{
  JUMPOUT(0xE0822008);
}
// 2C8C: control flows out of bounds to E0822008

//----- (00002CCC) --------------------------------------------------------
void sub_2CCC()
{
  JUMPOUT(0xE3A00000);
}
// 2CDC: control flows out of bounds to E3A00000

//----- (00002CF4) --------------------------------------------------------
void sub_2CF4()
{
  JUMPOUT(0xE3A0B000);
}
// 2D04: control flows out of bounds to E3A0B000

//----- (00002FEC) --------------------------------------------------------
int __fastcall sub_2FEC(int a1, int a2, int a3, int a4)
{
  return loc_2BC(a1, a2, a3, a4);
}

//----- (00003018) --------------------------------------------------------
int __fastcall sub_3018(int a1, int a2, int a3, int a4)
{
  return loc_2C0(a1, a2, a3, a4);
}

//----- (00003080) --------------------------------------------------------
int __fastcall sub_3080(int a1, int a2, int a3, int a4)
{
  return loc_2D0(a1, a2, a3, a4);
}

//----- (00003290) --------------------------------------------------------
__int64 __fastcall sub_3290(int a1, int a2, int a3, int a4, __int64 a5)
{
  loc_2FC(a1, a2, a3, a4);
  return a5;
}

//----- (0000337C) --------------------------------------------------------
_DWORD *__fastcall sub_337C(_DWORD *result, unsigned int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  _DWORD *v4; // r0
  int v5; // r1
  int v6; // r1
  _BYTE *v7; // r0

  v2 = a2 >= 0x20;
  v3 = a2 - 32;
  do
  {
    if ( !v2 )
      break;
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    v4 = result + 4;
    *v4 = 0;
    v4[1] = 0;
    v4[2] = 0;
    v4[3] = 0;
    result = v4 + 4;
    v2 = v3 >= 0x20;
    v3 -= 32;
  }
  while ( v2 );
  v2 = __CFSHL__(v3, 28);
  v5 = v3 << 28;
  if ( v2 )
  {
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    result += 4;
  }
  if ( v5 < 0 )
  {
    *result = 0;
    result[1] = 0;
    result += 2;
  }
  v2 = __CFSHL__(v5, 2);
  v6 = 4 * v5;
  if ( v2 )
    *result++ = 0;
  if ( v6 != 0 )
  {
    if ( v6 < 0 )
    {
      *(_BYTE *)result = 0;
      v7 = (char *)result + 1;
      *v7 = 0;
      result = v7 + 1;
    }
    if ( (v6 & 0x40000000) != 0 )
    {
      *(_BYTE *)result = 0;
      return (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (000033D4) --------------------------------------------------------
_DWORD *__fastcall sub_33D4(_BYTE *a1, char *a2, unsigned int a3)
{
  unsigned int v3; // r12
  char v4; // r3
  char v5; // t1
  bool v6; // cf
  bool v7; // cc
  unsigned int v8; // r2
  char v9; // t1
  char v10; // t1
  unsigned int v11; // r3
  unsigned int v13; // r2
  char *v14; // r1
  unsigned int v15; // r12
  unsigned int v16; // t1
  unsigned int v17; // r3
  unsigned int v18; // t1
  unsigned int v19; // r3
  unsigned int v20; // t1
  unsigned int v21; // r3
  unsigned int v22; // t1

  if ( a3 <= 3 )
    goto LABEL_22;
  v3 = (unsigned __int8)a1 & 3;
  if ( ((unsigned __int8)a1 & 3) != 0 )
  {
    v5 = *a2++;
    v4 = v5;
    v6 = v3 >= 2;
    v7 = ((unsigned __int8)a1 & 3) == 3;
    v8 = a3 + v3;
    if ( ((unsigned __int8)a1 & 3) != 3 )
    {
      v9 = *a2++;
      LOBYTE(v3) = v9;
    }
    *a1++ = v4;
    if ( !v6 )
    {
      v10 = *a2++;
      v4 = v10;
    }
    a3 = v8 - 4;
    if ( !v7 )
      *a1++ = v3;
    if ( !v6 )
      *a1++ = v4;
  }
  v11 = (unsigned __int8)a2 & 3;
  if ( ((unsigned __int8)a2 & 3) != 0 )
  {
    v6 = a3 >= 4;
    v13 = a3 - 4;
    if ( v6 )
    {
      v16 = *(_DWORD *)&a2[-v11];
      v14 = &a2[-v11];
      v15 = v16;
      if ( v11 == 2 )
      {
        do
        {
          v19 = HIWORD(v15);
          v20 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v20;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v19 | (v20 << 16);
          a1 += 4;
        }
        while ( v6 );
      }
      else if ( v11 > 2 )
      {
        do
        {
          v21 = HIBYTE(v15);
          v22 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v22;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v21 | (v22 << 8);
          a1 += 4;
        }
        while ( v6 );
      }
      else
      {
        do
        {
          v17 = v15 >> 8;
          v18 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v18;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v17 | (v18 << 24);
          a1 += 4;
        }
        while ( v6 );
      }
    }
LABEL_22:
    JUMPOUT(0x369C);
  }
  return sub_3650(a1, a2, a3, 0);
}
// 33D8: control flows out of bounds to 369C

//----- (00003488) --------------------------------------------------------
int __fastcall sub_3488(unsigned int a1, unsigned int a2)
{
  unsigned int v2; // r2
  int v3; // r3
  char v4; // cf
  bool v5; // cf
  unsigned int v6; // r2
  bool v7; // cf
  unsigned int v8; // r2
  bool v9; // cf
  unsigned int v10; // r2
  bool v11; // cf
  bool v12; // cf
  bool v13; // cf
  unsigned int v14; // r2
  bool v15; // cf
  unsigned int v16; // r2
  bool v17; // cf
  unsigned int v18; // off

  v2 = a1 & 0x80000000;
  if ( (a1 & 0x80000000) != 0 )
    a1 = -a1;
  v3 = v2 ^ ((int)a2 >> 31);
  if ( (a2 & 0x80000000) != 0 )
    a2 = -a2;
  if ( a2 >> 3 < a1 )
    goto LABEL_27;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF000000;
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  if ( a2 >> 8 < a1 )
    goto LABEL_15;
  a1 <<= 8;
  v2 |= 0xFF0000u;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 |= 0xFF00u;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_24;
  v4 = a1 == 0;
  if ( a1 == 0 )
    return sub_37D0(2, 2, v2, (const char *)v3);
  do
  {
    if ( v4 )
      a1 >>= 8;
LABEL_15:
    v5 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v6 = v2 + v5 + v2;
    v7 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v8 = v6 + v7 + v6;
    v9 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v10 = v8 + v9 + v8;
    v11 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v10 + v11 + v10;
LABEL_24:
    v12 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v12 + v2;
LABEL_27:
    v13 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v14 = v2 + v13 + v2;
    v15 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v16 = v14 + v15 + v14;
    v17 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v18 = v17 + v16;
    v4 = __CFADD__(v17, v16) | __CFADD__(v16, v18);
    v2 = v16 + v18;
  }
  while ( v4 );
  return (v2 ^ (v3 >> 31)) + ((unsigned int)v3 >> 31);
}

//----- (0000355C) --------------------------------------------------------
int __fastcall sub_355C(unsigned int a1, unsigned int a2)
{
  int v2; // r2
  char v3; // cf
  bool v4; // cf
  int v5; // r2
  bool v6; // cf
  int v7; // r2
  bool v8; // cf
  int v9; // r2
  bool v10; // cf
  bool v11; // cf
  bool v12; // cf
  int v13; // r2
  bool v14; // cf
  int v15; // r2
  bool v16; // cf
  int v17; // off

  v2 = 0;
  if ( a2 >> 3 < a1 )
    goto LABEL_23;
  if ( a2 >> 8 < a1 )
    goto LABEL_11;
  a1 <<= 8;
  v2 = -16777216;
  if ( a2 >> 4 < a1 )
    goto LABEL_20;
  if ( a2 >> 8 < a1 )
    goto LABEL_11;
  a1 <<= 8;
  v2 = -65536;
  if ( a2 >> 8 >= a1 )
  {
    a1 <<= 8;
    v2 = -256;
  }
  if ( a2 >> 4 < a1 )
    goto LABEL_20;
  v3 = a1 == 0;
  if ( a1 == 0 )
    return sub_37D0(2, 2, v2);
  do
  {
    if ( v3 )
      a1 >>= 8;
LABEL_11:
    v4 = a2 >> 7 >= a1;
    if ( a2 >> 7 >= a1 )
      a2 -= a1 << 7;
    v5 = v2 + v4 + v2;
    v6 = a2 >> 6 >= a1;
    if ( a2 >> 6 >= a1 )
      a2 -= a1 << 6;
    v7 = v5 + v6 + v5;
    v8 = a2 >> 5 >= a1;
    if ( a2 >> 5 >= a1 )
      a2 -= 32 * a1;
    v9 = v7 + v8 + v7;
    v10 = a2 >> 4 >= a1;
    if ( a2 >> 4 >= a1 )
      a2 -= 16 * a1;
    v2 = v9 + v10 + v9;
LABEL_20:
    v11 = a2 >> 3 >= a1;
    if ( a2 >> 3 >= a1 )
      a2 -= 8 * a1;
    v2 += v11 + v2;
LABEL_23:
    v12 = a2 >> 2 >= a1;
    if ( a2 >> 2 >= a1 )
      a2 -= 4 * a1;
    v13 = v2 + v12 + v2;
    v14 = a2 >> 1 >= a1;
    if ( a2 >> 1 >= a1 )
      a2 -= 2 * a1;
    v15 = v13 + v14 + v13;
    v16 = a2 >= a1;
    if ( a2 >= a1 )
      a2 -= a1;
    v17 = v16 + v15;
    v3 = __CFADD__(v16, v15) | __CFADD__(v15, v17);
    v2 = v15 + v17;
  }
  while ( v3 );
  return v2;
}
// 37D0: using guessed type int __fastcall sub_37D0(_DWORD, _DWORD, _DWORD);

//----- (0000362C) --------------------------------------------------------
int sub_362C()
{
  sub_37B8();
  return sub_3640();
}

//----- (00003650) --------------------------------------------------------
_DWORD *__fastcall sub_3650(_DWORD *result, char *a2, unsigned int a3, int a4)
{
  bool v4; // cf
  unsigned int i; // r2
  _DWORD *v6; // r1
  int v7; // r3
  int v8; // r4
  int v9; // r12
  int v10; // lr
  _DWORD *v11; // r0
  int v12; // r4
  int v13; // r12
  int v14; // lr
  int v15; // r4
  int v16; // r12
  int v17; // lr
  int v18; // r4
  char v19; // r12
  int v20; // t1
  bool v21; // cf
  bool v22; // nf
  int v23; // r2
  char v24; // t1
  _BYTE *v25; // r0

  v4 = a3 >= 0x20;
  for ( i = a3 - 32; v4; i -= 32 )
  {
    if ( !v4 )
      break;
    v7 = *(_DWORD *)a2;
    v8 = *((_DWORD *)a2 + 1);
    v9 = *((_DWORD *)a2 + 2);
    v10 = *((_DWORD *)a2 + 3);
    v6 = a2 + 16;
    *result = v7;
    result[1] = v8;
    result[2] = v9;
    result[3] = v10;
    v11 = result + 4;
    a4 = *v6;
    v12 = v6[1];
    v13 = v6[2];
    v14 = v6[3];
    a2 = (char *)(v6 + 4);
    *v11 = a4;
    v11[1] = v12;
    v11[2] = v13;
    v11[3] = v14;
    result = v11 + 4;
    v4 = i >= 0x20;
  }
  if ( __CFSHL__(i, 28) )
  {
    a4 = *(_DWORD *)a2;
    v15 = *((_DWORD *)a2 + 1);
    v16 = *((_DWORD *)a2 + 2);
    v17 = *((_DWORD *)a2 + 3);
    a2 += 16;
    *result = a4;
    result[1] = v15;
    result[2] = v16;
    result[3] = v17;
    result += 4;
  }
  if ( (i & 8) != 0 )
  {
    a4 = *(_DWORD *)a2;
    v18 = *((_DWORD *)a2 + 1);
    a2 += 8;
    *result = a4;
    result[1] = v18;
    result += 2;
  }
  v19 = 0;
  if ( __CFSHL__(i, 30) )
  {
    v20 = *(_DWORD *)a2;
    a2 += 4;
    LOBYTE(a4) = v20;
    *result++ = v20;
  }
  if ( i << 30 != 0 )
  {
    v21 = __CFSHL__(i, 31);
    v23 = i << 31;
    v22 = v23 < 0;
    if ( v23 < 0 )
    {
      v24 = *a2++;
      LOBYTE(v23) = v24;
    }
    if ( v21 )
    {
      LOBYTE(a4) = *a2;
      v19 = a2[1];
    }
    if ( v22 )
    {
      *(_BYTE *)result = v23;
      result = (_DWORD *)((char *)result + 1);
    }
    if ( v21 )
    {
      *(_BYTE *)result = a4;
      v25 = (char *)result + 1;
      *v25 = v19;
      return v25 + 1;
    }
  }
  return result;
}

//----- (000036BC) --------------------------------------------------------
int sub_36BC()
{
  return sub_362C();
}

//----- (000036D4) --------------------------------------------------------
_UNKNOWN **sub_36D4()
{
  _DWORD *v0; // r4

  sub_3B4C();
  v0 = (_DWORD *)sub_3960();
  v0[8] = 0;
  v0[9] = 1;
  v0[10] = 0;
  v0[11] = 0;
  v0[12] = 0;
  return &off_37CC;
}
// 37A8: returning address of temporary local variable '%var_C'
// 37CC: using guessed type _UNKNOWN *off_37CC;

//----- (000037B8) --------------------------------------------------------
void sub_37B8()
{
  ;
}

//----- (000037D0) --------------------------------------------------------
int __fastcall sub_37D0(int a1, int a2, int a3, const char *a4)
{
  int result; // r0

  result = sub_38FC(a1, a2, a3, a4);
  if ( result != 0 )
    return sub_38E4();
  return result;
}

//----- (00003878) --------------------------------------------------------
int __fastcall sub_3878(int a1, _DWORD *a2)
{
  int v2; // r4
  char *v3; // r3
  int v4; // r2
  int v5; // lr
  unsigned int v6; // r3
  unsigned int v7; // r1
  _DWORD savedregs[2]; // [sp+8h] [bp+0h] BYREF

  v2 = sub_3960();
  v3 = (char *)savedregs - *(_DWORD *)(v2 + 28);
  v4 = *(_DWORD *)(v2 + 20);
  *a2 = v4;
  v5 = v4 + a1;
  if ( v4 + a1 > (unsigned int)v3 )
    return 0;
  v6 = ((unsigned int)&v3[v5] >> 1) & 0x7FFFFFF8 | (__CFADD__(v3, v5) << 31);
  v7 = (v5 + 4103) & 0xFFFFFFF8;
  if ( v7 > v6 )
    v7 = v6;
  *(_DWORD *)(v2 + 20) = v7;
  return v7 - v4;
}

//----- (000038E4) --------------------------------------------------------
int sub_38E4()
{
  return __semihost(24, (void *)0x20026);
}

//----- (000038FC) --------------------------------------------------------
int __fastcall sub_38FC(int a1, int a2, int a3, const char *a4)
{
  return sub_39C4(a1, a2, 0xFFFF8187, a4);
}

//----- (00003960) --------------------------------------------------------
int sub_3960()
{
  _DWORD **v0; // r9

  return **v0 + 4;
}
// 3960: variable 'v0' is possibly undefined

//----- (00003978) --------------------------------------------------------
int sub_3978()
{
  int v0; // r9
  int v1; // r0
  int *v3; // [sp+0h] [bp-14h] BYREF
  int v4; // [sp+4h] [bp-10h] BYREF

  v3 = &v4;
  __semihost(22, &v3);
  v1 = v4;
  if ( v4 == 0 )
    v1 = 100;
  return v1 + v0;
}
// 39AC: variable 'v0' is possibly undefined

//----- (000039C4) --------------------------------------------------------
int __fastcall sub_39C4(int a1, int a2, int a3, const char *a4)
{
  const char *v4; // r5
  char *v5; // r2
  const char *v6; // r4
  bool v7; // zf
  int v8; // r1
  int v9; // r2
  int v10; // r3
  char v11; // t1
  char v12; // t1

  v5 = (char *)(a1 - 1);
  if ( (unsigned int)(a1 - 1) >= 0xD )
    v4 = "Unknown signal";
  v6 = (const char *)&unk_3AA8;
  if ( (unsigned int)(a1 - 1) < 0xD )
  {
    a4 = "Abnormal termination";
    v5 = &aAbnormalTermin[23 * a1];
    v4 = v5 - 23;
    if ( a1 == 2 )
    {
      if ( (a2 & 0x4000000) != 0 )
      {
        v6 = "Invalid Operation";
      }
      else if ( (a2 & 0x8000002) != 0 )
      {
        v6 = "Divide By Zero";
      }
      else if ( (a2 & 0x10000000) != 0 )
      {
        v6 = "Overflow";
      }
      else if ( (a2 & 0x20000000) != 0 )
      {
        v6 = "Underflow";
      }
      else if ( (a2 & 0x40000000) != 0 )
      {
        v6 = "Inexact Result";
      }
    }
    else if ( a1 == 8 )
    {
      v6 = (const char *)a2;
    }
    else
    {
      v7 = a1 == 9;
      if ( a1 == 9 )
        v7 = a2 == 1;
      if ( v7 )
        v4 = ": Heap memory corrupted";
    }
  }
  sub_3B34(10, a2, (int)v5, (int)a4);
  while ( *v4 != 0 )
  {
    v11 = *v4++;
    sub_3B34(v11, v8, v9, v10);
  }
  while ( *v6 != 0 )
  {
    v12 = *v6++;
    sub_3B34(v12, v8, v9, v10);
  }
  sub_3B34(10, v8, v9, v10);
  return 1;
}
// 3A58: variable 'v4' is possibly undefined
// 3A68: variable 'v8' is possibly undefined
// 3A68: variable 'v9' is possibly undefined
// 3A68: variable 'v10' is possibly undefined

//----- (00003B24) --------------------------------------------------------
int sub_3B24()
{
  return sub_3960() + 4;
}

//----- (00003B34) --------------------------------------------------------
int __fastcall sub_3B34(char a1, int a2, int a3, int a4)
{
  int v5; // [sp+0h] [bp-4h] BYREF

  v5 = a4;
  LOBYTE(v5) = a1;
  return __semihost(3, &v5);
}

//----- (00003B4C) --------------------------------------------------------
_DWORD *sub_3B4C()
{
  _DWORD *result; // r0

  result = (_DWORD *)sub_3B24();
  *result = 0;
  return result;
}

// nfuncs=99 queued=97 decompiled=97 lumina nreq=0 worse=0 better=0
// ALL OK, 97 function(s) have been successfully decompiled
