/* This file was generated by the Hex-Rays decompiler version 9.4.0.260713.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

int sub_188();
int sub_18C();
_DWORD *__fastcall sub_198(_DWORD *result, unsigned int a2, unsigned int a3);
int __fastcall sub_1DC(int a1, int a2, unsigned int a3, int *a4, _DWORD *a5);
int __fastcall sub_340(int a1);
__int64 __fastcall sub_354(int a1, _DWORD *a2);
int __fastcall sub_3BC(_DWORD *a1);
int __fastcall sub_518(int a1);
int __fastcall sub_78C(_DWORD *a1);
int __fastcall sub_824(_DWORD *a1, int a2, int a3);
int __fastcall sub_844(int a1, _DWORD *a2);
int __fastcall sub_8B4(int a1, unsigned int a2, unsigned int a3);
int __fastcall sub_A30(_DWORD *a1, int a2, unsigned int a3, unsigned int a4);
int (*__fastcall sub_A98(_DWORD *a1, _DWORD *a2))();
int sub_AC0();
int __fastcall sub_AD4(int a1);
int __fastcall sub_AF4(int a1);
unsigned int __fastcall sub_B14(unsigned int result);
int __fastcall sub_B3C(__int64 a1, unsigned __int64 a2);
int __fastcall sub_C6C(unsigned int a1, int a2);
int __fastcall sub_CA8(_BYTE *a1, _DWORD *a2, _DWORD **a3);
int sub_DC0(int a1, _BYTE *a2, ...);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_AB8; // weak
_BYTE byte_ABC[4] = { 37, 117, 0, 0 }; // weak


//----- (0000018C) --------------------------------------------------------
int sub_18C()
{
  return 240;
}

//----- (00000198) --------------------------------------------------------
_DWORD *__fastcall sub_198(_DWORD *result, unsigned int a2, unsigned int a3)
{
  unsigned int v3; // r3
  unsigned int v4; // r3
  unsigned int v5; // r3
  unsigned int v6; // r1

  v3 = result[27];
  if ( v3 > a2 )
    v3 = a2;
  result[27] = v3;
  v4 = result[28];
  if ( v4 > a3 )
    v4 = a3;
  result[28] = v4;
  v5 = result[29];
  if ( v5 < a2 )
    v5 = a2;
  v6 = result[30];
  result[29] = v5;
  if ( v6 < a3 )
    v6 = a3;
  result[30] = v6;
  return result;
}

//----- (000001DC) --------------------------------------------------------
int __fastcall sub_1DC(int a1, int a2, unsigned int a3, int *a4, _DWORD *a5)
{
  int v7; // r0
  int v8; // r5
  int v9; // r7
  int v10; // r6
  int v11; // r8
  unsigned int v13; // [sp+0h] [bp-10h] BYREF
  int v14; // [sp+4h] [bp-Ch] BYREF
  int v15; // [sp+8h] [bp-8h] BYREF
  int v16; // [sp+Ch] [bp-4h]

  v7 = (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 84) + 8))(*(_DWORD *)(a1 + 84), a2, 1);
  v8 = 0;
  v9 = v7;
  if ( v7 != 0 )
  {
    if ( (*(int (__fastcall **)(int, int *, int))(*(_DWORD *)v7 + 8))(v7, &v14, 4) == 4
      && v14 == 812805498
      && (*(int (__fastcall **)(int, unsigned int *, int))(*(_DWORD *)v9 + 8))(v9, &v13, 4) == 4
      && a3 < v13
      && (*(int (__fastcall **)(int, _DWORD, unsigned int))(*(_DWORD *)v9 + 32))(v9, 0, 4 * a3 + 8) == 0
      && (*(int (__fastcall **)(int, int *, int))(*(_DWORD *)v9 + 8))(v9, &v15, 8) == 8
      && (*(int (__fastcall **)(int, _DWORD, int))(*(_DWORD *)v9 + 32))(v9, 0, v15) == 0 )
    {
      v10 = v16 - v15;
      v11 = sub_AD4(v16 - v15);
      if ( (*(int (__fastcall **)(int, int, int))(*(_DWORD *)v9 + 8))(v9, v11, v10) == v10 )
      {
        *a4 = v11;
        *a5 = v10;
        v8 = 1;
      }
      else if ( v11 != 0 )
      {
        sub_AF4(v11);
      }
    }
    (*(void (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
  }
  return v8;
}

//----- (00000340) --------------------------------------------------------
int __fastcall sub_340(int a1)
{
  return (*(int (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 72) + 36))(*(_DWORD *)(a1 + 72), 0);
}

//----- (00000354) --------------------------------------------------------
__int64 __fastcall sub_354(int a1, _DWORD *a2)
{
  __int64 v5; // [sp+0h] [bp-8h]

  (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int))(**(_DWORD **)(a1 + 76) + 112))(
    *(_DWORD *)(a1 + 76),
    *a2,
    a2[1],
    a2[2],
    a2[3],
    -1973791);
  HIDWORD(v5) = -5395027;
  LODWORD(v5) = a2[3];
  (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(a1 + 76) + 108))(
    *(_DWORD *)(a1 + 76),
    *a2,
    a2[1],
    a2[2]);
  return v5;
}

//----- (000003BC) --------------------------------------------------------
int __fastcall sub_3BC(_DWORD *a1)
{
  int v2; // r1
  int v3; // r1
  __int64 v4; // r8
  int *v5; // r6
  __int64 v6; // r0
  unsigned int v7; // r0
  int v8; // r1
  __int64 v9; // r4
  int v10; // r7
  __int64 v11; // r0
  int v12; // r1
  __int64 v13; // r0
  __int64 v14; // r0
  int v16; // [sp+0h] [bp-2Ch]
  int i; // [sp+4h] [bp-28h]
  __int64 v18; // [sp+8h] [bp-24h]
  int v19; // [sp+18h] [bp-14h]
  unsigned __int64 v20; // [sp+20h] [bp-Ch]

  LODWORD(v18) = sub_B14((a1[23] - 24) / 5u);
  HIDWORD(v18) = v2;
  LODWORD(v20) = sub_B14((a1[24] - 24) / 5u);
  HIDWORD(v20) = v3;
  v4 = 0x4010000000000000LL;
  v5 = a1 + 31;
  for ( i = 5; i != 0; --i )
  {
    v16 = 5;
    LODWORD(v6) = sub_B3C(v20, v4);
    v7 = sub_B3C(v6, 0x4010000000000000uLL);
    v19 = sub_C6C(v7, v8);
    v9 = 0x4010000000000000LL;
    do
    {
      v10 = sub_C6C(v9, SHIDWORD(v9));
      *v5 = v10;
      v5[1] = sub_C6C(v4, SHIDWORD(v4));
      LODWORD(v11) = sub_B3C(v18, v9);
      LODWORD(v9) = sub_B3C(v11, 0x4010000000000000uLL);
      HIDWORD(v9) = v12;
      v5[2] = sub_C6C(v9, v12) - v10 - 4;
      v5[3] = v19 - v5[1] - 4;
      v5 += 4;
      --v16;
    }
    while ( v16 != 0 );
    LODWORD(v13) = sub_B3C(v4, v20);
    LODWORD(v14) = sub_B3C(v13, 0x4010000000000000uLL);
    v4 = v14;
  }
  return v14;
}
// 3E0: variable 'v2' is possibly undefined
// 404: variable 'v3' is possibly undefined
// 444: variable 'v6' is possibly undefined
// 448: variable 'v8' is possibly undefined
// 498: variable 'v11' is possibly undefined
// 4A0: variable 'v12' is possibly undefined
// 4F4: variable 'v13' is possibly undefined
// 500: variable 'v14' is possibly undefined

//----- (00000518) --------------------------------------------------------
int __fastcall sub_518(int a1)
{
  int v2; // r0
  int v3; // r0
  int v4; // r0
  int v5; // r4
  int v6; // r0
  int v7; // r7
  _DWORD *v8; // r8
  int v9; // r0
  int v10; // r4
  int v11; // r0
  int v12; // r4
  int v13; // r1
  int v15; // [sp+0h] [bp-1B8h] BYREF
  _DWORD v16[4]; // [sp+Ch] [bp-1ACh] BYREF
  _BYTE v17[12]; // [sp+1Ch] [bp-19Ch] BYREF
  _BYTE v18[40]; // [sp+28h] [bp-190h] BYREF
  _BYTE v19[8]; // [sp+50h] [bp-168h] BYREF
  int v20; // [sp+58h] [bp-160h]
  int v21; // [sp+5Ch] [bp-15Ch]

  v2 = sub_AC0();
  *(_DWORD *)(a1 + 72) = v2;
  if ( (*(int (__fastcall **)(int, int, int))(*(_DWORD *)v2 + 8))(v2, 16777221, a1 + 76) != 0
    || (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 72) + 8))(*(_DWORD *)(a1 + 72), 16777219, a1 + 84) != 0
    || (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 72) + 8))(*(_DWORD *)(a1 + 72), 16777227, a1 + 80) != 0
    || (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 72) + 8))(*(_DWORD *)(a1 + 72), 16777228, a1 + 88) != 0
    || (v3 = sub_18C(),
        (*(void (__fastcall **)(int, int))(v3 + 136))(a1 + 532, a1 + 4),
        v4 = sub_18C(),
        (v5 = (*(int (__fastcall **)(int, int))(v4 + 168))(a1 + 532, 46)) == 0) )
  {
    sub_340(a1);
  }
  else
  {
    v6 = sub_18C();
    (*(void (__fastcall **)(int, void *))(v6 + 136))(v5 + 1, &unk_AB8);
    v7 = 0;
    v8 = (_DWORD *)(a1 + 124);
    (*(void (__fastcall **)(_DWORD, _DWORD))(**(_DWORD **)(a1 + 80) + 20))(*(_DWORD *)(a1 + 80), 0);
    (*(void (__fastcall **)(_DWORD, _BYTE *))(**(_DWORD **)(a1 + 72) + 16))(*(_DWORD *)(a1 + 72), v19);
    v9 = *(_DWORD *)(a1 + 76);
    *(_DWORD *)(a1 + 92) = v20;
    *(_DWORD *)(a1 + 96) = v21;
    (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v9 + 32))(v9, 0);
    sub_3BC((_DWORD *)a1);
    (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 76) + 64))(*(_DWORD *)(a1 + 76), 1);
    (*(void (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int))(**(_DWORD **)(a1 + 76) + 112))(
      *(_DWORD *)(a1 + 76),
      0,
      0,
      *(_DWORD *)(a1 + 92),
      *(_DWORD *)(a1 + 96),
      -1);
    do
    {
      v10 = sub_DC0((int)v17, byte_ABC, ++v7);
      v11 = sub_18C();
      v12 = (*(int (__fastcall **)(_BYTE *, int, _BYTE *, int))(v11 + 32))(v17, v10, v18, 10);
      sub_354(a1, v8);
      (*(void (__fastcall **)(_DWORD, _DWORD *, _BYTE *, int, int, _DWORD, int))(**(_DWORD **)(a1 + 76) + 80))(
        *(_DWORD *)(a1 + 76),
        v8,
        v18,
        v12,
        -16777216,
        0,
        20);
      v8 += 4;
    }
    while ( v7 < 25 );
    v16[0] = 0;
    v16[1] = 0;
    v16[2] = *(_DWORD *)(a1 + 92);
    v13 = *(_DWORD *)(a1 + 96);
    v15 = 0;
    v16[3] = v13;
    (*(void (__fastcall **)(_DWORD, _DWORD *, int, int *))(**(_DWORD **)(a1 + 76) + 44))(
      *(_DWORD *)(a1 + 76),
      v16,
      1,
      &v15);
  }
  return 1;
}
// ABC: using guessed type _BYTE byte_ABC[4];

//----- (0000078C) --------------------------------------------------------
int __fastcall sub_78C(_DWORD *a1)
{
  int v2; // r0
  int v3; // r0
  int v4; // r0
  int v5; // r0
  int v6; // r0

  v2 = a1[22];
  if ( v2 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v2 + 4))(v2);
    a1[22] = 0;
  }
  v3 = a1[21];
  if ( v3 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v3 + 4))(v3);
    a1[21] = 0;
  }
  v4 = a1[20];
  if ( v4 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v4 + 4))(v4);
    a1[20] = 0;
  }
  v5 = a1[19];
  if ( v5 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
    a1[19] = 0;
  }
  v6 = a1[131];
  if ( v6 != 0 )
  {
    sub_AF4(v6);
    a1[131] = 0;
  }
  return 1;
}

//----- (00000824) --------------------------------------------------------
int __fastcall sub_824(_DWORD *a1, int a2, int a3)
{
  a1[25] = a2;
  a1[26] = a3;
  a1[27] = a2;
  a1[28] = a3;
  a1[29] = a2;
  a1[30] = a3;
  return 1;
}

//----- (00000844) --------------------------------------------------------
int __fastcall sub_844(int a1, _DWORD *a2)
{
  int result; // r0
  int v4; // r3
  _DWORD *v5; // r2
  unsigned int v6; // r5
  unsigned int v7; // r4

  result = -1;
  v4 = 0;
  v5 = (_DWORD *)(a1 + 124);
  v6 = a2[1];
  while ( 1 )
  {
    if ( *a2 >= *v5 )
    {
      v7 = v5[1];
      if ( v6 >= v7 && *a2 < (unsigned int)(v5[2] + *v5) && v6 < v5[3] + v7 )
        break;
    }
    ++v4;
    v5 += 4;
    if ( v4 >= 25 )
      return result;
  }
  return v4;
}

//----- (000008B4) --------------------------------------------------------
int __fastcall sub_8B4(int a1, unsigned int a2, unsigned int a3)
{
  unsigned int v6; // r0
  signed int v7; // r5
  int v8; // r0
  unsigned int *v9; // r1
  unsigned int v10; // r3
  int v11; // r0

  sub_198((_DWORD *)a1, a2, a3);
  v6 = *(_DWORD *)(a1 + 96) / 3u;
  if ( *(_DWORD *)(a1 + 104) >= v6
    || a3 <= 2 * v6
    || *(_DWORD *)(a1 + 116) - *(_DWORD *)(a1 + 108) >= *(_DWORD *)(a1 + 92) / 3u )
  {
    v7 = -1;
    v8 = 0;
    v9 = (unsigned int *)(a1 + 124);
    while ( 1 )
    {
      if ( a2 >= *v9 )
      {
        v10 = v9[1];
        if ( a3 >= v10 && a2 < v9[2] + *v9 && a3 < v9[3] + v10 )
          break;
      }
      ++v8;
      v9 += 4;
      if ( v8 >= 25 )
        goto LABEL_13;
    }
    v7 = v8;
LABEL_13:
    if ( v7 == sub_844(a1, (_DWORD *)(a1 + 100)) && v7 >= 0 )
    {
      (*(void (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 88) + 20))(*(_DWORD *)(a1 + 88));
      v11 = *(_DWORD *)(a1 + 524);
      if ( v11 != 0 )
      {
        sub_AF4(v11);
        *(_DWORD *)(a1 + 524) = 0;
        *(_DWORD *)(a1 + 528) = 0;
      }
      if ( sub_1DC(a1, a1 + 532, v7, (int *)(a1 + 524), (_DWORD *)(a1 + 528)) != 0 )
        (*(void (__fastcall **)(_DWORD, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))(**(_DWORD **)(a1 + 88) + 16))(
          *(_DWORD *)(a1 + 88),
          4,
          *(_DWORD *)(a1 + 524),
          *(_DWORD *)(a1 + 528),
          0,
          0,
          0);
    }
  }
  else
  {
    sub_340(a1);
  }
  return 1;
}

//----- (00000A30) --------------------------------------------------------
int __fastcall sub_A30(_DWORD *a1, int a2, unsigned int a3, unsigned int a4)
{
  int result; // r0

  if ( a1 == nullptr )
    return -4;
  switch ( a2 )
  {
    case 0:
      result = sub_518((int)a1);
      break;
    case 1:
      result = sub_78C(a1);
      break;
    case 9:
      result = sub_824(a1, a3, a4);
      break;
    case 10:
      result = sub_8B4((int)a1, a3, a4);
      break;
    case 11:
      sub_198(a1, a3, a4);
      goto LABEL_9;
    default:
LABEL_9:
      result = 1;
      break;
  }
  return result;
}

//----- (00000A98) --------------------------------------------------------
int (*__fastcall sub_A98(_DWORD *a1, _DWORD *a2))()
{
  *a1 = 596;
  *a2 = 0;
  a2[1] = 0;
  a2[2] = sub_A30;
  return sub_A30;
}
// A30: using guessed type int sub_A30();

//----- (00000AC0) --------------------------------------------------------
int sub_AC0()
{
  _DWORD *v0; // r0

  v0 = (_DWORD *)sub_18C();
  return ((int (__fastcall *)(_DWORD))*v0)(*v0);
}

//----- (00000AD4) --------------------------------------------------------
int __fastcall sub_AD4(int a1)
{
  int v2; // r1

  v2 = sub_18C();
  return (*(int (__fastcall **)(int))(v2 + 8))(a1);
}

//----- (00000AF4) --------------------------------------------------------
int __fastcall sub_AF4(int a1)
{
  int v2; // r1

  v2 = sub_18C();
  return (*(int (__fastcall **)(int))(v2 + 12))(a1);
}

//----- (00000B14) --------------------------------------------------------
unsigned int __fastcall sub_B14(unsigned int result)
{
  if ( result != 0 )
    return result << __clz(result) << 21;
  return result;
}

//----- (00000B3C) --------------------------------------------------------
int __fastcall sub_B3C(__int64 a1, unsigned __int64 a2)
{
  unsigned __int64 v2; // kr78_8
  _BOOL1 v3; // cf
  int v4; // r12
  int v5; // lr
  bool v6; // zf
  int v7; // lr
  unsigned int v8; // r4
  int v9; // r4
  int v10; // off
  int v11; // off
  unsigned int v12; // r4
  unsigned int v13; // lr
  bool v14; // cf
  int v15; // r12
  int v16; // lr
  int v17; // r12
  bool v18; // zf
  unsigned int v19; // lr
  unsigned int v20; // t2
  unsigned int v21; // lr
  unsigned int v22; // lr
  bool v23; // cf
  int v24; // r0
  bool v25; // zf
  int v26; // lr
  int v27; // r4
  int v28; // r4
  int v29; // r4
  int v30; // r4
  _BOOL1 v31; // off

  if ( (HIDWORD(a1) ^ HIDWORD(a2)) >= 0 )
  {
    v2 = a1 - a2;
    if ( a1 < a2 )
    {
      a1 = a2;
      a2 += v2;
    }
    v3 = __CFADD__(2 * HIDWORD(a1), 0x200000);
    if ( (unsigned int)(2 * HIDWORD(a1)) < 0xFFE00000 )
      v3 = __CFSUB__(0x200000, 2 * HIDWORD(a2), __CFSHL__(HIDWORD(a2), 1));
    if ( v3 )
    {
      if ( (unsigned int)(2 * HIDWORD(a1)) >= 0xFFE00000 || ((unsigned int)a2 | (2 * HIDWORD(a2))) == 0 )
        return a1;
      if ( (unsigned int)(2 * HIDWORD(a1)) < 0x200000 )
      {
        LODWORD(a1) = a1 + a2;
        return a1;
      }
      v4 = HIDWORD(a1) >> 20;
      HIDWORD(a2) &= ~0x80000000;
      v5 = (HIDWORD(a1) >> 20) - 1;
      if ( HIDWORD(a1) >> 20 > 0x35 )
        return a1;
    }
    else
    {
      v4 = HIDWORD(a1) >> 20;
      v5 = (HIDWORD(a1) >> 20) - (HIDWORD(a2) >> 20);
      if ( v5 > 53 )
        return a1;
      HIDWORD(a2) = ((HIDWORD(a2) << 11) | 0x80000000) >> 11;
    }
    HIDWORD(a1) = (int)((HIDWORD(a1) << 11) | 0x80000000) >> 11;
    if ( v5 <= 32 )
    {
      v9 = __ROR4__(a2, v5);
      LODWORD(a2) = (unsigned int)a2 >> v5;
      v8 = v9 ^ a2;
      LODWORD(a1) = a1 + (a2 ^ __ROR4__(HIDWORD(a2), v5) ^ (HIDWORD(a2) >> v5));
      v3 = __CFADD__(__CFSHR__(HIDWORD(a2), v5), HIDWORD(a1));
      HIDWORD(a1) += __CFSHR__(HIDWORD(a2), v5);
      v3 |= __CFADD__(HIDWORD(a2) >> v5, HIDWORD(a1));
      HIDWORD(a1) += HIDWORD(a2) >> v5;
      if ( !v3 )
      {
LABEL_21:
        HIDWORD(a1) += 0x100000;
        a1 += __PAIR64__(v4 << 20, __CFSUB__(v8, 0x80000000, a1 & 1));
        if ( (unsigned int)(2 * HIDWORD(a1)) >= 0xFFE00000 )
          LODWORD(a1) = 0;
        return a1;
      }
    }
    else
    {
      v7 = v5 - 32;
      v6 = v7 == 0;
      if ( v7 != 0 )
        v6 = (_DWORD)a2 == 0;
      v8 = __ROR4__(HIDWORD(a2), v7) ^ (HIDWORD(a2) >> v7);
      if ( !v6 )
        v8 |= 1u;
      v3 = __CFADD__(__CFADD__((_DWORD)a1, HIDWORD(a2) >> v7), HIDWORD(a1));
      a1 += (unsigned int)(HIDWORD(a2) >> v7);
      if ( !v3 )
        goto LABEL_21;
    }
    v3 = BYTE4(a1) & 1;
    HIDWORD(a1) >>= 1;
    v10 = v3 << 31;
    v3 = a1 & 1;
    LODWORD(a1) = ((unsigned int)a1 >> 1) | v10;
    v11 = v3 << 31;
    v3 = v8 & 1;
    v8 = (v8 >> 1) | v11;
    if ( v3 )
      v8 |= 1u;
    goto LABEL_21;
  }
  HIDWORD(a2) ^= 0x80000000;
  v12 = a1 - a2;
  if ( a1 < a2 )
  {
    v13 = ((a1 - a2) >> 32) ^ 0x80000000;
    a1 -= __PAIR64__(v13, v12);
    a2 += __PAIR64__(v13, v12);
  }
  v14 = __CFADD__(2 * HIDWORD(a1), 0x200000);
  if ( (unsigned int)(2 * HIDWORD(a1)) < 0xFFE00000 )
    v14 = __CFSUB__(0x200000, 2 * HIDWORD(a2), __CFSHL__(HIDWORD(a2), 1));
  if ( v14 )
  {
    if ( (unsigned int)(2 * HIDWORD(a1)) >= 0xFFE00000 )
      return a1;
    HIDWORD(a2) &= ~0x80000000;
    if ( ((unsigned int)a2 | (2 * HIDWORD(a2))) == 0 )
      return a1;
    if ( (unsigned int)(2 * HIDWORD(a1)) < 0x400000 )
    {
      LODWORD(a1) = a1 - a2;
      return a1;
    }
    v15 = HIDWORD(a1) >> 20;
    v16 = (HIDWORD(a1) >> 20) - 1;
    if ( HIDWORD(a1) >> 20 > 0x35 )
      return a1;
    goto LABEL_51;
  }
  v15 = HIDWORD(a1) >> 20;
  v16 = (HIDWORD(a1) >> 20) - (HIDWORD(a2) >> 20);
  if ( v16 > 54 )
    return a1;
  if ( v16 > 1 )
  {
    HIDWORD(a2) = ((HIDWORD(a2) << 11) | 0x80000000) >> 11;
LABEL_51:
    HIDWORD(a1) = ((HIDWORD(a1) << 11) | 0x80000000) >> 11;
    if ( v16 <= 32 )
    {
      v29 = __ROR4__(a2, v16);
      LODWORD(a2) = (unsigned int)a2 >> v16;
      v30 = v29 ^ a2;
      LODWORD(a2) = a2 ^ __ROR4__(HIDWORD(a2), v16);
      HIDWORD(a2) >>= v16;
      LODWORD(a2) = a2 ^ HIDWORD(a2);
      v3 = v30 == 0;
      v28 = -v30;
      v31 = v3;
      v3 = __CFSUB__((_DWORD)a1, (_DWORD)a2, v3);
      LODWORD(a1) = a1 - (a2 + !v31);
      HIDWORD(a1) -= HIDWORD(a2) + !v3;
    }
    else
    {
      v26 = v16 - 32;
      v25 = v26 == 0;
      if ( v26 != 0 )
        v25 = (_DWORD)a2 == 0;
      v27 = __ROR4__(HIDWORD(a2), v26) ^ (HIDWORD(a2) >> v26);
      if ( !v25 )
        v27 |= 1u;
      v28 = -v27;
      v3 = __CFSUB__((_DWORD)a1, HIDWORD(a2) >> v26, __CFSHR__(HIDWORD(a2), v26));
      LODWORD(a1) = a1 - ((HIDWORD(a2) >> v26) + !__CFSHR__(HIDWORD(a2), v26));
      HIDWORD(a1) -= !v3;
    }
    if ( (a1 & 0x10000000000000LL) == 0 && (v15 - 1) << 21 != 0 )
    {
      v3 = __CFSHL__(v28, 1);
      v28 *= 2;
      LODWORD(a1) = a1 + v3 + (_DWORD)a1;
    }
    LODWORD(a1) = __CFSUB__(v28, 0x80000000, a1 & 1) + (_DWORD)a1;
    return a1;
  }
  v17 = v15 << 20;
  HIDWORD(a2) = (HIDWORD(a2) << 11) | 0x80000000 | ((unsigned int)a2 >> 21);
  if ( v16 == 1 )
  {
    LODWORD(a2) = (_DWORD)a2 << 10;
    HIDWORD(a2) >>= 1;
  }
  else
  {
    LODWORD(a2) = (_DWORD)a2 << 11;
  }
  a1 = __PAIR64__((HIDWORD(a1) << 11) | 0x80000000 | ((unsigned int)a1 >> 21), (_DWORD)a1 << 11) - a2;
  v18 = HIDWORD(a1) == 0;
  if ( a1 < 0 )
  {
LABEL_47:
    v23 = __CFSHR__(a1, 11);
    v24 = a1 >> 11;
    if ( v23 )
      v23 = v24 & 1;
    LODWORD(a1) = v23 + v24;
    return a1;
  }
  if ( HIDWORD(a1) == 0 )
  {
    HIDWORD(a1) = a1;
    LODWORD(a1) = 0;
  }
  v19 = __clz(HIDWORD(a1));
  HIDWORD(a1) = (HIDWORD(a1) << v19) | ((unsigned int)a1 >> (32 - v19));
  LODWORD(a1) = (_DWORD)a1 << v19;
  if ( !v18 || (v19 += 32, HIDWORD(a1) != 0) )
  {
    v20 = __ROR4__(v17, 31);
    v3 = v20 >= v19 << 21;
    v21 = (v20 - (v19 << 21)) & 0xFFFFFFFE;
    if ( v21 == 0 || !v3 )
    {
      v22 = (0x200000 - v21) >> 21;
      LODWORD(a1) = ((unsigned int)a1 >> v22) ^ __ROR4__(HIDWORD(a1), v22);
      HIDWORD(a1) >>= v22;
      LODWORD(a1) = a1 ^ HIDWORD(a1);
    }
    goto LABEL_47;
  }
  return a1;
}

//----- (00000C6C) --------------------------------------------------------
int __fastcall sub_C6C(unsigned int a1, int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  int v4; // r0
  int v5; // r1
  bool v6; // nf
  bool v7; // vf
  int v8; // r1
  unsigned int v9; // r0
  int v10; // r1

  v2 = __CFADD__(a2, a2);
  v3 = 2 * a2;
  v4 = (a1 >> 21) | (v3 << 10);
  if ( v2 )
    return 0;
  v5 = (v3 >> 21) - 1024;
  v7 = __OFADD__(v5, 1);
  v6 = v5 + 1 < 0;
  v8 = v5 + 1;
  v9 = v4 | 0x80000000;
  if ( v6 != v7 )
    return 0;
  v10 = 31 - v8;
  if ( v10 < 0 )
    return -1;
  else
    return v9 >> v10;
}

//----- (00000CA8) --------------------------------------------------------
int __fastcall sub_CA8(_BYTE *a1, _DWORD *a2, _DWORD **a3)
{
  int i; // r7
  int v7; // r0
  int v8; // t1
  int v9; // r0
  unsigned __int8 *v10; // r0
  unsigned __int8 *v11; // r2
  int v12; // r0
  int v13; // r1
  _QWORD *v15; // r3
  __int64 v16; // [sp+0h] [bp-8h]

  for ( i = 0; ; ++i )
  {
    while ( 1 )
    {
      do
      {
        v8 = (unsigned __int8)*a1++;
        v7 = v8;
        if ( v8 == 0 )
        {
          *a2 = i;
          return 1;
        }
      }
      while ( v7 != 37 );
      if ( *a1 != 37 )
        break;
      ++a1;
    }
    v9 = sub_18C();
    v10 = (unsigned __int8 *)(*(int (__fastcall **)(_BYTE *, const char *))(v9 + 164))(a1, "dufocsxXp");
    v11 = v10;
    if ( v10 == nullptr )
      break;
    v12 = *v10;
    if ( v12 == 111 || v12 == 112 || v12 == 115 || v12 == 117 || v12 == 120 || v12 == 88 || v12 == 99 || v12 == 100 )
    {
      v13 = *(*a3)++;
      a2[2 * i + 1] = v13;
    }
    else if ( v12 == 102 )
    {
      v15 = (_QWORD *)(((unsigned int)*a3 + 7) & 0xFFFFFFF8);
      *a3 = v15;
      v16 = *v15;
      *a3 = v15 + 1;
      *(_QWORD *)&a2[2 * i + 1] = v16;
    }
    a1 = v11 + 1;
  }
  return 0;
}

//----- (00000DC0) --------------------------------------------------------
int sub_DC0(int a1, _BYTE *a2, ...)
{
  int result; // r0
  int v5; // r0
  _DWORD *v6; // [sp+0h] [bp-8Ch] BYREF
  _DWORD v7[34]; // [sp+4h] [bp-88h] BYREF
  int varg_r2; // [sp+98h] [bp+Ch] BYREF
  va_list varg_r2a; // [sp+98h] [bp+Ch]
  int varg_r3; // [sp+9Ch] [bp+10h]
  va_list va1; // [sp+A0h] [bp+14h] BYREF

  va_start(va1, a2);
  va_start(varg_r2a, a2);
  varg_r2 = va_arg(va1, _DWORD);
  varg_r3 = va_arg(va1, _DWORD);
  v7[33] = varg_r3;
  va_copy((va_list)v6, varg_r2a);
  result = sub_CA8(a2, v7, &v6);
  if ( result != 0 )
  {
    v5 = sub_18C();
    return (*(int (__fastcall **)(int, _BYTE *, _DWORD *))(v5 + 108))(a1, a2, v7);
  }
  return result;
}

// nfuncs=22 queued=21 decompiled=21 lumina nreq=0 worse=0 better=0
// ALL OK, 21 function(s) have been successfully decompiled
