/* This file was generated by the Hex-Rays decompiler version 9.4.0.260713.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void __fastcall sub_274(int a1);
void __fastcall sub_2C8(int *a1);
_DWORD *__fastcall sub_2EC(_DWORD *result, int a2, int a3);
int *__fastcall sub_33C(int *result, int a2, int a3);
_DWORD *__fastcall sub_3BC(_DWORD *result);
int __fastcall sub_3E8(int a1);
_DWORD *sub_434();
_DWORD *sub_450();
int __fastcall nullsub_1(_DWORD); // weak
int sub_470();
void __fastcall sub_564(_DWORD *a1);
_DWORD *__fastcall sub_63C(_DWORD *result, int a2, int a3);
int (__fastcall *__fastcall sub_8F0(_DWORD *a1, int (__fastcall **a2)(int a1)))(int result, int a2, int a3);
int __fastcall sub_944(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
int __fastcall sub_9B8(int result, int a2, int a3);
int __fastcall sub_A2C(_DWORD *a1, int a2, int a3, int a4);
int __fastcall sub_B10(int a1);
int __fastcall sub_BB8(int a1);
int __fastcall sub_C50(int a1);
int __fastcall sub_C6C(int a1, int a2, _BYTE *a3, int a4);
int __fastcall sub_D10(int a1, int a2);
void sub_D80();
void __fastcall sub_DB8(int a1, int a2, int a3);
void __fastcall sub_E24(int a1, _BYTE *a2, int a3);
void __fastcall sub_E68(int a1, _BYTE *a2, int a3);
void __fastcall sub_EAC(_DWORD *a1);
void __fastcall sub_F64(int a1);
void __fastcall sub_F90(int a1);
BOOL __fastcall sub_FBC(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
int __fastcall sub_1074(int result);
int __fastcall sub_1234(int result, int a2, int a3);
int __fastcall sub_1268(int a1);
int __fastcall sub_12D4(int a1, int a2, int a3, int a4);
_DWORD *__fastcall sub_1504(int a1);
int __fastcall sub_17AC(int a1);
int __fastcall sub_1914(int a1, _DWORD *a2);
int __fastcall sub_197C(int result);
int __fastcall sub_19C8(int a1, int a2, int a3, int a4);
void __fastcall sub_1BB0(int a1);
int __fastcall sub_1E24(int a1);
int __fastcall sub_1FE0(int a1, int a2);
void __fastcall sub_205C(int a1, int a2);
int __fastcall sub_21B0(int a1, int a2);
int __fastcall sub_21D4(int a1);
int __fastcall sub_2380(int a1);
int __fastcall sub_2404(int a1);
int __fastcall sub_256C(int a1, int a2);
int __fastcall sub_25B0(int a1, int a2);
int __fastcall sub_28E4(int a1, int a2);
int __fastcall sub_29D8(int a1, int a2, int a3);
int __fastcall sub_2BE4(int a1, int a2);
int __fastcall sub_2C08(int *a1, _BYTE *a2);
int __fastcall sub_2C68(int *a1, const char *a2, int a3, int *a4, int a5, int a6);
int __fastcall sub_2D24(int a1);
int __fastcall sub_2FE4(_DWORD *a1);
int __fastcall sub_3394(int result);
int __fastcall sub_35DC(int result, int a2);
void __fastcall sub_3830(int a1);
void sub_38D8();
void sub_3900();
void sub_3914();
int __fastcall sub_3964(int a1, int a2, int a3, int a4);
void sub_399C();
void sub_39B0();
void sub_3A28();
void __fastcall sub_3A3C(_BYTE *a1, _DWORD *a2, int **a3);
void sub_3B60(_BYTE *a1, ...);
void sub_3C24();
void sub_3C38();
void sub_3C4C();
void sub_3C88(int a1, _BYTE *a2, ...);
void __fastcall sub_3CE4(int a1, _BYTE *a2, int **a3);
void sub_3D44();
void sub_3D58();
void sub_3D80();
void sub_3D94();
void sub_3DA8();
void sub_3DD0();
void sub_3DF8();
void sub_3E5C();
void sub_3EAC();
void sub_3EFC();
int __fastcall sub_40C8(int a1, int a2, int a3, int a4);
int __fastcall sub_40F4(int a1, int a2, int a3, int a4);
int __fastcall sub_415C(int a1, int a2, int a3, int a4);
__int64 __fastcall sub_436C(int a1, int a2, int a3, int a4, __int64 a5);
int __fastcall sub_43F0(int result);
int sub_4400();
_DWORD *__fastcall sub_4458(_DWORD *result, unsigned int a2);
_DWORD *__fastcall sub_44B0(_BYTE *a1, char *a2, unsigned int a3);
int sub_4574();
int sub_4588();
_DWORD *__fastcall sub_458C(_DWORD *result, char *a2, unsigned int a3, int a4);
int sub_45F8();
_UNKNOWN **sub_4610();
void sub_46F4();
int __fastcall sub_479C(int a1, _DWORD *a2);
int sub_4808();
int sub_4820();
char *sub_4838();
int sub_4884();
_DWORD *sub_4894();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN *off_0 = (_UNKNOWN *)0x1772; // weak
_UNKNOWN unk_7; // weak
_UNKNOWN unk_64; // weak
int dword_184 = 0; // weak
_BYTE byte_E20[4] = { 37, 100, 0, 0 }; // weak
_BYTE byte_219C[4] = { 98, 97, 108, 0 }; // weak
_UNKNOWN *off_4708 = &off_C0; // weak
_UNKNOWN unk_48A8; // weak
_UNKNOWN unk_48B4; // weak
_UNKNOWN unk_48BA; // weak
_UNKNOWN unk_48C4; // weak
_UNKNOWN unk_48D2; // weak
_UNKNOWN unk_4902; // weak
_UNKNOWN unk_4908; // weak
_UNKNOWN unk_490E; // weak
_UNKNOWN unk_4914; // weak
_UNKNOWN unk_4920; // weak
_UNKNOWN unk_492A; // weak
_UNKNOWN unk_4970; // weak
_UNKNOWN unk_49A4; // weak
char byte_49B4[46] =
{
  '\xA8',
  '`',
  '\xF2',
  ']',
  '\xD1',
  'S',
  '\x01',
  '\x90',
  '0',
  '\0',
  'a',
  'g',
  '\f',
  '\xFF',
  '\xD8',
  '\x8F',
  '\x81',
  '\x89',
  '\xD1',
  'S',
  '\x01',
  '\x90',
  '0',
  '\0',
  'a',
  'g',
  '\f',
  '\xFF',
  '\xF7',
  '\x8B',
  'n',
  'x',
  '\xA4',
  '\x8B',
  ',',
  '{',
  '0',
  '\0',
  'a',
  'g',
  '\x02',
  '0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // weak
char aCkW[4] = "ck(W"; // weak


//----- (00000274) --------------------------------------------------------
void __fastcall sub_274(int a1)
{
  _DWORD *v2; // r0
  _DWORD *v3; // r4
  int v4; // r0

  sub_F90(16);
  v3 = v2;
  if ( v2 != nullptr )
  {
    sub_3C4C();
    if ( a1 > 0 )
    {
      sub_F90(a1);
      *v3 = v4;
      sub_3C4C();
    }
    v3[2] = a1;
  }
}
// 284: variable 'v2' is possibly undefined
// 2B4: variable 'v4' is possibly undefined

//----- (000002C8) --------------------------------------------------------
void __fastcall sub_2C8(int *a1)
{
  int v2; // r0

  if ( a1 != nullptr )
  {
    v2 = *a1;
    if ( *a1 != 0 )
      sub_F64(v2);
    sub_F64((int)a1);
  }
}

//----- (000002EC) --------------------------------------------------------
_DWORD *__fastcall sub_2EC(_DWORD *result, int a2, int a3)
{
  bool v3; // zf
  _DWORD *v4; // r4
  int v5; // r12
  int v6; // r5

  v4 = result;
  v3 = result == nullptr;
  if ( result != nullptr )
    v3 = *result == 0;
  if ( !v3 )
  {
    result = (_DWORD *)result[1];
    v5 = v4[2];
    if ( (int)result + a3 > v5 )
      a3 = v5 - (_DWORD)result;
    v6 = a3;
    if ( a3 > 0 )
    {
      sub_3C38();
      result = (_DWORD *)(v4[1] + v6);
      v4[1] = result;
    }
  }
  return result;
}

//----- (0000033C) --------------------------------------------------------
int *__fastcall sub_33C(int *result, int a2, int a3)
{
  int v3; // r5
  bool v4; // zf
  int *v5; // r4
  int v8; // r1
  int v9; // r0
  int v10; // r0
  int v11; // r0

  v5 = result;
  v4 = result == nullptr;
  if ( result != nullptr )
    v3 = *result;
  if ( result != nullptr )
    v4 = v3 == 0;
  if ( !v4 )
  {
    v8 = result[2];
    v9 = result[1] + a3;
    if ( v9 > v8 )
    {
      v10 = ((v9 / 1024) << 10) + 1024;
      v5[2] = v10;
      sub_F90(v10);
      *v5 = v11;
      if ( v11 != 0 )
      {
        sub_3C38();
        sub_F64(v3);
      }
      else
      {
        *v5 = v3;
      }
    }
    return sub_2EC(v5, a2, a3);
  }
  return result;
}
// 350: variable 'v3' is possibly undefined
// 384: variable 'v11' is possibly undefined

//----- (000003BC) --------------------------------------------------------
_DWORD *__fastcall sub_3BC(_DWORD *result)
{
  _DWORD *v1; // r4

  v1 = result;
  if ( result != nullptr )
  {
    if ( *result != 0 )
      sub_3C4C();
    v1[1] = 0;
    return nullptr;
  }
  return result;
}

//----- (000003E8) --------------------------------------------------------
int __fastcall sub_3E8(int a1)
{
  bool v1; // zf
  int result; // r0
  int v4; // r1

  v1 = a1 == 0;
  result = 0;
  if ( !v1 )
  {
    sub_3C24();
    result = *(_DWORD *)(a1 + 12);
    v4 = *(_DWORD *)(a1 + 4) - result;
    *(_DWORD *)(a1 + 4) = v4;
    *(_DWORD *)(a1 + 12) = 0;
    if ( v4 < 0 )
      *(_DWORD *)(a1 + 4) = 0;
  }
  return result;
}

//----- (00000434) --------------------------------------------------------
_DWORD *sub_434()
{
  _DWORD v1[16]; // [sp+4h] [bp-40h] BYREF

  return sub_4458(v1, 0x40u);
}

//----- (00000450) --------------------------------------------------------
_DWORD *sub_450()
{
  _DWORD v1[16]; // [sp+4h] [bp-40h] BYREF

  return sub_4458(v1, 0x40u);
}

//----- (00000470) --------------------------------------------------------
int sub_470()
{
  int v0; // r0
  int v1; // r4
  int v2; // r0
  int result; // r0
  int i; // r4
  int v5; // r0
  int v6; // r5
  int v7; // r0
  _DWORD v8[16]; // [sp+0h] [bp-44h] BYREF
  int v9; // [sp+40h] [bp-4h] BYREF

  v9 = 0;
  sub_4458(v8, 0x40u);
  sub_38D8();
  v1 = v0;
  sub_38D8();
  (*(void (__fastcall **)(int, int, int *))(*(_DWORD *)v2 + 8))(v1, 16777219, &v9);
  result = v9;
  if ( v9 != 0 )
  {
    for ( i = 1; i >= 0; --i )
    {
      LOBYTE(v8[0]) = (*(int (__fastcall **)(int, int))(*(_DWORD *)v9 + 48))(v9, i);
      if ( LOBYTE(v8[0]) != 0 )
      {
        sub_38D8();
        v6 = v5;
        sub_38D8();
        (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 20))(v6);
        sub_3D58();
        sub_3D58();
        (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)v9 + 16))(v9, v8);
      }
    }
    result = v9;
    if ( v9 != 0 )
      return (*(int (__fastcall **)(int))(*(_DWORD *)v9 + 4))(v9);
  }
  return result;
}
// 490: variable 'v0' is possibly undefined
// 498: variable 'v2' is possibly undefined
// 4E4: variable 'v5' is possibly undefined
// 4EC: variable 'v7' is possibly undefined

//----- (00000564) --------------------------------------------------------
void __fastcall sub_564(_DWORD *a1)
{
  int v2; // r0
  int v3; // r5
  int v4; // r0
  int v5; // r0
  int v6; // r5
  int v7; // r0
  int v8; // r0
  int v9; // r5
  int v10; // r0
  int v11; // r0

  if ( a1[4] == 0 )
  {
    sub_38D8();
    v3 = v2;
    sub_38D8();
    (*(void (__fastcall **)(int, int, _DWORD *))(*(_DWORD *)v4 + 8))(v3, 16777225, a1 + 4);
  }
  sub_3C4C();
  sub_38D8();
  v6 = v5;
  sub_38D8();
  (*(void (__fastcall **)(int, _DWORD *))(*(_DWORD *)v7 + 16))(v6, a1 + 5);
  if ( (int)a1[96] >= 0 )
  {
    sub_38D8();
    v9 = v8;
    sub_38D8();
    (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v10 + 64))(v9, a1[96]);
    a1[96] = -1;
  }
  v11 = a1[3];
  if ( v11 != 0 )
  {
    (*(void (__fastcall **)(int))(*(_DWORD *)v11 + 4))(v11);
    a1[3] = 0;
  }
  a1[98] = 0;
  sub_3C4C();
}
// 57C: variable 'v2' is possibly undefined
// 584: variable 'v4' is possibly undefined
// 5B4: variable 'v5' is possibly undefined
// 5BC: variable 'v7' is possibly undefined
// 5E0: variable 'v8' is possibly undefined
// 5E8: variable 'v10' is possibly undefined

//----- (0000063C) --------------------------------------------------------
_DWORD *__fastcall sub_63C(_DWORD *result, int a2, int a3)
{
  int v3; // r5
  bool v4; // zf
  _DWORD *v5; // r4
  bool v6; // zf
  int v8; // r0
  int v9; // r7
  int v10; // r0
  int v11; // r0
  int v12; // r7
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r6
  int v17; // r0

  v3 = (int)result;
  if ( result != nullptr )
  {
    if ( a2 == 5679 )
    {
      result[150] = a3;
    }
    else if ( a2 == 5680 )
    {
      result[153] = a3;
    }
    else if ( a2 == 5681 )
    {
      v4 = a3 == 0;
      if ( a3 != 0 )
        v4 = a3 == 1;
      if ( v4 )
        result[101] = a3;
    }
    else if ( a2 == 5682 )
    {
      result[148] = a3;
    }
    else if ( a2 == 5683 )
    {
      result[149] = a3;
    }
    else
    {
      if ( a2 == 6601 )
      {
        result[155] = a3;
      }
      else if ( a2 == 6602 )
      {
        result[156] = a3;
      }
      if ( a2 == 1000 )
      {
        v5 = (_DWORD *)result[154];
        v6 = a3 == 0;
        if ( a3 != 0 )
          v6 = v5 == nullptr;
        if ( !v6 )
        {
          nullsub_1("ZMAEE_CHARGE_UINOTIFY");
          result = *(_DWORD **)(v3 + 604);
          if ( result == (_UNKNOWN **)((char *)&off_0 + 3) )
          {
            if ( (int)v5[85] >= 0 )
            {
              sub_38D8();
              v9 = v8;
              sub_38D8();
              (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v10 + 64))(v9, v5[85]);
              v5[85] = -1;
            }
            if ( v5[16] == 2 )
            {
              return (_DWORD *)sub_29D8(v3, *(_DWORD *)(a3 + 16), *(_DWORD *)(a3 + 12));
            }
            else
            {
              sub_3DA8();
              sub_3DA8();
              if ( v5[86] == 0 )
              {
                sub_3DD0();
                v12 = v11;
                v13 = v5[129];
                if ( v13 != 0 )
                {
                  sub_F64(v13);
                  v5[129] = 0;
                }
                sub_F90(v12 + 2);
                v5[129] = v14;
                sub_3C4C();
                sub_3DA8();
              }
              *(_DWORD *)(v3 + 604) = 4;
              return (_DWORD *)sub_2380(v3);
            }
          }
          else if ( result == (_DWORD *)&unk_7 )
          {
            if ( (int)v5[85] >= 0 )
            {
              sub_38D8();
              v16 = v15;
              sub_38D8();
              (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v17 + 64))(v16, v5[85]);
              v5[85] = -1;
            }
            nullsub_1(" p_charge->m_cmd == zmaee_charge_cmd_sms_mtwait success");
            if ( *(_DWORD *)(v3 + 612) == 1 )
            {
              nullsub_1("delete mnet file");
              sub_470();
            }
            nullsub_1("zmaee_charge_sendsms_success time begin... ");
            sub_2404(v3);
            return (_DWORD *)nullsub_1("zmaee_charge_sendsms_success time end2");
          }
        }
      }
    }
  }
  return result;
}
// 700: variable 'v8' is possibly undefined
// 708: variable 'v10' is possibly undefined
// 768: variable 'v11' is possibly undefined
// 798: variable 'v14' is possibly undefined
// 7D8: variable 'v15' is possibly undefined
// 7E0: variable 'v17' is possibly undefined
// 0: using guessed type _UNKNOWN *off_0;
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (000008F0) --------------------------------------------------------
int (__fastcall *__fastcall sub_8F0(_DWORD *a1, int (__fastcall **a2)(int a1)))(int result, int a2, int a3)
{
  *a1 = 708;
  *a2 = sub_C50;
  a2[1] = sub_BB8;
  a2[2] = sub_B10;
  a2[3] = (int (__fastcall *)(int))sub_A2C;
  a2[4] = (int (__fastcall *)(int))sub_944;
  a2[5] = (int (__fastcall *)(int))sub_9B8;
  return sub_9B8;
}

//----- (00000944) --------------------------------------------------------
int __fastcall sub_944(_DWORD *a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10)
{
  if ( a1 == nullptr )
    return -1;
  sub_564(a1);
  a1[105] = a2;
  a1[106] = a4;
  a1[107] = a3;
  if ( a5 != 0 )
    sub_3DA8();
  a1[99] = a6;
  a1[100] = a7;
  a1[102] = a8;
  a1[103] = a9;
  a1[104] = a10;
  if ( sub_3394((int)a1) != 0 )
    return 0;
  else
    return -1;
}

//----- (000009B8) --------------------------------------------------------
int __fastcall sub_9B8(int result, int a2, int a3)
{
  int v3; // r4
  int v4; // r6
  _DWORD v5[32]; // [sp+4h] [bp-80h] BYREF

  v3 = result;
  if ( result != 0 )
  {
    if ( a3 != 0 )
    {
      sub_4458(v5, 0x80u);
      v4 = *(_DWORD *)(v3 + 616);
      sub_39B0();
      sub_29D8(v3, v4 + 356, (int)v5);
    }
    else
    {
      *(_DWORD *)(result + 604) = 4;
      sub_2380(result);
    }
    return 1;
  }
  return result;
}

//----- (00000A2C) --------------------------------------------------------
int __fastcall sub_A2C(_DWORD *a1, int a2, int a3, int a4)
{
  bool v7; // zf
  int v8; // r1
  bool v9; // zf
  int v10; // r2

  if ( a1 == nullptr )
    return -1;
  if ( a2 > 5 )
  {
    if ( a2 == 6 )
    {
      v7 = a3 == 10;
      if ( a3 != 10 )
        v7 = a3 == 25;
      if ( !v7 && a3 != 4 && a3 != 5 )
      {
        v9 = a3 == 11;
        if ( a3 != 11 )
          v9 = a3 == 6;
        if ( !v9 )
          return 0;
LABEL_21:
        v8 = 0;
        goto LABEL_22;
      }
LABEL_16:
      v8 = 1;
LABEL_22:
      sub_35DC((int)a1, v8);
      return 0;
    }
    if ( a2 == 9 )
    {
      a1[152] = a4;
      return 0;
    }
    if ( a2 != 10 )
    {
      if ( a2 == 28672 )
        sub_63C(a1, a3, a4);
      return 0;
    }
    if ( a1[152] > a1[8] - 30 )
    {
      v10 = a1[7] / 2;
      if ( v10 - 20 <= a3 )
      {
        if ( v10 + 20 >= a3 )
          return 0;
        goto LABEL_21;
      }
      goto LABEL_16;
    }
  }
  return 0;
}

//----- (00000B10) --------------------------------------------------------
int __fastcall sub_B10(int a1)
{
  if ( a1 == 0 )
    return -1;
  sub_43F0(a1);
  *(_DWORD *)(a1 + 4) = 1;
  *(_DWORD *)(a1 + 8) = 0;
  *(_DWORD *)(a1 + 12) = 0;
  *(_DWORD *)(a1 + 16) = 0;
  *(_DWORD *)(a1 + 380) = 0;
  *(_DWORD *)(a1 + 384) = -1;
  *(_DWORD *)(a1 + 416) = 0;
  *(_DWORD *)(a1 + 612) = 0;
  *(_DWORD *)(a1 + 600) = 0;
  sub_3C4C();
  sub_3C4C();
  sub_3C4C();
  sub_3C4C();
  *(_DWORD *)(a1 + 620) = 0;
  *(_DWORD *)(a1 + 624) = 0;
  *(_DWORD *)(a1 + 616) = 0;
  *(_DWORD *)(a1 + 628) = 0;
  *(_WORD *)(a1 + 632) = 0;
  *(_WORD *)(a1 + 634) = -1;
  return 0;
}

//----- (00000BB8) --------------------------------------------------------
int __fastcall sub_BB8(int a1)
{
  if ( a1 == 0 )
    return -4;
  --*(_DWORD *)(a1 + 4);
  nullsub_1("zmsys002_Release begin.....\r\n");
  sub_1074(a1);
  sub_3914();
  nullsub_1("zmsys002_Release end.....\r\n");
  return 0;
}
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (00000C50) --------------------------------------------------------
int __fastcall sub_C50(int a1)
{
  if ( a1 == 0 )
    return -4;
  ++*(_DWORD *)(a1 + 4);
  return 0;
}

//----- (00000C6C) --------------------------------------------------------
int __fastcall sub_C6C(int a1, int a2, _BYTE *a3, int a4)
{
  bool v4; // cc
  bool v6; // zf
  int v7; // r0
  int v8; // r0
  int v9; // r4
  int v10; // r0
  int v12; // r5

  v4 = a1 <= 0;
  if ( a1 != 0 )
    v4 = a2 <= 0;
  if ( v4 )
    return 0;
  v6 = a3 == nullptr;
  if ( a3 != nullptr )
    v6 = *a3 == 0;
  if ( v6 )
    return 0;
  sub_3DD0();
  sub_3E5C();
  if ( v7 == 0 )
    return 0;
  sub_3E5C();
  if ( v8 == 0 )
    return 0;
  v9 = v8 + 1;
  sub_3E5C();
  if ( v10 == 0 )
    return 0;
  v12 = v10 - v9;
  sub_3C38();
  *(_BYTE *)(a4 + v12) = 0;
  return 1;
}
// CB0: variable 'v7' is possibly undefined
// CC0: variable 'v8' is possibly undefined
// CD8: variable 'v10' is possibly undefined

//----- (00000D10) --------------------------------------------------------
int __fastcall sub_D10(int a1, int a2)
{
  int v4; // r5
  int v5; // r0
  bool v6; // cc
  int v7; // r0
  _DWORD v9[16]; // [sp+4h] [bp-40h] BYREF

  v4 = 0;
  sub_3DD0();
  v6 = a1 <= 0;
  if ( a1 != 0 )
    v6 = a2 <= v5;
  if ( !v6 )
  {
    sub_4458(v9, 0x40u);
    sub_3C38();
    sub_3D80();
    if ( v7 == 0 )
      return 1;
  }
  return v4;
}
// D34: variable 'v5' is possibly undefined
// D68: variable 'v7' is possibly undefined

//----- (00000D80) --------------------------------------------------------
void sub_D80()
{
  sub_3D58();
  sub_3D58();
  sub_3D58();
  sub_3D58();
}

//----- (00000DB8) --------------------------------------------------------
void __fastcall sub_DB8(int a1, int a2, int a3)
{
  _DWORD v4[25]; // [sp+4h] [bp-64h] BYREF

  sub_4458(v4, 0x64u);
  sub_3C88((int)v4, byte_E20, a3);
  sub_3D58();
  sub_3D58();
  sub_3D58();
  sub_3D58();
}
// E20: using guessed type _BYTE byte_E20[4];

//----- (00000E24) --------------------------------------------------------
void __fastcall sub_E24(int a1, _BYTE *a2, int a3)
{
  _DWORD v5[25]; // [sp+4h] [bp-64h] BYREF

  sub_4458(v5, 0x64u);
  sub_3C88((int)v5, a2, a3);
  sub_3D58();
}

//----- (00000E68) --------------------------------------------------------
void __fastcall sub_E68(int a1, _BYTE *a2, int a3)
{
  _DWORD v5[25]; // [sp+4h] [bp-64h] BYREF

  sub_4458(v5, 0x64u);
  sub_3C88((int)v5, a2, a3);
  sub_3D58();
}

//----- (00000EAC) --------------------------------------------------------
void __fastcall sub_EAC(_DWORD *a1)
{
  int v2; // r0
  int v3; // r5
  int v4; // r0
  int v5; // r0
  int v6; // r5
  int v7; // r0
  int v8; // r0
  _DWORD *v9; // r0
  int v10; // r0

  if ( a1 != nullptr )
  {
    if ( (int)a1[96] >= 0 )
    {
      sub_38D8();
      v3 = v2;
      sub_38D8();
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v4 + 64))(v3, a1[96]);
      a1[96] = -1;
    }
    if ( a1[2] == 0 )
    {
      sub_38D8();
      v6 = v5;
      sub_38D8();
      (*(void (__fastcall **)(int, int, _DWORD *))(*(_DWORD *)v7 + 8))(v6, 16777220, a1 + 2);
    }
    v8 = a1[3];
    if ( v8 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v8 + 4))(v8);
      a1[3] = 0;
    }
    v9 = (_DWORD *)a1[95];
    if ( v9 != nullptr )
    {
      sub_3BC(v9);
    }
    else
    {
      sub_274(1024);
      a1[95] = v10;
    }
    a1[97] = 0;
  }
}
// EC8: variable 'v2' is possibly undefined
// ED0: variable 'v4' is possibly undefined
// EFC: variable 'v5' is possibly undefined
// F04: variable 'v7' is possibly undefined
// F58: variable 'v10' is possibly undefined

//----- (00000F64) --------------------------------------------------------
void __fastcall sub_F64(int a1)
{
  int v2; // r0
  void (__fastcall *v3)(int); // r1
  bool v4; // zf

  v2 = sub_4400();
  v4 = v2 == 0;
  if ( v2 != 0 )
  {
    v3 = *(void (__fastcall **)(int))(v2 + 624);
    v4 = v3 == nullptr;
  }
  if ( v4 )
    sub_3914();
  else
    v3(a1);
}
// F8C: variable 'v3' is possibly undefined

//----- (00000F90) --------------------------------------------------------
void __fastcall sub_F90(int a1)
{
  int v2; // r0
  void (__fastcall *v3)(int); // r1
  bool v4; // zf

  v2 = sub_4400();
  v4 = v2 == 0;
  if ( v2 != 0 )
  {
    v3 = *(void (__fastcall **)(int))(v2 + 620);
    v4 = v3 == nullptr;
  }
  if ( v4 )
    sub_3900();
  else
    v3(a1);
}
// FB8: variable 'v3' is possibly undefined
// FBC: using guessed type int sub_FBC(void);

//----- (00000FBC) --------------------------------------------------------
BOOL __fastcall sub_FBC(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9)
{
  int v11; // r0
  BOOL result; // r0

  result = a1 != 0
        && ((sub_EAC((_DWORD *)a1), *(_DWORD *)(a1 + 12) != 0)
         || (v11 = (*(int (__fastcall **)(_DWORD, _DWORD, void (__fastcall *)(int), void (__fastcall *)(int)))(**(_DWORD **)(a1 + 8) + 28))(
                     *(_DWORD *)(a1 + 8),
                     *(_DWORD *)(a1 + 404),
                     sub_F90,
                     sub_F64),
             *(_DWORD *)(a1 + 12) = v11,
             v11 != 0))
        && (*(int (__fastcall **)(_DWORD, int, int))(**(_DWORD **)(a1 + 12) + 8))(*(_DWORD *)(a1 + 12), a2, a1) == 0
        && (*(int (__fastcall **)(_DWORD, int, int, int, int, int, int, int, int))(**(_DWORD **)(a1 + 12) + 12))(
             *(_DWORD *)(a1 + 12),
             a3,
             a4,
             a5,
             a6,
             a7,
             a8,
             a9,
             a1) == 0;
  return result;
}

//----- (00001074) --------------------------------------------------------
int __fastcall sub_1074(int result)
{
  _DWORD *v1; // r4
  int v2; // r0
  int v3; // r5
  int v4; // r0
  int v5; // r0
  int v6; // r0
  int v7; // r0
  int *v8; // r0

  v1 = (_DWORD *)result;
  if ( result != 0 )
  {
    if ( *(int *)(result + 384) >= 0 )
    {
      sub_38D8();
      v3 = v2;
      sub_38D8();
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v4 + 64))(v3, v1[96]);
      v1[96] = -1;
      nullsub_1("zmsys002_free m_http_timeid.....\r\n");
    }
    v5 = v1[3];
    if ( v5 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v5 + 4))(v5);
      v1[3] = 0;
      nullsub_1("zmsys002_free m_http.....\r\n");
    }
    v6 = v1[2];
    if ( v6 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v6 + 4))(v6);
      v1[2] = 0;
      nullsub_1("zmsys002_free m_netmgr.....\r\n");
    }
    v7 = v1[4];
    if ( v7 != 0 )
    {
      (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 4))(v7);
      v1[4] = 0;
      nullsub_1("zmsys002_free m_tapi.....\r\n");
    }
    v8 = (int *)v1[95];
    if ( v8 != nullptr )
    {
      sub_2C8(v8);
      v1[95] = 0;
      nullsub_1("zmsys002_free m_http_buf.....\r\n");
    }
    result = v1[154];
    if ( result != 0 )
    {
      sub_3830((int)v1);
      v1[154] = 0;
      return nullsub_1("zmsys002_free m_smscmd.....\r\n");
    }
  }
  return result;
}
// 1090: variable 'v2' is possibly undefined
// 1098: variable 'v4' is possibly undefined
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (00001234) --------------------------------------------------------
int __fastcall sub_1234(int result, int a2, int a3)
{
  int v5; // r4

  v5 = result;
  if ( result != 0 )
  {
    sub_1074(result);
    return (*(int (__fastcall **)(_DWORD, int, int))(v5 + 408))(*(_DWORD *)(v5 + 416), a2, a3);
  }
  return result;
}

//----- (00001268) --------------------------------------------------------
int __fastcall sub_1268(int a1)
{
  int v2; // r0
  int v3; // r2
  int v4; // r3
  int v5; // r0

  v2 = *(_DWORD *)(a1 + 616);
  v3 = *(_DWORD *)(v2 + 24);
  v4 = *(_DWORD *)(v2 + 28);
  v5 = *(_DWORD *)(a1 + 416);
  if ( v3 == v4 )
    return (*(int (__fastcall **)(int, int, _DWORD))(a1 + 408))(v5, 1, 0);
  *(_DWORD *)(a1 + 604) = 12;
  return (*(int (__fastcall **)(int, int, void *, void *))(a1 + 412))(v5, 1, &unk_48C4, &unk_48A8);
}

//----- (000012D4) --------------------------------------------------------
int __fastcall sub_12D4(int a1, int a2, int a3, int a4)
{
  int v5; // r0
  int v6; // r6
  int v7; // r0
  int v8; // r0
  int v9; // r5
  int v10; // r0
  int v11; // r0
  int *v12; // r2
  int v13; // r1
  int v14; // r0
  int v15; // r0
  int v16; // r6
  int v17; // r0
  int v18; // r0
  int v19; // r5
  int v20; // r0
  int v22; // r0
  int v23; // r6
  int v24; // r0
  int v25; // r0
  int v26; // r5
  int v27; // r0

  if ( a1 != 0 )
  {
    switch ( a2 )
    {
      case 0:
        nullsub_1("zmsys002_notify_event ZMAEE_HTTP_EV_FAILURE");
        if ( *(int *)(a1 + 384) >= 0 )
        {
          sub_38D8();
          v6 = v5;
          sub_38D8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v7 + 64))(v6, *(_DWORD *)(a1 + 384));
          *(_DWORD *)(a1 + 384) = -1;
        }
        sub_38D8();
        v9 = v8;
        sub_38D8();
        v11 = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, _DWORD *), _DWORD))(*(_DWORD *)v10 + 60))(
                v9,
                1000,
                sub_1914,
                0);
        goto LABEL_14;
      case 3:
        sub_33C(*(int **)(a1 + 380), a3, a4);
        sub_3DD0();
        v12 = *(int **)(a1 + 380);
        v13 = v12[1];
        if ( v14 > v13 || sub_D10(*v12, v13) != 0 )
          return 1;
        nullsub_1("zmsys002_notify_event packet_isvalid");
        sub_3BC(*(_DWORD **)(a1 + 380));
        if ( *(int *)(a1 + 384) >= 0 )
        {
          sub_38D8();
          v16 = v15;
          sub_38D8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v17 + 64))(v16, *(_DWORD *)(a1 + 384));
          *(_DWORD *)(a1 + 384) = -1;
        }
        sub_38D8();
        v19 = v18;
        sub_38D8();
        *(_DWORD *)(a1 + 384) = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, _DWORD *), _DWORD))(*(_DWORD *)v20 + 60))(
                                  v19,
                                  1000,
                                  sub_1914,
                                  0);
        return 0;
      case 4:
        if ( *(int *)(a1 + 384) >= 0 )
        {
          sub_38D8();
          v23 = v22;
          sub_38D8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v24 + 64))(v23, *(_DWORD *)(a1 + 384));
          *(_DWORD *)(a1 + 384) = -1;
        }
        sub_38D8();
        v26 = v25;
        sub_38D8();
        v11 = (*(int (__fastcall **)(int, _DWORD, void (__fastcall *)(int, int), _DWORD))(*(_DWORD *)v27 + 60))(
                v26,
                0,
                sub_205C,
                0);
LABEL_14:
        *(_DWORD *)(a1 + 384) = v11;
        break;
      default:
        return 1;
    }
  }
  return 1;
}
// 1330: variable 'v5' is possibly undefined
// 1338: variable 'v7' is possibly undefined
// 1354: variable 'v8' is possibly undefined
// 1360: variable 'v10' is possibly undefined
// 139C: variable 'v14' is possibly undefined
// 13D0: variable 'v15' is possibly undefined
// 13D8: variable 'v17' is possibly undefined
// 13F4: variable 'v18' is possibly undefined
// 1400: variable 'v20' is possibly undefined
// 1438: variable 'v22' is possibly undefined
// 1440: variable 'v24' is possibly undefined
// 145C: variable 'v25' is possibly undefined
// 1468: variable 'v27' is possibly undefined
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (00001504) --------------------------------------------------------
_DWORD *__fastcall sub_1504(int a1)
{
  int *v1; // r5
  int v3; // r6

  v1 = *(int **)(a1 + 616);
  sub_3C4C();
  v3 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 16) + 64))(*(_DWORD *)(a1 + 16));
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 16) + 44))(*(_DWORD *)(a1 + 16), v3);
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 16) + 28))(*(_DWORD *)(a1 + 16), v3);
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"dllver", *(_DWORD *)(a1 + 600));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"smsdlver", 33);
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"uid", *(_DWORD *)(a1 + 24));
  sub_D80();
  sub_D80();
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"screen_w", *(_DWORD *)(a1 + 28));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"screen_h", *(_DWORD *)(a1 + 32));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"version", *(_DWORD *)(a1 + 20));
  sub_D80();
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"appid", *(_DWORD *)(a1 + 420));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"feeid", *(_DWORD *)(a1 + 428));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"fee", *(_DWORD *)(a1 + 424));
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"cmdid", v1[2]);
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"sendcount", v1[7]);
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"feereqseq", v1[4]);
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"feeconfid", v1[3]);
  sub_3DD0();
  return sub_434();
}

//----- (000017AC) --------------------------------------------------------
int __fastcall sub_17AC(int a1)
{
  int v2; // r0
  int v3; // r6
  int v4; // r5
  int v5; // r0
  int v6; // r0
  int v7; // r5
  int v8; // r0
  int result; // r0
  _DWORD v10[32]; // [sp+18h] [bp-100h] BYREF
  _DWORD v11[32]; // [sp+98h] [bp-80h] BYREF

  sub_4458(v11, 0x80u);
  sub_4458(v10, 0x80u);
  sub_1504(a1);
  sub_3DD0();
  v3 = v2;
  sub_3DA8();
  sub_3DA8();
  v4 = 80;
  sub_3D94();
  if ( v5 == 0 )
  {
    sub_3DA8();
    v4 = 443;
  }
  if ( !sub_FBC(a1, (int)sub_12D4, 1, (int)v10, v4, (int)"/paysyn", (int)v11, *(_DWORD *)(a1 + 592), v3) )
    return sub_1268(a1);
  sub_38D8();
  v7 = v6;
  sub_38D8();
  result = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, _DWORD *), _DWORD, int))(*(_DWORD *)v8 + 60))(
             v7,
             15000,
             sub_1914,
             0,
             a1);
  *(_DWORD *)(a1 + 384) = result;
  return result;
}
// 17E0: variable 'v2' is possibly undefined
// 1814: variable 'v5' is possibly undefined
// 1860: variable 'v6' is possibly undefined
// 186C: variable 'v8' is possibly undefined

//----- (00001914) --------------------------------------------------------
int __fastcall sub_1914(int a1, _DWORD *a2)
{
  int result; // r0

  if ( a2 != nullptr )
  {
    sub_EAC(a2);
    if ( (int)a2[98] < 2 )
    {
      nullsub_1("timeout restart billreq_start");
      sub_17AC(a2);
      result = a2[98] + 1;
      a2[98] = result;
    }
    else
    {
      return sub_1268((int)a2);
    }
  }
  return result;
}
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);
// 17AC: using guessed type int __fastcall sub_17AC(_DWORD);

//----- (0000197C) --------------------------------------------------------
int __fastcall sub_197C(int result)
{
  int v1; // r4

  v1 = result;
  if ( result != 0 )
  {
    *(_DWORD *)(result + 604) = 8;
    (*(void (__fastcall **)(_DWORD, int, void *))(result + 412))(*(_DWORD *)(result + 416), 2, &unk_48D2);
    *(_DWORD *)(v1 + 392) = 0;
    sub_17AC(v1);
    return 1;
  }
  return result;
}

//----- (000019C8) --------------------------------------------------------
int __fastcall sub_19C8(int a1, int a2, int a3, int a4)
{
  int v5; // r0
  int v6; // r6
  int v7; // r0
  int v8; // r0
  int v9; // r5
  int v10; // r0
  int v11; // r0
  int *v12; // r2
  int v13; // r1
  int v14; // r0
  int v15; // r0
  int v16; // r6
  int v17; // r0
  int v18; // r0
  int v19; // r5
  int v20; // r0
  int v22; // r0
  int v23; // r6
  int v24; // r0
  int v25; // r0
  int v26; // r5
  int v27; // r0

  if ( a1 != 0 )
  {
    switch ( a2 )
    {
      case 0:
        nullsub_1("ZMAEE_HTTP_EV_FAILURE 222");
        if ( *(int *)(a1 + 384) >= 0 )
        {
          sub_38D8();
          v6 = v5;
          sub_38D8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v7 + 64))(v6, *(_DWORD *)(a1 + 384));
          *(_DWORD *)(a1 + 384) = -1;
        }
        sub_38D8();
        v9 = v8;
        sub_38D8();
        v11 = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, int), _DWORD))(*(_DWORD *)v10 + 60))(
                v9,
                1000,
                sub_1FE0,
                0);
        goto LABEL_14;
      case 3:
        sub_33C(*(int **)(a1 + 380), a3, a4);
        sub_3DD0();
        v12 = *(int **)(a1 + 380);
        v13 = v12[1];
        if ( v14 > v13 || sub_D10(*v12, v13) != 0 )
          return 1;
        sub_3BC(*(_DWORD **)(a1 + 380));
        if ( *(int *)(a1 + 384) >= 0 )
        {
          sub_38D8();
          v16 = v15;
          sub_38D8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v17 + 64))(v16, *(_DWORD *)(a1 + 384));
          *(_DWORD *)(a1 + 384) = -1;
        }
        sub_38D8();
        v19 = v18;
        sub_38D8();
        *(_DWORD *)(a1 + 384) = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, int), _DWORD))(*(_DWORD *)v20 + 60))(
                                  v19,
                                  1000,
                                  sub_1FE0,
                                  0);
        return 0;
      case 4:
        if ( *(int *)(a1 + 384) >= 0 )
        {
          sub_38D8();
          v23 = v22;
          sub_38D8();
          (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v24 + 64))(v23, *(_DWORD *)(a1 + 384));
          *(_DWORD *)(a1 + 384) = -1;
        }
        sub_38D8();
        v26 = v25;
        sub_38D8();
        v11 = (*(int (__fastcall **)(int, _DWORD, int (__fastcall *)(int, int), _DWORD))(*(_DWORD *)v27 + 60))(
                v26,
                0,
                sub_21B0,
                0);
LABEL_14:
        *(_DWORD *)(a1 + 384) = v11;
        break;
      default:
        return 1;
    }
  }
  return 1;
}
// 1A24: variable 'v5' is possibly undefined
// 1A2C: variable 'v7' is possibly undefined
// 1A48: variable 'v8' is possibly undefined
// 1A54: variable 'v10' is possibly undefined
// 1A90: variable 'v14' is possibly undefined
// 1ABC: variable 'v15' is possibly undefined
// 1AC4: variable 'v17' is possibly undefined
// 1AE0: variable 'v18' is possibly undefined
// 1AEC: variable 'v20' is possibly undefined
// 1B24: variable 'v22' is possibly undefined
// 1B2C: variable 'v24' is possibly undefined
// 1B48: variable 'v25' is possibly undefined
// 1B54: variable 'v27' is possibly undefined
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (00001BB0) --------------------------------------------------------
void __fastcall sub_1BB0(int a1)
{
  int v2; // r5

  sub_3C4C();
  v2 = (*(int (__fastcall **)(_DWORD))(**(_DWORD **)(a1 + 16) + 64))(*(_DWORD *)(a1 + 16));
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 16) + 44))(*(_DWORD *)(a1 + 16), v2);
  (*(void (__fastcall **)(_DWORD, int))(**(_DWORD **)(a1 + 16) + 28))(*(_DWORD *)(a1 + 16), v2);
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"dllver", *(_DWORD *)(a1 + 600));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"smsdlver", 33);
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"uid", *(_DWORD *)(a1 + 24));
  sub_D80();
  sub_D80();
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"screen_w", *(_DWORD *)(a1 + 28));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"screen_h", *(_DWORD *)(a1 + 32));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"version", *(_DWORD *)(a1 + 20));
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"appid", *(_DWORD *)(a1 + 420));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"feeid", *(_DWORD *)(a1 + 428));
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"fee", *(_DWORD *)(a1 + 424));
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"appupdver", 1);
  sub_D80();
  sub_D80();
  sub_DB8(*(_DWORD *)(a1 + 592), (int)"mnet", *(_DWORD *)(a1 + 612));
  sub_3D58();
  sub_3D58();
}

//----- (00001E24) --------------------------------------------------------
int __fastcall sub_1E24(int a1)
{
  int result; // r0
  int v3; // r0
  int v4; // r6
  int v5; // r5
  int v6; // r0
  int v7; // r0
  int v8; // r5
  int v9; // r0
  _DWORD v10[32]; // [sp+18h] [bp-100h] BYREF
  _DWORD v11[32]; // [sp+98h] [bp-80h] BYREF

  sub_4458(v11, 0x80u);
  sub_4458(v10, 0x80u);
  result = a1;
  if ( a1 != 0 )
  {
    sub_1BB0(a1);
    sub_3DD0();
    v4 = v3;
    sub_3DA8();
    sub_3DA8();
    v5 = 80;
    sub_3D94();
    if ( v6 == 0 )
    {
      sub_3DA8();
      v5 = 443;
    }
    if ( sub_FBC(a1, (int)sub_19C8, 1, (int)v10, v5, (int)"/billreq", (int)v11, *(_DWORD *)(a1 + 592), v4) )
    {
      sub_38D8();
      v8 = v7;
      sub_38D8();
      *(_DWORD *)(a1 + 384) = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, int), _DWORD, int))(*(_DWORD *)v9 + 60))(
                                v8,
                                15000,
                                sub_1FE0,
                                0,
                                a1);
      *(_DWORD *)(a1 + 604) = 11;
      (*(void (__fastcall **)(_DWORD, int, void *))(a1 + 412))(*(_DWORD *)(a1 + 416), 2, &unk_48D2);
    }
    else
    {
      *(_DWORD *)(a1 + 604) = 12;
      (*(void (__fastcall **)(_DWORD, int, void *, void *, void *))(a1 + 412))(
        *(_DWORD *)(a1 + 416),
        1,
        &unk_48BA,
        &unk_48A8,
        &unk_48B4);
    }
    return 1;
  }
  return result;
}
// 1E60: variable 'v3' is possibly undefined
// 1E98: variable 'v6' is possibly undefined
// 1EE8: variable 'v7' is possibly undefined
// 1EF4: variable 'v9' is possibly undefined

//----- (00001FE0) --------------------------------------------------------
int __fastcall sub_1FE0(int a1, int a2)
{
  int result; // r0

  if ( a2 != 0 )
  {
    sub_EAC((_DWORD *)a2);
    if ( *(int *)(a2 + 392) >= 2 )
    {
      *(_DWORD *)(a2 + 604) = 12;
      return (*(int (__fastcall **)(_DWORD, int, void *, void *))(a2 + 412))(
               *(_DWORD *)(a2 + 416),
               1,
               &unk_48BA,
               &unk_48A8);
    }
    else
    {
      nullsub_1("timeout restart billreq_start");
      sub_1E24(a2);
      result = *(_DWORD *)(a2 + 392) + 1;
      *(_DWORD *)(a2 + 392) = result;
    }
  }
  return result;
}
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);
// 1E24: using guessed type int __fastcall sub_1E24(_DWORD);

//----- (0000205C) --------------------------------------------------------
void __fastcall sub_205C(int a1, int a2)
{
  int v2; // r10
  int *v4; // r0
  int v5; // r7
  int v6; // r8
  int v7; // r5
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  bool v12; // zf
  _BYTE *v13; // [sp+4h] [bp-4h]

  v2 = 0;
  if ( a2 != 0 )
  {
    v4 = *(int **)(a2 + 380);
    v5 = *v4;
    v6 = v4[1];
    sub_3C4C();
    v7 = *(_DWORD *)(a2 + 592);
    v13 = (_BYTE *)(v7 + 16);
    sub_C6C(v5, v6, byte_219C, v7);
    sub_3DD0();
    if ( v8 != 0 )
    {
      sub_3D44();
      v2 = v9;
    }
    sub_C6C(v5, v6, "retcode", (int)v13);
    sub_C6C(v5, v6, "desc", v7 + 32);
    if ( *v13 == 49 )
      v10 = 13;
    else
      v10 = 12;
    *(_DWORD *)(a2 + 604) = v10;
    v11 = *(_DWORD *)(a2 + 428);
    v12 = v11 == 8888;
    if ( v11 == 8888 )
      v12 = *(_DWORD *)(a2 + 424) == v2;
    if ( v12 )
    {
      (*(void (__fastcall **)(_DWORD, int, _DWORD))(a2 + 408))(*(_DWORD *)(a2 + 416), 1, 0);
    }
    else
    {
      sub_3DD0();
      sub_399C();
      (*(void (__fastcall **)(_DWORD, int, int, void *))(a2 + 412))(*(_DWORD *)(a2 + 416), 1, v7 + 512, &unk_48A8);
    }
  }
}
// 20B8: variable 'v8' is possibly undefined
// 20CC: variable 'v9' is possibly undefined
// 219C: using guessed type _BYTE byte_219C[4];

//----- (000021B0) --------------------------------------------------------
int __fastcall sub_21B0(int a1, int a2)
{
  int result; // r0

  result = a2;
  if ( a2 != 0 )
  {
    *(_DWORD *)(a2 + 396) = **(_DWORD **)(a2 + 380);
    *(_DWORD *)(a2 + 400) = *(_DWORD *)(*(_DWORD *)(a2 + 380) + 4);
    return sub_3394(a2);
  }
  return result;
}

//----- (000021D4) --------------------------------------------------------
int __fastcall sub_21D4(int a1)
{
  _DWORD *v2; // r5
  int v3; // r7
  int v5; // [sp+0h] [bp-40h] BYREF
  __int16 v6; // [sp+8h] [bp-38h]
  __int16 v7; // [sp+16h] [bp-2Ah]
  __int16 v8; // [sp+24h] [bp-1Ch]
  _BYTE v9[8]; // [sp+30h] [bp-10h] BYREF
  int v10; // [sp+38h] [bp-8h]
  int v11; // [sp+3Ch] [bp-4h]

  sub_44B0(v9, "\r", 6u);
  v11 = *(_DWORD *)(a1 + 396);
  v10 = *(_DWORD *)(a1 + 400);
  v2 = *(_DWORD **)(a1 + 616);
  sub_3C4C();
  v3 = *(_DWORD *)(a1 + 592);
  sub_C6C(v11, v10, "desc", v3);
  sub_C6C(v11, v10, "tipinfo", v3 + 256);
  sub_3DD0();
  sub_399C();
  sub_3DD0();
  sub_399C();
  sub_3EFC();
  if ( (int)v2[6] > 1 && v2[130] == 0 )
  {
    sub_44B0(&v5, byte_49B4, 0x2Eu);
    v6 += v2[7];
    v7 += v2[6] - v2[7];
    v8 += v2[7] + 1;
    sub_3EAC();
    sub_3EAC();
  }
  sub_3EAC();
  sub_3EAC();
  return (*(int (__fastcall **)(_DWORD, int, int, void *, void *))(a1 + 412))(
           *(_DWORD *)(a1 + 416),
           1,
           v3 + 1024,
           &unk_4902,
           &unk_4908);
}

//----- (00002380) --------------------------------------------------------
int __fastcall sub_2380(int a1)
{
  int v2; // r6

  sub_3C4C();
  v2 = *(_DWORD *)(a1 + 592);
  sub_3DD0();
  sub_399C();
  return (*(int (__fastcall **)(_DWORD, int, int, void *))(a1 + 412))(*(_DWORD *)(a1 + 416), 1, v2, &unk_4902);
}

//----- (00002404) --------------------------------------------------------
int __fastcall sub_2404(int a1)
{
  int v1; // r1
  int v2; // r5
  int v3; // lr
  int v4; // r12
  int v5; // r4
  int v6; // r3
  int v7; // r12
  __int16 v8; // r12
  int v9; // r12
  bool v10; // zf
  const char *v12; // r0

  v1 = *(_DWORD *)(a1 + 616);
  v2 = *(unsigned __int16 *)(a1 + 634);
  v3 = 0;
  v4 = v2 - 0xFFFF;
  if ( v2 == 0xFFFF )
    v4 = *(_DWORD *)(v1 + 28);
  v5 = 0;
  if ( v2 == 0xFFFF )
    *(_DWORD *)(v1 + 28) = v4 + 1;
  v6 = 0;
  if ( v2 != 0xFFFF )
  {
    v7 = *(_DWORD *)(a1 + 628) + 524 * *(__int16 *)(a1 + 634);
    ++*(_DWORD *)(v7 + 28);
  }
  if ( *(_WORD *)(a1 + 632) != 0 && *(_DWORD *)(v1 + 28) == *(_DWORD *)(v1 + 24) )
  {
    v5 = 1;
    if ( *(unsigned __int16 *)(a1 + 634) == 0xFFFF )
      *(_WORD *)(a1 + 634) = 0;
    v8 = *(_WORD *)(a1 + 634);
    v6 = *(_DWORD *)(a1 + 628) + 524 * v8;
    if ( *(_DWORD *)(v6 + 28) == *(_DWORD *)(v6 + 24) )
    {
      v9 = (__int16)(v8 + 1);
      *(_WORD *)(a1 + 634) = v9;
      if ( v9 == *(unsigned __int16 *)(a1 + 632) )
        v3 = 1;
      else
        v6 = *(_DWORD *)(a1 + 628) + 524 * v9;
    }
  }
  v10 = (v3 | v5) == 0;
  if ( (v3 | v5) == 0 )
    v10 = *(_DWORD *)(v1 + 28) == *(_DWORD *)(v1 + 24);
  if ( v10 )
    v3 = 1;
  if ( v3 != 0 )
    return sub_197C(a1);
  if ( v5 == 1 )
  {
    sub_2BE4(a1, v6);
    v12 = "zmaee_charge_sendsms_success ext sms ok";
  }
  else
  {
    sub_2BE4(a1, v1);
    v12 = "zmaee_charge_sendsms_success ok";
  }
  return nullsub_1(v12);
}
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (0000256C) --------------------------------------------------------
int __fastcall sub_256C(int a1, int a2)
{
  *(_DWORD *)(*(_DWORD *)(a2 + 616) + 340) = -1;
  nullsub_1("zmaee_charge_ui_timeout");
  return sub_25B0(a2, -1);
}
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);
// 25B0: using guessed type int __fastcall sub_25B0(_DWORD, _DWORD);

//----- (000025B0) --------------------------------------------------------
int __fastcall sub_25B0(int a1, int a2)
{
  int *v2; // r5
  int v5; // r0
  int v6; // r7
  int v7; // r0
  int result; // r0
  bool v9; // zf
  int v10; // r0
  int v11; // r8
  int v12; // r0
  int v13; // r0
  int v14; // r8
  int v15; // r0

  v2 = *(int **)(a1 + 616);
  nullsub_1("sendsms_callback status = ");
  sub_450();
  if ( *(unsigned __int16 *)(a1 + 634) != 0xFFFF )
    v2 = (int *)(*(_DWORD *)(a1 + 628) + 524 * *(__int16 *)(a1 + 634));
  sub_38D8();
  v6 = v5;
  sub_38D8();
  v2[84] = (*(int (__fastcall **)(int))(*(_DWORD *)v7 + 72))(v6);
  if ( a2 != -1 )
  {
    result = v2[16];
    v9 = result == 0;
    if ( result != 0 )
      v9 = result == 1;
    if ( v9 )
    {
      if ( v2[17] != 1 )
      {
        sub_2404(a1);
        return nullsub_1("sendsms_success ");
      }
      goto LABEL_30;
    }
    switch ( result )
    {
      case 2:
        result = v2[83];
        if ( result == 1 )
        {
LABEL_27:
          *(_DWORD *)(a1 + 604) = 3;
          sub_38D8();
          v11 = v10;
          sub_38D8();
          result = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, int), _DWORD))(*(_DWORD *)v12 + 60))(
                     v11,
                     30000,
                     sub_256C,
                     0);
LABEL_31:
          v2[85] = result;
          return result;
        }
        if ( result != 2 )
          return result;
        if ( v2[17] == 1 )
        {
LABEL_30:
          *(_DWORD *)(a1 + 604) = 7;
          sub_38D8();
          v14 = v13;
          sub_38D8();
          result = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, int), _DWORD))(*(_DWORD *)v15 + 60))(
                     v14,
                     30000,
                     sub_256C,
                     0);
          goto LABEL_31;
        }
        break;
      case 3:
        result = v2[83];
        if ( result == 1 )
          goto LABEL_27;
        if ( result != 2 )
          return result;
        if ( v2[17] == 1 )
          goto LABEL_30;
        break;
      case 4:
        result = v2[83];
        if ( result == 1 )
          goto LABEL_27;
        if ( result != 2 )
          return result;
        if ( v2[17] == 1 )
          goto LABEL_30;
        break;
      default:
        return result;
    }
    return sub_2404(a1);
  }
  if ( v2[7] > 0 )
    return sub_197C(a1);
  *(_DWORD *)(a1 + 604) = 12;
  return (*(int (__fastcall **)(_DWORD, int, void *, void *))(a1 + 412))(*(_DWORD *)(a1 + 416), 1, &unk_49A4, &unk_4902);
}
// 25F8: variable 'v5' is possibly undefined
// 2600: variable 'v7' is possibly undefined
// 281C: variable 'v10' is possibly undefined
// 2828: variable 'v12' is possibly undefined
// 2864: variable 'v13' is possibly undefined
// 2870: variable 'v15' is possibly undefined
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (000028E4) --------------------------------------------------------
int __fastcall sub_28E4(int a1, int a2)
{
  _DWORD *v2; // r4
  int v4; // r6
  int v5; // r0
  int v6; // r7
  int v7; // r0
  int v8; // r0
  int v9; // r6
  int v10; // r0
  int result; // r0

  v2 = *(_DWORD **)(a2 + 616);
  v4 = (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, int (__fastcall *)(int, int)))(**(_DWORD **)(a2 + 16) + 16))(
         *(_DWORD *)(a2 + 16),
         v2[87],
         v2[88],
         sub_25B0);
  sub_38D8();
  v6 = v5;
  sub_38D8();
  (*(void (__fastcall **)(int))(*(_DWORD *)v7 + 72))(v6);
  sub_450();
  nullsub_1("sendsms");
  nullsub_1(v2[88]);
  nullsub_1(v2[87]);
  sub_450();
  v2[85] = -1;
  if ( v4 == -6 )
  {
    sub_38D8();
    v9 = v8;
    sub_38D8();
    result = (*(int (__fastcall **)(int, int (__fastcall *)(int), int (*)(), _DWORD))(*(_DWORD *)v10 + 60))(
               v9,
               sub_BB8,
               sub_28E4,
               0);
    v2[85] = result;
  }
  else if ( v4 != 0 )
  {
    return sub_25B0(a2, -1);
  }
  else
  {
    result = v2[83] + 1;
    v2[83] = result;
  }
  return result;
}
// 291C: variable 'v5' is possibly undefined
// 2924: variable 'v7' is possibly undefined
// 296C: variable 'v8' is possibly undefined
// 2978: variable 'v10' is possibly undefined
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (000029D8) --------------------------------------------------------
int __fastcall sub_29D8(int a1, int a2, int a3)
{
  int *v3; // r4
  int v7; // r0
  bool v8; // zf
  int result; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r0
  int v17; // r6
  int v18; // r0
  int v19; // r0
  int v20; // r6
  int v21; // r0
  int v22; // r7
  int v23; // r0
  int v24; // r0
  int v25; // r7
  int v26; // r0
  _BYTE v27[10]; // [sp+8h] [bp-40h] BYREF
  __int16 v28; // [sp+12h] [bp-36h]

  v3 = *(int **)(a1 + 616);
  *(_DWORD *)(a1 + 604) = 2;
  if ( v3[6] > 1 && v3[130] == 1 )
  {
    sub_44B0(v27, aCkW, 0x40u);
    v28 += v3[7] + 1;
    (*(void (__fastcall **)(_DWORD, int, _BYTE *))(a1 + 412))(*(_DWORD *)(a1 + 416), 2, v27);
  }
  else
  {
    (*(void (__fastcall **)(_DWORD, int, void *))(a1 + 412))(*(_DWORD *)(a1 + 416), 2, &unk_4970);
  }
  v7 = *(_DWORD *)(a1 + 16);
  v8 = v7 == 0;
  if ( v7 != 0 )
    v8 = a2 == 0;
  if ( !v8 )
    v8 = a3 == 0;
  if ( v8 )
    return sub_25B0(a1, -1);
  v10 = v3[87];
  if ( v10 != 0 )
  {
    sub_F64(v10);
    v3[87] = 0;
  }
  v11 = v3[88];
  if ( v11 != 0 )
  {
    sub_F64(v11);
    v3[88] = 0;
  }
  sub_3DD0();
  sub_F90(v12 + 2);
  v3[87] = v13;
  sub_3DD0();
  sub_3C4C();
  sub_3DA8();
  sub_3DD0();
  sub_F90(v14 + 2);
  v3[88] = v15;
  sub_3DD0();
  sub_3C4C();
  sub_3DA8();
  sub_38D8();
  v17 = v16;
  sub_38D8();
  v19 = (*(int (__fastcall **)(int))(*(_DWORD *)v18 + 72))(v17) - v3[84];
  if ( v19 >= 1000 * v3[82] )
    v20 = 0;
  else
    v20 = 1000 * v3[82] - v19;
  if ( v3[85] >= 0 )
  {
    sub_38D8();
    v22 = v21;
    sub_38D8();
    (*(void (__fastcall **)(int, int))(*(_DWORD *)v23 + 64))(v22, v3[85]);
    v3[85] = -1;
  }
  sub_38D8();
  v25 = v24;
  sub_38D8();
  result = (*(int (__fastcall **)(int, int, int (__fastcall *)(int, int), _DWORD, int))(*(_DWORD *)v26 + 60))(
             v25,
             v20,
             sub_28E4,
             0,
             a1);
  v3[85] = result;
  return result;
}
// 2AD0: variable 'v12' is possibly undefined
// 2AD8: variable 'v13' is possibly undefined
// 2B08: variable 'v14' is possibly undefined
// 2B10: variable 'v15' is possibly undefined
// 2B3C: variable 'v16' is possibly undefined
// 2B44: variable 'v18' is possibly undefined
// 2B84: variable 'v21' is possibly undefined
// 2B8C: variable 'v23' is possibly undefined
// 2BAC: variable 'v24' is possibly undefined
// 2BB8: variable 'v26' is possibly undefined

//----- (00002BE4) --------------------------------------------------------
int __fastcall sub_2BE4(int a1, int a2)
{
  *(_DWORD *)(a2 + 332) = 0;
  if ( *(_DWORD *)(a2 + 520) == 1 )
    return sub_29D8(a1, a2 + 32, a2 + 72);
  *(_DWORD *)(a1 + 604) = 0;
  return sub_21D4(a1);
}
// 2BFC: conditional instruction was optimized away because r3.4==1
// 29D8: using guessed type int __fastcall sub_29D8(_DWORD, _DWORD, _DWORD);

//----- (00002C08) --------------------------------------------------------
int __fastcall sub_2C08(int *a1, _BYTE *a2)
{
  int v4; // r5
  int v5; // r0
  int v6; // r0

  v4 = 0;
  sub_3C4C();
  sub_C6C(a1[99], a1[100], a2, a1[148]);
  sub_3DD0();
  if ( v5 != 0 )
  {
    sub_3D44();
    return v6;
  }
  return v4;
}
// 2C48: variable 'v5' is possibly undefined
// 2C5C: variable 'v6' is possibly undefined

//----- (00002C68) --------------------------------------------------------
int __fastcall sub_2C68(int *a1, const char *a2, int a3, int *a4, int a5, int a6)
{
  int v10; // r0
  _DWORD v12[8]; // [sp+4h] [bp-20h] BYREF

  sub_4458(v12, 0x20u);
  sub_3C88((int)v12, "%s_%d", a2, a3 + 1);
  if ( a6 != 0 )
  {
    sub_3C4C();
    sub_C6C(a1[99], a1[100], v12, a1[148]);
    sub_3DD0();
    if ( v10 != 0 )
      sub_3DF8();
  }
  else
  {
    *a4 = sub_2C08(a1, v12);
  }
  return 1;
}
// 2CF4: variable 'v10' is possibly undefined

//----- (00002D24) --------------------------------------------------------
int __fastcall sub_2D24(int a1)
{
  int v1; // r7
  int v3; // r0
  int v4; // r0
  int *v6; // r5
  int v7; // r0
  int v8; // r0
  int v9; // r0
  _DWORD v10[8]; // [sp+Ch] [bp-20h] BYREF

  v1 = 0;
  v3 = (unsigned __int16)sub_2C08((int *)a1, "ext_sms_count");
  *(_WORD *)(a1 + 632) = v3;
  if ( v3 != 0 )
  {
    sub_F90(524 * v3);
    *(_DWORD *)(a1 + 628) = v4;
    if ( v4 == 0 )
    {
      nullsub_1("zmsys002_sms_ext_parse, no memory");
      return -1;
    }
    sub_3C4C();
  }
  while ( *(unsigned __int16 *)(a1 + 632) > v1 )
  {
    sub_4458(v10, 0x20u);
    v6 = (int *)(*(_DWORD *)(a1 + 628) + 524 * v1);
    sub_2C68((int *)a1, "ext_sms_cmd", v1, v6 + 18, 256, 1);
    sub_2C68((int *)a1, "ext_sms_spnumber", v1, v6 + 8, 32, 1);
    sub_2C68((int *)a1, "ext_sms_need_interval", v1, v6 + 82, 0, 0);
    sub_2C68((int *)a1, "ext_sms_needcount", v1, v6 + 6, 0, 0);
    sub_2C68((int *)a1, "ext_sms_smstype", v1, v6 + 16, 0, 0);
    sub_2C68((int *)a1, "ext_sms_needmt", v1, v6 + 17, 0, 0);
    sub_2C68((int *)a1, "ext_sms_allsend", v1++, v6 + 130, 0, 0);
    sub_3C88((int)v10, "ext_sms_dicheck_%d", v1);
    sub_3C4C();
    sub_C6C(*(_DWORD *)(a1 + 396), *(_DWORD *)(a1 + 400), v10, *(_DWORD *)(a1 + 592));
    sub_3DD0();
    if ( v7 != 0 )
    {
      sub_3DD0();
      sub_F90(v8 + 2);
      v6[86] = v9;
      if ( v9 != 0 )
      {
        sub_3C4C();
        sub_3DA8();
      }
    }
  }
  return 1;
}
// 2D60: variable 'v4' is possibly undefined
// 2ED0: variable 'v7' is possibly undefined
// 2EE0: variable 'v8' is possibly undefined
// 2EE8: variable 'v9' is possibly undefined
// 46C: using guessed type int __fastcall nullsub_1(_DWORD);

//----- (00002FE4) --------------------------------------------------------
int __fastcall sub_2FE4(_DWORD *a1)
{
  _DWORD *v2; // r0
  _DWORD *v3; // r5
  int v4; // r6
  int v5; // r7
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0
  int v10; // r0
  int v11; // r0
  int v12; // r0
  int v13; // r0
  int v14; // r0
  int v15; // r0
  int v16; // r0
  int v17; // r0
  int v18; // r0
  int v19; // r0
  int v20; // r0
  int v21; // r0
  int v22; // r0
  int v23; // r0
  int v24; // r0
  int v25; // r0
  int v26; // r0

  sub_F90(524);
  v3 = v2;
  sub_3C4C();
  v3[85] = -1;
  a1[154] = v3;
  sub_3C4C();
  v4 = a1[99];
  v5 = a1[100];
  sub_3C4C();
  sub_C6C(v4, v5, "chargeid", a1[148]);
  sub_3DD0();
  if ( v6 != 0 )
  {
    sub_3D44();
    v3[2] = v7;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "feeconfid", a1[148]);
  sub_3DD0();
  if ( v8 != 0 )
  {
    sub_3D44();
    v3[3] = v9;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "feereqseq", a1[148]);
  sub_3DD0();
  if ( v10 != 0 )
  {
    sub_3D44();
    v3[4] = v11;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "price", a1[148]);
  sub_3DD0();
  if ( v12 != 0 )
  {
    sub_3D44();
    v3[5] = v13;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "need_interval", a1[148]);
  sub_3DD0();
  if ( v14 != 0 )
  {
    sub_3D44();
    v3[82] = v15;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "needcount", a1[148]);
  sub_3DD0();
  if ( v16 != 0 )
  {
    sub_3D44();
    v3[6] = v17;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "dicheck", a1[148]);
  sub_3DD0();
  if ( v18 != 0 )
  {
    sub_3DD0();
    sub_F90(v19 + 2);
    v3[86] = v20;
    if ( v20 != 0 )
    {
      sub_3C4C();
      sub_3DA8();
    }
  }
  sub_C6C(v4, v5, "sms", (int)(v3 + 18));
  sub_C6C(v4, v5, "spnumber", (int)(v3 + 8));
  sub_3C4C();
  sub_C6C(v4, v5, "smstype", a1[148]);
  sub_3DD0();
  if ( v21 != 0 )
  {
    sub_3D44();
    v3[16] = v22;
  }
  sub_3C4C();
  sub_C6C(v4, v5, "needmt", a1[148]);
  sub_3DD0();
  if ( v23 != 0 )
  {
    sub_3D44();
    v3[17] = v24;
  }
  v3[130] = 1;
  sub_3C4C();
  sub_C6C(v4, v5, "allsend", a1[148]);
  sub_3DD0();
  if ( v25 != 0 )
  {
    sub_3D44();
    v3[130] = v26;
  }
  sub_2D24((int)a1);
  return 1;
}
// 2FF4: variable 'v2' is possibly undefined
// 3058: variable 'v6' is possibly undefined
// 306C: variable 'v7' is possibly undefined
// 30A0: variable 'v8' is possibly undefined
// 30B4: variable 'v9' is possibly undefined
// 30E8: variable 'v10' is possibly undefined
// 30FC: variable 'v11' is possibly undefined
// 3130: variable 'v12' is possibly undefined
// 3144: variable 'v13' is possibly undefined
// 3178: variable 'v14' is possibly undefined
// 318C: variable 'v15' is possibly undefined
// 31C0: variable 'v16' is possibly undefined
// 31D4: variable 'v17' is possibly undefined
// 3208: variable 'v18' is possibly undefined
// 3218: variable 'v19' is possibly undefined
// 3220: variable 'v20' is possibly undefined
// 329C: variable 'v21' is possibly undefined
// 32B0: variable 'v22' is possibly undefined
// 32E4: variable 'v23' is possibly undefined
// 32F8: variable 'v24' is possibly undefined
// 3334: variable 'v25' is possibly undefined
// 3348: variable 'v26' is possibly undefined

//----- (00003394) --------------------------------------------------------
int __fastcall sub_3394(int result)
{
  int v1; // r4
  _BYTE *v2; // r8
  _BYTE *v3; // r6

  v1 = result;
  if ( result != 0 )
  {
    sub_3C4C();
    v2 = *(_BYTE **)(v1 + 592);
    v3 = v2 + 512;
    sub_C6C(*(_DWORD *)(v1 + 396), *(_DWORD *)(v1 + 400), "retcode", (int)v2);
    sub_C6C(*(_DWORD *)(v1 + 396), *(_DWORD *)(v1 + 400), "feetype", (int)(v2 + 32));
    sub_C6C(*(_DWORD *)(v1 + 396), *(_DWORD *)(v1 + 400), "desc", (int)(v2 + 64));
    switch ( *v2 )
    {
      case '0':
        sub_3DD0();
        sub_399C();
        *(_DWORD *)(v1 + 604) = 12;
        (*(void (__fastcall **)(_DWORD, int, _BYTE *, void *))(v1 + 412))(*(_DWORD *)(v1 + 416), 1, v3, &unk_4902);
        break;
      case '1':
        sub_3DD0();
        sub_399C();
        *(_DWORD *)(v1 + 604) = 13;
        (*(void (__fastcall **)(_DWORD, int, _BYTE *, void *))(v1 + 412))(*(_DWORD *)(v1 + 416), 1, v3, &unk_4902);
        break;
      case '2':
        if ( v2[32] != 49 || sub_2FE4((_DWORD *)v1) != 1 )
          goto LABEL_11;
        *(_DWORD *)(v1 + 604) = 0;
        sub_21D4(v1);
        break;
      case '3':
        sub_3DD0();
        sub_399C();
        *(_DWORD *)(v1 + 604) = 9;
        (*(void (__fastcall **)(_DWORD, int, _BYTE *, void *))(v1 + 412))(*(_DWORD *)(v1 + 416), 1, v3, &unk_4902);
        break;
      case '4':
        (*(void (__fastcall **)(_DWORD, int, _DWORD))(v1 + 408))(*(_DWORD *)(v1 + 416), 1, 0);
        break;
      default:
LABEL_11:
        *(_DWORD *)(v1 + 604) = 12;
        (*(void (__fastcall **)(_DWORD, int, void *, void *))(v1 + 412))(*(_DWORD *)(v1 + 416), 1, &unk_4920, &unk_4902);
        break;
    }
    return 1;
  }
  return result;
}

//----- (000035DC) --------------------------------------------------------
int __fastcall sub_35DC(int result, int a2)
{
  int v2; // r12
  int v3; // r0
  int v4; // r2
  int v5; // r1
  int v6; // r0

  v2 = result;
  if ( result != 0 )
  {
    result = *(_DWORD *)(result + 604);
    switch ( result )
    {
      case 0:
        if ( a2 == 1 )
        {
          v3 = *(_DWORD *)(v2 + 616);
          v4 = v3 + 72;
          v5 = v3 + 32;
          goto LABEL_22;
        }
        *(_DWORD *)(v2 + 604) = 1;
        result = (*(int (__fastcall **)(_DWORD, int, void *, void *))(v2 + 412))(
                   *(_DWORD *)(v2 + 416),
                   1,
                   &unk_492A,
                   &unk_490E);
        break;
      case 1:
        if ( a2 == 1 )
        {
          if ( *(int *)(*(_DWORD *)(v2 + 616) + 28) <= 0 )
            goto LABEL_27;
          goto LABEL_28;
        }
        *(_DWORD *)(v2 + 604) = 0;
        result = sub_21D4(v2);
        break;
      case 4:
        if ( a2 == 1 )
        {
          v6 = *(_DWORD *)(v2 + 616);
          if ( *(_DWORD *)(v6 + 64) == 4 )
          {
            result = (*(int (__fastcall **)(_DWORD, int, void *))(v2 + 412))(*(_DWORD *)(v2 + 416), 3, &unk_4914);
          }
          else
          {
            v4 = v6 + 388;
            v5 = v6 + 356;
LABEL_22:
            result = sub_29D8(v2, v5, v4);
          }
        }
        else
        {
          *(_DWORD *)(v2 + 604) = 5;
          result = (*(int (__fastcall **)(_DWORD, int, void *, void *))(v2 + 412))(
                     *(_DWORD *)(v2 + 416),
                     1,
                     &unk_492A,
                     &unk_490E);
        }
        break;
      case 5:
        if ( a2 == 1 )
        {
          if ( *(int *)(*(_DWORD *)(v2 + 616) + 28) <= 0 )
            goto LABEL_27;
LABEL_28:
          result = sub_197C(v2);
        }
        else
        {
          *(_DWORD *)(v2 + 604) = 4;
          result = sub_2380(v2);
        }
        break;
      case 9:
        if ( a2 == 1 )
        {
          result = sub_1E24(v2);
        }
        else
        {
          *(_DWORD *)(v2 + 604) = 10;
          result = (*(int (__fastcall **)(_DWORD, int, void *, void *))(v2 + 412))(
                     *(_DWORD *)(v2 + 416),
                     1,
                     &unk_492A,
                     &unk_490E);
        }
        break;
      case 10:
        if ( a2 == 1 )
          goto LABEL_27;
        result = sub_3394(v2);
        break;
      case 12:
LABEL_27:
        result = (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD))(v2 + 408))(*(_DWORD *)(v2 + 416), 0, 0);
        break;
      case 13:
        result = (*(int (__fastcall **)(_DWORD, int, _DWORD))(v2 + 408))(*(_DWORD *)(v2 + 416), 1, 0);
        break;
      default:
        return result;
    }
  }
  return result;
}
// 36CC: conditional instruction was optimized away because r1.4==1

//----- (00003830) --------------------------------------------------------
void __fastcall sub_3830(int a1)
{
  _DWORD *v1; // r4
  bool v2; // zf
  int v4; // r0
  int v5; // r6
  int v6; // r0
  int v7; // r0
  int v8; // r0
  int v9; // r0

  v2 = a1 == 0;
  if ( a1 != 0 )
  {
    v1 = *(_DWORD **)(a1 + 616);
    v2 = v1 == nullptr;
  }
  if ( !v2 )
  {
    if ( (int)v1[85] >= 0 )
    {
      sub_38D8();
      v5 = v4;
      sub_38D8();
      (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)v6 + 64))(v5, v1[85]);
      v1[85] = -1;
    }
    v7 = v1[86];
    if ( v7 != 0 )
    {
      sub_F64(v7);
      v1[86] = 0;
    }
    v8 = v1[87];
    if ( v8 != 0 )
    {
      sub_F64(v8);
      v1[87] = 0;
    }
    v9 = v1[88];
    if ( v9 != 0 )
    {
      sub_F64(v9);
      v1[88] = 0;
    }
    sub_F64(*(_DWORD *)(a1 + 616));
    *(_DWORD *)(a1 + 616) = 0;
  }
}
// 3844: variable 'v1' is possibly undefined
// 3854: variable 'v4' is possibly undefined
// 385C: variable 'v6' is possibly undefined

//----- (000038D8) --------------------------------------------------------
void sub_38D8()
{
  JUMPOUT(0x1772);
}
// 38E8: control flows out of bounds to 1772

//----- (00003900) --------------------------------------------------------
void sub_3900()
{
  JUMPOUT(0);
}
// 3910: control flows out of bounds to 0

//----- (00003914) --------------------------------------------------------
void sub_3914()
{
  JUMPOUT(0x48DC);
}
// 3924: control flows out of bounds to 48DC

//----- (00003964) --------------------------------------------------------
int __fastcall sub_3964(int a1, int a2, int a3, int a4)
{
  return ((int (__fastcall *)(int, int, int, int))off_0)(a1, a2, a3, a4);
}
// 0: using guessed type _UNKNOWN *off_0;

//----- (0000399C) --------------------------------------------------------
void sub_399C()
{
  JUMPOUT(0);
}
// 39AC: control flows out of bounds to 0

//----- (000039B0) --------------------------------------------------------
void sub_39B0()
{
  JUMPOUT(0);
}
// 39C0: control flows out of bounds to 0

//----- (00003A28) --------------------------------------------------------
void sub_3A28()
{
  JUMPOUT(0);
}
// 3A38: control flows out of bounds to 0

//----- (00003A3C) --------------------------------------------------------
void __fastcall sub_3A3C(_BYTE *a1, _DWORD *a2, int **a3)
{
  int v4; // r5
  unsigned __int8 *v6; // r0
  unsigned __int8 *v7; // r1
  unsigned int v8; // r0
  bool v9; // zf
  int *v10; // r0
  int v11; // r3
  int v12; // r0
  _DWORD *v13; // r2
  int v14; // r1
  bool v15; // zf
  int v16; // r2

  v4 = 0;
  while ( 1 )
  {
    v14 = (unsigned __int8)*a1;
    if ( *a1 == 0 )
      break;
    ++a1;
    if ( v14 == 37 )
    {
      if ( *a1 == 37 )
      {
        ++a1;
      }
      else
      {
        sub_3A28();
        if ( v6 == nullptr )
          return;
        v7 = v6;
        v8 = *v6;
        if ( v8 == 111 )
        {
LABEL_23:
          v16 = *(*a3)++;
          a2[2 * v4 + 1] = v16;
          goto LABEL_15;
        }
        if ( v8 > 0x6F )
        {
          v15 = v8 == 112;
          if ( v8 != 112 )
            v15 = v8 == 115;
          if ( v15 || v8 == 117 || v8 == 120 )
            goto LABEL_23;
        }
        else
        {
          v9 = v8 == 88;
          if ( v8 != 88 )
            v9 = v8 == 99;
          if ( !v9 )
            v9 = v8 == 100;
          if ( v9 )
            goto LABEL_23;
          if ( v8 == 102 )
          {
            v10 = *a3;
            *a3 += 2;
            v11 = *v10;
            v12 = v10[1];
            v13 = &a2[2 * v4];
            v13[1] = v11;
            v13[2] = v12;
          }
        }
LABEL_15:
        a1 = v7 + 1;
        ++v4;
      }
    }
  }
  *a2 = v4;
}
// 3A78: variable 'v6' is possibly undefined

//----- (00003B60) --------------------------------------------------------
void sub_3B60(_BYTE *a1, ...)
{
  int v1; // r0
  int *v2; // [sp+4h] [bp-88h] BYREF
  _DWORD v3[33]; // [sp+8h] [bp-84h] BYREF
  _BYTE *varg_r0; // [sp+90h] [bp+4h]
  va_list varg_r1; // [sp+94h] [bp+8h] BYREF

  va_start(varg_r1, a1);
  varg_r0 = a1;
  va_copy((va_list)v2, varg_r1);
  sub_3A3C(a1, v3, &v2);
  if ( v1 != 0 )
    ((void (__fastcall *)(_BYTE *, _DWORD *))off_0)(varg_r0, v3);
}
// 0: invalid function type '?' has been ignored
// 3B88: variable 'v1' is possibly undefined
// 0: using guessed type _UNKNOWN *off_0;

//----- (00003C24) --------------------------------------------------------
void sub_3C24()
{
  JUMPOUT(0);
}
// 3C34: control flows out of bounds to 0

//----- (00003C38) --------------------------------------------------------
void sub_3C38()
{
  JUMPOUT(0);
}
// 3C48: control flows out of bounds to 0

//----- (00003C4C) --------------------------------------------------------
void sub_3C4C()
{
  JUMPOUT(0);
}
// 3C5C: control flows out of bounds to 0

//----- (00003C88) --------------------------------------------------------
void sub_3C88(int a1, _BYTE *a2, ...)
{
  int v3; // r0
  int *v4; // [sp+0h] [bp-88h] BYREF
  _DWORD v5[33]; // [sp+4h] [bp-84h] BYREF
  _BYTE *varg_r1; // [sp+94h] [bp+Ch]
  va_list varg_r2; // [sp+98h] [bp+10h] BYREF

  va_start(varg_r2, a2);
  varg_r1 = a2;
  va_copy((va_list)v4, varg_r2);
  sub_3A3C(a2, v5, &v4);
  if ( v3 != 0 )
    ((void (__fastcall *)(int, _BYTE *, _DWORD *))off_0)(a1, varg_r1, v5);
}
// 0: invalid function type '?' has been ignored
// 3CB4: variable 'v3' is possibly undefined
// 0: using guessed type _UNKNOWN *off_0;

//----- (00003CE4) --------------------------------------------------------
void __fastcall sub_3CE4(int a1, _BYTE *a2, int **a3)
{
  int v5; // r0
  _DWORD v6[33]; // [sp+0h] [bp-84h] BYREF

  sub_3A3C(a2, v6, a3);
  if ( v5 != 0 )
    ((void (__fastcall *)(int, _BYTE *, _DWORD *))off_0)(a1, a2, v6);
}
// 0: invalid function type '?' has been ignored
// 3D04: variable 'v5' is possibly undefined
// 0: using guessed type _UNKNOWN *off_0;

//----- (00003D44) --------------------------------------------------------
void sub_3D44()
{
  JUMPOUT(0);
}
// 3D54: control flows out of bounds to 0

//----- (00003D58) --------------------------------------------------------
void sub_3D58()
{
  JUMPOUT(0);
}
// 3D68: control flows out of bounds to 0

//----- (00003D80) --------------------------------------------------------
void sub_3D80()
{
  JUMPOUT(0);
}
// 3D90: control flows out of bounds to 0

//----- (00003D94) --------------------------------------------------------
void sub_3D94()
{
  JUMPOUT(0);
}
// 3DA4: control flows out of bounds to 0

//----- (00003DA8) --------------------------------------------------------
void sub_3DA8()
{
  JUMPOUT(0);
}
// 3DB8: control flows out of bounds to 0

//----- (00003DD0) --------------------------------------------------------
void sub_3DD0()
{
  JUMPOUT(0);
}
// 3DE0: control flows out of bounds to 0

//----- (00003DF8) --------------------------------------------------------
void sub_3DF8()
{
  JUMPOUT(0);
}
// 3E08: control flows out of bounds to 0

//----- (00003E5C) --------------------------------------------------------
void sub_3E5C()
{
  JUMPOUT(0);
}
// 3E6C: control flows out of bounds to 0

//----- (00003EAC) --------------------------------------------------------
void sub_3EAC()
{
  JUMPOUT(0);
}
// 3EBC: control flows out of bounds to 0

//----- (00003EFC) --------------------------------------------------------
void sub_3EFC()
{
  JUMPOUT(0);
}
// 3F0C: control flows out of bounds to 0

//----- (000040C8) --------------------------------------------------------
int __fastcall sub_40C8(int a1, int a2, int a3, int a4)
{
  return ((int (__fastcall *)(int, int, int, int))off_0)(a1, a2, a3, a4);
}
// 0: invalid function type '?' has been ignored
// 0: using guessed type _UNKNOWN *off_0;

//----- (000040F4) --------------------------------------------------------
int __fastcall sub_40F4(int a1, int a2, int a3, int a4)
{
  return ((int (__fastcall *)(int, int, int, int))off_0)(a1, a2, a3, a4);
}
// 0: invalid function type '?' has been ignored
// 0: using guessed type _UNKNOWN *off_0;

//----- (0000415C) --------------------------------------------------------
int __fastcall sub_415C(int a1, int a2, int a3, int a4)
{
  return ((int (__fastcall *)(int, int, int, int))off_0)(a1, a2, a3, a4);
}
// 0: invalid function type '?' has been ignored
// 0: using guessed type _UNKNOWN *off_0;

//----- (0000436C) --------------------------------------------------------
__int64 __fastcall sub_436C(int a1, int a2, int a3, int a4, __int64 a5)
{
  ((void (__fastcall *)(int, int, int, int))off_0)(a1, a2, a3, a4);
  return a5;
}
// 0: invalid function type '?' has been ignored
// 0: using guessed type _UNKNOWN *off_0;

//----- (000043F0) --------------------------------------------------------
// write access to const memory has been detected, the output may be wrong!
int __fastcall sub_43F0(int result)
{
  dword_184 = result;
  return result;
}
// 43F8: write access to const memory at 184 has been detected
// 184: using guessed type int dword_184;

//----- (00004400) --------------------------------------------------------
int sub_4400()
{
  return 0;
}
// 184: using guessed type int dword_184;

//----- (00004458) --------------------------------------------------------
_DWORD *__fastcall sub_4458(_DWORD *result, unsigned int a2)
{
  bool v2; // cf
  unsigned int v3; // r1
  _DWORD *v4; // r0
  int v5; // r1
  int v6; // r1
  _BYTE *v7; // r0

  v2 = a2 >= 0x20;
  v3 = a2 - 32;
  do
  {
    if ( !v2 )
      break;
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    v4 = result + 4;
    *v4 = 0;
    v4[1] = 0;
    v4[2] = 0;
    v4[3] = 0;
    result = v4 + 4;
    v2 = v3 >= 0x20;
    v3 -= 32;
  }
  while ( v2 );
  v2 = __CFSHL__(v3, 28);
  v5 = v3 << 28;
  if ( v2 )
  {
    *result = 0;
    result[1] = 0;
    result[2] = 0;
    result[3] = 0;
    result += 4;
  }
  if ( v5 < 0 )
  {
    *result = 0;
    result[1] = 0;
    result += 2;
  }
  v2 = __CFSHL__(v5, 2);
  v6 = 4 * v5;
  if ( v2 )
    *result++ = 0;
  if ( v6 != 0 )
  {
    if ( v6 < 0 )
    {
      *(_BYTE *)result = 0;
      v7 = (char *)result + 1;
      *v7 = 0;
      result = v7 + 1;
    }
    if ( (v6 & 0x40000000) != 0 )
    {
      *(_BYTE *)result = 0;
      return (_DWORD *)((char *)result + 1);
    }
  }
  return result;
}

//----- (000044B0) --------------------------------------------------------
_DWORD *__fastcall sub_44B0(_BYTE *a1, char *a2, unsigned int a3)
{
  unsigned int v3; // r12
  char v4; // r3
  char v5; // t1
  bool v6; // cf
  bool v7; // cc
  unsigned int v8; // r2
  char v9; // t1
  char v10; // t1
  unsigned int v11; // r3
  unsigned int v13; // r2
  char *v14; // r1
  unsigned int v15; // r12
  unsigned int v16; // t1
  unsigned int v17; // r3
  unsigned int v18; // t1
  unsigned int v19; // r3
  unsigned int v20; // t1
  unsigned int v21; // r3
  unsigned int v22; // t1

  if ( a3 <= 3 )
    goto LABEL_22;
  v3 = (unsigned __int8)a1 & 3;
  if ( ((unsigned __int8)a1 & 3) != 0 )
  {
    v5 = *a2++;
    v4 = v5;
    v6 = v3 >= 2;
    v7 = ((unsigned __int8)a1 & 3) == 3;
    v8 = a3 + v3;
    if ( ((unsigned __int8)a1 & 3) != 3 )
    {
      v9 = *a2++;
      LOBYTE(v3) = v9;
    }
    *a1++ = v4;
    if ( !v6 )
    {
      v10 = *a2++;
      v4 = v10;
    }
    a3 = v8 - 4;
    if ( !v7 )
      *a1++ = v3;
    if ( !v6 )
      *a1++ = v4;
  }
  v11 = (unsigned __int8)a2 & 3;
  if ( ((unsigned __int8)a2 & 3) != 0 )
  {
    v6 = a3 >= 4;
    v13 = a3 - 4;
    if ( v6 )
    {
      v16 = *(_DWORD *)&a2[-v11];
      v14 = &a2[-v11];
      v15 = v16;
      if ( v11 == 2 )
      {
        do
        {
          v19 = HIWORD(v15);
          v20 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v20;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v19 | (v20 << 16);
          a1 += 4;
        }
        while ( v6 );
      }
      else if ( v11 > 2 )
      {
        do
        {
          v21 = HIBYTE(v15);
          v22 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v22;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v21 | (v22 << 8);
          a1 += 4;
        }
        while ( v6 );
      }
      else
      {
        do
        {
          v17 = v15 >> 8;
          v18 = *((_DWORD *)v14 + 1);
          v14 += 4;
          v15 = v18;
          v6 = v13 >= 4;
          v13 -= 4;
          *(_DWORD *)a1 = v17 | (v18 << 24);
          a1 += 4;
        }
        while ( v6 );
      }
    }
LABEL_22:
    JUMPOUT(0x45D8);
  }
  return sub_458C(a1, a2, a3, 0);
}
// 44B4: control flows out of bounds to 45D8

//----- (00004574) --------------------------------------------------------
int sub_4574()
{
  sub_46F4();
  return sub_4588();
}

//----- (0000458C) --------------------------------------------------------
_DWORD *__fastcall sub_458C(_DWORD *result, char *a2, unsigned int a3, int a4)
{
  bool v4; // cf
  unsigned int i; // r2
  _DWORD *v6; // r1
  int v7; // r3
  int v8; // r4
  int v9; // r12
  int v10; // lr
  _DWORD *v11; // r0
  int v12; // r4
  int v13; // r12
  int v14; // lr
  int v15; // r4
  int v16; // r12
  int v17; // lr
  int v18; // r4
  char v19; // r12
  int v20; // t1
  bool v21; // cf
  bool v22; // nf
  int v23; // r2
  char v24; // t1
  _BYTE *v25; // r0

  v4 = a3 >= 0x20;
  for ( i = a3 - 32; v4; i -= 32 )
  {
    if ( !v4 )
      break;
    v7 = *(_DWORD *)a2;
    v8 = *((_DWORD *)a2 + 1);
    v9 = *((_DWORD *)a2 + 2);
    v10 = *((_DWORD *)a2 + 3);
    v6 = a2 + 16;
    *result = v7;
    result[1] = v8;
    result[2] = v9;
    result[3] = v10;
    v11 = result + 4;
    a4 = *v6;
    v12 = v6[1];
    v13 = v6[2];
    v14 = v6[3];
    a2 = (char *)(v6 + 4);
    *v11 = a4;
    v11[1] = v12;
    v11[2] = v13;
    v11[3] = v14;
    result = v11 + 4;
    v4 = i >= 0x20;
  }
  if ( __CFSHL__(i, 28) )
  {
    a4 = *(_DWORD *)a2;
    v15 = *((_DWORD *)a2 + 1);
    v16 = *((_DWORD *)a2 + 2);
    v17 = *((_DWORD *)a2 + 3);
    a2 += 16;
    *result = a4;
    result[1] = v15;
    result[2] = v16;
    result[3] = v17;
    result += 4;
  }
  if ( (i & 8) != 0 )
  {
    a4 = *(_DWORD *)a2;
    v18 = *((_DWORD *)a2 + 1);
    a2 += 8;
    *result = a4;
    result[1] = v18;
    result += 2;
  }
  v19 = 0;
  if ( __CFSHL__(i, 30) )
  {
    v20 = *(_DWORD *)a2;
    a2 += 4;
    LOBYTE(a4) = v20;
    *result++ = v20;
  }
  if ( i << 30 != 0 )
  {
    v21 = __CFSHL__(i, 31);
    v23 = i << 31;
    v22 = v23 < 0;
    if ( v23 < 0 )
    {
      v24 = *a2++;
      LOBYTE(v23) = v24;
    }
    if ( v21 )
    {
      LOBYTE(a4) = *a2;
      v19 = a2[1];
    }
    if ( v22 )
    {
      *(_BYTE *)result = v23;
      result = (_DWORD *)((char *)result + 1);
    }
    if ( v21 )
    {
      *(_BYTE *)result = a4;
      v25 = (char *)result + 1;
      *v25 = v19;
      return v25 + 1;
    }
  }
  return result;
}

//----- (000045F8) --------------------------------------------------------
int sub_45F8()
{
  return sub_4574();
}

//----- (00004610) --------------------------------------------------------
_UNKNOWN **sub_4610()
{
  _DWORD *v0; // r4

  sub_4894();
  v0 = (_DWORD *)sub_4820();
  v0[8] = 0;
  v0[9] = 1;
  v0[10] = 0;
  v0[11] = 0;
  v0[12] = 0;
  return &off_4708;
}
// 46E4: returning address of temporary local variable '%var_C'
// 4708: using guessed type _UNKNOWN *off_4708;

//----- (000046F4) --------------------------------------------------------
void sub_46F4()
{
  ;
}

//----- (0000479C) --------------------------------------------------------
int __fastcall sub_479C(int a1, _DWORD *a2)
{
  int v2; // r4
  char *v3; // r3
  int v4; // r2
  int v5; // lr
  unsigned int v6; // r3
  unsigned int v7; // r1
  _DWORD savedregs[2]; // [sp+8h] [bp+0h] BYREF

  v2 = sub_4820();
  v3 = (char *)savedregs - *(_DWORD *)(v2 + 28);
  v4 = *(_DWORD *)(v2 + 20);
  *a2 = v4;
  v5 = v4 + a1;
  if ( v4 + a1 > (unsigned int)v3 )
    return 0;
  v6 = ((unsigned int)&v3[v5] >> 1) & 0x7FFFFFF8 | (__CFADD__(v3, v5) << 31);
  v7 = (v5 + 4103) & 0xFFFFFFF8;
  if ( v7 > v6 )
    v7 = v6;
  *(_DWORD *)(v2 + 20) = v7;
  return v7 - v4;
}

//----- (00004808) --------------------------------------------------------
int sub_4808()
{
  return __semihost(24, (void *)0x20026);
}

//----- (00004820) --------------------------------------------------------
int sub_4820()
{
  _DWORD **v0; // r9

  return **v0 + 4;
}
// 4820: variable 'v0' is possibly undefined

//----- (00004838) --------------------------------------------------------
char *sub_4838()
{
  int v0; // r9
  char *v1; // r0
  void **v3; // [sp+0h] [bp-14h] BYREF
  char *v4; // [sp+4h] [bp-10h] BYREF

  v3 = (void **)&v4;
  __semihost(22, &v3);
  v1 = v4;
  if ( v4 == nullptr )
    v1 = (char *)&unk_64;
  return &v1[v0];
}
// 486C: variable 'v0' is possibly undefined

//----- (00004884) --------------------------------------------------------
int sub_4884()
{
  return sub_4820() + 4;
}

//----- (00004894) --------------------------------------------------------
_DWORD *sub_4894()
{
  _DWORD *result; // r0

  result = (_DWORD *)sub_4884();
  *result = 0;
  return result;
}

// nfuncs=103 queued=100 decompiled=100 lumina nreq=0 worse=0 better=0
// ALL OK, 100 function(s) have been successfully decompiled
